PORTNAME=	nishang
DISTVERSION=	0.7.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Using PowerShell for Penetration Testing.
WWW=		https://github.com/samratashok/nishang/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
