PORTNAME=	rcrdcarver
DISTVERSION=	5.54507d21
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Carve RCRD records ($LogFile) from a chunk of data..
WWW=		https://github.com/jschicht/RcrdCarver

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/wine-mono \
		??/wine_gecko \
		emulators/wine


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
