PORTNAME=	android-apktool
DISTVERSION=	2.7.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool for reverse engineering Android apk files.
WWW=		https://github.com/iBotPeaches/Apktool/releases

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/jdk17-openjdk


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
