PORTNAME=	pip3line
DISTVERSION=	92.5e27195
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The Swiss army knife of byte manipulation.
WWW=		https://github.com/nccgroup/pip3line

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git

RUN_DEPENDS=	??/distorm \
		??/qt4 \
		??/xdg-utils \
		lang/python \
		lang/python3 \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
