PORTNAME=	libee
DISTVERSION=	0.4.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Event expression library inspired by CEE.
WWW=		http://www.libee.org/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libestr


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
