PORTNAME=	analyzepesig
DISTVERSION=	0.0.0.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Analyze digital signature of PE file.
WWW=		https://blog.didierstevens.com/my-software/#AnalyzePESig

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-pefile@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
