PORTNAME=	reaver-wps-fork-t6x
DISTVERSION=	318.f9b5e15
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Brute force attack against Wifi Protected Setup mod with Pixie Dust Attack.
WWW=		https://github.com/t6x/reaver-wps-fork-t6x

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/pixiewps \
		??/sqlite3 \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
