PORTNAME=	paho-mqtt-c
DISTVERSION=	1.3.10
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An Eclipse Paho C client library for MQTT.
WWW=		https://github.com/eclipse/paho.mqtt.c

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake

RUN_DEPENDS=	security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
