PORTNAME=	webscarab
DISTVERSION=	20120422.001828
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Framework for analysing applications that communicate using the HTTP and HTTPS protocols
WWW=		http://www.owasp.org/index.php/Category:OWASP_WebScarab_Project

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
