PORTNAME=	pkt2flow
DISTVERSION=	82.e4cd57b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple utility to classify packets into flows.
WWW=		https://github.com/caesar0301/pkt2flow

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/scons \
		devel/git

RUN_DEPENDS=	net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
