PORTNAME=	pbscan
DISTVERSION=	10.566c3d7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Faster and more efficient stateless SYN scanner and banner grabber due to userland TCP/IP stack usage.
WWW=		https://github.com/gvb84/pbscan

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	net/libpcap \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
