PORTNAME=	libpcap-1.4
DISTVERSION=	1.4.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A system-independent interface for user-level packet capture
WWW=		http://www.tcpdump.org/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/flex

RUN_DEPENDS=	??/libnl \
		??/libusb \
		??/sh


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
