PORTNAME=	jwt-cracker
DISTVERSION=	23.8130879
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	JWT brute force cracker written in C.
WWW=		https://github.com/brendan-rius/c-jwt-cracker

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
