PORTNAME=	paketto
DISTVERSION=	3.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Advanced TCP/IP Toolkit.
WWW=		http://www.doxpara.com/paketto/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libghthash \
		??/libnet \
		??/libnetfilter_queue \
		??/libtomcrypt \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
