PORTNAME=	shhgit
DISTVERSION=	67.bac0c7d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Find committed secrets and sensitive files across GitHub, Gists, GitLab and BitBucket or your local repositories in real time.
WWW=		https://github.com/eth0izzle/shhgit

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
