PORTNAME=	naabu
DISTVERSION=	v2.3.4.r236.g67a1cca
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A fast port scanner written in go with focus on reliability and simplicity.
WWW=		https://github.com/projectdiscovery/naabu

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go \
		net/libpcap



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
