PORTNAME=	bruteforce-wallet
DISTVERSION=	43.648d7d7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Try to find the password of an encrypted Peercoin (or Bitcoin,Litecoin, etc...) wallet file.
WWW=		https://github.com/glv2/bruteforce-wallet

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/db5.3 \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
