PORTNAME=	bletchley
DISTVERSION=	0.0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A collection of practical application cryptanalysis tools.
WWW=		https://code.google.com/p/bletchley/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/scons \
		??/subversion

RUN_DEPENDS=	??/python3 \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
