PORTNAME=	python2-pdfkit
DISTVERSION=	1.0.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Wkhtmltopdf python wrapper to convert html to pdf using the webkit rendering engine and qt.
WWW=		https://pypi.python.org/pypi/pdfkit/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
