PORTNAME=	k55
DISTVERSION=	86.b3c4aa9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Linux x86_64 Process Injection Utility.
WWW=		https://github.com/josh0xA/K55

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
