PORTNAME=	can-utils
DISTVERSION=	1262.cbbe4b4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Linux-CAN / SocketCAN user space applications.
WWW=		https://github.com/linux-can/can-utils

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
