PORTNAME=	btscanner
DISTVERSION=	2.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Bluetooth device scanner.
WWW=		http://www.pentest.co.uk

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/bluez-libs \
		??/libxml2 \
		??/ncurses5-compat-libs


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
