PORTNAME=	rtlamr
DISTVERSION=	197.03369d1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An rtl-sdr receiver for smart meters operating in the 900MHz ISM band.
WWW=		https://github.com/bemasher/rtlamr/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go

RUN_DEPENDS=	??/fftw


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
