PORTNAME=	mikrotik-npk
DISTVERSION=	11.d54e97c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python tools for manipulating Mikrotik NPK format.
WWW=		https://github.com/kost/mikrotik-npk

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
