PORTNAME=	hash-identifier
DISTVERSION=	6.0e08a97
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Software to identify the different types of hashes used to encrypt data and especially passwords.
WWW=		https://github.com/blackploit/hash-identifier

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/dos2unix \
		devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
