PORTNAME=	perl-digest-md4
DISTVERSION=	1.9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl interface to the MD4 Algorithm.
WWW=		http://search.cpan.org/dist/Digest-MD4

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
