PORTNAME=	libdb
DISTVERSION=	5.3.28
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Berkley DB.
WWW=		https://github.com/berkeleydb/libdb/releases

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/libtool



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
