PORTNAME=	gggooglescan
DISTVERSION=	0.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Google scraper which performs automated searches and returns results of search queries in the form of URLs or hostnames.
WWW=		http://www.morningstarsecurity.com/research/gggooglescan

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		ftp/curl \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
