PORTNAME=	detect-it-easy
DISTVERSION=	3.10
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A program for determining types of files.
WWW=		https://github.com/horsicq/DIE-engine/releases

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/qt5-script


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
