PORTNAME=	recaf
DISTVERSION=	4.0.0.alpha.r170.g6b86485
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Modern Java bytecode editor.
WWW=		https://github.com/Col-E/Recaf

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gradle \
		??/jdk-openjdk \
		devel/git

RUN_DEPENDS=	??/java$_javaver-openjfx-bin \
		??/java-environment \
		??/java-runtime


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
