PORTNAME=	interactsh-client
DISTVERSION=	v1.3.0.r0.g4da329c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Open-Source Solution for Out of band Data Extraction.
WWW=		https://github.com/projectdiscovery/interactsh

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
