PORTNAME=	libvmi
DISTVERSION=	1440.c461e20
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A virtual machine introspection library.
WWW=		https://github.com/libvmi/libvmi

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		??/glib2 \
		??/libvirt \
		devel/git

RUN_DEPENDS=	??/json-c


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
