PORTNAME=	dvcs-ripper
DISTVERSION=	54.2c1bbc6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Rip web accessible (distributed) version control systems: SVN/GIT/BZR/CVS/HG.
WWW=		https://github.com/kost/dvcs-ripper

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl \
		??/perl-getopt-long \
		??/perl-io-socket-ssl \
		??/perl-lwp-protocol-https


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
