PORTNAME=	cvemap
DISTVERSION=	v1.0.0.r29.g36a1dd5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	CLI tool designed to provide a structured and easily navigable interface to various vulnerability databases.
WWW=		https://github.com/projectdiscovery/cvemap

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
