PORTNAME=	uff
DISTVERSION=	46.93fea53
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Unleashed ffuf. A fork of ffuf with more functions & a modified HTTP stack.
WWW=		https://github.com/sw33tLie/uff

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
