PORTNAME=	wondershaper
DISTVERSION=	48.98792b5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Limit the bandwidth of one or more network adapters.
WWW=		https://github.com/magnific0/wondershaper

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/iproute \
		??/kmod


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
