PORTNAME=	hulk
DISTVERSION=	27.ed2b11c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A webserver DoS tool (Http Unbearable Load King) ported to Go with some additional features.
WWW=		https://github.com/grafov/hulk

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
