PORTNAME=	enum4linux
DISTVERSION=	0.9.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool for enumerating information from Windows and Samba systems.
WWW=		http://labs.portcullis.co.uk/application/enum4linux/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/openldap \
		??/perl \
		??/polenum \
		??/smbclient


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
