PORTNAME=	gtksourceview2
DISTVERSION=	2.10.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A text widget adding syntax highlighting and more to GNOME.
WWW=		http://www.gnome.org/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/intltool \
		??/pkg-config \
		lang/python

RUN_DEPENDS=	??/gtk2 \
		??/libxml2


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
