PORTNAME=	t50
DISTVERSION=	5.8.7c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Experimental Multi-protocol Packet Injector Tool.
WWW=		https://gitlab.com/fredericopissarra/t50/-/releases

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/linux-headers


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
