PORTNAME=	scrounge-ntfs
DISTVERSION=	0.9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Data recovery program for NTFS file systems.
WWW=		http://thewalter.net/stef/software/scrounge/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/autoconf \
		??/automake



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
