PORTNAME=	gtk2
DISTVERSION=	2.24.33
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	GObject-based multi-platform GUI toolkit (legacy).
WWW=		https://www.gtk.org/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/glib2-devel \
		??/gobject-introspection \
		??/gtk-doc \
		devel/git

RUN_DEPENDS=	??/atk \
		??/cairo \
		??/desktop-file-utils \
		??/fontconfig \
		??/gdk-pixbuf2 \
		??/glib2 \
		??/gtk-update-icon-cache \
		??/libcups \
		??/librsvg \
		??/libx11 \
		??/libxcomposite \
		??/libxcursor \
		??/libxdamage \
		??/libxext \
		??/libxfixes \
		??/libxi \
		??/libxinerama \
		??/libxrandr \
		??/libxrender \
		??/pango \
		??/shared-mime-info


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
