PORTNAME=	viper
DISTVERSION=	2099.fdd7855
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Binary analysis framework.
WWW=		https://github.com/botherder/viper

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-sphinx@${PY_FLAVOR} \
		devel/git \
		devel/py-pip@${PY_FLAVOR} \
		devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	??/py-beautifulsoup4@${PY_FLAVOR} \
		??/py-bitstring@${PY_FLAVOR} \
		??/py-bottle@${PY_FLAVOR} \
		??/py-dateutil@${PY_FLAVOR} \
		??/py-django-extensions@${PY_FLAVOR} \
		??/py-django@${PY_FLAVOR} \
		??/py-dnspython@${PY_FLAVOR} \
		??/py-jsonschema@${PY_FLAVOR} \
		??/py-magic@${PY_FLAVOR} \
		??/py-olefile@${PY_FLAVOR} \
		??/py-oletools@${PY_FLAVOR} \
		??/py-pbkdf2@${PY_FLAVOR} \
		??/py-pefile@${PY_FLAVOR} \
		??/py-prettytable@${PY_FLAVOR} \
		??/py-pyasn1@${PY_FLAVOR} \
		??/py-pycryptodome@${PY_FLAVOR} \
		??/py-pydeep@${PY_FLAVOR} \
		??/py-pyelftools@${PY_FLAVOR} \
		??/py-pyexiftool@${PY_FLAVOR} \
		??/py-pylzma@${PY_FLAVOR} \
		??/py-pymisp@${PY_FLAVOR} \
		??/py-pypdns@${PY_FLAVOR} \
		??/py-pype32@${PY_FLAVOR} \
		??/py-pypssl@${PY_FLAVOR} \
		??/py-r2pipe@${PY_FLAVOR} \
		??/py-rarfile@${PY_FLAVOR} \
		??/py-requests-cache@${PY_FLAVOR} \
		??/py-scandir@${PY_FLAVOR} \
		??/py-sqlalchemy@${PY_FLAVOR} \
		??/py-ssdeep@${PY_FLAVOR} \
		??/py-terminaltables@${PY_FLAVOR} \
		??/py-whitenoise@${PY_FLAVOR} \
		??/ssdeep \
		devel/py-six@${PY_FLAVOR} \
		lang/python \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
