PORTNAME=	beholder
DISTVERSION=	0.8.10
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A wireless intrusion detection tool that looks for anomalies in a wifi environment.
WWW=		http://www.beholderwireless.org/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
