PORTNAME=	dublin-traceroute
DISTVERSION=	348.ea3a974
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	NAT-aware multipath tracerouting tool.
WWW=		https://github.com/insomniacslk/dublin-traceroute

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		??/libcap \
		devel/git

RUN_DEPENDS=	??/gtest \
		??/jsoncpp \
		??/libtins \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
