PORTNAME=	42zip
DISTVERSION=	42
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Recursive Zip archive bomb.
WWW=		http://blog.fefe.de/?ts=b6cea88d

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
