PORTNAME=	striptls
DISTVERSION=	55.5ec712c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Proxy PoC implementation of STARTTLS stripping attacks.
WWW=		https://github.com/tintinweb/striptls

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
