PORTNAME=	maskprocessor
DISTVERSION=	0.73
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A High-Performance word generator with a per-position configurable charset.
WWW=		http://hashcat.net/wiki/doku.php?id=maskprocessor

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/p7zip



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
