PORTNAME=	python2-speechrecognition
DISTVERSION=	3.8.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Library for performing speech recognition, with support for several engines and APIs, online and offline.
WWW=		https://pypi.org/project/speechrecognition/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-standard-aifc@${PY_FLAVOR} \
		devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
