PORTNAME=	sdrsharp
DISTVERSION=	1.0.0.1457
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The most popular SDR program.
WWW=		https://airspy.com

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/icoutils \
		archivers/unzip

RUN_DEPENDS=	??/alsa-lib \
		??/hicolor-icon-theme \
		??/mono \
		??/portaudio \
		??/rtl-sdr \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
