PORTNAME=	sonar-scanner
DISTVERSION=	6.2.1.4610
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Generic CLI tool to launch project analysis on SonarQube servers.
WWW=		https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-runtime \
		??/sh


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
