PORTNAME=	docem
DISTVERSION=	21.59db436
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Uility to embed XXE and XSS payloads in docx,odt,pptx,etc (OXML_XEE on steroids).
WWW=		https://github.com/whitel1st/docem

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-lxml@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
