PORTNAME=	smbcrunch
DISTVERSION=	12.313400e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	3 tools that work together to simplify reconnaissance of Windows File Shares.
WWW=		https://github.com/Raikia/SMBCrunch

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
