PORTNAME=	bfbtester
DISTVERSION=	2.1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perform checks of single and multiple argument command line overflows and environment variable overflows.
WWW=		https://sourceforge.net/projects/bfbtester/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
