PORTNAME=	ultimate-facebook-scraper
DISTVERSION=	323.16f9a15
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A bot which scrapes almost everything about a Facebook users profile.
WWW=		https://github.com/harismuneer/Ultimate-Facebook-Scraper

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/chromium \
		??/py-selenium@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
