PORTNAME=	adape-script
DISTVERSION=	43.4d0b9ff
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Active Directory Assessment and Privilege Escalation Script.
WWW=		https://github.com/hausec/ADAPE-Script

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
