PORTNAME=	python2-backports.shutil_get_terminal_size
DISTVERSION=	1.0.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A backport of the get_terminal_size function from Python 3.3s shutil.
WWW=		https://pypi.org/project/backports.shutil_get_terminal_size/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
