PORTNAME=	braa
DISTVERSION=	0.82
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A mass snmp scanner.
WWW=		http://s-tech.elsat.net.pl/braa/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/nasm \
		??/subversion



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
