PORTNAME=	zeek-aux
DISTVERSION=	765.b41bb80
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Handy auxiliary programs related to the use of the Zeek Network Security Monitor.
WWW=		https://github.com/zeek/zeek-aux

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git

RUN_DEPENDS=	??/zeek


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
