PORTNAME=	extended-ssrf-search
DISTVERSION=	28.680f815
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Smart ssrf scanner using different methods like parameter brute forcing in post and get.
WWW=		https://github.com/Damian89/extended-ssrf-search

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
