PORTNAME=	etherchange
DISTVERSION=	1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Can change the Ethernet address of the network adapters in Windows.
WWW=		https://vidstromlabs.com/freetools/etherchange/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
