PORTNAME=	python2-setuptools-scm
DISTVERSION=	5.0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Handles managing your python package versions in scm metadata.
WWW=		https://github.com/pypa/setuptools_scm/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
