PORTNAME=	ropeme
DISTVERSION=	4.9b3a8fd
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A set of python scripts to generate ROP gadgets and payload.
WWW=		http://www.vnsecurity.net/2010/08/ropeme-rop-exploit-made-easy/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-distorm@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
