PORTNAME=	arpantispoofer
DISTVERSION=	1.0.1.32
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A utility to detect and resist BIDIRECTIONAL ARP spoofing.
WWW=		http://arpantispoofer.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gtk2 \
		??/libbonoboui \
		??/libgnomeui \
		??/libnotify


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
