PORTNAME=	vt-cli
DISTVERSION=	0.13.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	VirusTotal Command Line Interface.
WWW=		https://github.com/VirusTotal/vt-cli

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
