PORTNAME=	libtirpc-compat
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Transport Independent RPC library (SunRPC replacement, backwards compatible links).
WWW=		http://libtirpc.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/libtirpc

RUN_DEPENDS=	??/libtirpc


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
