PORTNAME=	ntlmv1-multi
DISTVERSION=	102.d1f79e1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	NTLMv1 Multitool.
WWW=		https://github.com/evilmog/ntlmv1-multi

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
