PORTNAME=	chainsaw
DISTVERSION=	v2.13.1.r4.gc692405
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A powerful ‘first-response’ capability to quickly identify threats within Windows event logs.
WWW=		https://github.com/countercept/chainsaw

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/cargo \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
