PORTNAME=	qt5-remoteobjects
DISTVERSION=	5.15.18
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Inter-process communication (IPC) module developed for Qt.
WWW=		https://www.qt.io

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/qt5-declarative \
		devel/git

RUN_DEPENDS=	??/qt5-base


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
