PORTNAME=	omen
DISTVERSION=	19.10aa99e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Ordered Markov ENumerator - Password Guesser.
WWW=		https://github.com/RUB-SysSec/OMEN

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
