PORTNAME=	python-flask-httpauth
DISTVERSION=	4.8.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Basic, Digest and Token HTTP authentication for Flask routes.
WWW=		https://github.com/miguelgrinberg/Flask-HTTPAuth

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-flask@${PY_FLAVOR} \
		devel/py-setuptools@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
