PORTNAME=	sign
DISTVERSION=	10.2dc4018
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Automatically signs an apk with the Android test certificate.
WWW=		https://github.com/appium/sign

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/maven \
		devel/git

RUN_DEPENDS=	??/java-runtime


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
