PORTNAME=	redasm
DISTVERSION=	1815.27108ec
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Interactive, multiarchitecture disassembler written in C++ using Qt5 as UI Framework.
WWW=		https://github.com/REDasmOrg/REDasm

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		??/gcc \
		??/qt5-base \
		??/qt5-webengine \
		devel/git

RUN_DEPENDS=	??/qt5-base \
		??/qt5-webengine


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
