PORTNAME=	dns2tcp
DISTVERSION=	0.5.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool for relaying TCP connections over DNS.
WWW=		http://www.hsc.fr/ressources/outils/dns2tcp/index.html.en

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
