PORTNAME=	rinetd
DISTVERSION=	0.62
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Internet redirection server.
WWW=		http://www.boutell.com/rinetd

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
