PORTNAME=	meg
DISTVERSION=	89.5cc1d34
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fetch many paths for many hosts - without killing the hosts.
WWW=		https://github.com/tomnomnom/meg

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
