PORTNAME=	xxxpwn-smart
DISTVERSION=	6.b11b95b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A fork of xxxpwn adding further optimizations and tweaks.
WWW=		https://github.com/aayla-secura/xxxpwn_smart

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
