PORTNAME=	fusil
DISTVERSION=	1.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Python library used to write fuzzing programs.
WWW=		http://bitbucket.org/haypo/fusil/wiki/Home

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-ptrace@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
