PORTNAME=	gspoof
DISTVERSION=	3.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple GTK/command line TCP/IP packet generator.
WWW=		http://gspoof.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/autoconf \
		??/automake \
		??/make

RUN_DEPENDS=	??/glib2 \
		??/gtk2 \
		??/libnet


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
