PORTNAME=	perl-cache-lru
DISTVERSION=	0.04
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple, fast implementation of LRU cache in pure perl.
WWW=		http://search.cpan.org/~kazuho/Cache-LRU-0.04/lib/Cache/LRU.pm

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl-module-install

RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
