PORTNAME=	goohak
DISTVERSION=	31.815a31e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Automatically Launch Google Hacking Queries Against A Target Domain.
WWW=		https://github.com/1N3/Goohak

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
