PORTNAME=	packetq
DISTVERSION=	311.9ebf537
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool that provides a basic SQL-frontend to PCAP-files.
WWW=		https://github.com/DNS-OARC/PacketQ

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/zlib


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
