PORTNAME=	sqlsus
DISTVERSION=	0.7.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An open source MySQL injection and takeover tool.
WWW=		http://sqlsus.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-dbd-sqlite \
		??/perl-html-linkextractor \
		??/perl-libwww \
		??/perl-lwp-protocol-https \
		??/perl-switch \
		??/perl-www-mechanize


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
