PORTNAME=	sshatter
DISTVERSION=	1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Password bruteforcer for SSH.
WWW=		http://www.nth-dimension.org.uk/downloads.php?id=34

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-cryptx \
		??/perl-net-ssh-perl \
		??/perl-parallel-forkmanager


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
