PORTNAME=	wmi-forensics
DISTVERSION=	11.0ab08dc
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Scripts used to find evidence in WMI repositories.
WWW=		https://github.com/davidpany/WMI_Forensics

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
