PORTNAME=	stackflow
DISTVERSION=	2.2af525d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Universal stack-based buffer overfow exploitation tool.
WWW=		https://github.com/d4rkcat/stackflow

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
