PORTNAME=	xssscan
DISTVERSION=	17.7f1ea90
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Command line tool for detection of XSS attacks in URLs. Based on ModSecurity rules from OWASP CRS.
WWW=		https://github.com/gwroblew/detectXSSlib

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
