PORTNAME=	dmitry
DISTVERSION=	1.3a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Deepmagic Information Gathering Tool.
WWW=		http://www.mor-pah.net/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
