PORTNAME=	rfidtool
DISTVERSION=	0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An open source tool to read / write rfid tags.
WWW=		http://www.bindshell.net/tools/rfidtool.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
