PORTNAME=	0d1n
DISTVERSION=	0d1n.v37.r6.g2d723ae
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Web security tool to make fuzzing at HTTP inputs, made in C with libCurl.
WWW=		https://github.com/CoolerVoid/0d1n

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	ftp/curl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
