PORTNAME=	expose
DISTVERSION=	1144.218d915
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Dynamic Symbolic Execution (DSE) engine for JavaScript
WWW=		https://github.com/ExpoSEJS/ExpoSE

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/clang \
		??/gnuplot \
		??/libxtst \
		??/mitmproxy \
		lang/python3 \
		www/node \
		www/npm


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
