PORTNAME=	perl-url-encode
DISTVERSION=	0.03
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Encoding and decoding of application/x-www-form-urlencoded encoding.
WWW=		https://metacpan.org/dist/URL-Encode/view/lib/URL/Encode.pod

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl-extutils-makemaker \
		??/perl-test-simple

RUN_DEPENDS=	??/perl \
		??/perl-carp \
		??/perl-exporter \
		??/perl-xsloader


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
