PORTNAME=	kh2hc
DISTVERSION=	0.1.0.r0.gc9e1bfe
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Convert OpenSSH known_hosts file hashed with HashKnownHosts to hashes crackable by Hashcat.
WWW=		https://github.com/noraj/kh2hc

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/ctf-party \
		??/ruby-docopt \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
