PORTNAME=	termcap
DISTVERSION=	1.3.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Enables programs to use display computer terminals in a device-independent manner.
WWW=		http://www.catb.org/~esr/terminfo/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
