PORTNAME=	pulledpork
DISTVERSION=	397.5ccf5c5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Snort rule management.
WWW=		https://github.com/shirkdog/pulledpork

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl \
		??/perl-bytes-random-secure \
		??/perl-crypt-ssleay \
		??/perl-lwp-protocol-https


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
