PORTNAME=	php-mt-seed
DISTVERSION=	4.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	PHP mt_rand() seed cracker.
WWW=		http://www.openwall.com/php_mt_seed/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/php82


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
