PORTNAME=	hashcatch
DISTVERSION=	52.8145660
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Capture handshakes of nearby WiFi networks automatically.
WWW=		https://github.com/staz0t/hashcatch/releases

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/aircrack-ng \
		??/hashcat-utils \
		??/hcxtools \
		??/jq \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
