PORTNAME=	cameradar
DISTVERSION=	213.7bd7460
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Hacks its way into RTSP videosurveillance cameras.
WWW=		https://github.com/Ullaakut/cameradar

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go

RUN_DEPENDS=	security/nmap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
