PORTNAME=	python-ptable-boxchar
DISTVERSION=	243.eb76080
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Simple Python library designed to make it quick and easy to represent tabular data in visually appealing ASCII tables.
WWW=		https://github.com/platomav/PTable

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
