PORTNAME=	ntds-decode
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This application dumps LM and NTLM hashes from active accounts stored in an Active Directory database.
WWW=		http://packetstormsecurity.com/files/121543/NTDS-Hash-Decoder-01.b.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	archivers/unzip



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
