PORTNAME=	batman-adv
DISTVERSION=	2025.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Batman kernel module, (included upstream since .38)
WWW=		http://www.open-mesh.net/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/linux-headers

RUN_DEPENDS=	??/libnl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
