PORTNAME=	naft
DISTVERSION=	0.0.9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Network Appliance Forensic Toolkit.
WWW=		https://blog.didierstevens.com/my-software/#NAFT

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-yara@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
