PORTNAME=	amap
DISTVERSION=	5.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Next-generation tool for assisting network penetration testing.
WWW=		http://freeworld.thc.org/releases.php

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/ca-certificates \
		??/pcre \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
