PORTNAME=	skydive
DISTVERSION=	0.28.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An open source real-time network topology and protocols analyzer.
WWW=		https://github.com/skydive-project/skydive

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
