PORTNAME=	python2-distorm
DISTVERSION=	3.5.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The goal of diStorm3 is to decode x86/AMD64 binary streams and return a structure that describes each instruction.
WWW=		https://pypi.org/project/distorm3/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
