PORTNAME=	autonessus
DISTVERSION=	24.7933022
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This script communicates with the Nessus API in an attempt to help with automating scans.
WWW=		https://github.com/redteamsecurity/AutoNessus

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3 \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
