PORTNAME=	vidalia
DISTVERSION=	0.3.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Controller GUI for Tor.
WWW=		https://www.torproject.org/vidalia

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake

RUN_DEPENDS=	??/geoip \
		??/qt4 \
		??/tor


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
