PORTNAME=	bsdiff
DISTVERSION=	4.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tools for building and applying patches to binary files.
WWW=		https://www.daemonology.net/bsdiff/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/bzip2


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
