PORTNAME=	steghide
DISTVERSION=	0.5.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Embeds a message in a file by replacing some of the least significant bits.
WWW=		http://steghide.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libjpeg \
		??/libmcrypt \
		??/mhash \
		??/zlib


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
