PORTNAME=	spectools
DISTVERSION=	3.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Spectrum-Tools is a set of utilities for using the Wi-Spy USB spectrum analyzer hardware.
WWW=		https://www.kismetwireless.net/spectools/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/cairo \
		??/gtk4 \
		??/libusb \
		??/ncurses


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
