PORTNAME=	webspa
DISTVERSION=	0.8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A web knocking tool, sending a single HTTP/S to run O/S commands.
WWW=		http://sourceforge.net/projects/webspa/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
