PORTNAME=	gsa
DISTVERSION=	24.6.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Greenbone Security Assistant - The web frontend for the Greenbone Community Edition.
WWW=		https://github.com/greenbone/gsa

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gsad \
		??/openvas-scanner


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
