PORTNAME=	nmbscan
DISTVERSION=	1.2.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool to scan the shares of a SMB/NetBIOS network, using the NMB/SMB/NetBIOS protocols.
WWW=		http://nmbscan.gbarbier.org/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/samba


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
