PORTNAME=	checkpwd
DISTVERSION=	1.23
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Oracle Password Checker (Cracker).
WWW=		http://www.red-database-security.com/software/checkpwd.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/lib32-openssl \
		??/unixodbc \
		??/zlib


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
