PORTNAME=	python2-pyclamd
DISTVERSION=	0.4.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A python interface to Clamd (Clamav daemon).
WWW=		https://pypi.python.org/pypi/pyClamd/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
