PORTNAME=	scamper
DISTVERSION=	20240920
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool that actively probes the Internet in order to analyze topology and performance.
WWW=		http://www.caida.org/tools/measurement/scamper/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/bzip2 \
		??/xz \
		??/zlib \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
