PORTNAME=	cloudget
DISTVERSION=	64.cba10b1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python script to bypass cloudflare from command line. Built upon cfscrape module.
WWW=		https://github.com/eudemonics/cloudget

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-cfscrape@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
