PORTNAME=	nsec3walker
DISTVERSION=	20101223
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Enumerate domain names using DNSSEC.
WWW=		https://dnscurve.org/nsec3walker.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
