PORTNAME=	blackeye
DISTVERSION=	v2.5.r8.gbdc11a2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Ultimate phishing tool with ngrok and serveo.
WWW=		https://github.com/Git-Ankitraj/blackeye-im

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/ngrok \
		archivers/unzip \
		ftp/curl \
		ftp/wget \
		lang/php82


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
