PORTNAME=	threat-dragon
DISTVERSION=	2.2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Electron Threat Modelling and diagramming tool.
WWW=		https://owasp.org/www-project-threat-dragon/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/alsa-lib \
		??/cairo \
		??/gtk3 \
		??/hicolor-icon-theme \
		??/libxkbcommon \
		??/nspr \
		??/nss \
		??/pango


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
