PORTNAME=	androidpincrack
DISTVERSION=	5.6439bd2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Bruteforce the Android Passcode given the hash and salt.
WWW=		https://github.com/PentesterES/AndroidPINCrack

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
