PORTNAME=	sshtrix
DISTVERSION=	0.0.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A very fast multithreaded SSH login cracker.
WWW=		http://nullsecurity.net/tools/cracker.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libssh


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
