PORTNAME=	dcfldd
DISTVERSION=	1.7.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	DCFL (DoD Computer Forensics Lab) dd replacement with hashing.
WWW=		https://github.com/resurrecting-open-source-projects/dcfldd/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
