PORTNAME=	backdoorppt
DISTVERSION=	88.d0e7f91
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Transform your payload.exe into one fake word doc (.ppt).
WWW=		https://github.com/r00t-3xp10it/backdoorppt

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/xterm \
		??/zenity \
		emulators/wine \
		lang/ruby \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
