PORTNAME=	haskell-iconv
DISTVERSION=	0.4.1.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Provides an interface to the POSIX iconv library functions for string encoding conversion.
WWW=		http://hackage.haskell.org/package/iconv

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/ghc

RUN_DEPENDS=	??/haskell-mtl \
		??/haskell-regex-compat


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
