PORTNAME=	kerbrute
DISTVERSION=	90.9cfb81e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool to perform Kerberos pre-auth bruteforcing.
WWW=		https://github.com/ropnop/kerbrute

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
