PORTNAME=	iisbruteforcer
DISTVERSION=	16
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	HTTP authentication cracker. Its a tool that launchs an online dictionary attack to test for weak or simple passwords against protected areas on an IIS Web server.
WWW=		http://www.open-labs.org/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gcc

RUN_DEPENDS=	security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
