PORTNAME=	rtlizer
DISTVERSION=	35.5614163
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Simple spectrum analyzer.
WWW=		https://github.com/csete/rtlizer

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/cairo \
		??/gtk3 \
		??/rtl-sdr


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
