PORTNAME=	peepdf
DISTVERSION=	0.4.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Python tool to explore PDF files in order to find out if the file can be harmful or not.
WWW=		https://eternal-todo.com/tools/peepdf-pdf-analysis-tool

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
