PORTNAME=	flasm
DISTVERSION=	1.62
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Disassembler tool for SWF bytecode.
WWW=		http://www.nowrap.de/flasm.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gperf

RUN_DEPENDS=	??/zlib


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
