PORTNAME=	portspoof
DISTVERSION=	154.f777355
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This programs primary goal is to enhance OS security through a set of new techniques.
WWW=		https://drk1wi.github.io/portspoof/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/automake \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
