PORTNAME=	ntpdos
DISTVERSION=	4.3fe389b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	PoC for distributed NTP reflection DoS (CVE-2013-5211)
WWW=		https://github.com/sepehrdaddev/ntpdos

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gcc \
		??/make \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
