PORTNAME=	ruby-iostruct
DISTVERSION=	0.7.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Struct that can read/write itself from/to IO-like objects.
WWW=		https://rubygems.org/gems/iostruct

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
