PORTNAME=	cook
DISTVERSION=	v2.2.1.r18.gbae4f39
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Easily create words permutation and combination to generate complex wordlists and passwords.
WWW=		https://github.com/giteshnxtlvl/cook

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
