PORTNAME=	burpsuite
DISTVERSION=	2026.1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An integrated platform for attacking web applications (community edition) + SHELLING plugin.
WWW=		https://portswigger.net/burp/releases

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/giflib \
		??/java-runtime \
		??/libxext \
		??/libxrender \
		??/libxtst


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
