PORTNAME=	perl-term-ansicolor
DISTVERSION=	5.01
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Color screen output using ANSI escape sequences.
WWW=		https://metacpan.org/pod/Term::ANSIColor

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
