PORTNAME=	office-dde-payloads
DISTVERSION=	34.53291f9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Collection of scripts and templates to generate Office documents embedded with the DDE, macro-less command execution technique.
WWW=		https://github.com/0xdeadbeefJERKY/Office-DDE-Payloads

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-future@${PY_FLAVOR} \
		??/py-lxml@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
