PORTNAME=	openssl-1.1
DISTVERSION=	1.1.1.w
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	OpenSSL 1.1 legacy branch (deprecated).
WWW=		https://openssl-library.org/source/old/1.1.1

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
