PORTNAME=	android-udev-rules
DISTVERSION=	20250525.r3.g35c52f9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Android udev rules.
WWW=		https://github.com/bbqlinux/android-udev-rules

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
