PORTNAME=	python-azure-mgmt-security
DISTVERSION=	7.0.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Microsoft Azure Security Center Management Client Library for Python.
WWW=		https://pypi.org/project/azure-mgmt-security/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
