PORTNAME=	bindiff
DISTVERSION=	6.0.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A comparison tool for binary files, that assists vulnerability researchers and engineers to quickly find differences and similarities in disassembled code.
WWW=		http://www.zynamics.com/bindiff.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-runtime


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
