PORTNAME=	mptcp-abuse
DISTVERSION=	6.b0eeb27
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A collection of tools and resources to explore MPTCP on your network. Initially released at Black Hat USA 2014.
WWW=		https://github.com/Neohapsis/mptcp-abuse

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
