PORTNAME=	codetective
DISTVERSION=	45.52b91f1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool to determine the crypto/encoding algorithm used according to traces of its representation.
WWW=		https://www.digitalloft.org/init/plugin_wiki/page/codetective

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
