PORTNAME=	bluemaho
DISTVERSION=	090417
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A GUI-shell (interface) for suite of tools for testing security of bluetooth devices
WWW=		http://wiki.thc.org/BlueMaho

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/bluediving \
		??/bss \
		??/bt-audit \
		??/glib2 \
		??/hidattack \
		??/wxpython


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
