PORTNAME=	snarf-mitm
DISTVERSION=	41.bada142
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	SMB Man in the Middle Attack Engine / relay suite.
WWW=		https://github.com/purpleteam/snarf

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	www/node


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
