PORTNAME=	sh00t
DISTVERSION=	214.8c7321f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Testing Environment for Manual Security Testers.
WWW=		https://github.com/pavanw3b/sh00t

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-django-rest-framework@${PY_FLAVOR} \
		??/py-django-tables2@${PY_FLAVOR} \
		??/py-pytz@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
