PORTNAME=	perl-test-tester
DISTVERSION=	0.109
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Ease testing test modules built with Test::Builder.
WWW=		https://search.cpan.org/dist/Test-Tester

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
