PORTNAME=	favfreak
DISTVERSION=	27.8acea5e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Weaponizing favicon.ico for BugBounties , OSINT and what not.
WWW=		https://github.com/devanshbatham/FavFreak

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-mmh3@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
