PORTNAME=	pdf-parser
DISTVERSION=	0.7.12
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Parses a PDF document to identify the fundamental elements used in the analyzed file.
WWW=		http://blog.didierstevens.com/programs/pdf-tools/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
