PORTNAME=	perl-math-bigint-gmp
DISTVERSION=	1.6007
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Big integer calculations using the GNU Multiple Precision Arithmetic Library.
WWW=		https://metacpan.org/release/Math-BigInt-GMP

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gmp \
		??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
