PORTNAME=	python2-progressbar
DISTVERSION=	2.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A progress bar for Python.
WWW=		https://github.com/WoLpH/python-progressbar

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-utils@${PY_FLAVOR} \
		devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	??/py-utils@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
