PORTNAME=	marc4dasm
DISTVERSION=	6.f11860f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A disassembler for the Atmel MARC4 (a 4 bit Harvard micro).
WWW=		https://github.com/ApertureLabsLtd/marc4dasm

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
