PORTNAME=	kiterunner
DISTVERSION=	19.7d5824c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Contextual Content Discovery Tool.
WWW=		https://github.com/assetnote/kiterunner

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
