PORTNAME=	instashell
DISTVERSION=	44.8f867bd
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Multi-threaded Instagram Brute Forcer without password limit.
WWW=		https://github.com/maxrooted/instashell

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/tor \
		ftp/curl \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
