PORTNAME=	python2-libvmdk-python
DISTVERSION=	20191221
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Library and tools to access the VMware Virtual Disk (VMDK) format.
WWW=		https://github.com/libyal/libvmdk

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
