PORTNAME=	mssqlscan
DISTVERSION=	0.8.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A small multi-threaded tool that scans for Microsoft SQL Servers.
WWW=		http://www.cqure.net/wp/mssqlscan/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
