PORTNAME=	ufo-wardriving
DISTVERSION=	4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Allows you to test the security of wireless networks by detecting their passwords based on the router model.
WWW=		http://www.ufo-wardriving.com/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-pyqt4@${PY_FLAVOR} \
		??/qtwebkit \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
