PORTNAME=	python-sqlalchemy-mixins
DISTVERSION=	2.0.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Active Record, Django-like queries, nested eager load and beauty __repr__ for SQLAlchemy.
WWW=		https://pypi.org/project/sqlalchemy-mixins/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
