PORTNAME=	apache-tika
DISTVERSION=	2.9.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Toolkit for detecting and extracting metadata and structured text content.
WWW=		https://tika.apache.org/download.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
