PORTNAME=	tgcd
DISTVERSION=	1.1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	TCP/IP Gender Changer Daemon utility.
WWW=		https://sourceforge.net/projects/tgcd/files/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
