PORTNAME=	python-ubi-reader
DISTVERSION=	0.8.12.r11.gdd6b724
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Collection of Python scripts for reading information about and extracting data from UBI and UBIFS images.
WWW=		https://github.com/onekey-sec/ubi_reader

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-build@${PY_FLAVOR} \
		devel/git \
		devel/py-pip@${PY_FLAVOR}

RUN_DEPENDS=	??/py-lzallright@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
