PORTNAME=	casefile
DISTVERSION=	1.0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The little brother to Maltego without transforms, but combines graph and link analysis to examine links between manually added data to mind map your information
WWW=		http://www.paterva.com/web6/products/casefile.php

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
