PORTNAME=	python-terminable-thread
DISTVERSION=	0.7.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Provides a subclass of Thread with facilities to raise an exception in the thread or terminate the thread from another thread.
WWW=		https://pypi.org/project/terminable_thread/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
