PORTNAME=	chaosmap
DISTVERSION=	1.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An information gathering tool and dns / whois / web server scanner
WWW=		http://freecode.com/projects/chaosmap

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
