PORTNAME=	uw-offish
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Clear-text protocol simulator.
WWW=		http://uberwall.org/bin/download/42/UW_offish-0.1.tar.gz

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
