PORTNAME=	perl-net-rawip
DISTVERSION=	0.25
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl extension to manipulate raw IP packets with interface to B<libpcap>.
WWW=		http://search.cpan.org/dist/Net-RawIP

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
