PORTNAME=	scanssh
DISTVERSION=	2.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fast SSH server and open proxy scanner.
WWW=		http://www.monkey.org/~provos/scanssh/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libevent \
		??/libmd \
		??/openssl-1.0 \
		??/openssl-1.1 \
		net/libdnet \
		net/libpcap \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
