PORTNAME=	gethsploit
DISTVERSION=	3.144778b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Finding Ethereum nodes which are vulnerable to RPC-attacks.
WWW=		https://github.com/KarmaHostage/gethspoit

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-yaml@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
