PORTNAME=	bisect
DISTVERSION=	1.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Code coverage tool for OCaml.
WWW=		http://bisect.x9c.fr/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/ocaml

RUN_DEPENDS=	??/ocaml \
		??/ocaml-findlib


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
