PORTNAME=	tlsenum
DISTVERSION=	78.787c88b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A command line tool to enumerate TLS cipher-suites supported by a server.
WWW=		https://github.com/Ayrx/tlsenum

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-pip@${PY_FLAVOR} \
		??/py-virtualenv@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
