PORTNAME=	ilty
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An interception phone system for VoIP network.
WWW=		http://chdir.org/~nico/ilty/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-pylibpcap@${PY_FLAVOR} \
		??/py-pypcap@${PY_FLAVOR} \
		??/sox \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
