PORTNAME=	firmwalker
DISTVERSION=	101.23ff299
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Script for searching the extracted firmware file system for goodies.
WWW=		https://github.com/craigz28/firmwalker

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
