PORTNAME=	ajpfuzzer
DISTVERSION=	0.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A command-line fuzzer for the Apache JServ Protocol (ajp13).
WWW=		https://github.com/doyensec/ajpfuzzer

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
