PORTNAME=	python-pybinaryedge
DISTVERSION=	0.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python 3 Wrapper for the binary edge API https://www.binaryedge.io/.
WWW=		https://pypi.org/project/pybinaryedge/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
