PORTNAME=	davoset
DISTVERSION=	1.3.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool for using Abuse of Functionality and XML External Entities vulnerabilities on some websites to attack other websites.
WWW=		http://websecurity.com.ua/davoset/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/dos2unix \
		??/unrar

RUN_DEPENDS=	??/perl \
		??/perl-io-socket-socks


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
