PORTNAME=	mausezahn
DISTVERSION=	0.40
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A free fast traffic generator written in C which allows you to send nearly every possible and impossible packet.
WWW=		http://www.perihel.at/sec/mz/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/cmake \
		??/libcli \
		??/libnet \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
