PORTNAME=	s3-fuzzer
DISTVERSION=	4.0a2a6f0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A concurrent, command-line AWS S3 Fuzzer.
WWW=		https://github.com/petermbenjamin/s3-fuzzer

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
