PORTNAME=	hostapd-mana
DISTVERSION=	2.6.5.r20.g8853d5a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Modified hostapd for Wi-Fi attacks to create a rogue access point.
WWW=		https://github.com/sensepost/hostapd-mana

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/libnl \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
