PORTNAME=	modlishka
DISTVERSION=	v.1.1.1.r8.gfc49cce
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A powerful and flexible HTTP reverse proxy.
WWW=		https://github.com/drk1wi/Modlishka

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
