PORTNAME=	asp-audit
DISTVERSION=	2BETA
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An ASP fingerprinting tool and vulnerability scanner.
WWW=		http://seclists.org/basics/2006/Sep/128

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
