PORTNAME=	tiger
DISTVERSION=	3.2.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A security scanner, that checks computer for known problems. Can also use tripwire, aide and chkrootkit.
WWW=		http://www.nongnu.org/tiger/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/patch

RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
