PORTNAME=	vais
DISTVERSION=	17.5c35c3a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	SWF Vulnerability & Information Scanner.
WWW=		https://github.com/hahwul/vais

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/jpexs-decompiler \
		??/swftools \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
