PORTNAME=	bless
DISTVERSION=	v0.6.3.r3.g103fbd6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	High-quality, full-featured hex editor.
WWW=		https://github.com/afrantzis/bless

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/itstool \
		??/meson \
		??/ninja \
		devel/git

RUN_DEPENDS=	??/gtk-sharp-2


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
