PORTNAME=	sinfp
DISTVERSION=	1.24
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A full operating system stack fingerprinting suite.
WWW=		https://cpan.metacpan.org/authors/id/G/GO/GOMOR/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-class-gomor \
		??/perl-data-dumper \
		??/perl-dbd-sqlite \
		??/perl-dbi \
		??/perl-digest-perl-md5 \
		??/perl-io-socket-inet6 \
		??/perl-net-frame \
		??/perl-net-frame-device \
		??/perl-net-frame-dump \
		??/perl-net-frame-layer-icmp6 \
		??/perl-net-frame-layer-ipv6 \
		??/perl-net-frame-layer-sinfp3 \
		??/perl-net-frame-simple \
		??/perl-net-ipv4addr \
		??/perl-net-libdnet \
		??/perl-net-libdnet6 \
		??/perl-net-netmask \
		??/perl-net-write \
		??/perl-net-write-fast \
		??/perl-parallel-forkmanager \
		??/perl-time-interval


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
