PORTNAME=	perl-string-hexconvert
DISTVERSION=	0.02
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Converts ascii strings to hex and reverse.
WWW=		https://metacpan.org/pod/String::HexConvert

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
