PORTNAME=	sniffer
DISTVERSION=	4.688854e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Packet Trace Parser for TCP, SMTP Emails, and HTTP Cookies.
WWW=		https://github.com/julioreynaga/sniffer

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/clang \
		devel/git

RUN_DEPENDS=	net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
