PORTNAME=	honssh
DISTVERSION=	1.1.2.r2.g821ce87
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A high-interaction Honey Pot solution designed to log all SSH communications between a client and server.
WWW=		

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
