PORTNAME=	redress
DISTVERSION=	v1.2.2.r0.gfe38d96
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool for analyzing stripped Go binaries.
WWW=		https://github.com/goretk/redress

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
