PORTNAME=	python-python-flirt
DISTVERSION=	0.9.10
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Python library for parsing, compiling, and matching Fast Library Identification and Recognition Technology (FLIRT) signatures.
WWW=		https://pypi.org/project/python-flirt/#files

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
