PORTNAME=	ppfuzz
DISTVERSION=	31.80982ec
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A fast tool to scan client-side prototype pollution vulnerability written in Rust.
WWW=		https://github.com/dwisiswant0/ppfuzz

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/cargo \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
