PORTNAME=	stunner
DISTVERSION=	v0.5.8.r122.g1a421a3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Test and exploit STUN, TURN and TURN over TCP servers.
WWW=		https://github.com/firefart/stunner

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
