PORTNAME=	dietlibc
DISTVERSION=	0.35
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A libc optimized for small size.
WWW=		https://www.fefe.de/dietlibc/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
