PORTNAME=	iaxscan
DISTVERSION=	0.02
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Python based scanner for detecting live IAX/2 hosts and then enumerating (by bruteforce) users on those hosts.
WWW=		http://code.google.com/p/iaxscan/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
