PORTNAME=	ferret
DISTVERSION=	0.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Free Entity Relationship and SQL Tables autogeneration Tool. Exports to MySQL, Postgres, XML, SQL95.
WWW=		https://savannah.gnu.org/projects/ferret/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	ftp/wget

RUN_DEPENDS=	??/tcl \
		??/tk \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
