PORTNAME=	firewalk
DISTVERSION=	5.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An active reconnaissance network security tool.
WWW=		http://packetfactory.openwall.net/projects/firewalk/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libnet \
		net/libdnet \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
