PORTNAME=	nfex
DISTVERSION=	2.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool for extracting files from the network in real-time or post-capture from an offline tcpdump pcap savefile.
WWW=		https://code.google.com/p/nfex/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/libnet \
		??/subversion \
		net/libpcap



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
