PORTNAME=	bypass-firewall-dns-history
DISTVERSION=	33.c55b7ce
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Firewall bypass script based on DNS history records.
WWW=		https://github.com/vincentcox/bypass-firewalls-by-DNS-history

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
