PORTNAME=	bdlogparser
DISTVERSION=	2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This is a utility to parse a Bit Defender log file, in order to sort them into a malware archive for easier maintenance of your malware collection.
WWW=		http://magikh0e.xyz/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
