PORTNAME=	ffuf-scripts
DISTVERSION=	1.2192bf7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Scripts and snippets for ffuf payloads.
WWW=		https://github.com/ffuf/ffuf-scripts

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
