PORTNAME=	ruby-snmp
DISTVERSION=	1.3.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Ruby implementation of SNMP (the Simple Network Management Protocol).
WWW=		https://rubygems.org/gems/snmp

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	lang/ruby



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
