PORTNAME=	python2-pythonwhois
DISTVERSION=	2.4.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Module for retrieving and parsing the WHOIS data for a domain. Supports most domains.
WWW=		https://pypi.org/project/pythonwhois/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
