PORTNAME=	inetsim
DISTVERSION=	1.3.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A software suite for simulating common internet services in a lab environment, e.g. for analyzing the network behaviour of unknown malware samples.
WWW=		http://www.inetsim.org/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-ipc-shareable \
		??/perl-net-dns \
		??/perl-net-server \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
