PORTNAME=	python2-distutils-extra
DISTVERSION=	2.39
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Enables you to easily integrate gettext support, themed icons and scrollkeeper based documentation into Pythons distutils.
WWW=		https://launchpad.net/python-distutils-extra

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	??/intltool \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
