PORTNAME=	minimysqlator
DISTVERSION=	0.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A multi-platform application used to audit web sites in order to discover and exploit SQL injection vulnerabilities.
WWW=		http://www.scrt.ch/en/attack/downloads/mini-mysqlat0r

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
