PORTNAME=	blacknurse
DISTVERSION=	12.934b6a2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A low bandwidth ICMP attack that is capable of doing denial of service to well known firewalls.
WWW=		https://github.com/jedisct1/blacknurse

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
