PORTNAME=	ruby-mechanize
DISTVERSION=	2.14.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Automates interaction with websites, handling cookies, redirects and forms.
WWW=		https://rubygems.org/gems/mechanize

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/ruby-rdoc \
		lang/ruby

RUN_DEPENDS=	??/ruby-domain_name \
		??/ruby-http-cookie \
		??/ruby-mime-types \
		??/ruby-net-http-digest_auth \
		??/ruby-net-http-persistent \
		??/ruby-nokogiri \
		??/ruby-ntlm-http \
		??/ruby-webrobots \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
