PORTNAME=	saleae-logic
DISTVERSION=	2.3.47
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Debug happy.
WWW=		https://www.saleae.com/downloads

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libxss


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
