PORTNAME=	libbtbb
DISTVERSION=	2020.12.R1.r7.gf0fe176
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Bluetooth baseband decoding library.
WWW=		https://github.com/greatscottgadgets/libbtbb

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		??/py-distutils-extra@${PY_FLAVOR} \
		devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
