PORTNAME=	zizzania
DISTVERSION=	124.8f2062f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Automated DeAuth attack.
WWW=		https://github.com/cyrus-and/zizzania

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/scons \
		devel/git

RUN_DEPENDS=	??/uthash \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
