PORTNAME=	noriben
DISTVERSION=	2.0.r5.g35327a6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Portable, Simple, Malware Analysis Sandbox.
WWW=		https://github.com/Rurik/Noriben

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-magic@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
