PORTNAME=	morxbtcrack
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Single Bitcoin private key cracking tool released.
WWW=		http://www.morxploit.com/tools/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/morxkeyfmt \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
