PORTNAME=	dnswalk
DISTVERSION=	2.0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A DNS debugger and zone-transfer utility.
WWW=		http://sourceforge.net/projects/dnswalk/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl-net-dns


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
