PORTNAME=	brakeman
DISTVERSION=	v8.0.2.r0.gc07289241
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A static analysis security vulnerability scanner for Ruby on Rails applications.
WWW=		https://brakemanscanner.org/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/ruby \
		sysutils/rubygem-bundler


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
