PORTNAME=	libdab
DISTVERSION=	dab.cmdline.0.8.r354.gd621d6c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	DAB decoding library.
WWW=		https://github.com/JvanKatwijk/dab-cmdline

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git

RUN_DEPENDS=	??/faad2 \
		??/fftw


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
