PORTNAME=	ruby-ntlm-http
DISTVERSION=	0.1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Ruby/NTLM HTTP library.
WWW=		https://rubygems.org/gems/ntlm-http

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	lang/ruby



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
