PORTNAME=	saruman
DISTVERSION=	2.4be8db5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	ELF anti-forensics exec, for injecting full dynamic executables into process image (With thread injection).
WWW=		https://github.com/elfmaster/saruman

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
