PORTNAME=	feroxbuster
DISTVERSION=	v2.13.1.r16.g242b134
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A fast, simple, recursive content discovery tool written in Rust.
WWW=		https://github.com/epi052/feroxbuster

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/cargo \
		devel/git

RUN_DEPENDS=	??/pkgconf \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
