PORTNAME=	bing-ip2hosts
DISTVERSION=	1.0.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Enumerates all hostnames which Bing has indexed for a specific IP address.
WWW=		https://github.com/urbanadventurer/bing-ip2hosts/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/bind-tools \
		ftp/wget \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
