PORTNAME=	cnamulator
DISTVERSION=	5.4667c68
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A phone CNAM lookup utility using the OpenCNAM API.
WWW=		https://github.com/packetassailant/cnamulator

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
