PORTNAME=	tracedump
DISTVERSION=	23.921e0f2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	tcpdump of single programs - captures all tcp andudp packets of a signle program.
WWW=		https://github.com/iitis/tracedump

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/gcc \
		??/libpjf \
		??/linux-headers \
		??/pcre \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
