PORTNAME=	xsscrapy
DISTVERSION=	153.4966255
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	XSS spider - 66/66 wavsep XSS detected.
WWW=		https://github.com/DanMcInerney/xsscrapy

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-pip@${PY_FLAVOR} \
		devel/git

RUN_DEPENDS=	??/py-typing@${PY_FLAVOR} \
		??/py-virtualenv@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
