PORTNAME=	sidguesser
DISTVERSION=	1.0.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Guesses sids/instances against an Oracle database according to a predefined dictionary file.
WWW=		http://www.cqure.net/wp/tools/database/sidguesser/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
