PORTNAME=	galleta
DISTVERSION=	20040505.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Examine the contents of the IEs cookie files for forensic purposes.
WWW=		https://www.jonesdykstra.com/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
