PORTNAME=	perl-net-socks
DISTVERSION=	0.03
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	TCP/IP access through firewalls using SOCKS.
WWW=		http://search.cpan.org/~CLINTDW/SOCKS

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
