PORTNAME=	manul
DISTVERSION=	197.f525df9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A coverage-guided parallel fuzzer for open-source and blackbox binaries on Windows, Linux and MacOS.
WWW=		https://github.com/mxmssh/manul

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-psutil@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
