PORTNAME=	python2-filebytes
DISTVERSION=	0.10.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Classes to parse the following file formats - Executable and Linking Format (ELF) , Portable Executable (PE), Mach-O and OAT (Android Runtime).
WWW=		https://pypi.org/project/filebytes/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
