PORTNAME=	sipbrute
DISTVERSION=	11.5be2fdd
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A utility to perform dictionary attacks against the VoIP SIP Register hash.
WWW=		https://github.com/packetassailant/sipbrute

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
