PORTNAME=	facebrok
DISTVERSION=	33.0f6fe8d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Social Engineering Tool Oriented to facebook.
WWW=		https://github.com/PowerScript/facebrok

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/mariadb \
		lang/php82


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
