PORTNAME=	logkeys
DISTVERSION=	97.98aac72
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A GNU/Linux keylogger that worked.
WWW=		https://github.com/kernc/logkeys

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/kbd \
		??/procps-ng


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
