PORTNAME=	fernmelder
DISTVERSION=	0.4s2.r2.g030212e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Asynchronous mass DNS scanner.
WWW=		https://github.com/stealth/fernmelder

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
