PORTNAME=	python-rfc5424-logging-handler
DISTVERSION=	1.4.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An up-to-date, RFC5424-Compliant syslog handler for the Python logging framework.
WWW=		https://pypi.org/project/rfc5424-logging-handler/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
