PORTNAME=	wmi-client
DISTVERSION=	1.3.13
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Linux WMI client.
WWW=		https://bitbucket.org/instarch/wmi-client/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gnutls \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
