PORTNAME=	athena-ssl-scanner
DISTVERSION=	0.6.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A SSL cipher scanner that checks all cipher codes. It can identify about 150 different ciphers.
WWW=		http://packetstormsecurity.com/files/93062/Athena-SSL-Cipher-Scanner.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
