PORTNAME=	username-anarchy
DISTVERSION=	72.e063191
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tools for generating usernames when penetration testing.
WWW=		http://www.morningstarsecurity.com/research/username-anarchy

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
