PORTNAME=	gcrypt
DISTVERSION=	32.d3f9f06
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Simple, secure and performance file encryption tool written in C
WWW=		https://gitlab.com/GasparVardanyan/gcrypt

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/libbsd


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
