PORTNAME=	dissy
DISTVERSION=	10
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A graphical frontend to the objdump disassembler for compiler-generated code.
WWW=		http://dissy.googlecode.com/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/pygtk \
		??/pywebkitgtk


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
