PORTNAME=	adassault
DISTVERSION=	0.0.4.r0.g8a1a243
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An Active Directory environments pentest tool complementary to existing ones like NetExec.
WWW=		https://noraj.github.io/ADAssault/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/ruby-erb \
		lang/ruby \
		sysutils/rubygem-bundler


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
