PORTNAME=	gene
DISTVERSION=	78.faf8cc0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Signature Engine for Windows Event Logs.
WWW=		https://github.com/0xrawsec/gene

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
