PORTNAME=	insanity
DISTVERSION=	117.cf51ff3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Generate Payloads and Control Remote Machines .
WWW=		https://github.com/4w4k3/Insanity-Framework

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	emulators/wine \
		ftp/wget \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
