PORTNAME=	zerowine
DISTVERSION=	0.0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Malware Analysis Tool - research project to dynamically analyze the behavior of malware
WWW=		http://zerowine.sf.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
