PORTNAME=	perl-algorithm-generatesequence
DISTVERSION=	0.02
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A sequence generator.
WWW=		http://www.cpan.org/authors/id/R/RC/RCLAMP/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
