PORTNAME=	lethalhta
DISTVERSION=	2.5602402
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Lateral Movement technique using DCOM and HTA.
WWW=		https://github.com/codewhitesec/LethalHTA

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/mono-msbuild \
		??/mono-msbuild-sdkresolver \
		devel/git

RUN_DEPENDS=	??/mono


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
