PORTNAME=	bkhive
DISTVERSION=	1.1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Program for dumping the syskey bootkey from a Windows NT/2K/XP system hive.
WWW=		http://sourceforge.net/projects/ophcrack

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
