PORTNAME=	replayproxy
DISTVERSION=	1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Forensic tool to replay web-based attacks (and also general HTTP traffic) that were captured in a pcap file.
WWW=		https://code.google.com/p/replayproxy/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-dpkt@${PY_FLAVOR} \
		??/py-pynids@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
