PORTNAME=	verinice
DISTVERSION=	1.28.0.r0.g4337e9c7e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool for managing information security.
WWW=		https://github.com/SerNet/verinice

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/jdk8-openjdk \
		??/maven \
		??/which \
		archivers/unzip \
		devel/git

RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
