PORTNAME=	dnssearch
DISTVERSION=	20.e4ea439
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A subdomain enumeration tool.
WWW=		https://github.com/evilsocket/dnssearch

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
