PORTNAME=	cryptohazemultiforcer
DISTVERSION=	1.31a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	High performance multihash brute forcer with CUDA support.
WWW=		http://www.cryptohaze.com/multiforcer.php

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
