PORTNAME=	snscan
DISTVERSION=	1.05
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Windows based SNMP detection utility that can quickly and accurately identify SNMP enabled devices on a network.
WWW=		http://www.mcafee.com/uk/downloads/free-tools/snscan.aspx

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
