PORTNAME=	mapcidr
DISTVERSION=	v1.1.97.r64.g19549b4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Utility program to perform multiple operations for a given subnet/CIDR ranges.
WWW=		https://github.com/projectdiscovery/mapcidr

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
