PORTNAME=	perl-modern-perl
DISTVERSION=	1.20200211
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Enable all of the features of Modern Perl with one command.
WWW=		https://metacpan.org/release/Modern-Perl

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
