PORTNAME=	pathzuzu
DISTVERSION=	64.4f4533c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Checks for PATH substitution vulnerabilities and logs the commands executed by the vulnerable executables.
WWW=		https://github.com/ShotokanZH/Pa-th-zuzu

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
