PORTNAME=	grepcidr
DISTVERSION=	2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Filter IPv4 and IPv6 addresses matching CIDR patterns.
WWW=		http://www.pc-tools.net/unix/grepcidr/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
