PORTNAME=	savvycan
DISTVERSION=	continuous.r0.geb1ea2e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	QT-based CAN bus analysis tool.
WWW=		https://github.com/collin80/SavvyCAN

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/qt5-base \
		??/qt5-declarative \
		??/qt5-tools \
		devel/git

RUN_DEPENDS=	??/qt5-serialbus


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
