PORTNAME=	python-googletransx
DISTVERSION=	2.4.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Free Google Translate API for Python. Translates totally free of charge.
WWW=		https://pypi.org/project/googletransx/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
