PORTNAME=	second-order
DISTVERSION=	v3.2.r12.g400a81d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Second-order subdomain takeover scanner.
WWW=		https://github.com/mhmdiaa/second-order

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
