PORTNAME=	postman
DISTVERSION=	10.20
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Build, test, and document your APIs faster.
WWW=		https://www.postman.com/downloads/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gtk3 \
		??/libxss \
		??/nss


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
