PORTNAME=	dhcdrop
DISTVERSION=	0.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Remove illegal dhcp servers with IP-pool underflow.
WWW=		http://www.netpatch.ru/dhcdrop.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
