PORTNAME=	openssl-1.0
DISTVERSION=	${.ver/[a.z]/.${.ver//[0.9.]/}}
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The Open Source toolkit for Secure Sockets Layer and Transport Layer Security with Chacha20 cipher.
WWW=		https://www.openssl.org

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
