PORTNAME=	qtwebkit
DISTVERSION=	2.3.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An open source web browser engine.
WWW=		http://trac.webkit.org/wiki/QtWebKit

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/mesa

RUN_DEPENDS=	??/gst-plugins-base-libs \
		??/qt4 \
		??/systemd


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
