PORTNAME=	python-plaso
DISTVERSION=	20201007
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Super timeline all the things.
WWW=		https://github.com/log2timeline/plaso

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	??/py-artifacts@${PY_FLAVOR} \
		??/py-bencode.py@${PY_FLAVOR} \
		??/py-biplist@${PY_FLAVOR} \
		??/py-certifi@${PY_FLAVOR} \
		??/py-chardet@${PY_FLAVOR} \
		??/py-cryptography@${PY_FLAVOR} \
		??/py-dateutil@${PY_FLAVOR} \
		??/py-defusedxml@${PY_FLAVOR} \
		??/py-dfdatetime@${PY_FLAVOR} \
		??/py-dfvfs@${PY_FLAVOR} \
		??/py-dfwinreg@${PY_FLAVOR} \
		??/py-dtfabric@${PY_FLAVOR} \
		??/py-efilter@${PY_FLAVOR} \
		??/py-elasticsearch@${PY_FLAVOR} \
		??/py-future@${PY_FLAVOR} \
		??/py-idna@${PY_FLAVOR} \
		??/py-libbde-python@${PY_FLAVOR} \
		??/py-libcreg-python@${PY_FLAVOR} \
		??/py-libesedb-python@${PY_FLAVOR} \
		??/py-libevt-python@${PY_FLAVOR} \
		??/py-libevtx-python@${PY_FLAVOR} \
		??/py-libewf-python@${PY_FLAVOR} \
		??/py-libfsapfs-python@${PY_FLAVOR} \
		??/py-libfsntfs-python@${PY_FLAVOR} \
		??/py-libfvde-python@${PY_FLAVOR} \
		??/py-libfwnt-python@${PY_FLAVOR} \
		??/py-libfwsi-python@${PY_FLAVOR} \
		??/py-liblnk-python@${PY_FLAVOR} \
		??/py-libluksde-python@${PY_FLAVOR} \
		??/py-libmsiecf-python@${PY_FLAVOR} \
		??/py-libolecf-python@${PY_FLAVOR} \
		??/py-libqcow-python@${PY_FLAVOR} \
		??/py-libregf-python@${PY_FLAVOR} \
		??/py-libscca-python@${PY_FLAVOR} \
		??/py-libsigscan-python@${PY_FLAVOR} \
		??/py-libsmdev-python@${PY_FLAVOR} \
		??/py-libsmraw-python@${PY_FLAVOR} \
		??/py-libvhdi-python@${PY_FLAVOR} \
		??/py-libvmdk-python@${PY_FLAVOR} \
		??/py-libvshadow-python@${PY_FLAVOR} \
		??/py-libvslvm-python@${PY_FLAVOR} \
		??/py-lz4@${PY_FLAVOR} \
		??/py-pefile@${PY_FLAVOR} \
		??/py-psutil@${PY_FLAVOR} \
		??/py-pyaml@${PY_FLAVOR} \
		??/py-pycryptodome@${PY_FLAVOR} \
		??/py-pyparsing@${PY_FLAVOR} \
		??/py-pytsk3@${PY_FLAVOR} \
		??/py-pytz@${PY_FLAVOR} \
		??/py-pyzmq@${PY_FLAVOR} \
		??/py-redis@${PY_FLAVOR} \
		??/py-urllib3@${PY_FLAVOR} \
		??/py-xlsxwriter@${PY_FLAVOR} \
		??/py-yara-dex@${PY_FLAVOR} \
		devel/py-pip@${PY_FLAVOR} \
		devel/py-six@${PY_FLAVOR} \
		lang/python \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
