PORTNAME=	python-unqlite
DISTVERSION=	1.0.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fast Python bindings for the UnQLite embedded NoSQL database.
WWW=		https://pypi.org/project/unqlite/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cython \
		??/cython2 \
		devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
