PORTNAME=	wiredtiger
DISTVERSION=	10.0.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	High performance, scalable, production quality, NoSQL, Open Source extensible platform for data management.
WWW=		https://github.com/wiredtiger/wiredtiger/releases

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/rsync

RUN_DEPENDS=	??/gperftools \
		??/lz4 \
		??/snappy \
		??/zlib


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
