PORTNAME=	dtp-spoof
DISTVERSION=	5.3ae05fc
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python script/security tool to test Dynamic Trunking Protocol configuration on a switch.
WWW=		https://github.com/fleetcaptain/dtp-spoof

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3 \
		net/py-scapy@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
