PORTNAME=	go-bindata
DISTVERSION=	4.0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A small utility which generates Go code from any file.
WWW=		https://github.com/kevinburke/go-bindata

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
