PORTNAME=	pcapsipdump
DISTVERSION=	0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool for dumping SIP sessions (+RTP traffic, if available) to disk in a fashion similar to tcpdump -w (format is exactly the same), but one file per sip session (even if there is thousands of concurrent SIP sessions).
WWW=		http://pcapsipdump.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
