PORTNAME=	base64dump
DISTVERSION=	0.0.14
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Extract and decode base64 strings from files.
WWW=		https://blog.didierstevens.com/my-software/#base64dump

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
