PORTNAME=	cachedump
DISTVERSION=	1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool that demonstrates how to recover cache entry information: username and hashed password (called MSCASH).
WWW=		https://packetstormsecurity.com/files/36781/cachedump-1.1.zip.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
