PORTNAME=	check-weak-dh-ssh
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Debian OpenSSL weak client Diffie-Hellman Exchange checker.
WWW=		http://packetstormsecurity.com/files/66683/check_weak_dh_ssh.pl.bz2.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-data-dumper \
		??/perl-getopt-long \
		??/perl-math-bigint-gmp \
		??/perl-net-packet


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
