PORTNAME=	scap-security-guide
DISTVERSION=	0.1.60
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Security compliance content in SCAP, Bash, Ansible, and other formats.
WWW=		https://www.open-scap.org/security-policies/scap-security-guide/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
