PORTNAME=	mitmap-old
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Shell Script for launching a Fake AP with karma functionality and launches ettercap for packet capture and traffic manipulation.
WWW=		http://www.darkoperator.com/tools-and-scripts/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/aircrack-ng \
		??/dhcp \
		??/ettercap \
		??/iptables \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
