PORTNAME=	rdpassspray
DISTVERSION=	33.c1ba58e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python3 tool to perform password spraying using RDP.
WWW=		https://github.com/xFreed0m/RDPassSpray

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/freerdp \
		??/py-colorlog@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
