PORTNAME=	bruteforce-salted-openssl
DISTVERSION=	64.30b272e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Try to find the password of a file that was encrypted with the openssl command.
WWW=		https://github.com/glv2/bruteforce-salted-openssl

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
