PORTNAME=	easy-creds
DISTVERSION=	45.bf9f00c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A bash script that leverages ettercap and other tools to obtain credentials.
WWW=		https://github.com/brav0hax/easy-creds

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/aircrack-ng \
		??/asleap \
		??/dhcp \
		??/dsniff \
		??/ettercap \
		??/freeradius \
		??/hamster \
		??/hostapd \
		??/ipcalc \
		??/mdk3 \
		??/metasploit \
		??/screen \
		??/sslstrip \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
