PORTNAME=	python-badges
DISTVERSION=	102.5fdc197
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python library that is used for advanced and intuitive printing.
WWW=		htps://github.com/EntySec/Badges

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	??/py-colorscript@${PY_FLAVOR} \
		??/py-translate@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
