PORTNAME=	netsed
DISTVERSION=	1.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Small and handful utility design to alter the contents of packets forwarded thru network in real time.
WWW=		http://silicone.homelinux.org/projects/netsed/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
