PORTNAME=	sgn
DISTVERSION=	36.f54fa65
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Shikata ga nai encoder ported into go with several improvements.
WWW=		https://github.com/EgeBalci/sgn

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go

RUN_DEPENDS=	??/capstone \
		??/keystone


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
