PORTNAME=	ssl-phuck3r
DISTVERSION=	2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	All in one script for Man-In-The-Middle attacks.
WWW=		https://github.com/zombiesam/ssl_phuck3r

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/driftnet \
		??/dsniff \
		??/ettercap \
		??/iptables \
		??/sslstrip \
		??/xterm \
		security/nmap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
