PORTNAME=	blackarch-installer
DISTVERSION=	1.2.24
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The official BlackArch Linux installer.
WWW=		https://github.com/BlackArch/blackarch-installer

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
