PORTNAME=	flyr
DISTVERSION=	76.4926ecc
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Block-based software vulnerability fuzzing framework.
WWW=		https://github.com/zznop/flyr

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/scons \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
