PORTNAME=	merlin-server
DISTVERSION=	1.3.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Merlin is a cross-platform post-exploitation HTTP/2 Command & Control server and agent written in golang.
WWW=		https://github.com/Ne0nd0g/merlin

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/p7zip \
		ftp/wget



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
