PORTNAME=	pyqt4-common
DISTVERSION=	4.12.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	
WWW=		https://riverbankcomputing.com/software/pyqt/intro

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/mesa \
		??/phonon-qt4 \
		??/py-dbus@${PY_FLAVOR} \
		??/py-distutils-extra@${PY_FLAVOR} \
		??/py-opengl@${PY_FLAVOR} \
		??/py-sip-pyqt4@${PY_FLAVOR} \
		??/sip4



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
