PORTNAME=	stacoan
DISTVERSION=	0.90
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Crossplatform tool which aids developers, bugbounty hunters and ethical hackers performing static code analysis on mobile applications.
WWW=		https://github.com/vincentcox/StaCoAn

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	archivers/unzip



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
