PORTNAME=	wirouter-keyrec
DISTVERSION=	1.1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A platform independent software to recover the default WPA passphrases of the supported router models
WWW=		http://www.salvatorefresta.net/tools/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
