PORTNAME=	adfind
DISTVERSION=	v1.0.3.r3.g46acf19
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Simple admin panel finder for php,js,cgi,asp and aspx admin panels.
WWW=		https://github.com/sahakkhotsanyan/adfind

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
