PORTNAME=	blackarch-config-calamares
DISTVERSION=	20.b453a21
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	BlackArch config for the calamares installer.
WWW=		https://github.com/BlackArch/blackarch-config-calamares

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/calamares


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
