PORTNAME=	perl-net-frame-device
DISTVERSION=	1.12
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Get network device information and gateway.
WWW=		http://search.cpan.org/~gomor/Net-Frame-Device/lib/Net/Frame/Device.pm

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-bit-vector \
		??/perl-carp-clan \
		??/perl-class-gomor \
		??/perl-net-frame \
		??/perl-net-frame-dump \
		??/perl-net-frame-layer-icmp6 \
		??/perl-net-frame-layer-ipv6 \
		??/perl-net-libdnet6 \
		??/perl-net-pcap \
		??/perl-net-write \
		??/perl-sub-uplevel \
		??/perl-test-exception


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
