PORTNAME=	dnsprobe
DISTVERSION=	56.7120008
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Allows you to perform multiple dns queries of your choice with a list of user supplied resolvers.
WWW=		https://github.com/projectdiscovery/dnsprobe

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
