PORTNAME=	phoneinfoga
DISTVERSION=	v2.11.0.r3.g041f34a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Information gathering & OSINT framework for phone numbers.
WWW=		https://github.com/sundowndev/PhoneInfoga

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
