PORTNAME=	spiga
DISTVERSION=	688.87fe9af
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Configurable web resource scanner.
WWW=		https://github.com/getdual/scripts-n-tools/blob/master/spiga.py

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
