PORTNAME=	jaeles
DISTVERSION=	233.243e0b6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The Swiss Army knife for automated Web Application Testing.
WWW=		https://github.com/jaeles-project/jaeles

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
