PORTNAME=	periscope
DISTVERSION=	3.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A PE file inspection tool.
WWW=		https://vidstromlabs.com/freetools/periscope/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
