PORTNAME=	python-jsonpath-rw
DISTVERSION=	1.4.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A robust and significantly extended implementation of JSONPath for Python.
WWW=		https://pypi.org/project/jsonpath-rw/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
