PORTNAME=	pafish
DISTVERSION=	193.b497899
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A demonstration tool that employs several techniques to detect sandboxes and analysis environments in the same way as malware families do.
WWW=		http://www.hoobie.net/pafish/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
