PORTNAME=	dsfs
DISTVERSION=	36.8e9f8e9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A fully functional File inclusion vulnerability scanner (supporting GET and POST parameters) written in under 100 lines of code.
WWW=		https://github.com/stamparm/DSFS

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
