PORTNAME=	joomscan
DISTVERSION=	83.2ea8cc7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Detects file inclusion, sql injection, command execution vulnerabilities of a target Joomla! web site.
WWW=		http://joomscan.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/dos2unix \
		devel/git

RUN_DEPENDS=	??/perl-switch \
		??/perl-term-ansicolor \
		??/perl-www-mechanize


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
