PORTNAME=	rabid
DISTVERSION=	v0.3.0.r1.gc4bad99
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A CLI tool and library allowing to simply decode all kind of BigIP cookies.
WWW=		https://noraj.github.io/rabid/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/ruby-docopt \
		??/ruby-paint \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
