PORTNAME=	netkit-bsd-finger
DISTVERSION=	0.17
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	BSD-finger ported to Linux.
WWW=		http://ftp.linux.org.uk/pub/linux/Networking/netkit

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
