PORTNAME=	kautilya
DISTVERSION=	52.1c9d5b0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Pwnage with Human Interface Devices using Teensy++2.0 and Teensy 3.0 devices.
WWW=		https://github.com/samratashok/Kautilya/releases

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/ruby \
		net/libpcap \
		sysutils/rubygem-bundler


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
