PORTNAME=	nsia
DISTVERSION=	1.0.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A website scanner that monitors websites in realtime in order to detect defacements, compliance violations, exploits, sensitive information disclosure and other issues.
WWW=		http://threatfactor.com/Products/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/dos2unix

RUN_DEPENDS=	??/java-environment \
		??/libstdc++5 \
		??/swt \
		??/systemd


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
