PORTNAME=	phrasendrescher
DISTVERSION=	1.2.2c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A modular and multi processing pass phrase cracking tool.
WWW=		http://www.leidecker.info/projects/phrasendrescher/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gpgme \
		??/libssh2 \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
