PORTNAME=	syms2elf
DISTVERSION=	12.329c2ce
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A plugin for Hex-Rays IDA Pro and radare2 to export the symbols recognized to the ELF symbol table.
WWW=		https://github.com/danigargu/syms2elf

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
