PORTNAME=	atscan
DISTVERSION=	2461.06521a9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Server, Site and Dork Scanner.
WWW=		https://github.com/AlisamTechnology/ATSCAN-V3.1

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/dos2unix \
		devel/git

RUN_DEPENDS=	??/perl \
		??/perl-encode-locale \
		??/perl-file-copy-recursive \
		??/perl-getopt-long \
		??/perl-html-parser \
		??/perl-http-cookies \
		??/perl-http-message \
		??/perl-io-socket \
		??/perl-libwww \
		??/perl-term-ansicolor \
		??/perl-term-readkey \
		??/perl-uri


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
