PORTNAME=	taof
DISTVERSION=	0.3.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A GUI cross-platform Python generic network protocol fuzzer.
WWW=		http://taof.sf.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-gobject@${PY_FLAVOR} \
		??/py-twistedx@${PY_FLAVOR} \
		??/pygtk \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
