PORTNAME=	sylkie
DISTVERSION=	0.0.4.r3.g1cf170f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	IPv6 address spoofing with the Neighbor Discovery Protocol.
WWW=		https://github.com/dlrobertson/sylkie

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git

RUN_DEPENDS=	??/json-c \
		??/libseccomp


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
