PORTNAME=	perl-crypt-openssl-x509
DISTVERSION=	1.908
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl extension to OpenSSLs X509 API.
WWW=		https://metacpan.org/pod/Crypt::OpenSSL::X509

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
