PORTNAME=	ida-free
DISTVERSION=	8.4.240527
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Freeware version of the worlds smartest and most feature-full disassembler.
WWW=		https://hex-rays.com/ida-free/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/fakechroot



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
