PORTNAME=	rlogin-scanner
DISTVERSION=	0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Multithreaded rlogin scanner. Tested on Linux, OpenBSD and Solaris.
WWW=		http://wayreth.eu.org/old_page/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
