PORTNAME=	perl-net-dns-lite
DISTVERSION=	0.12
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A pure-perl DNS resolver with support for timeout.
WWW=		https://metacpan.org/pod/Net::DNS::Lite

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl-module-install

RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
