PORTNAME=	sslnuke
DISTVERSION=	5.c5faeaa
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Transparent proxy that decrypts SSL traffic and prints out IRC messages.
WWW=		https://github.com/jtripper/sslnuke

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
