PORTNAME=	jstillery
DISTVERSION=	65.512e9af
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Advanced JavaScript Deobfuscation via Partial Evaluation.
WWW=		https://github.com/mindedsecurity/JStillery

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		www/npm

RUN_DEPENDS=	www/node


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
