PORTNAME=	magicrescue
DISTVERSION=	v1.1.10.r8.gd9a5793
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Find and recover deleted files on block devices.
WWW=		https://github.com/jbj/magicrescue

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
