PORTNAME=	spectrwm
DISTVERSION=	3.7.0.r1.gf6385bc
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A minimalistic automatic tiling window manager that tries to stay out of the way.
WWW=		https://github.com/conformal/spectrwm/releases

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/libxt \
		devel/git

RUN_DEPENDS=	??/dmenu \
		??/fontconfig \
		??/libbsd \
		??/libx11 \
		??/libxcb \
		??/libxcursor \
		??/libxft \
		??/libxrandr \
		??/terminus-font \
		??/xcb-util \
		??/xcb-util-keysyms \
		??/xcb-util-wm


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
