PORTNAME=	python-alexa-top-sites
DISTVERSION=	5.98d6109
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python library to fetch the top 1..N (where N < 1 million) sites from alexa.
WWW=		https://github.com/philarkwright/Alexa-Top-Sites

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
