PORTNAME=	linikatz
DISTVERSION=	48.d9cfdbf
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool to attack AD on UNIX.
WWW=		https://github.com/portcullislabs/linikatz

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
