PORTNAME=	ike-scan
DISTVERSION=	1.9.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool that uses IKE protocol to discover, fingerprint and test IPSec VPN servers.
WWW=		http://www.nta-monitor.com/tools/ike-scan/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gcc \
		??/make

RUN_DEPENDS=	security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
