PORTNAME=	ruby-cldr-plurals-runtime-rb
DISTVERSION=	1.1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Ruby runtime methods for CLDR plural rules (see camertron/cldr-plurals).
WWW=		https://github.com/camertron/cldr-plurals-runtime-rb

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
