PORTNAME=	lulzbuster
DISTVERSION=	1.3.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A very fast and smart web directory and file enumeration tool written in C.
WWW=		http://www.nullsecurity.net/tools/scanner.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	ftp/curl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
