PORTNAME=	xssya
DISTVERSION=	13.cd62817
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Cross Site Scripting Scanner & Vulnerability Confirmation.
WWW=		https://github.com/yehia-mamdouh/XSSYA

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-colorama@${PY_FLAVOR} \
		??/py-gdshortener@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
