PORTNAME=	mousejack
DISTVERSION=	5.58b69c1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Wireless mouse/keyboard attack with replay/transmit poc.
WWW=		https://github.com/iamckn/mousejack_transmit

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-pyusb@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
