PORTNAME=	hotpatch
DISTVERSION=	90.fd2baf1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Hot patches executables on Linux using .so file injection.
WWW=		http://www.selectiveintellect.com/hotpatch.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
