PORTNAME=	python2-beautifulsoup3
DISTVERSION=	3.2.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	HTML/XML parser for quick-turnaround applications like screen-scraping.
WWW=		https://pypi.python.org/pypi/BeautifulSoup/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
