PORTNAME=	payloadsallthethings
DISTVERSION=	4.2.r75.g66ef235
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A list of useful payloads and bypass for Web Application Security and Pentest/CTF.
WWW=		https://github.com/swisskyrepo/PayloadsAllTheThings/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
