PORTNAME=	facebash
DISTVERSION=	17.95c3c25
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Facebook Brute Forcer in shellscript using TOR.
WWW=		https://github.com/thelinuxchoice/facebash

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/tor \
		ftp/curl \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
