PORTNAME=	perl-crypt-des_ede3
DISTVERSION=	0.01
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl module for triple-DES EDE encryption/decryption.
WWW=		http://search.cpan.org/~btrott/Crypt-DES_EDE3

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl-crypt-des


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
