PORTNAME=	simple-lan-scan3
DISTVERSION=	1.0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple python3 script that leverages scapy for discovering live hosts on a network.
WWW=		https://codeberg.org/jahway603/Simple-LAN-Scanner3

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python \
		net/py-scapy@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
