PORTNAME=	bed
DISTVERSION=	0.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Collection of scripts to test for buffer overflows, format string vulnerabilities.
WWW=		http://www.aldeid.com/wiki/Bed

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
