PORTNAME=	linset
DISTVERSION=	9.8746b1f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Evil Twin Attack Bash script - An automated WPA/WPA2 hacker.
WWW=		https://github.com/vk496/linset

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/aircrack-ng \
		??/dhcp \
		??/gawk \
		??/hostapd \
		??/lighttpd \
		??/macchanger \
		??/mdk3 \
		??/php-cgi \
		??/pyrit \
		??/wireless_tools \
		??/xterm \
		archivers/unzip \
		ftp/curl \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
