PORTNAME=	silk
DISTVERSION=	3.24.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A collection of traffic analysis tools developed by the CERT NetSA to facilitate security analysis of large networks.
WWW=		https://tools.netsa.cert.org/silk/download.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/adns \
		??/c-ares \
		??/gnutls \
		??/libfixbuf \
		??/lzo \
		??/snappy \
		lang/python \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
