PORTNAME=	anontwi
DISTVERSION=	1.1b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A free software python client designed to navigate anonymously on social networks. It supports Identi.ca and Twitter.com.
WWW=		http://anontwi.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gtk2 \
		??/py-httplib2@${PY_FLAVOR} \
		??/py-pycryptodome@${PY_FLAVOR} \
		??/py-pycurl@${PY_FLAVOR} \
		??/pygtk \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
