PORTNAME=	pwdump
DISTVERSION=	7.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Extracts the binary SAM and SYSTEM file from the filesystem and then the hashes.
WWW=		http://www.tarasco.org/security/pwdump_7/index.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
