PORTNAME=	libsdrplay
DISTVERSION=	3.15.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Modules for the SDRplay receiver.
WWW=		https://www.sdrplay.com/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libusb


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
