PORTNAME=	recoverjpeg
DISTVERSION=	2.6.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Recover jpegs from damaged devices.
WWW=		https://github.com/samueltardieu/recoverjpeg

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
