PORTNAME=	rdp-cipher-checker
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Enumerate the encryption protocols supported by the server and the cipher strengths supported using native RDP encryption.
WWW=		https://labs.f-secure.com/tools/rdp-cipher-checker/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
