PORTNAME=	wpbrute-rpc
DISTVERSION=	3.e7d8145
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool for amplified bruteforce attacks on wordpress based website via xmlrcp API.
WWW=		https://github.com/zendoctor/wpbrute-rpc

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/ruby \
		sysutils/rubygem-bundler \
		textproc/libxslt


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
