PORTNAME=	gg-images
DISTVERSION=	35.b2dd863
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The application was created to allow anyone to easily download profile pictures from GG.
WWW=		https://codeberg.org/nanoory/gg_images

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/libglvnd \
		??/libxcursor \
		??/libxinerama \
		??/libxrandr \
		??/xorg-xinput \
		devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
