PORTNAME=	perl-cisco-copyconfig
DISTVERSION=	1.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	IOS running-config manipulation.
WWW=		http://search.cpan.org/dist/Cisco-CopyConfig

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl-net-snmp


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
