PORTNAME=	inurlbr
DISTVERSION=	34.dbf9773
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Advanced search in the search engines - Inurl scanner, dorker, exploiter.
WWW=		https://code.google.com/p/inurlbr/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/php82


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
