PORTNAME=	cminer
DISTVERSION=	25.d766f7e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool for enumerating the code caves in PE files.
WWW=		https://github.com/EgeBalci/Cminer/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
