PORTNAME=	lbmap
DISTVERSION=	147.2d15ace
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Proof of concept scripts for advanced web application fingerprinting, presented at OWASP AppSecAsia 2012.
WWW=		https://github.com/wireghoul/lbmap

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl \
		??/perl-data-dump \
		??/perl-getopt-long \
		??/perl-io-socket-ssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
