PORTNAME=	gsd
DISTVERSION=	1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Gives you the Discretionary Access Control List of any Windows NT service you specify as a command line option.
WWW=		https://vidstromlabs.com/freetools/gsd/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
