PORTNAME=	cloudlist
DISTVERSION=	853.18f6440
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool for listing Assets from multiple Cloud Providers.
WWW=		https://github.com/projectdiscovery/cloudlist

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
