PORTNAME=	dc3dd
DISTVERSION=	7.2.646
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A patched version of dd that includes a number of features useful for computer forensics.
WWW=		http://sourceforge.net/projects/dc3dd

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl-locale-gettext


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
