PORTNAME=	fakenetbios
DISTVERSION=	7.b83701e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A family of tools designed to simulate Windows hosts (NetBIOS) on a LAN.
WWW=		https://github.com/mubix/FakeNetBIOS

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
