PORTNAME=	python-pyexcel-ods
DISTVERSION=	0.6.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A wrapper library to read, manipulate and write data in ods format.
WWW=		https://pypi.org/project/pyexcel-ods/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	??/py-odfpy@${PY_FLAVOR} \
		??/py-pyexcel@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
