PORTNAME=	python2-rpi-gpio
DISTVERSION=	0.7.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A module to control Raspberry Pi GPIO channels.
WWW=		https://pypi.org/project/rpi-gpio/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
