PORTNAME=	bitdump
DISTVERSION=	34.6a5cbd8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool to extract database data from a blind SQL injection vulnerability.
WWW=		https://github.com/nbshelton/bitdump

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
