PORTNAME=	elevate
DISTVERSION=	27.1272d51
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Horizontal domain discovery tool you can use to discover other domains owned by a given company.
WWW=		https://github.com/Healdb/Elevate

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
