PORTNAME=	winregfs
DISTVERSION=	161.209a5d6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Windows Registry FUSE filesystem.
WWW=		https://github.com/jbruchon/winregfs

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/fuse \
		??/libjodycode


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
