PORTNAME=	bsqlbf
DISTVERSION=	2.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Blind SQL Injection Brute Forcer.
WWW=		http://code.google.com/p/bsqlbf-v2/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-getopt-long \
		??/perl-libwww


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
