PORTNAME=	brute-force
DISTVERSION=	52.78d1d8e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Brute-Force attack tool for Gmail Hotmail Twitter Facebook Netflix.
WWW=		https://github.com/Matrix07ksa/Brute_Force

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-mechanize@${PY_FLAVOR} \
		??/py-proxylist@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
