PORTNAME=	fortiscan
DISTVERSION=	0.7.r9.gbd8e460
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A high performance FortiGate SSL-VPN vulnerability scanning and exploitation tool.
WWW=		https://github.com/anasbousselham/fortiscan

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
