PORTNAME=	d-tect
DISTVERSION=	13.9555c25
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Pentesting the Modern Web.
WWW=		https://github.com/shawarkhanethicalhacker/D-TECT

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
