PORTNAME=	morxcrack
DISTVERSION=	1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A cracking tool written in Perl to perform a dictionary-based attack on various hashing algorithm and CMS salted-passwords.
WWW=		http://www.morxploit.com/morxcrack/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-digest-perl-md5 \
		??/perl-digest-sha \
		??/perl-io-socket


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
