PORTNAME=	pasco
DISTVERSION=	20040505.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Examines the contents of Internet Explorers cache files for forensic purposes.
WWW=		https://www.jonesdykstra.com/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
