PORTNAME=	python2-docx
DISTVERSION=	0.2.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The docx module creates, reads and writes Microsoft Office Word 2007 docx files.
WWW=		https://pypi.python.org/pypi/docx/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
