PORTNAME=	python2-pygoocanvas
DISTVERSION=	0.14.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python Bindings for goocanvas.
WWW=		https://github.com/dieterv/pygoocanvas

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gtk-doc \
		??/pkgconfig \
		devel/git

RUN_DEPENDS=	??/goocanvas \
		??/pygtk \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
