PORTNAME=	assassingo
DISTVERSION=	173.2dd8650
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Web pentest framework for information gathering and vulnerability scanning.
WWW=		https://github.com/AmyangXYZ/AssassinGo

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
