PORTNAME=	tsh
DISTVERSION=	0.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An open-source UNIX backdoor that compiles on all variants, has full pty support, and uses strong crypto for communication.
WWW=		http://packetstormsecurity.com/search/?q=tsh

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
