PORTNAME=	sc-make
DISTVERSION=	12.7e39718
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool for automating shellcode creation.
WWW=		https://github.com/t00sh/sc-make

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/binutils \
		??/nasm \
		??/perl \
		??/strace


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
