PORTNAME=	libusb3380
DISTVERSION=	16.92d102a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	USB3380 abstraction layer for libusb.
WWW=		https://github.com/xtrx-sdr/libusb3380

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
