PORTNAME=	python2-unicodecsv
DISTVERSION=	0.14.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python2s stdlib csv module is nice, but it doesnt support unicode. This module is a drop-in replacement which *does*.
WWW=		https://pypi.org/project/unicodecsv/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
