PORTNAME=	libnl1
DISTVERSION=	1.1.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Library for applications dealing with netlink sockets (Legacy version).
WWW=		https://www.infradead.org/~tgr/libnl/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
