PORTNAME=	samesame
DISTVERSION=	68.a9bcd7b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Command line tool to generate crafty homograph strings.
WWW=		https://github.com/TheTarquin/samesame

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/cargo \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
