PORTNAME=	http-parser
DISTVERSION=	2.9.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	HTTP request/response parser for C.
WWW=		https://github.com/nodejs/http-parser

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
