PORTNAME=	revsh
DISTVERSION=	267.36a9a90
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A reverse shell with terminal support, data tunneling, and advanced pivoting capabilities.
WWW=		https://github.com/emptymonkey/revsh/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
