PORTNAME=	cariddi
DISTVERSION=	v1.4.5.r3.ga32c495
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Take a list of domains, crawl urls and scan for endpoints, secrets, api keys, file extensions, token.
WWW=		https://github.com/edoardottt/cariddi

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
