PORTNAME=	nfdump
DISTVERSION=	1.6.23
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A set of tools to collect and process netflow data.
WWW=		https://github.com/phaag/nfdump

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/autoconf \
		??/automake \
		??/bison \
		??/flex

RUN_DEPENDS=	net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
