PORTNAME=	pnscan
DISTVERSION=	1.14.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A parallel network scanner that can be used to survey TCP network services.
WWW=		http://www.lysator.liu.se/~pen/pnscan/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
