PORTNAME=	pygtksourceview2
DISTVERSION=	2.10.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python bindings for gtksourceview2.
WWW=		http://www.gnome.org/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/intltool \
		??/pkg-config

RUN_DEPENDS=	??/gtksourceview2 \
		??/pygtk


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
