PORTNAME=	expimp-lookup
DISTVERSION=	4.79a96c7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Looks for all export and import names that contain a specified string in all Portable Executable in a directory tree.
WWW=		https://github.com/tr3w/ExpImp-Lookup

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
