PORTNAME=	pret
DISTVERSION=	108.a04bd04
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Printer Exploitation Toolkit - The tool that made dumpster diving obsolete.
WWW=		https://github.com/RUB-NDS/PRET

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-pysnmp@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
