PORTNAME=	gqrx-scanner
DISTVERSION=	1.0.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A frequency scanner for Gqrx Software Defined Radio receiver.
WWW=		https://github.com/neural75/gqrx-scanner

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
