PORTNAME=	python2-utidylib
DISTVERSION=	0.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python bindings for Tidy HTML parser/cleaner.
WWW=		http://utidylib.berlios.de

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR} \
		lang/python3

RUN_DEPENDS=	??/tidyhtml


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
