PORTNAME=	blackarch-config-icons
DISTVERSION=	6.f4bf107
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	BlackArch icons theme.
WWW=		https://github.com/BlackArch/blackarch-config-icons

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/gtk-update-icon-cache


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
