PORTNAME=	python2-gobject2
DISTVERSION=	2.28.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Legacy Python 2 bindings for GObject
WWW=		https://wiki.gnome.org/Projects/PyGObject

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/glib2 \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
