PORTNAME=	rita
DISTVERSION=	v5.1.1.r0.ga3c5150
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Real Intelligence Threat Analytics.
WWW=		https://github.com/activecm/rita

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go

RUN_DEPENDS=	??/bro \
		??/mongodb


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
