PORTNAME=	fssb
DISTVERSION=	73.51d2ac2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A low-level filesystem sandbox for Linux using syscall intercepts.
WWW=		https://github.com/adtac/fssb

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
