PORTNAME=	dnstracer
DISTVERSION=	1.10
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Determines where a given DNS server gets its information from, and follows the chain of DNS servers
WWW=		https://www.mavetju.org/unix/dnstracer.php

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
