PORTNAME=	zeus
DISTVERSION=	111.97db152
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	AWS Auditing & Hardening Tool.
WWW=		https://github.com/DenizParlak/Zeus

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/aws-cli \
		devel/py-pip@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
