PORTNAME=	python2-hgapi
DISTVERSION=	1.7.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A pure-Python API to Mercurial, that uses the command-line interface instead of the internal Mercurial API.
WWW=		https://bitbucket.org/haard/hgapi/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/mercurial \
		devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
