PORTNAME=	liblognorm
DISTVERSION=	2.0.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Log normalization library for rsyslog.
WWW=		http://www.liblognorm.com/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/json-c \
		??/libee \
		??/libfastjson \
		??/py-sphinx@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
