PORTNAME=	python2-txsocksx
DISTVERSION=	1.15.0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Twisted client endpoints for SOCKS{4,4a,5}.
WWW=		https://pypi.python.org/pypi/txsocksx/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
