PORTNAME=	jboss-autopwn
DISTVERSION=	2.986085d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A JBoss script for obtaining remote shell access.
WWW=		https://github.com/SpiderLabs/jboss-autopwn

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/metasploit \
		??/sbd \
		ftp/curl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
