PORTNAME=	braces
DISTVERSION=	0.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Bluetooth Tracking Utility.
WWW=		http://braces.shmoo.com/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/bluez \
		??/imagemagick \
		??/mariadb \
		??/nginx \
		??/perl \
		??/perl-net-dbus \
		??/perl-uri \
		??/php-fpm


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
