PORTNAME=	apkurlgrep
DISTVERSION=	8.a188a98
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Extract endpoints from APK files.
WWW=		https://github.com/ndelphit/apkurlgrep

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
