PORTNAME=	country-ip-blocks
DISTVERSION=	5689.b46ce3c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	CIDR country-level IP data, straight from the Regional Internet Registries, updated hourly.
WWW=		https://github.com/herrbischoff/country-ip-blocks

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
