PORTNAME=	shelling
DISTVERSION=	227.0a6c135
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An offensive approach to the anatomy of improperly written OS command injection sanitisers.
WWW=		https://github.com/ewilded/shelling

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
