PORTNAME=	ip2clue
DISTVERSION=	0.0.95
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A small memory/CPU footprint daemon to lookup country (and other info) based on IP (v4 and v6).
WWW=		http://kernel.embedromix.ro/us/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/conn \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
