PORTNAME=	wifi-radar
DISTVERSION=	2.0.s10
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A PyGTK2 utility for managing WiFi profiles.
WWW=		https://wifi-radar.tuxfamily.org/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/net-tools \
		??/pygtk \
		??/wireless_tools


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
