PORTNAME=	oscanner
DISTVERSION=	1.0.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An Oracle assessment framework developed in Java.
WWW=		http://www.cqure.net/wp/oscanner/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
