PORTNAME=	eapmd5pass
DISTVERSION=	3.3d5551f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An implementation of an offline dictionary attack against the EAP-MD5 protocol.
WWW=		http://www.willhackforsushi.com/?page_id=67

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
