PORTNAME=	netscan
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tcp/Udp/Tor port scanner with: synpacket, connect TCP/UDP and socks5 (tor connection).
WWW=		http://packetstormsecurity.com/files/125569/Netscan-Port-Scanner-1.0.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
