PORTNAME=	tcpdstat
DISTVERSION=	4.be5bd28
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Get protocol statistics from tcpdump pcap files.
WWW=		https://github.com/netik/tcpdstat

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/make \
		devel/git

RUN_DEPENDS=	net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
