PORTNAME=	bluepot
DISTVERSION=	0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Bluetooth Honeypot written in Java, it runs on Linux.
WWW=		https://github.com/andrewmichaelsmith/bluepot

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gksu \
		??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
