PORTNAME=	perl-ip-country
DISTVERSION=	2.28
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fast lookup of country codes from IP addresses.
WWW=		http://search.cpan.org/~NWETTERS/IP-Country

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl-geography-countries


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
