PORTNAME=	commentor
DISTVERSION=	20.4582674
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Extract all comments from the specified URL resource.
WWW=		https://github.com/D3vil0p3r/comMENTOR

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/tidy \
		??/xmlstarlet \
		ftp/curl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
