PORTNAME=	python2-pylibpcap
DISTVERSION=	0.6.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python module for the libpcap packet capture library, based on the original python libpcap module by Aaron Rhodes.
WWW=		http://pylibpcap.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3 \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
