PORTNAME=	snmpscan
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A free, multi-processes SNMP scanner.
WWW=		http://www.nothink.org/perl/snmpscan/index.php

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-net-ip \
		??/perl-net-snmp \
		??/perl-number-bytes-human \
		??/perl-uniq


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
