PORTNAME=	skype-dump
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This is a tool that demonstrates dumping MD5 password hashes from the configuration file in Skype.
WWW=		http://packetstormsecurity.com/files/119155/Skype-Hash-Dumper-1.0.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	archivers/unzip



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
