PORTNAME=	mkinitcpio-openswap
DISTVERSION=	0.1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A mkinitcpio hook to open swap at boot time.
WWW=		https://aur.archlinux.org/packages/mkinitcpio-openswap

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/mkinitcpio


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
