PORTNAME=	dsd
DISTVERSION=	v1.6.0.r96.g59423fa
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Digital Speech Decoder.
WWW=		https://github.com/szechyjs/dsd

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git

RUN_DEPENDS=	??/itpp \
		??/libsndfile \
		??/mbelib \
		??/portaudio


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
