PORTNAME=	apache-users
DISTVERSION=	2.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This perl script will enumerate the usernames on a unix system that use the apache module UserDir.
WWW=		https://labs.portcullis.co.uk/downloads/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-io-socket \
		??/perl-libwww \
		??/perl-parallel-forkmanager


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
