PORTNAME=	web-soul
DISTVERSION=	2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A plugin based scanner for attacking and data mining web sites written in Perl.
WWW=		http://packetstormsecurity.com/files/122064/Web-Soul-2-Scanner.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
