PORTNAME=	ddosify
DISTVERSION=	v2.6.0.r31.g0131056
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	High-performance load testing tool, written in Golang.
WWW=		https://github.com/ddosify/ddosify

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
