PORTNAME=	httpsniff
DISTVERSION=	0.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool to sniff HTTP responses from TCP/IP based networks and save contained files locally for later review.
WWW=		http://www.sump.org/projects/httpsniff/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/glib2 \
		??/libnet \
		??/libnids \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
