PORTNAME=	undbx
DISTVERSION=	0.21.r3.g5e31c75
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Extract e-mail messages from Outlook Express DBX files.
WWW=		https://github.com/ZungBang/undbx

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
