PORTNAME=	beroot
DISTVERSION=	1.0.1.r109.g4c0b648
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A post exploitation tool to check common misconfigurations to find a way to escalate our privilege.
WWW=		https://github.com/AlessandroZ/BeRoot

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-dbus@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
