PORTNAME=	pextractor
DISTVERSION=	0.18b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A forensics tool that can extract all files from an executable file created by a joiner or similar.
WWW=		http://packetstormsecurity.com/files/62977/PExtractor_v0.18b_binary_and_src.rar.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/unrar



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
