PORTNAME=	sherlocked
DISTVERSION=	1.f190c2b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Universal script packer-- transforms any type of script into a protected ELF executable, encrypted with anti-debugging.
WWW=		https://github.com/elfmaster/sherlocked

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
