PORTNAME=	redeye
DISTVERSION=	0.9.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Visual analytic tool supporting Red & Blue Team operations.
WWW=		https://github.com/cisagov/RedEye

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
