PORTNAME=	golang-glide
DISTVERSION=	1093.b94b39d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Vendor Package Management for Golang.
WWW=		https://github.com/Masterminds/glide

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
