PORTNAME=	androidmeda
DISTVERSION=	v2.0.0.r1.ge2e5084
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	AI tool to deobfuscate and find any potential vulnerabilities in android apps.
WWW=		https://github.com/In3tinct/androidmeda

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	devel/py-pip@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
