PORTNAME=	simple-lan-scan
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple python script that leverages scapy for discovering live hosts on a network.
WWW=		http://packetstormsecurity.com/files/97353/Simple-LAN-Scanner-1.0.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3 \
		net/py-scapy@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
