PORTNAME=	malheur
DISTVERSION=	0.5.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool for the automatic analyze of malware behavior.
WWW=		http://www.mlsec.org/malheur/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/uthash

RUN_DEPENDS=	??/libarchive \
		??/libconfig


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
