PORTNAME=	argus
DISTVERSION=	3.0.8.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Network monitoring tool with flow control.
WWW=		http://qosient.com/argus/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libsasl \
		??/perl \
		??/zlib \
		net/libpcap \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
