PORTNAME=	wol-e
DISTVERSION=	2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A suite of tools for the Wake on LAN feature of network attached computers.
WWW=		http://code.google.com/p/wol-e/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/impacket \
		??/py-pcapy@${PY_FLAVOR} \
		net/py-scapy@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
