PORTNAME=	juicy-potato
DISTVERSION=	53.744d321
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A sugared version of RottenPotatoNG, with a bit of juice.
WWW=		https://github.com/ohpe/juicy-potato

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
