PORTNAME=	phishery
DISTVERSION=	14.5743953
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An SSL Enabled Basic Auth Credential Harvester with a Word Document Template URL Injector.
WWW=		https://github.com/ryhanson/phishery

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/go-pie \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
