PORTNAME=	jomplug
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This php script fingerprints a given Joomla system and then uses Packet Storms archive to check for bugs related to the installed components.
WWW=		http://packetstormsecurity.com/files/121390/Janissaries-Joomla-Fingerprint-Tool.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/php82


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
