PORTNAME=	zdns
DISTVERSION=	v2.0.5.r33.g68c914b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fast CLI DNS Lookup Tool.
WWW=		https://github.com/zmap/zdns

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
