PORTNAME=	cmospwd
DISTVERSION=	5.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Decrypts password stored in CMOS used to access BIOS setup.
WWW=		http://www.cgsecurity.org/wiki/CmosPwd

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
