PORTNAME=	s2e
DISTVERSION=	v2.0.0.r544.g0cab056
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A platform for multi-path program analysis with selective symbolic execution.
WWW=		https://github.com/S2E/s2e

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/autoconf \
		??/binutils \
		??/boost \
		??/boost-libs \
		??/ca-certificates \
		??/capstone \
		??/cmake \
		??/gcc-multilib \
		??/glib2 \
		??/gtest \
		??/jemalloc \
		??/libbsd \
		??/libdwarf \
		??/libelf \
		??/libtool \
		??/lsb-release \
		??/memcached \
		??/mingw-w64-gcc \
		??/nasm \
		??/pixman \
		??/pkgconf \
		??/postgresql-libs \
		??/protobuf \
		??/protobuf-c \
		??/py-sphinx_rtd_theme@${PY_FLAVOR} \
		??/py-virtualenv@${PY_FLAVOR} \
		??/rapidjson \
		??/repo \
		??/zlib \
		??/zstd \
		archivers/unzip \
		devel/git \
		devel/py-pip@${PY_FLAVOR} \
		ftp/curl \
		ftp/wget \
		lang/python



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
