PORTNAME=	firecat
DISTVERSION=	6.b5205c8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A penetration testing tool that allows you to punch reverse TCP tunnels out of a compromised network.
WWW=		https://github.com/BishopFox/firecat

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
