PORTNAME=	pwfuzz-rs
DISTVERSION=	v0.2.0.r1.gac56f42
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Rust-based password mutator for brute force attacks.
WWW=		https://github.com/mttaggart/pwfuzz-rs

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/cargo \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
