PORTNAME=	vlan
DISTVERSION=	1.9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Virtual LAN configuration utility.
WWW=		https://www.candelatech.com/~greear/vlan.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
