PORTNAME=	daredevil
DISTVERSION=	42.81cb57f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool to perform (higher-order) correlation power analysis attacks (CPA).
WWW=		https://github.com/SideChannelMarvels/Daredevil

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/clang \
		devel/git

RUN_DEPENDS=	??/openmp


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
