PORTNAME=	zackattack
DISTVERSION=	5.1f96c14
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A new tool set to do NTLM Authentication relaying unlike any other tool currently out there.
WWW=		https://github.com/urbanesec/ZackAttack/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/ruby-sqlite3 \
		??/ruby-webrick \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
