PORTNAME=	bingoo
DISTVERSION=	3.698132f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Linux bash based Bing and Google Dorking Tool.
WWW=		https://github.com/Hood3dRob1n/BinGoo

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/lynx \
		ftp/curl \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
