PORTNAME=	mdcrack
DISTVERSION=	1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	MD4/MD5/NTLM1 hash cracker.
WWW=		http://c3rb3r.openwall.net/mdcrack/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
