PORTNAME=	byepass
DISTVERSION=	213.8cbfd9b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Automates password cracking tasks using optimized dictionaries and mangling rules.
WWW=		https://github.com/webpwnized/byepass

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/john \
		archivers/unzip \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
