PORTNAME=	mftcarver
DISTVERSION=	9.7bfcc0a2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Carve $MFT records from a chunk of data (for instance a memory dump).
WWW=		https://github.com/jschicht/MftCarver

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/wine-mono \
		??/wine_gecko \
		emulators/wine


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
