PORTNAME=	perl-net-pcaputils
DISTVERSION=	0.01
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl/CPAN Module Net::PcapUtils
WWW=		http://search.cpan.org/dist/Net-PcapUtils/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-net-pcap \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
