PORTNAME=	xrop
DISTVERSION=	90.0083e94
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool to generate ROP gadgets for ARM, AARCH64, x86, MIPS, PPC, RISCV, SH4 and SPARC.
WWW=		https://github.com/acama/xrop

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/binutils \
		??/libtool \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
