PORTNAME=	perl-color-output
DISTVERSION=	1.05
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Module to give color to the output.
WWW=		http://search.cpan.org/~animator/Color-Output-1.05/Output.pm

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
