PORTNAME=	ifchk
DISTVERSION=	1.1.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A network interface promiscuous mode detection tool.
WWW=		http://www.noorg.org/ifchk/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/sysfsutils


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
