PORTNAME=	android-sdk
DISTVERSION=	26.1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Google Android SDK
WWW=		https://developer.android.com/studio/releases/sdk-tools.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/fontconfig \
		??/freetype2 \
		??/java-environment \
		??/lib32-gcc-libs \
		??/lib32-glibc \
		??/libx11 \
		??/libxext \
		??/libxrender \
		??/libxtst \
		??/zlib


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
