PORTNAME=	perl-geography-countries
DISTVERSION=	2009041301
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	2-letter, 3-letter, and numerical codes for countries.
WWW=		http://search.cpan.org/~ABIGAIL/Geography-Countries

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
