PORTNAME=	qscintilla-qt3
DISTVERSION=	1.7.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A port to Qt3 of Neil Hodgsons Scintilla C++ editor class.
WWW=		http://www.riverbankcomputing.co.uk/software/qscintilla/intro/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/qt3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
