PORTNAME=	libestr
DISTVERSION=	0.1.11
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Essentials for string handling (and a bit more).
WWW=		http://libestr.adiscon.com/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
