PORTNAME=	inviteflood
DISTVERSION=	2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Flood a device with INVITE requests.
WWW=		https://github.com/foreni-packages/inviteflood

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libnet


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
