PORTNAME=	invoke-obfuscation
DISTVERSION=	45.f20e7f8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	PowerShell Obfuscator.
WWW=		https://github.com/danielbohannon/Invoke-Obfuscation

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
