PORTNAME=	python-ivre
DISTVERSION=	0.9.21.dev157
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Network recon framework based on Nmap, Masscan, Zeek (Bro), Argus, Netflow,...
WWW=		https://ivre.rocks/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
