PORTNAME=	dsss
DISTVERSION=	124.f354215
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A fully functional SQL injection vulnerability scanner (supporting GET and POST parameters) written in under 100 lines of code.
WWW=		https://github.com/stamparm/DSSS

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
