PORTNAME=	openobex
DISTVERSION=	1.7.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Implementation of the OBject EXchange (OBEX) protocol.
WWW=		http://dev.zuckschwerdt.org/openobex/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		??/doxygen \
		??/java-environment \
		textproc/libxslt

RUN_DEPENDS=	??/bluez-libs \
		??/libusb


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
