PORTNAME=	nbtenum
DISTVERSION=	3.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A utility for Windows that can be used to enumerate NetBIOS information from one host or a range of hosts.
WWW=		http://reedarvin.thearvins.com/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
