PORTNAME=	perl-universal-require
DISTVERSION=	0.19
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	require() modules from a variable.
WWW=		http://search.cpan.org/~neilb/UNIVERSAL-require/lib/UNIVERSAL/require.pm

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
