PORTNAME=	cutycapt
DISTVERSION=	11.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Qt and WebEngine-based command-line utility that captures a web pages rendered output.
WWW=		https://cutycapt.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		??/ninja

RUN_DEPENDS=	??/qt6-base \
		??/qt6-svg \
		??/qt6-webchannel \
		??/qt6-webengine


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
