PORTNAME=	mibble
DISTVERSION=	2.10.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An open-source SNMP MIB parser (or SMI parser) written in Java. It can be used to read SNMP MIB files as well as simple ASN.1 files.
WWW=		https://github.com/cederberg/mibble/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
