PORTNAME=	python-yara-python-dex
DISTVERSION=	1.0.9.r0.g84ad7d2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The Python interface for YARA.
WWW=		https://github.com/MobSF/yara-python-dex

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/yara \
		devel/git \
		devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
