PORTNAME=	safecopy
DISTVERSION=	1.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A disk data recovery tool to extract data from damaged media.
WWW=		https://sourceforge.net/projects/safecopy/files/safecopy/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
