PORTNAME=	maryam
DISTVERSION=	v.2.5.3.r0.g2bb4ea2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	OSINT Framework
WWW=		https://github.com/saeeddhqan/Maryam

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-virtualenv@${PY_FLAVOR} \
		devel/py-pip@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
