PORTNAME=	intelplot
DISTVERSION=	12.4dd9fc0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	OSINT Tool to Mark Points on Offline Map.
WWW=		https://github.com/itsmehacker/IntelPlot

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/php82


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
