PORTNAME=	fgscanner
DISTVERSION=	11.893372c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An advanced, opensource URL scanner.
WWW=		http://www.fantaghost.com/fgscanner

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl \
		??/perl-getopt-long \
		??/perl-io-socket-portstate \
		??/perl-libwww


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
