PORTNAME=	dockerscan
DISTVERSION=	v2.0.5.r32.g15889e6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Docker security analysis & hacking tools.
WWW=		https://github.com/cr0hn/dockerscan

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
