PORTNAME=	binaryninja
DISTVERSION=	5.2.8722
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A new kind of reversing platform (demo version).
WWW=		https://binary.ninja/free/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libglvnd \
		??/libxkbcommon-x11


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
