PORTNAME=	golismero
DISTVERSION=	73.7d605b9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Opensource web security testing framework.
WWW=		https://github.com/golismero/golismero

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-argcomplete@${PY_FLAVOR} \
		??/py-argparse@${PY_FLAVOR} \
		??/py-beautifulsoup3@${PY_FLAVOR} \
		??/py-cjson@${PY_FLAVOR} \
		??/py-colorizer@${PY_FLAVOR} \
		??/py-decorator@${PY_FLAVOR} \
		??/py-django@${PY_FLAVOR} \
		??/py-dnspython@${PY_FLAVOR} \
		??/py-docutils@${PY_FLAVOR} \
		??/py-netaddr@${PY_FLAVOR} \
		??/py-nltk@${PY_FLAVOR} \
		??/py-psycopg2@${PY_FLAVOR} \
		??/py-pycurl@${PY_FLAVOR} \
		??/py-pymongo@${PY_FLAVOR} \
		??/py-pysqlite@${PY_FLAVOR} \
		??/py-requests-ntlm@${PY_FLAVOR} \
		??/py-simplejson@${PY_FLAVOR} \
		??/py-texttable@${PY_FLAVOR} \
		??/py-tldextract@${PY_FLAVOR} \
		??/py-yaml@${PY_FLAVOR} \
		lang/python3 \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
