PORTNAME=	hidattack
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	HID Attack (attacking HID host implementations).
WWW=		http://mulliner.org/bluetooth/hidattack.php

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gcc

RUN_DEPENDS=	??/bluez \
		??/openobex


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
