PORTNAME=	jsfuck
DISTVERSION=	242.6f8fdf3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Write any JavaScript with 6 Characters: []()!+.
WWW=		https://github.com/aemkei/jsfuck

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/php82


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
