PORTNAME=	bunny
DISTVERSION=	0.93
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A closed loop, high-performance, general purpose protocol-blind fuzzer for C programs.
WWW=		https://code.google.com/p/bunny-the-fuzzer/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
