PORTNAME=	tlshelpers
DISTVERSION=	37.9908fd7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A collection of shell scripts that help handling X.509 certificate and TLS issues.
WWW=		https://github.com/hannob/tlshelpers

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/der-ascii \
		ftp/wget \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
