PORTNAME=	blackarch-config-lxdm
DISTVERSION=	20.b109457
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	BlackArch config for lxdm X11 login manager.
WWW=		https://github.com/BlackArch/blackarch-config-lxdm

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/blackarch-wallpaper \
		??/lxdm \
		??/terminus-font


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
