PORTNAME=	qt5-examples
DISTVERSION=	$.basever
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	
WWW=		https://www.qt.io

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/clang \
		??/gperf \
		??/libxcomposite \
		??/libxcursor \
		??/libxkbfile \
		??/libxrandr \
		??/libxss \
		??/libxtst \
		??/ninja \
		??/nss \
		??/pciutils \
		??/qt5-tools \
		lang/python \
		www/node



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
