PORTNAME=	wepbuster
DISTVERSION=	1.0.beta.0.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Script for automating aircrack-ng.
WWW=		http://code.google.com/p/wepbuster/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/aircrack-ng \
		??/perl-algorithm-permute \
		??/perl-expect \
		??/perl-file-slurp \
		??/perl-number-range \
		??/perl-term-readkey


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
