PORTNAME=	perl-crypt-primes
DISTVERSION=	0.50
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Provable Prime Number Generator suitable for Cryptographic Applications.
WWW=		http://search.cpan.org/~VIPUL/Crypt-Primes-0.50/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gmp \
		??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
