PORTNAME=	rulesfinder
DISTVERSION=	42.cf8255b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Machine-learn password mangling rules.
WWW=		https://github.com/synacktiv/rulesfinder

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/cargo \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
