PORTNAME=	dirscanner
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This is a python script that scans webservers looking for administrative directories, php shells, and more.
WWW=		http://packetstormsecurity.com/files/117773/Directory-Scanner-Tool.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
