PORTNAME=	plcscan
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This is a tool written in Python that will scan for PLC devices over s7comm or modbus protocols.
WWW=		http://packetstormsecurity.com/files/119726/PLC-Device-Scanner.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
