PORTNAME=	pipeline
DISTVERSION=	19.f4935c9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Designed to aid in targeted brute force password cracking attacks.
WWW=		https://github.com/hirnschallsebastian/Pipeline2

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
