PORTNAME=	goshs
DISTVERSION=	0.3.8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A SimpleHTTPServer written in Go, enhanced with features and with a nice design.
WWW=		https://github.com/patrickhener/goshs

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
