PORTNAME=	untwister
DISTVERSION=	119.a42b8f8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Seed recovery tool for PRNGs.
WWW=		https://github.com/altf4/untwister

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/boost \
		??/cppunit


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
