PORTNAME=	libvshadow
DISTVERSION=	186.6b3702f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A library to access the Volume Shadow Snapshot (VSS) format.
WWW=		https://github.com/libyal/libvshadow

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/autoconf \
		??/automake \
		??/bison \
		??/flex \
		??/gettext \
		??/libtool \
		??/pkg-config \
		devel/git

RUN_DEPENDS=	??/libbfio


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
