PORTNAME=	airspyhf
DISTVERSION=	1.6.8.r63.g30e0422
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Host code for AirspyHF+ SDR.
WWW=		https://airspy.com

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git

RUN_DEPENDS=	??/libusb


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
