PORTNAME=	invoke-cradlecrafter
DISTVERSION=	19.3ff8bac
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	PowerShell Remote Download Cradle Generator & Obfuscator.
WWW=		https://github.com/danielbohannon/Invoke-CradleCrafter

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
