PORTNAME=	perl-class-gomor
DISTVERSION=	1.03
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Another class and object builder
WWW=		http://search.cpan.org/dist/Class-Gomor

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
