PORTNAME=	swfintruder
DISTVERSION=	0.9.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	First tool for testing security in Flash movies. A runtime analyzer for SWF external movies. It helps to find flaws in Flash.
WWW=		http://code.google.com/p/swfintruder/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
