PORTNAME=	perl-test-refcount
DISTVERSION=	0.10
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Assert reference counts on objects.
WWW=		https://metacpan.org/release/Test-Refcount

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-module-build


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
