PORTNAME=	kimi
DISTVERSION=	28.e7cafda
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Script to generate malicious debian packages (debain trojans).
WWW=		https://github.com/ChaitanyaHaritash/kimi

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
