PORTNAME=	python2-sqlalchemy-utils
DISTVERSION=	0.35.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Various utility functions for SQLAlchemy.
WWW=		https://pypi.org/project/SQLAlchemy-Utils/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
