PORTNAME=	flashsploit
DISTVERSION=	23.c465a6d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Exploitation Framework for ATtiny85 Based HID Attacks.
WWW=		https://github.com/thewhiteh4t/flashsploit

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/metasploit \
		??/openssh \
		lang/php82 \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
