PORTNAME=	cpptest
DISTVERSION=	2.0.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A portable and powerful, yet simple, unit testing framework for handling automated tests in C++.
WWW=		https://github.com/cpptest/cpptest/releases

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
