PORTNAME=	cribdrag
DISTVERSION=	5.2d27dbf
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An interactive crib dragging tool for cryptanalysis on ciphertext generated with reused or predictable stream cipher keys.
WWW=		https://github.com/SpiderLabs/cribdrag

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
