PORTNAME=	wuzz
DISTVERSION=	v0.5.0.r16.g791aeb9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Interactive cli tool for HTTP inspection.
WWW=		https://github.com/asciimoo/wuzz

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
