PORTNAME=	rusthound-ce
DISTVERSION=	v2.4.7.r2.gb6f809f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Active Directory data collector for BloodHound community edition (v5).
WWW=		https://github.com/g0h4n/RustHound-CE

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/clang \
		devel/cargo \
		devel/git

RUN_DEPENDS=	??/krb5


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
