PORTNAME=	chaosreader
DISTVERSION=	0.94
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A freeware tool to trace tcp, udp etc. sessions and fetch application data from snoop or tcpdump logs.
WWW=		http://chaosreader.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
