PORTNAME=	firefox-security-toolkit
DISTVERSION=	17.d356ab8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool that transforms Firefox browsers into a penetration testing suite.
WWW=		https://github.com/mazen160/Firefox-Security-Toolkit

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/firefox \
		ftp/wget \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
