PORTNAME=	qt4
DISTVERSION=	4.8.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A cross-platform application and UI framework
WWW=		https://www.qt.io

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cups \
		??/gtk2 \
		??/libfbclient \
		??/mariadb-libs \
		??/mesa \
		??/patch \
		??/postgresql-libs \
		??/unixodbc

RUN_DEPENDS=	??/alsa-lib \
		??/ca-certificates \
		??/dbus \
		??/desktop-file-utils \
		??/fontconfig \
		??/hicolor-icon-theme \
		??/libgl \
		??/libmng \
		??/libxi \
		??/libxrandr \
		??/libxv \
		??/sqlite \
		??/xdg-utils


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
