PORTNAME=	phpggc
DISTVERSION=	725.f8aebde
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A library of PHP unserialize() payloads along with a tool to generate them, from command line or programmatically.
WWW=		https://github.com/ambionics/phpggc

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/php82


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
