PORTNAME=	malicious-pdf
DISTVERSION=	64.5676086
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Generate a bunch of malicious pdf files with phone-home functionality.
WWW=		https://github.com/jonaslejon/malicious-pdf

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
