PORTNAME=	kernelpop
DISTVERSION=	238.b3467d3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Kernel privilege escalation enumeration and exploitation framework.
WWW=		https://github.com/spencerdodd/kernelpop

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/pyinstaller \
		devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
