PORTNAME=	wordbrutepress
DISTVERSION=	30.5165648
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python script that performs brute forcing against WordPress installs using a wordlist.
WWW=		http://www.homelab.it/index.php/2014/11/03/wordpress-brute-force-multithreading/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-httplib2@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
