PORTNAME=	rtl8814au-dkms-git
DISTVERSION=	5.8.5.1.r190.g8d82854
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	RTL8814AU and RTL8813AU chipset driver with firmware v5.8.5.1.
WWW=		https://github.com/morrownr/8814au

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/bc \
		??/dkms


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
