PORTNAME=	protosint
DISTVERSION=	30.5fb396e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python script that helps you investigate Protonmail accounts and ProtonVPN IP addresses.
WWW=		https://github.com/pixelbubble/ProtOSINT

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
