PORTNAME=	vbsmin
DISTVERSION=	v1.2.0.r1.ge7dfeb0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	VBScript minifier.
WWW=		https://noraj.github.io/vbsmin/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/ruby-docopt \
		??/ruby-paint \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
