PORTNAME=	filebuster
DISTVERSION=	95.f2b04c7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An extremely fast and flexible web fuzzer.
WWW=		https://github.com/henshin/filebuster

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl \
		??/perl-cache-lru \
		??/perl-class-accessor-lite \
		??/perl-exporter-tiny \
		??/perl-furl \
		??/perl-html-parser \
		??/perl-http-parser-xs \
		??/perl-io-async \
		??/perl-io-socket-socks-wrapper \
		??/perl-io-socket-ssl \
		??/perl-list-moreutils \
		??/perl-net-dns \
		??/perl-net-dns-lite \
		??/perl-switch \
		??/perl-uri \
		??/perl-yaml


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
