PORTNAME=	perl-perlio-via-timeout
DISTVERSION=	0.32
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A PerlIO layer that adds read & write timeout to a handle.
WWW=		https://metacpan.org/release/PerlIO-via-Timeout

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl-module-build-tiny

RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
