PORTNAME=	nodejs-colors
DISTVERSION=	1.4.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Get colors in your node.js console.
WWW=		https://github.com/marak/colors.js/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	www/npm

RUN_DEPENDS=	www/node


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
