PORTNAME=	joomlascan
DISTVERSION=	1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Joomla scanner scans for known vulnerable remote file inclusion paths and files.
WWW=		http://packetstormsecurity.com/files/62126/joomlascan-1.2.py.txt.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-httplib2@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
