PORTNAME=	perl-md5
DISTVERSION=	2.03
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl interface to the MD5 Message-Digest Algorithm.
WWW=		http://search.cpan.org/~gaas/MD5-2.03/MD5.pm

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
