PORTNAME=	vncrack
DISTVERSION=	1.21
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	What it looks like: crack VNC.
WWW=		http://194.150.168.69/vncrack/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
