PORTNAME=	python2-multipartposthandler
DISTVERSION=	0.1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A handler for urllib2 to enable multipart form uploading.
WWW=		https://pypi.python.org/pypi/MultipartPostHandler/0.1.0

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
