PORTNAME=	backdoor-apk
DISTVERSION=	141.2710126
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Shell script that simplifies the process of adding a backdoor to any Android APK file
WWW=		https://github.com/dana-at-cp/backdoor-apk

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/smali


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
