PORTNAME=	dr-checker
DISTVERSION=	140.ea63c0f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Soundy Vulnerability Detection Tool for Linux Kernel Drivers.
WWW=		https://github.com/ucsb-seclab/dr_checker

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
