PORTNAME=	hodor
DISTVERSION=	1.01be107
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A general-use fuzzer that can be configured to use known-good input and delimiters in order to fuzz specific locations.
WWW=		https://github.com/nccgroup/hodor

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
