PORTNAME=	libicu52
DISTVERSION=	52.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	International Components for Unicode library.
WWW=		http://www.icu-project.org/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
