PORTNAME=	tempomail
DISTVERSION=	26.5600ec3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool to create a temporary email address in 1 Second and receive emails.
WWW=		https://github.com/kavishgr/tempomail

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
