PORTNAME=	cero
DISTVERSION=	v1.3.0.r19.gb73125b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Scrape domain names from SSL certificates of arbitrary hosts.
WWW=		https://github.com/glebarez/cero

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
