PORTNAME=	aurebeshjs
DISTVERSION=	77.75a8fc6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Translate JavaScript to Other Alphabets.
WWW=		https://github.com/aemkei/aurebesh.js

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/php82


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
