PORTNAME=	ffuf
DISTVERSION=	v2.1.0.r5.g57da720
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fast web fuzzer written in Go.
WWW=		https://github.com/ffuf/ffuf

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
