PORTNAME=	libxtrxll
DISTVERSION=	43.78fb365
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Low level XTRX hardware abstraction library.
WWW=		https://github.com/xtrx-sdr/libxtrxll

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git

RUN_DEPENDS=	??/libusb3380


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
