PORTNAME=	qt5-charts
DISTVERSION=	5.15.18
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Provides a set of easy to use chart components.
WWW=		https://www.qt.io

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/qt5-declarative \
		devel/git

RUN_DEPENDS=	??/qt5-base


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
