PORTNAME=	pyminifakedns
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Minimal DNS server written in Python; it always replies with a 127.0.0.1 A-record.
WWW=		http://code.activestate.com/recipes/491264/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
