PORTNAME=	linkfinder
DISTVERSION=	168.1debac5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Discovers endpoint and their parameters in JavaScript files.
WWW=		https://github.com/GerbenJavado/LinkFinder

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-jsbeautifier@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
