PORTNAME=	mailsend-go
DISTVERSION=	138.3f1b22f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A multi-platform command line tool to send mail via SMTP protocol.
WWW=		https://github.com/muquit/mailsend-go

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
