PORTNAME=	python-emailprotectionslib
DISTVERSION=	0.8.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python library to interact with SPF and DMARC.
WWW=		https://pypi.python.org/pypi/emailprotectionslib/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
