PORTNAME=	eazy
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This is a small python tool that scans websites to look for PHP shells, backups, admin panels, and more.
WWW=		http://packetstormsecurity.com/files/117572/EAZY-Web-Scanner.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
