PORTNAME=	seccomp-tools
DISTVERSION=	1.6.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Seccomp analysis toolkit.
WWW=		https://github.com/david942j/seccomp-tools

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/ruby-os \
		??/ruby-racc \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
