PORTNAME=	brutespray
DISTVERSION=	608.057218d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Brute-Forcing from Nmap output - Automatically attempts default creds on found services.
WWW=		https://github.com/x90skysn3k/brutespray

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
