PORTNAME=	argus-clients
DISTVERSION=	3.0.8.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Network monitoring client for Argus.
WWW=		http://qosient.com/argus/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/geoip \
		??/libedit \
		??/libmariadbclient \
		??/libsasl \
		??/libtirpc-compat \
		??/pcre


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
