PORTNAME=	nfcutils
DISTVERSION=	61.49aa178
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple command that lists tags which are in your NFC device field.
WWW=		https://github.com/nfc-tools/nfcutils

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/autoconf \
		??/automake \
		devel/git

RUN_DEPENDS=	??/libnfc


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
