PORTNAME=	nullinux
DISTVERSION=	124.9f8727a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool that can be used to enumerate OS information, domain information, shares, directories, and users through SMB null sessions.
WWW=		https://github.com/m8r0wn/nullinux

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-ipparser@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
