PORTNAME=	perl-libwhisker2
DISTVERSION=	2.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A full-featured Perl library used for HTTP-related functions, including vulnerability scanning and exploitation.
WWW=		http://sourceforge.net/projects/whisker/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-net-ssleay


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
