PORTNAME=	httpgrep
DISTVERSION=	2.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A python tool which scans for HTTP servers and finds given strings in HTTP body and HTTP response headers.
WWW=		https://nullsecurity.net/tools/scanner.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
