PORTNAME=	perl-net-whois-ip
DISTVERSION=	1.19
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl extension for looking up the whois information for ip addresses.
WWW=		http://search.cpan.org/dist/Net-Whois-IP

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
