PORTNAME=	wkhtmltopdf
DISTVERSION=	0.12.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Command line tools to render HTML into PDF and various image formats.
WWW=		https://wkhtmltopdf.org/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/qt5-svg \
		??/qt5-webkit \
		??/qt5-xmlpatterns


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
