PORTNAME=	perl-io-socket-portstate
DISTVERSION=	0.03
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl extension for checking the open or closed status of a port..
WWW=		http://search.cpan.org/~dmuey/IO-Socket-PortState-0.03/PortState.pm

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
