PORTNAME=	pyclutter
DISTVERSION=	1.3.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python bindings to Clutter.
WWW=		http://blogs.gnome.org/clutter/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/clutter \
		??/glib2 \
		??/gtk2 \
		??/py-cairo@${PY_FLAVOR} \
		??/pygobject \
		??/pygtk \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
