PORTNAME=	parsero
DISTVERSION=	81.e5b585a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A robots.txt audit tool.
WWW=		https://github.com/behindthefirewalls/Parsero

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-beautifulsoup4@${PY_FLAVOR} \
		??/py-urllib3@${PY_FLAVOR} \
		??/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
