PORTNAME=	android-sdk-platform-tools
DISTVERSION=	r36.0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Platform-Tools for Google Android SDK (adb and fastboot)
WWW=		https://developer.android.com/sdk/index.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/ncurses \
		??/zlib


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
