PORTNAME=	htshells
DISTVERSION=	89.3216523
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Self contained web shells and other attacks via .htaccess files.
WWW=		https://github.com/wireghoul/htshells

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
