PORTNAME=	reverseip
DISTVERSION=	13.42cc9c3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Ruby based reverse IP-lookup tool.
WWW=		https://github.com/lolwaleet/ReverseIP

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/ruby-colorize \
		??/ruby-mechanize \
		??/ruby-mini_portile2 \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
