PORTNAME=	python2-smart-open
DISTVERSION=	7.5.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Utils for streaming large files (S3, HDFS, gzip, bz2...).
WWW=		https://pypi.org/project/smart-open/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
