PORTNAME=	snow
DISTVERSION=	20130616
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Steganography program for concealing messages in text files.
WWW=		http://darkside.com.au/snow/index.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	ftp/wget



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
