PORTNAME=	jre21-openjdk-headless
DISTVERSION=	${.majorver}.${.minorver}.${.securityver}.u${.updatever}
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	
WWW=		https://openjdk.java.net/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/alsa-lib \
		??/cpio \
		??/freetype2 \
		??/giflib \
		??/graphviz \
		??/harfbuzz \
		??/java-environment \
		??/lcms2 \
		??/libcups \
		??/libelf \
		??/libjpeg-turbo \
		??/libnet \
		??/libpng \
		??/libx11 \
		??/libxext \
		??/libxrandr \
		??/libxrender \
		??/libxt \
		??/libxtst \
		??/pandoc \
		??/zip \
		archivers/unzip \
		shells/bash



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
