PORTNAME=	red-hawk
DISTVERSION=	36.fa54e23
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	All in one tool for Information Gathering, Vulnerability Scanning and Crawling.
WWW=		https://github.com/Tuhinshubhra/RED_HAWK

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/php82


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
