PORTNAME=	synner
DISTVERSION=	1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A custom eth->ip->tcp packet generator (spoofer) for testing firewalls and dos attacks.
WWW=		http://packetstormsecurity.com/files/69802/synner.c.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
