PORTNAME=	perl-net-frame-simple
DISTVERSION=	1.09
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Frame crafting made easy.
WWW=		http://search.cpan.org/~gomor/Net-Frame-Simple/lib/Net/Frame/Simple.pm

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
