PORTNAME=	pmdump
DISTVERSION=	1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool that lets you dump the memory contents of a process to a file without stopping the process.
WWW=		https://vidstromlabs.com/freetools/pmdump/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
