PORTNAME=	subterfuge
DISTVERSION=	64.69dda99
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Automated Man-in-the-Middle Attack Framework.
WWW=		https://github.com/Subterfuge-Framework/Subterfuge

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-configparser@${PY_FLAVOR} \
		??/py-django@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
