PORTNAME=	libfixbuf
DISTVERSION=	3.0.0.alpha2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	IPFIX Message Format Implementation.
WWW=		http://aircert.sourceforge.net/fixbuf

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/glib2


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
