PORTNAME=	dissector
DISTVERSION=	1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This code dissects the internal data structures in ELF files. It supports x86 and x86_64 archs and runs under Linux.
WWW=		http://packetstormsecurity.com/files/125972/Coloured-ELF-File-Dissector.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
