PORTNAME=	gocabrito
DISTVERSION=	4.33ac59a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Super organized and flexible script for sending phishing campaigns.
WWW=		https://github.com/KINGSABRI/goCabrito

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/ruby-json \
		??/ruby-mail \
		??/ruby-sqlite3 \
		??/sqlite3 \
		lang/ruby \
		sysutils/rubygem-bundler


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
