PORTNAME=	nodejs-electron-packager
DISTVERSION=	15.2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Customize and package your Electron app with OS-specific bundles (.app, .exe etc) via JS or CL.
WWW=		https://www.npmjs.com/package/electron-packager

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	www/npm

RUN_DEPENDS=	www/node


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
