PORTNAME=	agafi
DISTVERSION=	1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A gadget finder and a ROP-Chainer tool for x86 platforms.
WWW=		https://github.com/CoreSecurity/Agafi

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/unrar



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
