PORTNAME=	python2-pyqt5
DISTVERSION=	5.15.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	
WWW=		https://pypi.org/project/PyQt5/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-dbus@${PY_FLAVOR} \
		??/py-enum34@${PY_FLAVOR} \
		??/py-opengl@${PY_FLAVOR} \
		??/py-sip-pyqt5@${PY_FLAVOR} \
		??/qt5-connectivity \
		??/qt5-multimedia \
		??/qt5-networkauth \
		??/qt5-remoteobjects \
		??/qt5-serialport \
		??/qt5-svg \
		??/qt5-tools \
		??/qt5-webkit \
		??/qt5-websockets \
		??/qt5-x11extras \
		??/qt5-xmlpatterns \
		??/sip \
		??/sip4



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
