PORTNAME=	morpheus
DISTVERSION=	165.5d81c9e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Automated Ettercap TCP/IP Hijacking Tool.
WWW=		https://github.com/r00t-3xp10it/morpheus

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/apache \
		??/driftnet \
		??/dsniff \
		??/ettercap \
		??/metasploit \
		??/sudo \
		??/xterm \
		??/zenity \
		security/nmap \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
