PORTNAME=	subfinder
DISTVERSION=	v2.12.0.r16.g2d4f8048
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Modular subdomain discovery tool that can discover massive amounts of valid subdomains for any target.
WWW=		https://github.com/projectdiscovery/subfinder

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
