PORTNAME=	chownat
DISTVERSION=	0.08b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Allows two peers behind two separate NATs with no port forwarding and no DMZ setup on their routers to directly communicate with each other
WWW=		http://samy.pl/chownat/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-digest-md4


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
