PORTNAME=	promiscdetect
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Checks if your network adapter(s) is running in promiscuous mode, which may be a sign that you have a sniffer running on your computer.
WWW=		https://vidstromlabs.com/freetools/promiscdetect

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
