PORTNAME=	jeb-webasm
DISTVERSION=	3.0.5.201811021648
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	WebAssembly decompiler.
WWW=		https://www.pnfsoftware.com/jeb/#wasm

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment \
		??/java-runtime-common


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
