PORTNAME=	rustcat
DISTVERSION=	v3.0.0.r4.g245c791
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A modern port listener and reverse shell.
WWW=		https://github.com/robiot/rustcat

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/cargo \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
