PORTNAME=	fernflower
DISTVERSION=	816.36bc04c2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An analytical decompiler for Java.
WWW=		https://github.com/fesh0r/fernflower

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gradle \
		??/jdk17-openjdk \
		devel/git

RUN_DEPENDS=	??/jdk17-openjdk


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
