PORTNAME=	leechcore
DISTVERSION=	2.22
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Physical Memory Acquisition Library & The LeechAgent Remote Memory Acquisition Agent.
WWW=		https://github.com/ufrisk/LeechCore/releases

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gcc \
		??/make

RUN_DEPENDS=	??/libusb


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
