PORTNAME=	perl-io-socket-ip
DISTVERSION=	0.41
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Family-neutral IP socket supporting both IPv4 and IPv6.
WWW=		http://search.cpan.org/dist/IO-Socket-IP

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl-module-build

RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
