PORTNAME=	asn
DISTVERSION=	0.78.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	ASN, RPKI validity, BGP stats, IPv4v6, Prefix, URL, ASPath, Organization, IP reputation, IP geolocation, IP fingerprinting, Network recon, lookup API server, Web traceroute server.
WWW=		https://github.com/nitefood/asn

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/aha \
		??/bind \
		??/grepcidr \
		??/ipcalc \
		??/jq \
		??/mtr \
		??/openbsd-netcat \
		??/whois \
		ftp/curl \
		security/nmap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
