PORTNAME=	udpastcp
DISTVERSION=	29.683b5e3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This program hides UDP traffic as TCP traffic in order to bypass certain firewalls.
WWW=		https://github.com/Hello71/udpastcp

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/libev


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
