PORTNAME=	camlidl
DISTVERSION=	1.09
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A stub code generator and COM binding for Objective Caml (OCaml).
WWW=		http://caml.inria.fr/pub/old_caml_site/camlidl/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/ocaml


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
