PORTNAME=	zipexec
DISTVERSION=	19.f8d661f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A unique technique to execute binaries from a password protected zip.
WWW=		https://github.com/Tylous/ZipExec

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
