PORTNAME=	osslsigncode
DISTVERSION=	718.92f8761
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A small tool that implements part of the functionality of the Microsoft tool signtool.exe.
WWW=		https://github.com/mtrojnar/osslsigncode

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
