PORTNAME=	blackarch-devtools-toolkit
DISTVERSION=	0.3.0.r7.ge393678
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Development framework for the BlackArch Linux distribution written in Rust.
WWW=		https://github.com/Edu4rdSHL/blackarch-devtools

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/cargo \
		devel/git

RUN_DEPENDS=	??/btrfs-progs \
		??/devtools


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
