PORTNAME=	pfff
DISTVERSION=	0.29
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tools and APIs for code analysis, visualization and transformation
WWW=		https://github.com/facebook/pfff

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/camlp4 \
		??/ocaml \
		??/ocaml-findlib \
		??/ocaml-stdlib-shims

RUN_DEPENDS=	??/zlib


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
