PORTNAME=	sea
DISTVERSION=	103.9aca1c8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool to help to create exploits of binary programs.
WWW=		https://github.com/neuromancer/SEA

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-z3@${PY_FLAVOR} \
		??/z3 \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
