PORTNAME=	radare2-bindings
DISTVERSION=	5.2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Language bindings of the radare2 api for valabind and friends.
WWW=		http://radare.org

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/swig \
		??/vala \
		??/valabind

RUN_DEPENDS=	??/gawk \
		??/go-pie \
		??/java-environment \
		??/lua \
		??/radare2 \
		??/vala \
		??/valabind \
		lang/python3 \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
