PORTNAME=	shodanhat
DISTVERSION=	13.e5e7e68
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Search for hosts info with shodan.
WWW=		https://github.com/HatBashBR/ShodanHat

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-nmap@${PY_FLAVOR} \
		??/py-shodan@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
