PORTNAME=	rbkb
DISTVERSION=	v0.7.3.r3.g4645025
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A miscellaneous collection of command-line tools related to pen-testing and reversing.
WWW=		https://github.com/emonti/rbkb

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
