PORTNAME=	giskismet
DISTVERSION=	2.9ebe9d0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A program to visually represent the Kismet data in a flexible manner.
WWW=		https://www.giskismet.org

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl-dbd-sqlite \
		??/perl-dbi \
		??/perl-xml-libxml


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
