PORTNAME=	conscan
DISTVERSION=	1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A blackbox vulnerability scanner for the Concre5 CMS.
WWW=		http://nullsecurity.net/tools/scanner.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-lxml@${PY_FLAVOR} \
		??/py-wget@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
