PORTNAME=	ldsview
DISTVERSION=	47.d8bfcaa
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Offline search tool for LDAP directory dumps in LDIF format.
WWW=		https://github.com/kgoins/ldsview

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
