PORTNAME=	sprayingtoolkit
DISTVERSION=	60.82e2ec8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Scripts to make password spraying attacks against Lync/S4B & OWA a lot quicker, less painful and more efficient.
WWW=		https://github.com/byt3bl33d3r/$_pkgname

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-virtualenv@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
