PORTNAME=	python2-gunicorn
DISTVERSION=	20.0.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Green Unicorn is a WSGI HTTP Server for UNIX, fast clients and sleepy applications.
WWW=		https://github.com/benoitc/gunicorn/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
