PORTNAME=	air
DISTVERSION=	2.0.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A GUI front-end to dd/dc3dd designed for easily creating forensic images.
WWW=		https://sourceforge.net/projects/air-imager/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl-tk \
		??/sharutils


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
