PORTNAME=	strutscan
DISTVERSION=	4.8712c12
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Apache Struts2 vulnerability scanner written in Perl.
WWW=		https://github.com/riusksk/StrutScan

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl \
		??/perl-http-cookies \
		??/perl-libwww \
		??/perl-uri


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
