PORTNAME=	lisa.py
DISTVERSION=	66.9dd61e9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An Exploit Dev Swiss Army Knife.
WWW=		https://github.com/ant4g0nist/lisa.py

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/lldb \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
