PORTNAME=	swarm
DISTVERSION=	41.1713c1e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A distributed penetration testing tool.
WWW=		https://github.com/Arvin-X/swarm

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-ipy@${PY_FLAVOR} \
		??/py-pymongo@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
