PORTNAME=	ntfs-log-tracker
DISTVERSION=	1.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This tool can parse $LogFile, $UsnJrnl of NTFS.
WWW=		https://sites.google.com/site/forensicnote/ntfs-log-tracker

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/wine-mono \
		??/wine_gecko \
		emulators/wine


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
