PORTNAME=	ntp-ip-enum
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Script to pull addresses from a NTP server using the monlist command. Can also output Maltego resultset.
WWW=		http://www.securepla.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
