PORTNAME=	elettra-gui
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Gui for the elettra crypto application.
WWW=		http://www.winstonsmith.info/julia/elettra/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/elettra \
		??/wxwidgets-gtk3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
