PORTNAME=	nuclei-templates
DISTVERSION=	v10.3.8.r1214.g36ba45c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Community curated list of template files for the nuclei engine.
WWW=		https://github.com/projectdiscovery/nuclei-templates

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
