PORTNAME=	gadgettojscript
DISTVERSION=	22.98f5098
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	.NET serialized gadgets that can trigger .NET assembly from JS/VBS/VBA based scripts.
WWW=		https://github.com/med0x2e/GadgetToJScript

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/mono-msbuild \
		devel/git

RUN_DEPENDS=	??/mono


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
