PORTNAME=	ruby-unf_ext
DISTVERSION=	0.0.9.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Unicode Normalization Form support library for CRuby.
WWW=		https://rubygems.org/gems/unf_ext

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/ruby-rdoc \
		??/rubygems

RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
