PORTNAME=	obfs4proxy
DISTVERSION=	0.0.13
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A pluggable transport proxy written in Go.
WWW=		https://gitlab.com/yawning/obfs4

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
