PORTNAME=	python-setuptools-markdown
DISTVERSION=	0.4.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Use Markdown for your project description.
WWW=		https://github.com/msabramo/setuptools-markdown

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-pypandoc@${PY_FLAVOR} \
		devel/py-setuptools@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
