PORTNAME=	hyenae
DISTVERSION=	0.36.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Flexible platform independent packet generator.
WWW=		http://sourceforge.net/projects/hyenae/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	net/libdnet \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
