PORTNAME=	dns-reverse-proxy
DISTVERSION=	44.5a53ae3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A reverse DNS proxy written in Go.
WWW=		https://github.com/StalkR/dns-reverse-proxy

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
