PORTNAME=	darkbing
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool written in python that leverages bing for mining data on systems that may be susceptible to SQL injection.
WWW=		http://packetstormsecurity.com/files/111510/darkBing-SQL-Scanner-0.1.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-lxml@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
