PORTNAME=	perl-html-tagparser
DISTVERSION=	0.20
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Yet another HTML document parser with DOM-like methods.
WWW=		http://search.cpan.org/dist/HTML-TagParser/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
