PORTNAME=	afflib
DISTVERSION=	3.7.22
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An extensible open format for the storage of disk images and related forensic information.
WWW=		https://github.com/sshock/AFFLIBv3

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/expat \
		??/fuse2 \
		??/fuse3 \
		??/ncurses \
		??/readline \
		??/zlib \
		ftp/curl \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
