PORTNAME=	retdec
DISTVERSION=	2172.8be53bbd
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Retargetable machine-code decompiler based on LLVM.
WWW=		https://retdec.com/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/autoconf \
		??/automake \
		??/bison \
		??/cmake \
		??/doxygen \
		??/flex \
		??/gcc \
		??/graphviz \
		??/libtool \
		??/m4 \
		??/make \
		??/perl \
		??/upx \
		??/zlib \
		devel/git \
		ftp/wget \
		lang/python \
		security/openssl

RUN_DEPENDS=	??/bc \
		??/graphviz \
		??/upx \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
