PORTNAME=	preeny
DISTVERSION=	117.6fa4796
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Some helpful preload libraries for pwning stuff.
WWW=		https://github.com/zardus/preeny

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		??/ding-libs \
		??/libseccomp \
		??/make \
		devel/git

RUN_DEPENDS=	??/ding-libs \
		??/libseccomp


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
