PORTNAME=	goldeneye
DISTVERSION=	28.792862f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A HTTP DoS test tool. Attack Vector exploited: HTTP Keep Alive + NoCache.
WWW=		https://github.com/jseidl/GoldenEye

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
