PORTNAME=	python-filequeue
DISTVERSION=	0.4.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A thread-safe queue object which is interchangeable with the stdlib Queue.
WWW=		https://pypi.org/project/filequeue/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
