PORTNAME=	ldapenum
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Enumerate domain controllers using LDAP.
WWW=		https://gobag.googlecode.com/svn-history/r2/trunk/ldap/ldapenum/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-ldap \
		??/perl-net-dns \
		??/perl-net-nslookup


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
