PORTNAME=	xpl-search
DISTVERSION=	42.d4dbc97
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Search exploits in multiple exploit databases!.
WWW=		https://github.com/CoderPirata/XPL-SEARCH

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	ftp/curl \
		lang/php82


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
