PORTNAME=	netactview
DISTVERSION=	0.6.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A graphical network connections viewer similar in functionality to netstat.
WWW=		http://netactview.sourceforge.net/index.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/intltool \
		??/polkit

RUN_DEPENDS=	??/libglade \
		??/libgtop


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
