PORTNAME=	chaos-client
DISTVERSION=	283.17a19d7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Go client to communicate with Chaos dataset API.
WWW=		https://github.com/projectdiscovery/chaos-client

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
