PORTNAME=	tcpxtract
DISTVERSION=	1.0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool for extracting files from network traffic.
WWW=		http://tcpxtract.sourceforge.net

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/flex \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
