PORTNAME=	urlview
DISTVERSION=	0.9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A curses URL parser for text files.
WWW=		http://packages.qa.debian.org/u/urlview.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/autoconf \
		??/automake-1.11 \
		??/patch

RUN_DEPENDS=	??/ncurses \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
