PORTNAME=	rdp-sec-check
DISTVERSION=	11.d0cc143
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Script to enumerate security settings of an RDP Service.
WWW=		https://github.com/portcullislabs/rdp-sec-check

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl \
		??/perl-encoding-ber


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
