PORTNAME=	bluediving
DISTVERSION=	0.9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Bluetooth penetration testing suite.
WWW=		http://bluediving.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/bluez-utils \
		??/expat \
		??/libxml2 \
		??/obexftp \
		??/openobex \
		??/perl-xml-simple \
		??/readline \
		??/sox


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
