PORTNAME=	python2
DISTVERSION=	2.7.18
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A high-level scripting language.
WWW=		https://www.python.org/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/bluez-libs \
		??/tk

RUN_DEPENDS=	??/bzip2 \
		??/expat \
		??/gdbm \
		??/libffi \
		??/libnsl \
		??/sqlite \
		??/zlib \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
