PORTNAME=	python2-libarchive
DISTVERSION=	0.4.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python adapter for universal, libarchive-based archive access.
WWW=		https://pypi.python.org/pypi/libarchive/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
