PORTNAME=	brut3k1t
DISTVERSION=	104.793821f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Brute-force attack that supports multiple protocols and services.
WWW=		https://github.com/ex0dus-0x/brut3k1t

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-appdirs@${PY_FLAVOR} \
		??/py-astroid@${PY_FLAVOR} \
		??/py-attrs@${PY_FLAVOR} \
		??/py-bcrypt@${PY_FLAVOR} \
		??/py-beautifulsoup4@${PY_FLAVOR} \
		??/py-black@${PY_FLAVOR} \
		??/py-certifi@${PY_FLAVOR} \
		??/py-cffi@${PY_FLAVOR} \
		??/py-chardet@${PY_FLAVOR} \
		??/py-click@${PY_FLAVOR} \
		??/py-cryptography@${PY_FLAVOR} \
		??/py-html5lib@${PY_FLAVOR} \
		??/py-idna@${PY_FLAVOR} \
		??/py-isort@${PY_FLAVOR} \
		??/py-lazy-object-proxy@${PY_FLAVOR} \
		??/py-mccabe@${PY_FLAVOR} \
		??/py-mechanize@${PY_FLAVOR} \
		??/py-mock@${PY_FLAVOR} \
		??/py-more-itertools@${PY_FLAVOR} \
		??/py-mypy_extensions@${PY_FLAVOR} \
		??/py-packaging@${PY_FLAVOR} \
		??/py-paramiko@${PY_FLAVOR} \
		??/py-pathspec@${PY_FLAVOR} \
		??/py-pluggy@${PY_FLAVOR} \
		??/py-pycparser@${PY_FLAVOR} \
		??/py-pylint@${PY_FLAVOR} \
		??/py-pynacl@${PY_FLAVOR} \
		??/py-pyparsing@${PY_FLAVOR} \
		??/py-regex@${PY_FLAVOR} \
		??/py-selenium@${PY_FLAVOR} \
		??/py-soupsieve@${PY_FLAVOR} \
		??/py-toml@${PY_FLAVOR} \
		??/py-typed-ast@${PY_FLAVOR} \
		??/py-typing-extensions@${PY_FLAVOR} \
		??/py-urllib3@${PY_FLAVOR} \
		??/py-wcwidth@${PY_FLAVOR} \
		??/py-webencodings@${PY_FLAVOR} \
		??/py-wrapt@${PY_FLAVOR} \
		devel/py-six@${PY_FLAVOR} \
		lang/python \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
