PORTNAME=	shuffledns
DISTVERSION=	851.bc31821
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A wrapper around massdns written in GO.
WWW=		https://github.com/projectdiscovery/shuffledns.git

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go

RUN_DEPENDS=	??/massdns


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
