PORTNAME=	perl-tftp
DISTVERSION=	1.0b3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	TFTP Client class for perl.
WWW=		https://metacpan.org/pod/TFTP

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
