PORTNAME=	thc-keyfinder
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Finds crypto keys, encrypted data and compressed data in files by analyzing the entropy of parts of the file.
WWW=		https://www.thc.org/releases.php

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gcc



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
