PORTNAME=	ssl-hostname-resolver
DISTVERSION=	1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	CN (Common Name) grabber on X.509 Certificates over HTTPS.
WWW=		http://packetstormsecurity.com/files/120634/Common-Name-Grabber-Script.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-bytes-random-secure \
		??/perl-crypt-ssleay \
		??/perl-net-cidr-lite \
		??/perl-netaddr-ip


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
