PORTNAME=	vfeed
DISTVERSION=	81.fad17ae
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Open Source Cross Linked and Aggregated Local Vulnerability Database main repository.
WWW=		http://www.toolswatch.org/vfeed

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
