PORTNAME=	perl-getopt-long
DISTVERSION=	2.58
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Extended processing of command line options.
WWW=		https://metacpan.org/pod/Getopt::Long

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
