PORTNAME=	ftester
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool designed for testing firewall filtering policies and Intrusion Detection System (IDS) capabilities.
WWW=		http://www.inversepath.com/ftester.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-net-pcaputils \
		??/perl-net-rawip \
		??/perl-netpacket


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
