PORTNAME=	wscript
DISTVERSION=	201.0410be2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Emulator/tracer of the Windows Script Host functionality.
WWW=		https://github.com/mrpapercut/wscript

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		www/npm

RUN_DEPENDS=	??/xdg-utils


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
