PORTNAME=	cent
DISTVERSION=	v2.0.0.r0.gfe2e389
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Community edition nuclei templates.
WWW=		https://github.com/xm1k3/cent

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
