PORTNAME=	antiransom
DISTVERSION=	5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool capable of detect and stop attacks of Ransomware using honeypots.
WWW=		http://www.security-projects.com/?Anti_Ransom___Download

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
