PORTNAME=	tcpextract
DISTVERSION=	1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Extracts files from captured TCP sessions. Support live streams and pcap files.
WWW=		https://pypi.org/project/tcpextract/#files

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-pynids@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
