PORTNAME=	rustpad
DISTVERSION=	v1.8.1.r1.g11ce343
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Multi-threaded Padding Oracle attacks against any service.
WWW=		https://github.com/Kibouo/rustpad

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/cargo \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
