PORTNAME=	kacak
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tools for penetration testers that can enumerate which users logged on windows system.
WWW=		https://github.com/galkan/kacak

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/metasploit \
		??/py-lxml@${PY_FLAVOR} \
		??/py-nmap@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
