PORTNAME=	creds
DISTVERSION=	17.1ec8297
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Harvest FTP/POP/IMAP/HTTP/IRC credentials along with interesting data from each of the protocols.
WWW=		https://github.com/DanMcInerney/creds.py

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3 \
		net/py-scapy@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
