PORTNAME=	cisco5crack
DISTVERSION=	2.c4b228c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Crypt and decrypt the cisco enable 5 passwords.
WWW=		https://github.com/madrisan/cisco5crack

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
