PORTNAME=	passivedns
DISTVERSION=	297.be48a8e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A network sniffer that logs all DNS server replies for use in a passive DNS setup.
WWW=		https://github.com/gamelinux/passivedns

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/gcc \
		??/ldns \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
