PORTNAME=	python2-textblob
DISTVERSION=	0.19.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Pythonic text processing. Sentiment analysis, part-of-speech tagging, and more.
WWW=		https://pypi.org/project/textblob/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
