PORTNAME=	ruby-unicode-confusable
DISTVERSION=	1.13.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Unicode confusables helper in Ruby.
WWW=		https://github.com/janlelis/unicode-confusable

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
