PORTNAME=	libpff
DISTVERSION=	224.06f239d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A library to access the Personal Folder File (PFF) and the Offline Folder File (OFF) format.
WWW=		https://github.com/libyal/libpff

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/autoconf \
		??/automake \
		??/bison \
		??/flex \
		??/gettext \
		??/libtool \
		??/pkg-config \
		devel/git

RUN_DEPENDS=	??/libbfio


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
