PORTNAME=	truecrack
DISTVERSION=	35
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Password cracking for truecrypt(c) volumes.
WWW=		http://code.google.com/p/truecrack/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/cuda


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
