PORTNAME=	libdisasm
DISTVERSION=	0.23
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A disassembler library.
WWW=		http://bastard.sourceforge.net/libdisasm.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
