PORTNAME=	perl-netpacket
DISTVERSION=	1.7.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Assemble/disassemble network packets at the protocol level.
WWW=		http://search.cpan.org/dist/NetPacket/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl-module-build



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
