PORTNAME=	netexec
DISTVERSION=	v1.5.0.r59.g07447a0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Windows / Active Directory environments pentest tool.
WWW=		https://netexec.wiki/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-virtualenv@${PY_FLAVOR} \
		devel/git \
		lang/rust



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
