PORTNAME=	nzyme
DISTVERSION=	1.2.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	WiFi defense system.
WWW=		https://www.nzyme.org/download

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
