PORTNAME=	gtk-sharp-2
DISTVERSION=	2.12.45
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Gtk2 bindings for C#.
WWW=		https://www.mono-project.com/docs/gui/gtksharp/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/monodoc

RUN_DEPENDS=	??/gtk2 \
		??/mono


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
