PORTNAME=	dkmc
DISTVERSION=	56.3c238f0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Dont kill my cat - Malicious payload evasion tool.
WWW=		https://github.com/Mr-Un1k0d3r/DKMC

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
