PORTNAME=	python-chromedriver-autoinstaller
DISTVERSION=	0.6.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Automatically install chromedriver that supports the currently installed version of chrome.
WWW=		https://pypi.org/project/chromedriver-autoinstaller/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
