PORTNAME=	smap-scanner
DISTVERSION=	0.1.12.r5.gfcf43c1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Passive port scanner built with shodan free API.
WWW=		https://github.com/s0md3v/Smap

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
