PORTNAME=	gtp-scan
DISTVERSION=	0.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A small python script that scans for GTP (GPRS tunneling protocol) speaking hosts.
WWW=		http://www.c0decafe.de/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-ipy@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
