PORTNAME=	firstexecution
DISTVERSION=	6.a275793
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Collection of different ways to execute code outside of the expected entry points.
WWW=		https://github.com/nccgroup/firstexecution

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
