PORTNAME=	openpuff
DISTVERSION=	4.01
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Yet not another steganography SW.
WWW=		https://embeddedsw.net/OpenPuff_Steganography_Home.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/wine-mono \
		??/wine_gecko \
		emulators/wine


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
