PORTNAME=	rookie
DISTVERSION=	v0.5.6.r2.g60ba7ae
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Load cookies from your web browsers.
WWW=		https://github.com/thewh1teagle/rookie

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/cargo \
		devel/git

RUN_DEPENDS=	??/sqlite


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
