PORTNAME=	webhandler
DISTVERSION=	348.1bd971e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A handler for PHP system functions & also an alternative netcat handler.
WWW=		https://github.com/lnxg33k/webhandler

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
