PORTNAME=	ctunnel
DISTVERSION=	0.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tunnel and/or proxy TCP or UDP connections via a cryptographic tunnel.
WWW=		http://nardcore.org/ctunnel

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libgcrypt \
		??/zlib


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
