PORTNAME=	bluebugger
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An implementation of the bluebug technique which was discovered by Martin Herfurt.
WWW=		http://packetstormsecurity.com/files/54024/bluebugger-0.1.tar.gz.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/bluez-libs


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
