PORTNAME=	muraena
DISTVERSION=	230.9a535ba
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Almost-transparent reverse proxy to automate phishing and post-phishing activities.
WWW=		https://github.com/muraenateam/muraena

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
