PORTNAME=	pyssltest
DISTVERSION=	9.d7703f0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A python multithreaded script to make use of Qualys ssllabs api to test SSL flaws.
WWW=		https://github.com/moheshmohan/pyssltest

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-linecache2@${PY_FLAVOR} \
		??/py-unirest@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
