PORTNAME=	perl-test-identity
DISTVERSION=	0.01
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl module to test the referential identity of a reference.
WWW=		https://metacpan.org/release/Test-Identity

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-module-build


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
