PORTNAME=	meanalyzer
DISTVERSION=	1.273.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Intel Engine Firmware Analysis Tool.
WWW=		https://github.com/platomav/MEAnalyzer

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-colorama@${PY_FLAVOR} \
		??/py-crccheck@${PY_FLAVOR} \
		??/py-prettytable@${PY_FLAVOR} \
		??/py-ptable-boxchar@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
