PORTNAME=	blackarch-config-bash
DISTVERSION=	11.b2b10c8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	BlackArch config for the bash shell.
WWW=		https://github.com/BlackArch/blackarch-config-bash

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
