PORTNAME=	pkcrack
DISTVERSION=	1.2.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A PkZip encryption cracker.
WWW=		https://www.unix-ag.uni-kl.de/~conrad/krypto/pkcrack/download1.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
