PORTNAME=	powersploit
DISTVERSION=	591.d943001
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A PowerShell Post-Exploitation Framework.
WWW=		https://github.com/mattifestation/PowerSploit

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
