PORTNAME=	automake-1.11
DISTVERSION=	1.11.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A GNU tool for automatically creating Makefiles.
WWW=		https://www.gnu.org/software/automake

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
