PORTNAME=	shellter
DISTVERSION=	7.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A dynamic shellcode injection tool, and the first truly dynamic PE infector ever created.
WWW=		https://www.shellterproject.com/download/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	emulators/wine


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
