PORTNAME=	ecfs
DISTVERSION=	305.1758063
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Extended core file snapshot format.
WWW=		https://github.com/elfmaster/ecfs

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/clang \
		devel/git

RUN_DEPENDS=	??/libdwarf


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
