PORTNAME=	junkie
DISTVERSION=	28.83a6faf
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A modular packet sniffer and analyzer.
WWW=		https://github.com/securactive/junkie

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/doxygen \
		??/guile \
		??/openssl-1.0 \
		??/p0f \
		??/rlwrap \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
