PORTNAME=	ncpfs
DISTVERSION=	2.2.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Allows you to mount volumes of NetWare servers under Linux.
WWW=		http://www.novell.com/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/linux \
		??/pam


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
