PORTNAME=	blackarch-officials
DISTVERSION=	20251027
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Meta package for installing official security tools from the Arch Linux repository.
WWW=		https://www.blackarch.org/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
