PORTNAME=	nasnum
DISTVERSION=	5.df5df19
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Script to enumerate network attached storages.
WWW=		https://github.com/tcstool/nasnum.git

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/ncftp \
		??/net-snmp \
		??/nfs-utils \
		??/smbclient \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
