PORTNAME=	urldigger
DISTVERSION=	02c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A python tool to extract URL addresses from different HOT sources and/or detect SPAM and malicious code
WWW=		https://code.google.com/p/urldigger/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
