PORTNAME=	arcane
DISTVERSION=	2.750cb9f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Backdoor iOS packages and create the necessary resources for APT repositories.
WWW=		https://github.com/tokyoneon/Arcane

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/bzip2 \
		??/openbsd-netcat \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
