PORTNAME=	python2-yaml
DISTVERSION=	5.4.1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	YAML parser and emitter for Python.
WWW=		https://pypi.org/project/yaml/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cython2 \
		devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	??/libyaml \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
