PORTNAME=	modscan
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A new tool designed to map a SCADA MODBUS TCP based network.
WWW=		https://code.google.com/p/modscan/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-ipy@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
