PORTNAME=	airopy
DISTVERSION=	5.b83f11d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Get (wireless) clients and access points.
WWW=		https://github.com/Josue87/Airopy

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-termcolor@${PY_FLAVOR} \
		??/scapy \
		lang/python \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
