PORTNAME=	vbscan
DISTVERSION=	39.2b1ce48
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A black box vBulletin vulnerability scanner written in perl.
WWW=		https://github.com/rezasp/vbscan

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
