PORTNAME=	beleth
DISTVERSION=	36.0963699
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Multi-threaded Dictionary based SSH cracker.
WWW=		https://github.com/chokepoint/Beleth

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/libssh2


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
