PORTNAME=	codeql
DISTVERSION=	2.22.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The CLI tool for GitHub CodeQL
WWW=		https://github.com/codeql

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-runtime-headless \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
