PORTNAME=	amass
DISTVERSION=	v5.0.1.r1.g61f53cc
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	In-depth subdomain enumeration written in Go.
WWW=		https://github.com/OWASP/Amass

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
