PORTNAME=	wpa-bruteforcer
DISTVERSION=	4.d5f8586
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Attacking WPA/WPA encrypted access point without client.
WWW=		https://github.com/SYWorks/wpa-bruteforcer

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
