PORTNAME=	ruby-webrobots
DISTVERSION=	0.1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Ruby library to help write robots.txt compliant web robots.
WWW=		https://github.com/knu/webrobots

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	lang/ruby



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
