PORTNAME=	miniconda
DISTVERSION=	4.5.12
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Mini version of Anaconda Python distribution.
WWW=		https://conda.io/miniconda

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
