PORTNAME=	cmsfuzz
DISTVERSION=	5.6be5a98
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fuzzer for wordpress, cold fusion, drupal, joomla, and phpnuke.
WWW=		https://github.com/nahamsec/CMSFuzz

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
