PORTNAME=	subzy
DISTVERSION=	v1.2.1.r0.gf2e2ec7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Subdomain takeover vulnerability checker.
WWW=		https://github.com/PentestPad/subzy

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
