PORTNAME=	mac-robber
DISTVERSION=	1.02
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A digital investigation tool that collects data from allocated files in a mounted file system.
WWW=		http://www.sleuthkit.org/mac-robber/download.php

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
