PORTNAME=	shellcode-factory
DISTVERSION=	96.07ae857
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool to create and test shellcodes from custom assembly sources.
WWW=		https://github.com/danielhenrymantilla/shellcode-factory

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/binutils \
		??/gdb \
		??/nano \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
