PORTNAME=	monsoon
DISTVERSION=	261.f4f9852
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A fast HTTP enumerator that allows you to execute a large number of HTTP requests.
WWW=		https://github.com/RedTeamPentesting/monsoon

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
