PORTNAME=	matahari
DISTVERSION=	0.1.30
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A reverse HTTP shell to execute commands on remote machines behind firewalls.
WWW=		http://matahari.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
