PORTNAME=	winrelay
DISTVERSION=	2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A TCP/UDP forwarder/redirector that works with both IPv4 and IPv6.
WWW=		http://ntsecurity.nu/toolbox/winrelay/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
