PORTNAME=	cracken
DISTVERSION=	v1.0.1.r0.g7a325ff
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A fast password wordlist generator, Smartlist creation and password hybrid-mask analysis tool written in pure safe Rust.
WWW=		https://github.com/shmuelamar/cracken

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/cargo \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
