PORTNAME=	libfastjson
DISTVERSION=	0.99.9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A performance-focused json library for C.
WWW=		https://github.com/rsyslog/libfastjson

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
