PORTNAME=	dumpsmbshare
DISTVERSION=	23.1e5ceb1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A script to dump files and folders remotely from a Windows SMB share.
WWW=		https://github.com/p0dalirius/DumpSMBShare

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/impacket \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
