PORTNAME=	httprint-win32
DISTVERSION=	301
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A web server fingerprinting tool (Windows binaries).
WWW=		http://net-square.com/httprint

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
