PORTNAME=	vmap
DISTVERSION=	0.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Vulnerability-Exploit desktop finder.
WWW=		https://github.com/git-rep/vmap

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libxml++ \
		??/qt5-base \
		??/qt5-svg \
		ftp/curl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
