PORTNAME=	ruby-singleton
DISTVERSION=	0.3.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Implement the Singleton pattern.
WWW=		https://rubygems.org/gems/singleton

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
