PORTNAME=	magictree
DISTVERSION=	1.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A penetration tester productivity tool designed to allow easy and straightforward data consolidation, querying, external command execution and report generation.
WWW=		http://www.gremwell.com

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment \
		??/screen


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
