PORTNAME=	crackpkcs12
DISTVERSION=	0.2.10.11.c7dedb1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A multithreaded program to crack PKCS#12 files (p12 and pfx extensions).
WWW=		https://github.com/crackpkcs12/crackpkcs12

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
