PORTNAME=	log4cpp
DISTVERSION=	1.1.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A library of C++ classes for flexible logging to files, syslog, IDSA and other destinations.
WWW=		http://log4cpp.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libnsl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
