PORTNAME=	wxhexeditor
DISTVERSION=	v0.24.r109.gf439d8f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A free hex editor / disk editor for Linux, Windows and MacOSX.
WWW=		http://wxhexeditor.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/python \
		lang/python3

RUN_DEPENDS=	??/mhash \
		??/wxwidgets-gtk3 \
		lang/python \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
