PORTNAME=	stompy
DISTVERSION=	0.0.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An advanced utility to test the quality of WWW session identifiers and other tokens that are meant to be unpredictable.
WWW=		http://lcamtuf.coredump.cx/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
