PORTNAME=	sub7
DISTVERSION=	2.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A remote administration tool. No further comments ;-)
WWW=		https://dl.packetstormsecurity.net/trojans/Subseven.2.2.zip

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	archivers/unzip



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
