PORTNAME=	tpcat
DISTVERSION=	latest
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool based upon pcapdiff by the EFF.
WWW=		http://sourceforge.net/projects/tpcat/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-pcapy@${PY_FLAVOR} \
		??/wxpython \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
