PORTNAME=	blackarch-wallpaper
DISTVERSION=	3.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The default BlackArch Linux wallpaper.
WWW=		https://github.com/BlackArch/blackarch-artwork

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
