PORTNAME=	gooscan
DISTVERSION=	1.0.9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool that automates queries against Google search appliances, but with a twist.
WWW=		http://johnny.ihackstuff.com/downloads/task,doc_details&Itemid=/gid,28/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
