PORTNAME=	sandmap
DISTVERSION=	581.5be99d4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Simple CLI with the ability to run pure Nmap engine, 31 modules with 459 scan profiles.
WWW=		https://github.com/trimstray/sandmap

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/proxychains-ng \
		??/tor \
		??/xterm \
		security/nmap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
