PORTNAME=	hharp
DISTVERSION=	1beta
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This tool can perform man-in-the-middle and switch flooding attacks. It
WWW=		http://packetstormsecurity.com/files/81368/Hackers-Hideaway-ARP-Attack-Tool.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3 \
		net/py-scapy@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
