PORTNAME=	httpx
DISTVERSION=	v1.7.4.r54.gd54cb54
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A fast and multi-purpose HTTP toolkit allow to run multiple probers using retryablehttp library.
WWW=		https://github.com/projectdiscovery/httpx

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
