PORTNAME=	thc-pptp-bruter
DISTVERSION=	0.1.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A brute force program that works against pptp vpn endpoints (tcp port 1723).
WWW=		http://www.thc.org

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gcc \
		devel/git

RUN_DEPENDS=	security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
