PORTNAME=	hoover
DISTVERSION=	4.9bda860
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Wireless Probe Requests Sniffer.
WWW=		https://github.com/xme/hoover/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/net-tools \
		??/perl \
		??/perl-getopt-long \
		??/wireless_tools \
		??/wireshark-cli


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
