PORTNAME=	bqm
DISTVERSION=	v1.5.1.r5.ge287280
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Download BloudHound query lists, deduplicate entries and merge them in one file.
WWW=		https://github.com/Acceis/bqm

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
