PORTNAME=	gwcheck
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple program that checks if a host in an ethernet network is a gateway to Internet.
WWW=		http://packetstormsecurity.com/files/62047/gwcheck.c.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
