PORTNAME=	python2-python-libnmap
DISTVERSION=	0.7.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python NMAP library enabling you to start async nmap tasks, parse and compare/diff scan results.
WWW=		https://pypi.org/project/python-libnmap/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
