PORTNAME=	kamerka
DISTVERSION=	47.23a9bd6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Build interactive map of cameras from Shodan.
WWW=		https://github.com/s7x/kamerka

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-virtualenv@${PY_FLAVOR} \
		devel/git \
		devel/py-pip@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
