PORTNAME=	perl-crypt-dsa
DISTVERSION=	1.17
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	DSA Signatures and Key Generation.
WWW=		http://search.cpan.org/dist/Crypt-DSA

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl-module-install

RUN_DEPENDS=	??/perl \
		??/perl-data-buffer \
		??/perl-digest-sha1 \
		??/perl-file-which


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
