PORTNAME=	binflow
DISTVERSION=	5.7fb02a9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	POSIX function tracing. Much better and faster than ftrace.
WWW=		https://github.com/elfmaster/binflow

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/capstone \
		??/linux-headers


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
