PORTNAME=	mimikatz
DISTVERSION=	2.2.0.20220919
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A little tool to play with Windows security.
WWW=		https://github.com/gentilkiwi/mimikatz

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
