PORTNAME=	msmailprobe
DISTVERSION=	1.c01c8bf
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Office 365 and Exchange Enumeration tool.
WWW=		https://github.com/busterb/msmailprobe

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
