PORTNAME=	blackarch-config-spectrwm
DISTVERSION=	8.ee5d156
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	BlackArch menu, theme and config for spectrwm window manager.
WWW=		https://github.com/BlackArch/blackarch-config-spectrwm

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/blackarch-wallpaper \
		??/feh \
		??/rxvt-unicode \
		??/spectrwm \
		??/terminus-font


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
