PORTNAME=	dcrawl
DISTVERSION=	7.3273c35
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Simple, but smart, multi-threaded web crawler for randomly gathering huge lists of unique domain names.
WWW=		https://github.com/kgretzky/dcrawl

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
