PORTNAME=	perl-net-packet
DISTVERSION=	3.28
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A unified framework to send a receive packets.
WWW=		https://metacpan.org/release/Net-Packet

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl-extutils-makemaker

RUN_DEPENDS=	??/perl-bit-vector \
		??/perl-class-gomor \
		??/perl-net-ipv4addr \
		??/perl-net-ipv6addr \
		??/perl-net-libdnet \
		??/perl-net-pcap \
		??/perl-net-write \
		??/perl-socket6


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
