PORTNAME=	bluebox-ng
DISTVERSION=	1.1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A GPL VoIP/UC vulnerability scanner.
WWW=		https://github.com/jesusprubio/bluebox-ng

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/coffee-script \
		lang/python3 \
		security/nmap \
		www/node


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
