PORTNAME=	hetty
DISTVERSION=	v0.7.0.r7.gf7def87
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	HTTP toolkit for security research. Aims to become an open source alternative to commercial software like Burp Suite Pro.
WWW=		https://github.com/dstotijn/hetty

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/yarn \
		devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
