PORTNAME=	pwd-hash
DISTVERSION=	2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A password hashing tool that use the crypt function to generate the hash of a string given on standard input.
WWW=		http://vladz.devzero.fr/pwd-hash.php

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
