PORTNAME=	mfcuk
DISTVERSION=	0.3.8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	MIFARE Classic Universal toolKit.
WWW=		https://github.com/nfc-tools/mfcuk/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/autoconf \
		??/make

RUN_DEPENDS=	??/libnfc


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
