PORTNAME=	viproy-voipkit
DISTVERSION=	82.52b27db
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	VoIP Pen-Test Kit for Metasploit Framework.
WWW=		http://viproy.com/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/metasploit \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
