PORTNAME=	ncurses5-compat-libs
DISTVERSION=	6.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	System V Release 4.0 curses emulation library, ABI 5.
WWW=		http://invisible-island.net/ncurses/ncurses.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/sh


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
