PORTNAME=	perl-math-pari
DISTVERSION=	2.030528
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl interface to PARI.
WWW=		https://metacpan.org/pod/Math::Pari

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
