PORTNAME=	0trace
DISTVERSION=	1.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A hop enumeration tool.
WWW=		http://jon.oberheide.org/0trace/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-dpkt@${PY_FLAVOR} \
		??/py-pydnet@${PY_FLAVOR} \
		??/py-pypcap@${PY_FLAVOR} \
		devel/py-setuptools@${PY_FLAVOR} \
		net/libdnet


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
