PORTNAME=	swap-digger
DISTVERSION=	51.4d18ce0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool used to automate Linux swap analysis during post-exploitation or forensics.
WWW=		https://github.com/sevagas/swap_digger

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
