PORTNAME=	protos-sip
DISTVERSION=	2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	SIP test suite.
WWW=		https://www.ee.oulu.fi/research/ouspg/PROTOS_Test-Suite_c07-sip

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-runtime-headless


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
