PORTNAME=	onesixtyone
DISTVERSION=	0.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An SNMP scanner that sends multiple SNMP requests to multiple IP addresses
WWW=		http://labs.portcullis.co.uk/application/onesixtyone/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
