PORTNAME=	h2spec
DISTVERSION=	2.6.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A conformance testing tool for HTTP/2 implementation.
WWW=		https://github.com/summerwind/h2spec

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
