PORTNAME=	scrying
DISTVERSION=	v0.9.2.r0.g9d50ade
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Collect RDP, web, and VNC screenshots smartly.
WWW=		https://github.com/nccgroup/scrying

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/webkit2gtk \
		devel/cargo \
		devel/git

RUN_DEPENDS=	??/chromium


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
