PORTNAME=	python2-iampoliciesgonewild
DISTVERSION=	1.0.6.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	AWS IAM Policy Expander Minimizer.
WWW=		https://pypi.org/project/iampoliciesgonewild/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
