PORTNAME=	tsh-sctp
DISTVERSION=	2.850a2da
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An open-source UNIX backdoor.
WWW=		https://github.com/infodox/tsh-sctp

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
