PORTNAME=	oclhashcat
DISTVERSION=	2.01
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Worlds fastest WPA cracker with dictionary mutation engine.
WWW=		http://hashcat.net/oclhashcat/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
