PORTNAME=	ccrawldns
DISTVERSION=	v1.0.r2.gdfd5062
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Retrieves from the CommonCrawl data set unique subdomains for a given domain name.
WWW=		https://github.com/lgandx/CCrawlDNS

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
