PORTNAME=	perl-digest-crc
DISTVERSION=	0.23
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Generic interface to CRC algorithms.
WWW=		http://search.cpan.org/dist/Digest-CRC/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl-module-build \
		??/perl-module-install

RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
