PORTNAME=	dnsteal
DISTVERSION=	28.1b09d21
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	DNS Exfiltration tool for stealthily sending files over DNS requests..
WWW=		https://github.com/m57/dnsteal

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
