PORTNAME=	python2-xgoogle
DISTVERSION=	20.3db20fb
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python library to Google services (google search, google sets, google translate, sponsored links).
WWW=		https://github.com/pkrumins/xgoogle

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
