PORTNAME=	capa
DISTVERSION=	7.4.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The FLARE teams open-source tool to identify capabilities in executable files.
WWW=		https://github.com/mandiant/capa

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
