PORTNAME=	tftp-fuzz
DISTVERSION=	1337
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Master TFTP fuzzing script as part of the ftools series of fuzzers.
WWW=		http://nullsecurity.net/tools/fuzzer.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
