PORTNAME=	gadgetinspector
DISTVERSION=	6.ac7832d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A byte code analyzer for finding deserialization gadget chains in Java applications.
WWW=		https://github.com/JackOfMostTrades/gadgetinspector

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/apache-ant \
		??/gradle \
		??/jdk-openjdk \
		devel/git

RUN_DEPENDS=	??/java-runtime


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
