PORTNAME=	shosubgo
DISTVERSION=	V5.0.r0.gccb6dc7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Small tool to Grab subdomains using Shodan API.
WWW=		https://github.com/incogbyte/shosubgo

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
