PORTNAME=	grig
DISTVERSION=	0.8.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Rig control (cat) program.
WWW=		http://groundstation.sourceforge.net/grig/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gtk2 \
		??/hamlib \
		??/intltool


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
