PORTNAME=	tcpcontrol-fuzzer
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	2^6 TCP control bit fuzzer (no ECN or CWR).
WWW=		https://www.ee.oulu.fi/research/ouspg/tcpcontrol-fuzzer

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-net-rawip


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
