PORTNAME=	tinja
DISTVERSION=	1.2.0.r3.g7a8e921
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	CLI tool for testing web pages for template injection vulnerabilities.
WWW=		https://github.com/Hackmanit/TInjA

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
