PORTNAME=	blackarch-config-xfce
DISTVERSION=	15.996cb2d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	BlackArch theme and config for xfce desktop enviroment.
WWW=		https://github.com/BlackArch/blackarch-config-xfce

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/blackarch-menus


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
