PORTNAME=	slurp-scanner
DISTVERSION=	93.2dea27e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Evaluate the security of S3 buckets.
WWW=		https://github.com/0xbharath/slurp

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
