PORTNAME=	lodowep
DISTVERSION=	1.2.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Lodowep is a tool for analyzing password strength of accounts on a Lotus Domino webserver system.
WWW=		http://www.cqure.net/wp/lodowep/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
