PORTNAME=	perl-io-socket
DISTVERSION=	1.45
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Object interface to socket communications.
WWW=		http://search.cpan.org/~gbarr/IO-1.25/lib/IO/Socket.pm

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
