PORTNAME=	dnspy
DISTVERSION=	6.1.8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	.NET debugger and assembly editor.
WWW=		https://github.com/0xd4d/dnSpy/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
