PORTNAME=	veles
DISTVERSION=	2018.05
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	New open source tool for binary data analysis.
WWW=		https://codisec.com/veles/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/double-conversion \
		??/py-msgpack@${PY_FLAVOR} \
		??/py-pbr@${PY_FLAVOR} \
		??/py-pyopenssl@${PY_FLAVOR} \
		??/qt5-base \
		devel/py-six@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
