PORTNAME=	ysoserial
DISTVERSION=	0.0.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A proof-of-concept tool for generating payloads that exploit unsafe Java object deserialization.
WWW=		https://github.com/frohoff/ysoserial

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
