PORTNAME=	calamares
DISTVERSION=	3.3.0.23.0321
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Distribution-independent installer framework.
WWW=		https://github.com/calamares/calamares

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/boost \
		??/extra-cmake-modules \
		??/kdbusaddons \
		??/kparts \
		??/qt5-tools \
		??/qt5-translations \
		devel/git \
		lang/python

RUN_DEPENDS=	??/appstream-qt \
		??/boost-libs \
		??/ckbcomp \
		??/efibootmgr \
		??/gtk-update-icon-cache \
		??/hwinfo \
		??/icu \
		??/kconfig \
		??/kcoreaddons \
		??/kdbusaddons \
		??/ki18n \
		??/kiconthemes \
		??/kio \
		??/kpmcore \
		??/libpwquality \
		??/mkinitcpio-openswap \
		??/plasma-framework \
		??/polkit-qt5 \
		??/qt5-svg \
		??/qt5-xmlpatterns \
		??/solid \
		??/squashfs-tools \
		??/yaml-cpp \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
