PORTNAME=	pyfuscation
DISTVERSION=	17.6d8d53f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Obfuscate powershell scripts by replacing Function names, Variables and Parameters.
WWW=		https://github.com/CBHue/PyFuscation

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
