PORTNAME=	python2-fs
DISTVERSION=	2.4.11
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Filesystem abstraction layer.
WWW=		https://pypi.org/project/fs/#files

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-appdirs@${PY_FLAVOR} \
		??/py-pytz@${PY_FLAVOR} \
		devel/py-setuptools@${PY_FLAVOR} \
		devel/py-six@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
