PORTNAME=	aptdec
DISTVERSION=	v1.8.0.r2.g7db2030
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	NOAA APT satellite imagery decoder.
WWW=		https://github.com/Xerbo/aptdec

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git

RUN_DEPENDS=	??/libpng \
		??/libsndfile


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
