PORTNAME=	crunch
DISTVERSION=	3.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A wordlist generator for all combinations/permutations of a given character set.
WWW=		http://sourceforge.net/projects/crunch-wordlist/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
