PORTNAME=	python-backports-lzma
DISTVERSION=	0.0.14
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Backport of Python 3.3s standard library module lzma for LZMA/XY compressed files.
WWW=		https://github.com/peterjc/backports.lzma

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
