PORTNAME=	pwnloris
DISTVERSION=	14.7ad1486
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An improved slowloris DOS tool which keeps attacking until the server starts getting exhausted.
WWW=		https://github.com/h0ussni/pwnloris

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-pysocks@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
