PORTNAME=	android-ndk
DISTVERSION=	r29
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Android C/C++ developer kit
WWW=		https://developer.android.com/ndk/downloads

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/android-sdk


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
