PORTNAME=	go-windapsearch
DISTVERSION=	v0.3.0.r22.ged05587
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Utility to enumerate users, groups and computers from a Windows domain through LDAP queries.
WWW=		https://github.com/ropnop/go-windapsearch

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/mage \
		devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
