PORTNAME=	ms-sys
DISTVERSION=	2.8.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool to write Win9x- master boot records (mbr) under linux - RTM!
WWW=		http://ms-sys.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
