PORTNAME=	perl-test-tcp
DISTVERSION=	2.22
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Testing TCP program.
WWW=		https://metacpan.org/release/Test-TCP

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-test-sharedfork


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
