PORTNAME=	outlook-webapp-brute
DISTVERSION=	1.61d7177
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Microsoft Outlook WebAPP Brute.
WWW=		https://github.com/lijiejie/OutLook_WebAPP_Brute

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
