PORTNAME=	pown
DISTVERSION=	332.0e32edf
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Security testing and exploitation toolkit built on top of Node.js and NPM.
WWW=		https://github.com/pownjs/pown

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		www/npm

RUN_DEPENDS=	www/node


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
