PORTNAME=	netbios-share-scanner
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This tool could be used to check windows workstations and servers if they have accessible shared resources.
WWW=		http://www.secpoint.com/netbios-share-scanner.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
