PORTNAME=	peach
DISTVERSION=	3.0.202
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A SmartFuzzer that is capable of performing both generation and mutation based fuzzing.
WWW=		http://peachfuzzer.com/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/giflib \
		??/mono \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
