PORTNAME=	dbpwaudit
DISTVERSION=	0.8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Java tool that allows you to perform online audits of password quality for several database engines.
WWW=		http://www.cqure.net/wp/dbpwaudit/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
