PORTNAME=	punk
DISTVERSION=	9.c2bc420
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A post-exploitation tool meant to help network pivoting from a compromised unix box.
WWW=		https://github.com/r3vn/punk.py

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
