PORTNAME=	easyfuzzer
DISTVERSION=	3.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A flexible fuzzer, not only for web, has a CSV output for efficient output analysis (platform independent).
WWW=		http://www.mh-sec.de/downloads.html.en

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-io-socket-ip


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
