PORTNAME=	python2-capstone
DISTVERSION=	4.0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A disassembly framework with the target of becoming the ultimate disasm engine for binary analysis and reversing in the security community.
WWW=		https://github.com/aquynh/capstone

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	??/capstone \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
