PORTNAME=	phonon-qt4
DISTVERSION=	4.10.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The multimedia framework for KDE4.
WWW=		http://phonon.kde.org/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/extra-cmake-modules \
		??/libpulse \
		??/qt4



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
