PORTNAME=	windows-prefetch-parser
DISTVERSION=	88.bc1fa58
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Parse Windows Prefetch files.
WWW=		https://github.com/PoorBillionaire/Windows-Prefetch-Parser

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
