PORTNAME=	promptfoo
DISTVERSION=	0.120.20
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Test and evaluate LLM outputs - AI red teaming, pentesting, and vulnerability scanning.
WWW=		https://github.com/promptfoo/promptfoo

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gcc \
		??/jq \
		??/make \
		lang/python \
		www/npm

RUN_DEPENDS=	??/sqlite \
		www/node


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
