PORTNAME=	brutessh
DISTVERSION=	0.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple sshd password bruteforcer using a wordlist, its very fast for internal networks. Its multithreads.
WWW=		http://www.edge-security.com/edge-soft.php

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-paramiko@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
