PORTNAME=	perl-crypt-random
DISTVERSION=	1.52
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Cryptographically Secure, True Random Number Generator.
WWW=		http://search.cpan.org/~VIPUL/Crypt-Random-1.25/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gmp \
		??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
