PORTNAME=	dumpzilla
DISTVERSION=	03152013
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A forensic tool for firefox.
WWW=		http://www.dumpzilla.org/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/nss \
		??/py-pysqlite3@${PY_FLAVOR} \
		??/py-simplejson@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
