PORTNAME=	phpstress
DISTVERSION=	5.f987a7e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A PHP denial of service / stress test for Web Servers running PHP-FPM or PHP-CGI.
WWW=		https://github.com/nightlionsecurity/phpstress

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/php82


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
