PORTNAME=	unibrute
DISTVERSION=	1.b3fb4b7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Multithreaded SQL union bruteforcer.
WWW=		https://github.com/GDSSecurity/Unibrute

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
