PORTNAME=	sshfuzz
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A SSH Fuzzing utility written in Perl that uses Net::SSH2.
WWW=		https://packetstormsecurity.com/fuzzer/sshfuzz.txt

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-net-ssh2


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
