PORTNAME=	android-sdk-build-tools
DISTVERSION=	r34
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Build-Tools for Google Android SDK (aapt, aidl, dexdump, dx, llvm-rs-cc).
WWW=		https://developer.android.com/studio/releases/build-tools

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/zlib


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
