PORTNAME=	spooftooph
DISTVERSION=	0.5.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Designed to automate spoofing or cloning Bluetooth device Name, Class, and Address. Cloning this information effectively allows Bluetooth device to hide in plain sight.
WWW=		http://www.hackfromacave.com/projects/spooftooph.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/make

RUN_DEPENDS=	??/bluez \
		??/bluez-libs \
		??/ncurses


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
