PORTNAME=	halberd
DISTVERSION=	0.2.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Halberd discovers HTTP load balancers. It is useful for web application security auditing and for load balancer configuration testing.
WWW=		http://halberd.superadditive.com/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
