PORTNAME=	php-findsock-shell
DISTVERSION=	2.b8a984f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Findsock Shell implementation in PHP + C.
WWW=		https://github.com/pentestmonkey/php-findsock-shell

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/php82


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
