PORTNAME=	penbox
DISTVERSION=	81.3b77c69
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Penetration Testing Framework - The Tool With All The Tools.
WWW=		https://github.com/x3omdax/PenBox

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl \
		??/py-lxml@${PY_FLAVOR} \
		??/python3 \
		devel/git \
		lang/python3 \
		lang/ruby \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
