PORTNAME=	secure-delete
DISTVERSION=	1.b63d814
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Secure file, disk, swap, memory erasure utilities.
WWW=		http://www.thc.org/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
