PORTNAME=	perl-io-socket-socks
DISTVERSION=	0.74
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Provides a way to create socks client or server both 4 and 5 version.
WWW=		http://search.cpan.org/~oleg/IO-Socket-Socks-0.62

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
