PORTNAME=	bruno
DISTVERSION=	v1.34.2.r3.g4894ac2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Opensource API Client for Exploring and Testing APIs.
WWW=		https://www.usebruno.com/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/asar \
		??/nvm \
		devel/py-setuptools@${PY_FLAVOR} \
		lang/python

RUN_DEPENDS=	??/$_electron \
		??/alsa-lib


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
