PORTNAME=	aggroargs
DISTVERSION=	51.c032446
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Bruteforce commandline buffer overflows, linux, aggressive arguments.
WWW=		https://github.com/tintinweb/aggroArgs

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
