PORTNAME=	soot
DISTVERSION=	3.4.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Java Bytecode Analysis and Transformation Framework.
WWW=		http://www.sable.mcgill.ca/soot

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-runtime


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
