PORTNAME=	avaloniailspy
DISTVERSION=	v7.2.rc.r11.g21d4939
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	.NET Decompiler (port of ILSpy)
WWW=		https://github.com/icsharpcode/AvaloniaILSpy

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/dotnet-sdk \
		??/libicns \
		devel/git

RUN_DEPENDS=	??/dotnet-runtime


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
