PORTNAME=	smplshllctrlr
DISTVERSION=	9.2baf390
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	PHP Command Injection exploitation tool.
WWW=		https://github.com/z0noxz/smplshllctrlr

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
