PORTNAME=	python2-flask-whooshalchemy-redux
DISTVERSION=	0.7.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Whoosh extension to Flask/SQLAlchemy.
WWW=		https://pypi.python.org/pypi/Flask-WhooshAlchemy-Redux/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
