PORTNAME=	python2-cybox
DISTVERSION=	2.1.0.21
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Python library for parsing and generating CybOX 2.1.0 content.
WWW=		https://github.com/CybOXProject/python-cybox

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
