PORTNAME=	dinouml
DISTVERSION=	0.9.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A network simulation tool, based on UML (User Mode Linux) that can simulate big Linux networks on a single PC
WWW=		http://kernel.embedromix.ro/us/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
