PORTNAME=	perl-convert-ascii-armour
DISTVERSION=	1.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Converts binary octets into ASCII armoured messages
WWW=		http://search.cpan.org/~VIPUL/Convert-ASCII-Armour-1.4/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gmp \
		??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
