PORTNAME=	fakedns
DISTVERSION=	118.39609da
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A regular-expression based python MITM DNS server with correct DNS request passthrough and Not Found responses.
WWW=		https://github.com/Crypt0s/FakeDns

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
