PORTNAME=	sdrangel
DISTVERSION=	v7.23.1.r11.ga87fb6b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Qt6/OpenGL SDR and signal analyzer frontend.
WWW=		https://github.com/f4exb/sdrangel

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/airspy \
		??/airspyhf \
		??/aptdec \
		??/bladerf \
		??/boost \
		??/cmake \
		??/codec2 \
		??/doxygen \
		??/faad2 \
		??/ffmpeg \
		??/glslang \
		??/graphviz \
		??/hackrf \
		??/hamlib \
		??/libdab \
		??/libiio \
		??/libmirisdr4 \
		??/libperseus-sdr \
		??/libsdrplay \
		??/libuhd \
		??/libxtrx \
		??/limesuite \
		??/ninja \
		??/rtl-sdr \
		??/sgp4 \
		??/spirv-headers \
		??/spirv-tools \
		??/vulkan-headers \
		??/vulkan-icd-loader \
		??/zlib \
		devel/git

RUN_DEPENDS=	??/cm256cc \
		??/dsdcc \
		??/fftw \
		??/lz4 \
		??/nanomsg \
		??/opencv \
		??/pulse-native-provider \
		??/qt6-base \
		??/qt6-charts \
		??/qt6-declarative \
		??/qt6-location \
		??/qt6-multimedia \
		??/qt6-scxml \
		??/qt6-serialport \
		??/qt6-speech \
		??/qt6-svg \
		??/qt6-tools \
		??/qt6-webengine \
		??/qt6-websockets


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
