PORTNAME=	perl-net-subnet
DISTVERSION=	1.03
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fast IP-in-subnet matcher for IPv4 and IPv6, CIDR or mask.
WWW=		https://metacpan.org/pod/Net::Subnet

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
