PORTNAME=	exe2hex
DISTVERSION=	1.5.1.r6.ge563b35
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Inline file transfer using in-built Windows tools (DEBUG.exe or PowerShell).
WWW=		https://github.com/g0tmi1k/exe2hex

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
