PORTNAME=	aws-extender-cli
DISTVERSION=	17.a351154
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Script to test S3 buckets as well as Google Storage buckets and Azure Storage containers for common misconfiguration issues.
WWW=		https://github.com/VirtueSecurity/aws-extender-cli

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-virtualenv@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
