PORTNAME=	recentfilecache-parser
DISTVERSION=	2.5e22518
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python parser for the RecentFileCache.bcf on Windows.
WWW=		https://github.com/prolsen/recentfilecache-parser

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
