PORTNAME=	inundator
DISTVERSION=	0.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An ids evasion tool, used to anonymously inundate intrusion detection logs with false positives in order to obfuscate a real attack.
WWW=		http://inundator.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-net-cidr \
		??/perl-net-socks \
		security/nmap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
