PORTNAME=	spiderfoot
DISTVERSION=	4.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The Open Source Footprinting Tool.
WWW=		https://github.com/smicallef/spiderfoot

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-adblockparser@${PY_FLAVOR} \
		??/py-beautifulsoup4@${PY_FLAVOR} \
		??/py-cherrycors@${PY_FLAVOR} \
		??/py-cherrypy@${PY_FLAVOR} \
		??/py-cryptography@${PY_FLAVOR} \
		??/py-dnspython@${PY_FLAVOR} \
		??/py-docx@${PY_FLAVOR} \
		??/py-exifread@${PY_FLAVOR} \
		??/py-future@${PY_FLAVOR} \
		??/py-httpagentparser@${PY_FLAVOR} \
		??/py-ipaddr@${PY_FLAVOR} \
		??/py-ipwhois@${PY_FLAVOR} \
		??/py-lxml@${PY_FLAVOR} \
		??/py-mako@${PY_FLAVOR} \
		??/py-netaddr@${PY_FLAVOR} \
		??/py-networkx@${PY_FLAVOR} \
		??/py-openpyxl@${PY_FLAVOR} \
		??/py-phonenumbers@${PY_FLAVOR} \
		??/py-pptx@${PY_FLAVOR} \
		??/py-publicsuffixlist@${PY_FLAVOR} \
		??/py-pygexf@${PY_FLAVOR} \
		??/py-pyopenssl@${PY_FLAVOR} \
		??/py-pypdf2@${PY_FLAVOR} \
		??/py-pysocks@${PY_FLAVOR} \
		??/py-secure@${PY_FLAVOR} \
		??/py-stem@${PY_FLAVOR} \
		??/py-whois@${PY_FLAVOR} \
		??/py-yaml@${PY_FLAVOR} \
		lang/python \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
