PORTNAME=	libperseus-sdr
DISTVERSION=	v0.8.2.r3.gc2c95da
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perseus Software Defined Radio Control Library for Linux.
WWW=		https://github.com/Microtelecom/libperseus-sdr

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/vim \
		devel/git

RUN_DEPENDS=	??/libusb


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
