PORTNAME=	vanguard
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A comprehensive web penetration testing tool written in Perl thatidentifies vulnerabilities in web applications.
WWW=		http://packetstormsecurity.com/files/110603/Vanguard-Pentesting-Scanner.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-clone \
		??/perl-data-dumper \
		??/perl-io-socket \
		??/perl-libwww \
		??/perl-yaml


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
