PORTNAME=	yinjector
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A MySQL injection penetration tool. It has multiple features, proxy support, and multiple exploitation methods.
WWW=		http://packetstormsecurity.com/files/98359/yInjector-MySQL-Injection-Tool.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/lib32-libxcrypt-compat \
		??/lib32-openssl-1.0


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
