PORTNAME=	pwned
DISTVERSION=	2927.a40d7f6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A command-line tool for querying the Have I been pwned? service.
WWW=		https://github.com/wKovacs64/pwned

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		www/npm

RUN_DEPENDS=	www/node


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
