PORTNAME=	xxeinjector
DISTVERSION=	56.150067a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool for automatic exploitation of XXE vulnerability using direct and different out of band methods.
WWW=		https://github.com/enjoiz/XXEinjector

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
