PORTNAME=	ruby-cairo
DISTVERSION=	1.18.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Ruby bindings for cairo
WWW=		https://cairographics.org/rcairo

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/ruby-rdoc

RUN_DEPENDS=	??/cairo \
		??/ruby-native-package-installer \
		??/ruby-pkg-config \
		??/ruby-red-colors \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
