PORTNAME=	mongosh
DISTVERSION=	2.5.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An interactive shell to connect with MongoDB with syntax highlighting, autocomplete, contextual help and error messages.
WWW=		https://github.com/mongodb-js/mongosh.git

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/krb5


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
