PORTNAME=	ckbcomp
DISTVERSION=	1.207
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Compile a XKB keyboard description to a keymap suitable for loadkeys or kbdcontrol.
WWW=		http://anonscm.debian.org/cgit/d-i/console-setup.git

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
