PORTNAME=	goocanvas1
DISTVERSION=	1.0.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A cairo canvas widget for GTK+.
WWW=		http://live.gnome.org/GooCanvas

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/glib2-devel \
		lang/python

RUN_DEPENDS=	??/gtk2


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
