PORTNAME=	perl-net-tftp
DISTVERSION=	0.1901
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	TFTP Client class.
WWW=		http://search.cpan.org/~gbarr/Net-TFTP-0.19/TFTP.pm

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
