PORTNAME=	assetfinder
DISTVERSION=	19.4e95d87
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Find domains and subdomains potentially related to a given domain.
WWW=		https://github.com/tomnomnom/assetfinder

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
