PORTNAME=	cipherscan
DISTVERSION=	423.30bd239
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A very simple way to find out which SSL ciphersuites are supported by a target.
WWW=		https://github.com/jvehent/cipherscan

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3 \
		security/openssl \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
