PORTNAME=	paranoic
DISTVERSION=	1.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple vulnerability scanner written in Perl.
WWW=		http://packetstormsecurity.com/files/128065/Paranoic-Scan-1.7.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/dos2unix

RUN_DEPENDS=	??/perl \
		??/perl-color-output \
		??/perl-dbd-mysql \
		??/perl-dbi \
		??/perl-html-form \
		??/perl-image-exiftool \
		??/perl-libwww


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
