PORTNAME=	python-weakrefmethod
DISTVERSION=	1.0.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A WeakMethod class for storing bound methods using weak references.
WWW=		https://pypi.org/project/weakrefmethod/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
