PORTNAME=	python2-pysqlite-legacy
DISTVERSION=	1.0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python DB-API 2.0 interface for the legacy SQLite 2.
WWW=		https://initd.org/tracker/pysqlite

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/sqlite2 \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
