PORTNAME=	jbrofuzz
DISTVERSION=	2.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Web application protocol fuzzer that emerged from the needs of penetration testing.
WWW=		http://sourceforge.net/projects/jbrofuzz/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
