PORTNAME=	trid-defs
DISTVERSION=	2025.10.03
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Filesignature database for trid.
WWW=		http://mark0.net/soft-trid-e.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
