PORTNAME=	perl-crypt-dh
DISTVERSION=	0.07
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl/CPAN Module Crypt::DH: Diffie-Hellman key exchange system.
WWW=		http://search.cpan.org/~mithaldu/Crypt-DH-0.07/lib/Crypt/DH.pm

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/make

RUN_DEPENDS=	??/perl \
		??/perl-math-bigint-gmp \
		??/perl-module-install


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
