PORTNAME=	swt
DISTVERSION=	4.31
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An open source widget toolkit for Java.
WWW=		https://www.eclipse.org/swt/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/ant \
		??/glu \
		??/gtk3 \
		??/gtk4 \
		??/pkgconfig \
		??/webkit2gtk \
		archivers/unzip

RUN_DEPENDS=	??/java-runtime \
		??/libxtst


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
