PORTNAME=	bluescan
DISTVERSION=	1.0.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Bluetooth Device Scanner.
WWW=		http://www.darknet.org.uk/2015/01/bluescan-bluetooth-device-scanner/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/bluez \
		??/bluez-hciconfig \
		??/bluez-libs \
		??/bluez-utils \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
