PORTNAME=	siparmyknife
DISTVERSION=	11232011
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A small command line tool for developers and administrators of Session Initiation Protocol (SIP) applications.
WWW=		http://packetstormsecurity.com/files/107301/sipArmyKnife_11232011.pl.txt

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-digest-crc \
		??/perl-digest-md4 \
		??/perl-digest-md5


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
