PORTNAME=	dexpatcher
DISTVERSION=	1.7.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Modify Android DEX/APK files at source-level using Java.
WWW=		https://github.com/DexPatcher/dexpatcher-tool

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
