PORTNAME=	wifichannelmonitor
DISTVERSION=	1.70
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A utility for Windows that captures wifi traffic on the channel you choose, using Microsoft Network Monitor capture driver.
WWW=		https://www.nirsoft.net/utils/wifi_channel_monitor.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	archivers/unzip



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
