PORTNAME=	python2-flask-restplus
DISTVERSION=	0.13.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fully featured framework for fast, easy and documented API development with Flask.
WWW=		https://pypi.org/project/Flask-restplus/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
