PORTNAME=	ruby-camertron-eprun
DISTVERSION=	1.1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Efficient Pure Ruby Unicode Normalization.
WWW=		https://github.com/camertron/camertron-eprun

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
