PORTNAME=	asnmap
DISTVERSION=	v1.1.1.r3.gd2b5b11
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Map organization network ranges using ASN information.
WWW=		https://github.com/projectdiscovery/asnmap

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
