PORTNAME=	libglade
DISTVERSION=	2.6.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Allows you to load glade interface files in a program at runtime.
WWW=		http://www.gnome.org/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/pkgconfig \
		lang/python3

RUN_DEPENDS=	??/gtk2 \
		??/libxml2


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
