PORTNAME=	perl-class-accessor-lite
DISTVERSION=	0.08
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A minimalistic variant of Class::Accessor.
WWW=		https://metacpan.org/pod/Class::Accessor::Lite

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl-module-install

RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
