PORTNAME=	multiinjector
DISTVERSION=	0.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Automatic SQL injection utility using a lsit of URI addresses to test parameter manipulation.
WWW=		http://chaptersinwebsecurity.blogspot.de/2008/11/multiinjector-v03-released.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-pycurl@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
