PORTNAME=	mrkaplan
DISTVERSION=	1.1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Help red teamers to stay hidden by clearing evidence of execution.
WWW=		https://github.com/Idov31/MrKaplan

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
