PORTNAME=	x64dbg
DISTVERSION=	2025.07.04
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An open-source x64/x32 debugger for windows.
WWW=		https://github.com/x64dbg/x64dbg/releases

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
