PORTNAME=	yasat
DISTVERSION=	848
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Yet Another Stupid Audit Tool.
WWW=		https://yasat.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
