PORTNAME=	samdump2
DISTVERSION=	3.0.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Dump password hashes from a Windows NT/2k/XP installation.
WWW=		http://sourceforge.net/projects/ophcrack/files/samdump2/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
