PORTNAME=	f-scrack
DISTVERSION=	19.9a00357
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A single file bruteforcer supports multi-protocol.
WWW=		https://github.com/ysrc/F-Scrack

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
