PORTNAME=	tilt
DISTVERSION=	90.2bc2ef2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An easy and simple tool implemented in Python for ip reconnaissance, with reverse ip lookup.
WWW=		https://github.com/AeonDave/tilt

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
