PORTNAME=	marshalsec
DISTVERSION=	10.2dc4018
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Java Unmarshaller Security - Turning your data into code execution.
WWW=		https://github.com/mbechler/marshalsec/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/maven \
		devel/git

RUN_DEPENDS=	??/java-runtime


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
