PORTNAME=	perl-net-nslookup
DISTVERSION=	2.04
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Provide nslookup(1)-like capabilties.
WWW=		http://search.cpan.org/~darren/Net-Nslookup/lib/Net/Nslookup.pm

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
