PORTNAME=	xxxpwn
DISTVERSION=	12.fcca6b0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool Designed for blind optimized XPath 1 injection attacks.
WWW=		https://github.com/feakk/xxxpwn

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
