PORTNAME=	python-sip4
DISTVERSION=	4.19.25
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	
WWW=		https://www.riverbankcomputing.com/software/sip/intro

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	lang/python



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
