PORTNAME=	padre
DISTVERSION=	v2.2.0.r15.g9a2e1f2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Padding Oracle attack tool.
WWW=		https://github.com/glebarez/padre

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
