PORTNAME=	iphoneanalyzer
DISTVERSION=	2.1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Allows you to forensically examine or recover date from in iOS device.
WWW=		http://downloads.sourceforge.net/project/iphoneanalyzer/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
