PORTNAME=	bluphish
DISTVERSION=	9.a7200bd
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Bluetooth device and service discovery tool that can be used for security assessment and penetration testing.
WWW=		https://github.com/olivo/BluPhish

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
