PORTNAME=	perl-test-checkdeps
DISTVERSION=	0.010
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Check for presence of dependencies.
WWW=		http://search.cpan.org/dist/Test-CheckDeps

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-cpan-meta-check \
		??/perl-module-build-tiny


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
