PORTNAME=	octopwnweb
DISTVERSION=	14.e0f83ee
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Internal pentest framework running in your browser via WebAssembly, powerd by Pyodide
WWW=		https://github.com/skelsec/octopwnweb

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-wsnet@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
