PORTNAME=	perl-uri-fetch
DISTVERSION=	0.15
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Smart URI fetching/caching.
WWW=		https://metacpan.org/pod/URI::Fetch

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-class-errorhandler \
		??/perl-libwww \
		??/perl-uri


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
