PORTNAME=	fragroute
DISTVERSION=	1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A network intrusion detection evasion toolkit.
WWW=		http://www.monkey.org/~dugsong/fragroute/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libevent \
		net/libdnet \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
