PORTNAME=	peepingtom
DISTVERSION=	56.bc6f4d8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool to take screenshots of websites. Much like eyewitness.
WWW=		https://bitbucket.org/LaNMaSteR53/peepingtom

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/phantomjs \
		ftp/curl \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
