PORTNAME=	rpcsniffer
DISTVERSION=	7.9fab095
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Sniffs WINDOWS RPC messages in a given RPC server process.
WWW=		https://github.com/AdiKo/RPCSniffer

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
