PORTNAME=	spfmap
DISTVERSION=	8.a42d15a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A program to map out SPF and DKIM records for a large number of domains.
WWW=		https://github.com/BishopFox/spfmap

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go

RUN_DEPENDS=	??/sqlite


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
