PORTNAME=	perl-net-netmask
DISTVERSION=	2.0001
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Parse, manipulate and lookup IP network blocks.
WWW=		https://metacpan.org/release/Net-Netmask

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
