PORTNAME=	blackarch-config-x11
DISTVERSION=	21.e38cf84
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	BlackArch config for the X11 user settings.
WWW=		https://github.com/BlackArch/blackarch-config-x11

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/rxvt-unicode \
		??/terminus-font \
		??/xterm


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
