PORTNAME=	arptools
DISTVERSION=	13.41cdb23
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple tool about ARP broadcast, ARP attack, and data transmission.
WWW=		https://github.com/Lab-Zjt/ARPTools

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
