PORTNAME=	devaudit
DISTVERSION=	803.ca0a68e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An open-source, cross-platform, multi-purpose security auditing tool targeted at developers and teams.
WWW=		https://github.com/sonatype-nexus-community/DevAudit

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/mono \
		??/mono-msbuild \
		??/mono-tools


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
