PORTNAME=	pcapfix
DISTVERSION=	1.1.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tries to repair your broken pcap and pcapng files.
WWW=		http://f00l.de/pcapfix/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
