PORTNAME=	lfi-autopwn
DISTVERSION=	3.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Perl script to try to gain code execution on a remote server via LFI.
WWW=		https://www.blackhatlibrary.net/Lfi_autopwn.pl

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-libwhisker2


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
