PORTNAME=	manspider
DISTVERSION=	89.aa5194a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Spider entire networks for juicy files sitting on SMB shares. Search filenames or file content - regex supported!
WWW=		https://github.com/blacklanternsecurity/MANSPIDER

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-pipx@${PY_FLAVOR} \
		devel/git

RUN_DEPENDS=	??/py-pipx@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
