PORTNAME=	seclists
DISTVERSION=	2025.3.r847.gc39974d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A collection of multiple types of lists used during security assessments.
WWW=		https://github.com/danielmiessler/SecLists/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
