PORTNAME=	bytecode-viewer
DISTVERSION=	2.12
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Java 8/Android APK Reverse Engineering Suite.
WWW=		https://github.com/Konloch/bytecode-viewer

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
