PORTNAME=	ruby-ruby-gtkhex
DISTVERSION=	0.2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An hexadecimal widget using gtk2, inspired by GHex.
WWW=		https://rubygems.org/gems/ruby-gtkhex

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/ruby-gtk2 \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
