PORTNAME=	libfvde
DISTVERSION=	209.4b8485c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Library and tools to access FileVault Drive Encryption (FVDE) encrypted volumes.
WWW=		https://github.com/libyal/libfvde

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/autoconf \
		??/automake \
		??/binutils \
		??/gcc \
		??/libtool \
		??/make \
		devel/git

RUN_DEPENDS=	??/libxml2 \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
