PORTNAME=	tcpjunk
DISTVERSION=	2.9.03
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A general tcp protocols testing and hacking utility.
WWW=		http://code.google.com/p/tcpjunk

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/openssl-1.0

RUN_DEPENDS=	??/gtksourceview2


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
