PORTNAME=	shuji
DISTVERSION=	v0.8.0.r98.g92ae20d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Reverse engineering JavaScript and CSS sources from sourcemaps.
WWW=		https://github.com/paazmaya/shuji

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		www/npm

RUN_DEPENDS=	www/node


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
