PORTNAME=	tls-map
DISTVERSION=	v3.2.0.r0.gd11f3be
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	CLI & library for TLS cipher suites manipulation.
WWW=		https://noraj.github.io/tls-map/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/ruby-csv \
		??/ruby-docopt \
		??/ruby-paint \
		??/ruby-rexml \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
