PORTNAME=	snmpcheck
DISTVERSION=	1.9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A free open source utility to get information via SNMP protocols.
WWW=		http://www.nothink.org/perl/snmpcheck/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/ruby-snmp \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
