PORTNAME=	synscan
DISTVERSION=	5.02
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fast asynchronous half-open TCP portscanner.
WWW=		http://www.digit-labs.org/files/tools/synscan/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
