PORTNAME=	perl-encoding-ber
DISTVERSION=	1.02
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl module for encoding/decoding data using ASN.1 Basic Encoding Rules (BER).
WWW=		https://metacpan.org/pod/Encoding::BER

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
