PORTNAME=	darkjumper
DISTVERSION=	5.8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This tool will try to find every website that host at the same server at your target.
WWW=		http://sourceforge.net/projects/darkjumper/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
