PORTNAME=	lolbas
DISTVERSION=	192.d148d27
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Living Off The Land Binaries And Scripts - (LOLBins and LOLScripts).
WWW=		https://github.com/api0cradle/LOLBAS

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
