PORTNAME=	urx
DISTVERSION=	0.8.0.r146.gd4e25c0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Extracts URLs from OSINT Archives for Security Insights.
WWW=		https://github.com/hahwul/urx

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/cargo \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
