PORTNAME=	python-demjson
DISTVERSION=	2.2.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Encoder, decoder, and lint/validator for JSON (JavaScript Object Notation) compliant with RFC 4627.
WWW=		https://pypi.org/project/demjson/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
