PORTNAME=	bindead
DISTVERSION=	4504.67019b97b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A static analysis tool for binaries
WWW=		https://bitbucket.org/mihaila/bindead

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/java-environment \
		??/maven \
		devel/git

RUN_DEPENDS=	??/java-runtime \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
