PORTNAME=	netripper
DISTVERSION=	84.c763bd0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Smart traffic sniffing for penetration testers.
WWW=		https://github.com/NytroRST/NetRipper

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/sed \
		devel/git \
		ftp/curl



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
