PORTNAME=	nuclei
DISTVERSION=	v3.6.2.r68.g2e1a81e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A fast tool for configurable targeted scanning based on templates offering massive extensibility and ease of use.
WWW=		https://github.com/projectdiscovery/nuclei

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go

RUN_DEPENDS=	??/nuclei-templates


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
