PORTNAME=	arpwner
DISTVERSION=	26.f300fdf
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	GUI-based python tool for arp poisoning and dns poisoning attacks.
WWW=		https://github.com/ntrippar/ARPwner

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-pypcap@${PY_FLAVOR} \
		??/pygtk \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
