PORTNAME=	sha1collisiondetection
DISTVERSION=	106.a06f1ad
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Library and command line tool to detect SHA-1 collision in a file
WWW=		https://github.com/cr-marcstevens/sha1collisiondetection

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
