PORTNAME=	pwdlyser
DISTVERSION=	v1.0.0.r8.gb84c635
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python-based CLI Password Analyser (Reporting Tool).
WWW=		https://github.com/ins1gn1a/pwdlyser

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
