PORTNAME=	ophcrack
DISTVERSION=	3.8.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Windows password cracker based on rainbow tables.
WWW=		http://ophcrack.sourceforge.net

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/qt5-charts


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
