PORTNAME=	python-cluster
DISTVERSION=	1.4.1.post3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Allows grouping a list of arbitrary objects into related groups (clusters).
WWW=		https://github.com/exhuma/python-cluster

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
