PORTNAME=	hercules-payload
DISTVERSION=	222.2607a3a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A special payload generator that can bypass all antivirus software.
WWW=		https://github.com/EgeBalci/HERCULES

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
