PORTNAME=	urlcrazy
DISTVERSION=	v0.8.2.r0.g78bf6e8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Generate and test domain typos and variations to detect and perform typo squatting, URL hijacking, phishing, and corporate espionage.
WWW=		http://www.morningstarsecurity.com/research/urlcrazy

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/ruby \
		sysutils/rubygem-bundler


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
