PORTNAME=	remote-method-guesser
DISTVERSION=	v5.1.0.r11.g3398ec6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Java RMI vulnerability scanner.
WWW=		https://github.com/qtc-de/remote-method-guesser

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/maven \
		devel/git

RUN_DEPENDS=	??/java-runtime \
		??/ysoserial


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
