PORTNAME=	blisqy
DISTVERSION=	20.e9995fc
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Exploit Time-based blind-SQL injection in HTTP-Headers (MySQL/MariaDB).
WWW=		https://github.com/JohnTroony/Blisqy

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
