PORTNAME=	ruby-foreman
DISTVERSION=	0.90.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Process manager for Procfile based applications.
WWW=		https://rubygems.org/gems/foreman

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/ruby-thor \
		??/ruby2.6


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
