PORTNAME=	pentbox
DISTVERSION=	1.8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A security suite that packs security and stability testing oriented tools for networks and systems.
WWW=		http://www.pentbox.net

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
