PORTNAME=	hyperion-crypter
DISTVERSION=	2.3.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A runtime encrypter for 32-bit and 64-bit portable executables.
WWW=		http://nullsecurity.net/tools/binary.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
