PORTNAME=	metoscan
DISTVERSION=	05
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool for scanning the HTTP methods supported by a webserver.
WWW=		http://www.open-labs.org/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	ftp/curl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
