PORTNAME=	richsploit
DISTVERSION=	3.6b15e0f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Exploitation toolkit for RichFaces.
WWW=		https://github.com/redtimmy/Richsploit

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/maven \
		devel/git

RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
