PORTNAME=	hachoir-parser
DISTVERSION=	1.3.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Most common file format parsers written using hachoir-core.
WWW=		http://bitbucket.org/haypo/hachoir/wiki/hachoir-parser

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/hachoir-core \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
