PORTNAME=	libmirisdr4
DISTVERSION=	v2.0.0.r0.gfd0452e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Support of Mirics MSi001 + MSi2500 SDR devices (yet another flavour of libmirisdr).
WWW=		https://github.com/f4exb/libmirisdr-4

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git

RUN_DEPENDS=	??/libusb


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
