PORTNAME=	spookflare
DISTVERSION=	24.19491b5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Loader, dropper generator with multiple features for bypassing client-side and network-side countermeasures.
WWW=		https://github.com/hlldz/SpookFlare

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-terminaltables@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
