PORTNAME=	jpegdump
DISTVERSION=	0.0.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool to analyzse JPEG images Reads binary files and parses the JPEG markers inside them.
WWW=		https://blog.didierstevens.com/my-software/#jpegdump

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
