PORTNAME=	bkcrack
DISTVERSION=	v1.8.1.r35.g1f34dd5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Crack legacy zip encryption with Biham and Kocher known plaintext attack.
WWW=		https://github.com/kimci86/bkcrack

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		??/doxygen \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
