PORTNAME=	ubitack
DISTVERSION=	0.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool, which automates some of the tasks you might need on a (wireless) penetration test or while you are on the go.
WWW=		https://code.google.com/p/ubitack/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
