PORTNAME=	sipsak
DISTVERSION=	0.9.8.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A small command line tool for developers and administrators of Session Initiation Protocol (SIP) applications.
WWW=		https://github.com/nils-ohlmeier/sipsak/releases

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/c-ares \
		??/gnutls \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
