PORTNAME=	loadlibrary
DISTVERSION=	104.c40033b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Porting Windows Dynamic Link Libraries to Linux.
WWW=		https://github.com/taviso/loadlibrary

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/cabextract \
		??/gcc \
		??/lib32-gcc-libs \
		??/lib32-glibc \
		??/readline


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
