PORTNAME=	narthex
DISTVERSION=	v1.2.r7.g8b78746
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Modular personalized dictionary generator.
WWW=		https://github.com/MichaelDim02/Narthex

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
