PORTNAME=	wdict
DISTVERSION=	v0.1.22.r0.gb7c1a0c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Create dictionaries by scraping webpages or crawling local files.
WWW=		https://github.com/pyqlsa/wdict

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/cargo \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
