PORTNAME=	openscap
DISTVERSION=	1.4.3.r25.g4c34b120e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Open Source Security Compliance Solution.
WWW=		https://www.open-scap.org/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git

RUN_DEPENDS=	??/acl \
		??/attr \
		??/bzip2 \
		??/dbus \
		??/dbus-glib \
		??/gconf \
		??/libcap \
		??/libcap-ng \
		??/libgcrypt \
		??/libldap \
		??/libutil-linux \
		??/libxml2 \
		??/openldap \
		??/pcre \
		??/pcre2 \
		??/perl \
		??/perl-xml-parser \
		??/perl-xml-xpath \
		??/procps-ng \
		??/swig \
		??/xmlsec \
		ftp/curl \
		lang/python \
		textproc/libxslt


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
