PORTNAME=	ruby-dry-cli
DISTVERSION=	1.4.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	General purpose Command Line Interface (CLI) framework for Ruby.
WWW=		https://rubygems.org/gems/dry-cli

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
