PORTNAME=	subjs
DISTVERSION=	48.3eb4dc9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fetches javascript file from a list of URLS or subdomains.
WWW=		https://github.com/lc/subjs

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
