PORTNAME=	blindelephant
DISTVERSION=	8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A web application fingerprinter. Attempts to discover the version of a (known) web application by comparing static files at known locations
WWW=		http://blindelephant.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/svn

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
