PORTNAME=	dirbuster-ng
DISTVERSION=	9.0c34920
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	C CLI implementation of the Java dirbuster tool.
WWW=		https://github.com/digination/dirbuster-ng

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git

RUN_DEPENDS=	ftp/curl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
