PORTNAME=	chromefreak
DISTVERSION=	24.12745b1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Cross-Platform Forensic Framework for Google Chrome
WWW=		http://osandamalith.github.io/ChromeFreak/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-pysqlite@${PY_FLAVOR} \
		??/py-simplejson@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
