PORTNAME=	emp3r0r
DISTVERSION=	v3.20.1.r3.g7e97eef5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Linux post-exploitation framework made by linux user.
WWW=		https://github.com/jm33-m0/emp3r0r

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go

RUN_DEPENDS=	??/tmux \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
