PORTNAME=	zykeys
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Demonstrates how default wireless settings are derived on some models of ZyXEL routers.
WWW=		http://packetstormsecurity.com/files/119156/Zykeys-Wireless-Tool.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gcc

RUN_DEPENDS=	security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
