PORTNAME=	linenum
DISTVERSION=	75.c47f9b2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Scripted Local Linux Enumeration & Privilege Escalation Checks
WWW=		https://github.com/rebootuser/LinEnum

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
