PORTNAME=	unicorn-powershell
DISTVERSION=	212.5421d46
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple tool for using a PowerShell downgrade attack and inject shellcode straight into memory.
WWW=		https://github.com/trustedsec/unicorn

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
