PORTNAME=	navgix
DISTVERSION=	3.6f25c98
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Multi-threaded golang tool that will check for nginx alias traversal vulnerabilities.
WWW=		https://github.com/hakaioffsec/navgix

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
