PORTNAME=	grabbb
DISTVERSION=	0.0.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Clean, functional, and fast banner scanner.
WWW=		https://packetstormsecurity.com/files/11372/grabbb-0.0.7.tar.gz.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
