PORTNAME=	mubeng
DISTVERSION=	272.164c0b1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An incredibly fast proxy checker & IP rotator with ease.
WWW=		https://github.com/kitabisa/mubeng

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
