PORTNAME=	drupalscan
DISTVERSION=	0.5.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Simple non-intrusive Drupal scanner.
WWW=		https://rubygems.org/gems/DrupalScan/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	lang/ruby

RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
