PORTNAME=	rbac-lookup
DISTVERSION=	v0.10.3.r0.g46385c5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A CLI that allows you to easily find Kubernetes roles and cluster roles bound to any user.
WWW=		https://github.com/FairwindsOps/rbac-lookup

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
