PORTNAME=	trixd00r
DISTVERSION=	0.0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An advanced and invisible userland backdoor based on TCP/IP for UNIX systems.
WWW=		http://nullsecurity.net/tools/backdoor.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
