PORTNAME=	vuls
DISTVERSION=	v0.35.1.r3.g0ba85f8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Vulnerability scanner for Linux/FreeBSD, agentless, written in Go.
WWW=		https://github.com/future-architect/vuls

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go

RUN_DEPENDS=	??/sqlite


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
