PORTNAME=	electric-fence
DISTVERSION=	2.2.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A malloc(3) debugger that uses virtual memory hardware to detect illegal memory accesses.
WWW=		https://packages.debian.org/sid/electric-fence

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
