PORTNAME=	ubertooth-kismet
DISTVERSION=	2020.12.R1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A kismet plugin for ubertooth.
WWW=		http://sourceforge.net/projects/ubertooth/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/kismet \
		??/ubertooth


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
