PORTNAME=	aiengine
DISTVERSION=	2.4.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A packet inspection engine with capabilities of learning without any human intervention.
WWW=		https://bitbucket.org/camp0/aiengine/downloads/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/boost \
		??/boost-libs \
		lang/python \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
