PORTNAME=	perl-io-socket-socks-wrapper
DISTVERSION=	0.17
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Add SOCKS support for any perl object / package / program.
WWW=		http://search.cpan.org/~oleg/IO-Socket-Socks-Wrapper-0.15/lib/IO/Socket/Socks/Wrapper.pm

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-io-socket-socks


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
