PORTNAME=	smbrelay
DISTVERSION=	3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	SMB / HTTP to SMB replay attack toolkit.
WWW=		http://www.tarasco.org/security/smbrelay/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	emulators/wine


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
