PORTNAME=	perl-lwp-useragent-proxyany
DISTVERSION=	1.02
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A LWP UserAgent supports both HTTP_PROXY and IE proxy
WWW=		https://metacpan.org/pod/LWP::UserAgent::ProxyAny

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl-libwww


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
