PORTNAME=	infip
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A python script that checks output from netstat against RBLs from Spamhaus.
WWW=		http://packetstormsecurity.com/files/104927/infIP-0.1-Blacklist-Checker.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-beautifulsoup3@${PY_FLAVOR} \
		??/py-httplib2@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
