PORTNAME=	fbcmd
DISTVERSION=	2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Command Line Interface (CLI) for Facebook
WWW=		http://fbcmd.dtompkins.com/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/php82


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
