PORTNAME=	katsnoop
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Utility that sniffs HTTP Basic Authentication information and prints the base64 decoded form.
WWW=		http://packetstormsecurity.com/files/52514/katsnoop.tbz2.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
