PORTNAME=	payloadmask
DISTVERSION=	17.58e0525
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Web Payload list editor to use techniques to try bypass web application firewall.
WWW=		https://github.com/CoolerVoid/payloadmask

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
