PORTNAME=	perl-number-range
DISTVERSION=	0.12
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl extension defining ranges of numbers and testing if a number is found in the range.
WWW=		http://search.cpan.org/dist/Number-Range

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
