PORTNAME=	snuck
DISTVERSION=	6.76196b6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Automatic XSS filter bypass.
WWW=		https://github.com/mauro-g/snuck

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/apache-ant \
		devel/git

RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
