PORTNAME=	netmap
DISTVERSION=	0.1.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Can be used to make a graphical representation of the surrounding network.
WWW=		http://netmap.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/graphviz


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
