PORTNAME=	cookie-cadger
DISTVERSION=	1.08
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An auditing tool for Wi-Fi or wired Ethernet connections.
WWW=		https://cookiecadger.com/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment \
		??/wireshark-cli


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
