PORTNAME=	ghost-phisher
DISTVERSION=	2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	GUI suite for phishing and penetration attacks.
WWW=		https://github.com/Obsidian-Covenant/ghost-phisher

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/aircrack-ng \
		??/py-bottle@${PY_FLAVOR} \
		??/py-pyqt6@${PY_FLAVOR} \
		??/xterm \
		lang/python \
		net/py-scapy@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
