PORTNAME=	libpng12
DISTVERSION=	1.2.59
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A collection of routines used to create PNG format graphics files.
WWW=		http://www.libpng.org/pub/png/libpng.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/zlib


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
