PORTNAME=	fakeap
DISTVERSION=	0.3.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Black Alchemys Fake AP generates thousands of counterfeit 802.11b access points. Hide in plain sight amongst Fake APs cacophony of beacon frames.
WWW=		http://www.blackalchemy.to/project/fakeap/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
