PORTNAME=	evil-ssdp
DISTVERSION=	08..beta.r7.g0d41a11
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Spoof SSDP replies to phish for NetNTLM challenge/response on a network.
WWW=		https://gitlab.com/initstring/evil-ssdp

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-netifaces@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
