PORTNAME=	goofuzz
DISTVERSION=	2.0.r1.gc32df39
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Bash script that uses advanced Google search techniques to obtain sensitive information in files or directories without making requests to the web server.
WWW=		https://github.com/m3n0sd0n4ld/GooFuzz

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/sed \
		ftp/curl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
