PORTNAME=	ghost-py
DISTVERSION=	2.0.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Webkit based webclient (relies on PyQT).
WWW=		http://jeanphix.github.com/Ghost.py/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-distribute@${PY_FLAVOR}

RUN_DEPENDS=	??/py-pyqt@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
