PORTNAME=	perl-io-async
DISTVERSION=	0.78
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Asynchronous event-driven programming.
WWW=		https://metacpan.org/release/IO-Async

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl-test-fatal \
		??/perl-test-identity \
		??/perl-test-refcount

RUN_DEPENDS=	??/perl \
		??/perl-future \
		??/perl-struct-dumb


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
