PORTNAME=	notspikefile
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Linux based file format fuzzing tool
WWW=		http://packetstormsecurity.com/files/39627/notSPIKEfile.tgz.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
