PORTNAME=	suid3num
DISTVERSION=	63.881b488
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python script which utilizes pythons built-in modules to enumerate SUID binaries.
WWW=		https://github.com/Anon-Exploiter/SUID3NUM

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
