PORTNAME=	cntlm
DISTVERSION=	4.b35d55c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An NTLM, NTLM2SR, and NTLMv2 authenticating HTTP proxy.
WWW=		https://github.com/bseb/cntlm

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
