PORTNAME=	smtp-fuzz
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Simple smtp fuzzer.
WWW=		https://no.ne/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
