PORTNAME=	java24-openjfx-bin
DISTVERSION=	24.0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Java OpenJFX ${_ver} client application platform (Gluon build).
WWW=		https://openjfx.io/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/ffmpeg \
		??/gstreamer \
		??/java-environment \
		??/libxtst \
		??/qt5-base \
		??/webkit2gtk


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
