PORTNAME=	caido-desktop
DISTVERSION=	0.53.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Intercepting proxy to replay, inject, scan and fuzz HTTP requests.
WWW=		https://caido.io/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
