PORTNAME=	ciphr
DISTVERSION=	127.5da7137
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A CLI tool for encoding, decoding, encryption, decryption, and hashing streams of data.
WWW=		https://github.com/frohoff/ciphr

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/ruby \
		sysutils/rubygem-bundler


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
