PORTNAME=	de4dotex
DISTVERSION=	3.2.4.r0.ga5fd177
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	.NET deobfuscator and unpacker.
WWW=		https://github.com/GDATAAdvancedAnalytics/de4dotEx

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/dotnet-sdk \
		??/mono \
		??/mono-msbuild \
		devel/git

RUN_DEPENDS=	??/mono


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
