PORTNAME=	hopper
DISTVERSION=	5.19.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Reverse engineering tool that lets you disassemble, decompile and debug your applications.
WWW=		https://www.hopperapp.com/download.html?

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/hicolor-icon-theme \
		??/libbsd \
		??/qt5-base \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
