PORTNAME=	prads
DISTVERSION=	1134.81334aa
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Passive Real-time Asset Detection System.
WWW=		http://gamelinux.github.io/prads/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-docutils@${PY_FLAVOR} \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
