PORTNAME=	gps-sdr-sim
DISTVERSION=	224.28ca29a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Software-Defined GPS Signal Simulator.
WWW=		https://github.com/osqzss/gps-sdr-sim

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/bladerf \
		??/gnuradio \
		??/gnuradio-osmosdr \
		??/hackrf \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
