PORTNAME=	pcileech
DISTVERSION=	4.19.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool, which uses PCIe hardware devices to read and write from the target system memory.
WWW=		https://github.com/ufrisk/pcileech/releases

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/leechcore \
		??/libusb


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
