PORTNAME=	perl-moose
DISTVERSION=	2.2015
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A postmodern object system for Perl 5.
WWW=		https://metacpan.org/pod/Moose

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl-dist-checkconflicts \
		??/perl-test-fatal \
		??/perl-test-requires \
		??/perl-test-without-module

RUN_DEPENDS=	??/perl-class-load \
		??/perl-class-load-xs \
		??/perl-data-optlist \
		??/perl-devel-globaldestruction \
		??/perl-dist-checkconflicts \
		??/perl-eval-closure \
		??/perl-list-moreutils \
		??/perl-mro-compat \
		??/perl-package-deprecationmanager \
		??/perl-package-stash \
		??/perl-package-stash-xs \
		??/perl-params-util \
		??/perl-sub-exporter \
		??/perl-sub-name \
		??/perl-task-weaken \
		??/perl-test-checkdeps \
		??/perl-try-tiny


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
