PORTNAME=	wcc
DISTVERSION=	v0.0.11.r41.gfad40be
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The Witchcraft Compiler Collection.
WWW=		https://github.com/endrazine/wcc

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/clang \
		devel/cargo \
		devel/git

RUN_DEPENDS=	??/capstone \
		??/gsl \
		??/libelf \
		??/zlib


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
