PORTNAME=	backorifice
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A remote administration system which allows a user to control a computer across a tcpip connection using a simple console or GUI application.
WWW=		http://www.cultdeadcow.com/tools/bo.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	archivers/unzip



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
