PORTNAME=	sloth-fuzzer
DISTVERSION=	40.0f0cf2e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A smart file fuzzer.
WWW=		https://github.com/mfontanini/sloth-fuzzer

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/bison \
		??/crypto++ \
		??/flex


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
