PORTNAME=	proxycheck
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This is a simple proxy tool that checks for the HTTP CONNECT method and grabs verbose output from a webserver.
WWW=		http://packetstormsecurity.com/files/61864/proxycheck.pl.txt.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-io-socket


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
