PORTNAME=	androidsniffer
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A perl script that lets you search for 3rd party passwords, dump the call log, dump contacts, dump wireless configuration, and more.
WWW=		http://packetstormsecurity.com/files/97464/Andr01d-Magic-Dumper-0.1.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-dbi \
		??/perl-term-menu


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
