PORTNAME=	neighbor-cache-fingerprinter
DISTVERSION=	83.f1e596f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An ARP based Operating System version scanner.
WWW=		https://github.com/PherricOxide/Neighbor-Cache-Fingerprinter

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/boost \
		net/libdnet \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
