PORTNAME=	intrace
DISTVERSION=	1.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Traceroute-like application piggybacking on existing TCP connections.
WWW=		http://intrace.googlecode.com

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
