PORTNAME=	python-hrt
DISTVERSION=	0.1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Translates raw HTTP requests to Python,Ruby,Php and Bash scripts.
WWW=		https://pypi.org/project/hrt/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
