PORTNAME=	perl-uri-escape
DISTVERSION=	1.76
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Percent-encode and percent-decode unsafe characters.
WWW=		https://metacpan.org/pod/URI::Escape

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
