PORTNAME=	hbad
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This tool allows you to test clients on the heartbleed bug.
WWW=		http://www.curesec.com/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/openssl-1.0


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
