PORTNAME=	adminpagefinder
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This python script looks for a large amount of possible administrative interfaces on a given site.
WWW=		http://packetstormsecurity.com/files/112855/Admin-Page-Finder-Script.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
