PORTNAME=	fuzzbunch
DISTVERSION=	34.a27780c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	NSA Exploit framework
WWW=		https://github.com/mdiazcl/fuzzbunch-debian

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/winetricks \
		emulators/wine


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
