PORTNAME=	sticky-keys-hunter
DISTVERSION=	15.c816fc9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Script to test an RDP host for sticky keys and utilman backdoor.
WWW=		https://github.com/ztgrace/sticky_keys_hunter

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/bc \
		??/imagemagick \
		??/rdesktop \
		??/xdotool \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
