PORTNAME=	mildew
DISTVERSION=	11.df49c23
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Dotmil subdomain discovery tool that scrapes domains from official DoD website directories and certificate transparency logs.
WWW=		https://github.com/daehee/mildew

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
