PORTNAME=	dirble
DISTVERSION=	1.4.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fast directory scanning and scraping tool.
WWW=		https://github.com/nccgroup/dirble

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/cargo

RUN_DEPENDS=	ftp/curl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
