PORTNAME=	wolpertinger
DISTVERSION=	3.683ad04
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A distributed portscanner.
WWW=		https://github.com/Crapworks/wolpertinger

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/linux-headers \
		??/sqlite \
		lang/python3 \
		net/libdnet \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
