PORTNAME=	jsonbee
DISTVERSION=	30.c0c87fc
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A ready to use JSONP endpoints/payloads to help bypass content security policy (CSP).
WWW=		https://github.com/zigoo0/JSONBee

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/php82


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
