PORTNAME=	skyjack
DISTVERSION=	16.24e3878
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Takes over Parrot drones, deauthenticating their true owner and taking over control, turning them into zombie drones under your own control.
WWW=		https://github.com/samyk/skyjack

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/net-tools \
		??/node-ar-drone


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
