PORTNAME=	jeb-android
DISTVERSION=	3.7.0.201909272058
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Android decompiler.
WWW=		https://www.pnfsoftware.com/jeb/android

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment \
		??/java-runtime-common


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
