PORTNAME=	pax-oracle
DISTVERSION=	v0.2.2.r1.g38ac0d8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	CLI tool for PKCS7 padding oracle attacks.
WWW=		https://github.com/liamg/pax

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
