PORTNAME=	evilclippy
DISTVERSION=	62.fa610c6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A cross-platform assistant for creating malicious MS Office documents.
WWW=		https://github.com/outflanknl/EvilClippy

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/mono


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
