PORTNAME=	nbtool
DISTVERSION=	2.bf90c76
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Some tools for NetBIOS and DNS investigation, attacks, and communication.
WWW=		http://wiki.skullsecurity.org/Nbtool

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/nasm \
		devel/git

RUN_DEPENDS=	net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
