PORTNAME=	ace
DISTVERSION=	1.11
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple yet powerful VoIP Corporate Directory enumeration tool that mimics the behavior of an IP Phone in order to download the name and extension entries that a given phone can display on its screen interface.
WWW=		https://ucsniff.sourceforge.net/ace.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libtirpc \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
