PORTNAME=	perl-xml-dom
DISTVERSION=	1.46
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Implements Level 1 of W3s DOM.
WWW=		http://search.cpan.org/dist/XML-DOM

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libxml-perl \
		??/perl \
		??/perl-libwww \
		??/perl-xml-parser \
		??/perl-xml-regexp


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
