PORTNAME=	dnsbf
DISTVERSION=	0.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Search for available domain names in an IP range.
WWW=		http://code.google.com/p/dnsbf

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/subversion

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
