PORTNAME=	skul
DISTVERSION=	27.7bd83f1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A PoC to bruteforce the Cryptsetup implementation of Linux Unified Key Setup (LUKS).
WWW=		https://github.com/cryptcoffee/skul

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
