PORTNAME=	blackarch-dwm
DISTVERSION=	6.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Dynamic window manager for X with BlackArch colors.
WWW=		https://dl.suckless.org/dwm/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/dmenu \
		??/libx11 \
		??/libxinerama \
		??/xorg-server \
		??/xorg-xsetroot


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
