PORTNAME=	snmp-fuzzer
DISTVERSION=	0.1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	SNMP fuzzer uses Protos test cases with an entirely new engine written in Perl.
WWW=		http://www.arhont.com/en/category/resources/tools-utilities/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
