PORTNAME=	dumpusers
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Dumps account names and information even though RestrictAnonymous has been set to 1.
WWW=		https://vidstromlabs.com/freetools/dumpusers/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
