PORTNAME=	ocs
DISTVERSION=	0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Compact mass scanner for Cisco routers with default telnet/enable passwords.
WWW=		http://packetstormsecurity.com/files/119462/OCS-Cisco-Scanner-0.2.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gcc



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
