PORTNAME=	userrecon-py
DISTVERSION=	15.eebd422
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Recognition usernames in 187 social networks.
WWW=		https://github.com/lucmski/userrecon-py

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-aiohttp@${PY_FLAVOR} \
		??/py-colorama@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
