PORTNAME=	pipal
DISTVERSION=	3.4.0.r9.g392f0aa
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A password analyser.
WWW=		https://github.com/digininja/pipal

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	devel/git \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
