PORTNAME=	webkiller
DISTVERSION=	36.7ad72d3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool Information Gathering Write By Python.
WWW=		https://github.com/ultrasecurity/webkiller

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-builtwith@${PY_FLAVOR} \
		??/py-colorama@${PY_FLAVOR} \
		??/py-ipapi@${PY_FLAVOR} \
		lang/python \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
