PORTNAME=	shitflood
DISTVERSION=	14.e74fc42
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Socks5 clone flooder for the Internet Relay Chat (IRC) protocol.
WWW=		https://github.com/acidvegas/shitflood

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
