PORTNAME=	sambascan
DISTVERSION=	0.5.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Allows you to search an entire network or a number of hosts for SMB shares. It will also list the contents of all public shares that it finds.
WWW=		http://sourceforge.net/projects/sambascan2/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/samba \
		security/nmap \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
