PORTNAME=	klar
DISTVERSION=	2.4.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Integration of Clair and Docker Registry.
WWW=		https://github.com/optiopay/klar

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
