PORTNAME=	ngrok
DISTVERSION=	3.33.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tunneling, reverse proxy for developing and understanding networked, HTTP services.
WWW=		https://ngrok.com/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
