PORTNAME=	petools
DISTVERSION=	1.9.762
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Portable executable (PE) manipulation toolkit.
WWW=		https://github.com/petoolse/petools

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
