PORTNAME=	sakis3g
DISTVERSION=	0.2.0e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An all-in-one script for connecting with 3G.
WWW=		http://www.sakis3g.org/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/net-tools \
		??/ppp


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
