PORTNAME=	python-httpreplay
DISTVERSION=	0.2.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Properly interpret, decrypt, and replay pcap files.
WWW=		https://pypi.org/project/HTTPReplay/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
