PORTNAME=	msf-mpc
DISTVERSION=	35.8007ef2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Msfvenom payload creator.
WWW=		https://github.com/g0tmi1k/mpc

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/metasploit


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
