PORTNAME=	perl-convert-pem
DISTVERSION=	0.08
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Read/write encrypted ASN.1 PEM files.
WWW=		http://search.cpan.org/dist/Convert-PEM

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl-module-install \
		??/perl-test-exception

RUN_DEPENDS=	??/perl \
		??/perl-class-errorhandler \
		??/perl-convert-asn1 \
		??/perl-crypt-des_ede3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
