PORTNAME=	perl-furl
DISTVERSION=	3.14
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Lightning-fast URL fetcher.
WWW=		https://metacpan.org/pod/Furl

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl-module-build \
		??/perl-module-build-tiny

RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
