PORTNAME=	rogue-mysql-server
DISTVERSION=	2.78ebbfc
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A rogue MySQL server written in Python.
WWW=		https://github.com/Gifts/Rogue-MySql-Server

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
