PORTNAME=	grokevt
DISTVERSION=	0.5.0.6.1.r0.gfb16294
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A collection of scripts built for reading Windows® NT/2K/XP/2K eventlog files.
WWW=		https://projects.sentinelchicken.org/grokevt/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	??/cpio \
		??/reglookup \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
