PORTNAME=	kscan
DISTVERSION=	v1.85.r55.gcf76af2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Asset mapping tool that can perform port scanning, TCP fingerprinting and banner capture for specified assets.
WWW=		https://github.com/lcvvvv/kscan

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
