PORTNAME=	cower
DISTVERSION=	18
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple AUR agent with a pretentious name.
WWW=		http://github.com/falconindy/cower

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl

RUN_DEPENDS=	??/pacman \
		??/yajl \
		ftp/curl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
