PORTNAME=	python-build-utils
DISTVERSION=	0.0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Some tools to help build python2 and python3 libraries.
WWW=		https://pypi.org/project/build-utils/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-colorama@${PY_FLAVOR} \
		devel/py-setuptools@${PY_FLAVOR} \
		ftp/wget



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
