PORTNAME=	libgksu
DISTVERSION=	2.0.12
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	gksu authorization library.
WWW=		http://www.nongnu.org/gksu/index.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gtk-doc \
		??/intltool

RUN_DEPENDS=	??/gconf \
		??/gtk2 \
		??/libgnome-keyring \
		??/libgtop \
		??/startup-notification


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
