PORTNAME=	qt3
DISTVERSION=	3.3.8b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A cross-platform application and UI framework.
WWW=		http://www.trolltech.com/products/qt/index.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/mariadb \
		??/mesa \
		??/postgresql \
		??/sqlite \
		??/unixodbc

RUN_DEPENDS=	??/glu \
		??/libmng \
		??/libpng \
		??/libxcursor \
		??/libxft \
		??/libxinerama \
		??/libxmu \
		??/libxrandr


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
