PORTNAME=	box-js
DISTVERSION=	703.a3bb0c8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool for studying JavaScript malware.
WWW=		https://github.com/CapacitorSet/box-js

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		www/npm

RUN_DEPENDS=	??/gnuplot \
		www/node


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
