PORTNAME=	python-dict2xml
DISTVERSION=	1.7.8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Super Simple utility to convert a python dictionary into an xml string.
WWW=		https://pypi.org/project/dict2xml/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
