PORTNAME=	bashscan
DISTVERSION=	94.80c066c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A port scanner built to utilize /dev/tcp for network and service discovery.
WWW=		https://github.com/astryzia/BashScan

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/bc \
		??/bind \
		??/net-tools \
		ftp/curl \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
