PORTNAME=	wups
DISTVERSION=	1.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An UDP port scanner for Windows.
WWW=		http://ntsecurity.nu/toolbox/wups/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
