PORTNAME=	inzider
DISTVERSION=	1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This is a tool that lists processes in your Windows system and the ports each one listen on.
WWW=		https://vidstromlabs.com/freetools/inzider/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
