PORTNAME=	tfsec
DISTVERSION=	v0.63.1.r408.gb692c20b6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Security scanner for your Terraform code.
WWW=		https://github.com/aquasecurity/tfsec

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
