PORTNAME=	videosnarf
DISTVERSION=	0.63
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A new security assessment tool for pcap analysis.
WWW=		http://ucsniff.sourceforge.net/videosnarf.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libnet \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
