PORTNAME=	ycrawler
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A web crawler that is useful for grabbing all user supplied input related to a given website and will save the output. It has proxy and log file support.
WWW=		http://packetstormsecurity.com/files/98546/yCrawler-Web-Crawling-Utility.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-io-socket \
		??/perl-libwww


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
