PORTNAME=	python2-poppler
DISTVERSION=	0.12.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python 2.x bindings for Poppler.
WWW=		https://launchpad.net/poppler-python

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/poppler-glib \
		??/pygtk


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
