PORTNAME=	haiti
DISTVERSION=	v4.0.0.r2.g6f6934b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Hash type identifier (CLI & lib).
WWW=		https://noraj.github.io/haiti/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/ruby-docopt \
		??/ruby-paint \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
