PORTNAME=	node-ar-drone
DISTVERSION=	281.11667d4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A node.js client for controlling Parrot AR Drone 2.0 quad-copters.
WWW=		https://github.com/felixge/node-ar-drone

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		www/npm

RUN_DEPENDS=	www/node


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
