PORTNAME=	cloudunflare
DISTVERSION=	14.b91a8a7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Reconnaissance Real IP address for Cloudflare Bypass.
WWW=		https://github.com/greycatz/CloudUnflare

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/bind-tools \
		??/whois \
		ftp/curl \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
