PORTNAME=	dotdotpwn
DISTVERSION=	3.0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The Transversal Directory Fuzzer.
WWW=		http://dotdotpwn.blogspot.com

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-http-lite \
		??/perl-io-socket \
		??/perl-io-socket-ssl \
		??/perl-libwww \
		??/perl-switch \
		??/perl-tftp


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
