PORTNAME=	usnjrnl2csv
DISTVERSION=	29.1ecbddc
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Parser for $UsnJrnl on NTFS.
WWW=		https://github.com/jschicht/UsnJrnl2Csv

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/wine-mono \
		??/wine_gecko \
		emulators/wine


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
