PORTNAME=	zulu
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A light weight 802.11 wireless frame generation tool to enable fast and easy debugging and probing of 802.11 networks.
WWW=		http://sourceforge.net/projects/zulu-wireless/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
