PORTNAME=	qsreplace
DISTVERSION=	5.320475b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Accept URLs on stdin, replace all query string values with a user-supplied value, only output each combination of query string parameters once per host and path.
WWW=		https://github.com/tomnomnom/qsreplace

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
