PORTNAME=	python2-pyrtlsdr
DISTVERSION=	0.3.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Python wrapper for librtlsdr (a driver for Realtek RTL2832U based SDRs).
WWW=		https://pypi.org/project/pyrtlsdr/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
