PORTNAME=	bing-lfi-rfi
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python script for searching Bing for sites that may have local and remote file inclusion vulnerabilities.
WWW=		http://packetstormsecurity.com/files/121590/Bing-LFI-RFI-Scanner.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
