PORTNAME=	timegen
DISTVERSION=	0.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This program generates a *.wav file to send an own time signal to DCF77 compatible devices.
WWW=		http://bastianborn.de/radio-clock-hack/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
