PORTNAME=	tls-fingerprinting
DISTVERSION=	257.4b6e878
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool and scripts to perform TLS Fingerprinting.
WWW=		https://github.com/LeeBrotherston/tls-fingerprinting

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3 \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
