PORTNAME=	lsrtunnel
DISTVERSION=	0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Spoofs connections using source routed packets.
WWW=		http://www.synacklabs.net/projects/lsrtunnel/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	net/libdnet \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
