PORTNAME=	perl-net-frame-layer-ipv6
DISTVERSION=	1.08
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Internet Protocol v6 layer object.
WWW=		https://metacpan.org/pod/Net::Frame::Layer::IPv6

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
