PORTNAME=	brutus
DISTVERSION=	2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	One of the fastest, most flexible remote password crackers you can get your hands on.
WWW=		http://www.hoobie.net/brutus/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
