PORTNAME=	perl-www-lw2
DISTVERSION=	0.10
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	WWW::LW2 - the module for easy and convenient use LW2.
WWW=		https://metacpan.org/pod/release/PEARL/WWW-LW2-0.10/lib/WWW/LW2.pm

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
