PORTNAME=	elasticsearch
DISTVERSION=	7.10.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Distributed RESTful search engine built on top of Lucene.
WWW=		https://www.elastic.co/products/elasticsearch/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/java-environment

RUN_DEPENDS=	??/java-runtime-headless \
		??/libxml2 \
		??/systemd


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
