PORTNAME=	perl-net-libdnet
DISTVERSION=	0.99
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Binding for Dug Songs libdnet.
WWW=		https://metacpan.org/release/Net-Libdnet

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl-extutils-makemaker

RUN_DEPENDS=	??/perl \
		??/perl-class-gomor \
		net/libdnet


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
