PORTNAME=	fuzzdiff
DISTVERSION=	1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple tool designed to help out with crash analysis during fuzz testing. It selectively un-fuzzes portions of a fuzzed file that is known to cause a crash, re-launches the targeted application, and sees if it still crashes.
WWW=		http://vsecurity.com/resources/tool/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
