PORTNAME=	simple-ducky
DISTVERSION=	20.f15079e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A payload generator.
WWW=		https://code.google.com/p/simple-ducky-payload-generator

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
