PORTNAME=	perl-data-buffer
DISTVERSION=	0.04
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Read/write buffer class.
WWW=		http://search.cpan.org/dist/Data-Buffer

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
