PORTNAME=	proxyp
DISTVERSION=	2013
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Small multithreaded Perl script written to enumerate latency, port numbers, server names, & geolocations of proxy IP addresses.
WWW=		http://sourceforge.net/projects/proxyp/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-ip-country \
		??/perl-libwww


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
