PORTNAME=	python2-wxpython3
DISTVERSION=	3.0.2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Classic wxWidgets GUI toolkit for Python
WWW=		https://www.wxpython.org

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/glu \
		??/mesa

RUN_DEPENDS=	??/wxwidgets-gtk3-3.0 \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
