PORTNAME=	ba-testpkg
DISTVERSION=	11
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	BlackArch Linux Test Package.
WWW=		https://www.blackarch.org/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
