PORTNAME=	tor-browser
DISTVERSION=	15.0.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tor Browser Bundle: anonymous browsing using Firefox and Tor.
WWW=		https://www.torproject.org/projects/torbrowser.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/alsa-lib \
		??/dbus-glib \
		??/desktop-file-utils \
		??/hicolor-icon-theme \
		??/hunspell \
		??/icu \
		??/libevent \
		??/libvpx \
		??/libxt \
		??/mime-types \
		??/nss \
		??/sqlite \
		??/startup-notification


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
