PORTNAME=	sliver
DISTVERSION=	v1.7.0.r12.gd7dce58
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Opensource C2 framework.
WWW=		https://github.com/BishopFox/sliver

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/zip \
		archivers/unzip \
		devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
