PORTNAME=	python-user-agents
DISTVERSION=	2.2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A library to identify devices (phones, tablets) and their capabilities by parsing (browser/HTTP) user agent strings.
WWW=		https://pypi.org/project/user-agents/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
