PORTNAME=	fstealer
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Automates file system mirroring through remote file disclosure vulnerabilities on Linux machines.
WWW=		http://packetstormsecurity.com/files/106450/FStealer-Filesystem-Mirroring-Tool.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-simplejson@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
