PORTNAME=	rrst
DISTVERSION=	1.0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	HTTP/2 Rapid Reset PoC tool written in Rust.
WWW=		https://github.com/X-croot/rrst

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/rustup



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
