PORTNAME=	rdesktop-brute
DISTVERSION=	1.5.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	It connects to windows terminal servers - Bruteforce patch included.
WWW=		http://www.rdesktop.org/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libao \
		??/libsamplerate \
		??/libx11 \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
