PORTNAME=	nipe
DISTVERSION=	302.9e628df
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A script to make Tor Network your default gateway.
WWW=		https://github.com/GouveaHeitor/nipe

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl \
		??/perl-config-simple \
		??/perl-json \
		??/perl-libwww \
		??/perl-switch


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
