PORTNAME=	sqlpat
DISTVERSION=	1.0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This tool should be used to audit the strength of Microsoft SQL Server passwords offline.
WWW=		http://www.cqure.net/wp/sqlpat/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
