PORTNAME=	perl-net-dhcp
DISTVERSION=	0.7.007
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Object methods to create a DHCP packet.
WWW=		http://search.cpan.org/~djzort/Net-DHCP-0.684/lib/Net/DHCP.pm

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl-module-build


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
