PORTNAME=	apkstat
DISTVERSION=	18.81cdad3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Automated Information Retrieval From APKs For Initial Analysis.
WWW=		https://github.com/hexabin/APKStat

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/android-apktool \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
