PORTNAME=	ubiquiti-probing
DISTVERSION=	5.c28f4c1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Ubiquiti device discovery tool.
WWW=		https://github.com/headlesszeke/ubiquiti-probing

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
