PORTNAME=	stomper
DISTVERSION=	63.0a4c397
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A transport neutral client implementation of the STOMP protocol.
WWW=		http://code.google.com/p/stomper/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-distribute@${PY_FLAVOR} \
		devel/git

RUN_DEPENDS=	??/py-twisted@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
