PORTNAME=	shellinabox
DISTVERSION=	v2.21.r0.g4f0ecc3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Implements a web server that can export arbitrary command line tools to a web based terminal emulator.
WWW=		https://github.com/shellinabox/shellinabox

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/autoconf \
		devel/git

RUN_DEPENDS=	??/openssl-1.0 \
		??/zlib


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
