PORTNAME=	nsdtool
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A netgear switch discovery tool. It contains some extra features like bruteoforce and setting a new password.
WWW=		http://www.curesec.com/en/publications/tools.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-configparser@${PY_FLAVOR} \
		??/python3 \
		lang/python \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
