PORTNAME=	avr-libc-manpages
DISTVERSION=	2.0.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Man pages for the standard C library for Atmel AVR 8-bit RISC microcontrollers.
WWW=		http://www.nongnu.org/avr-libc/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
