PORTNAME=	sees
DISTVERSION=	67.cd741aa
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Increase the success rate of phishing attacks by sending emails to company users as if they are coming from the very same companys domain.
WWW=		https://github.com/galkan/sees/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/postfix \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
