PORTNAME=	python-clickclick
DISTVERSION=	20.10.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Click utility functions
WWW=		https://pypi.org/project/clickclick/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/flake8 \
		devel/py-pip@${PY_FLAVOR} \
		devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	??/py-click@${PY_FLAVOR} \
		??/py-yaml@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
