PORTNAME=	rpctools
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Contains three separate tools for obtaining information from a system that is running RPC services
WWW=		https://packetstormsecurity.com/files/31879/rpctools-1.0.zip.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
