PORTNAME=	spade
DISTVERSION=	114
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A general-purpose Internet utility package, with some extra features to help in tracing the source of spam and other forms of Internet harassment.
WWW=		http://www.hoobie.net/brutus/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
