PORTNAME=	python-sphinxcontrib-httpdomain
DISTVERSION=	1.8.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Sphinx domain for documenting HTTP APIs.
WWW=		https://pypi.org/project/sphinxcontrib-httpdomain/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
