PORTNAME=	flashscanner
DISTVERSION=	11.6815b02
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Flash XSS Scanner.
WWW=		https://github.com/riusksk/FlashScanner

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl \
		??/perl-libwww \
		??/perl-uri


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
