PORTNAME=	u3-pwn
DISTVERSION=	2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool designed to automate injecting executables to Sandisk smart usb devices with default U3 software install.
WWW=		http://www.nullsecurity.net/tools/backdoor.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/cdrkit \
		??/metasploit \
		??/u3-tool \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
