PORTNAME=	mdbtools
DISTVERSION=	738.823b32f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Utilities for viewing data and exporting schema from Microsoft Access Database files.
WWW=		https://github.com/evanmiller/mdbtools

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/autoconf \
		??/bison \
		??/flex \
		??/txt2man \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
