PORTNAME=	zipdump
DISTVERSION=	0.0.21
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	ZIP dump utility.
WWW=		https://blog.didierstevens.com/my-software/#zipdump

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
