PORTNAME=	lanmap2
DISTVERSION=	127.1197999
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Passive network mapping tool.
WWW=		http://github.com/rflynn/lanmap2

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/make \
		devel/git

RUN_DEPENDS=	??/graphviz \
		??/libbsd \
		??/sqlite3 \
		lang/php82 \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
