PORTNAME=	pdfid
DISTVERSION=	0.2.10
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Scan a file to look for certain PDF keywords.
WWW=		http://blog.didierstevens.com/programs/pdf-tools/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
