PORTNAME=	lorsrf
DISTVERSION=	v2.1.r3.g5c69453
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Find the parameters that can be used to find SSRF or Out-of-band resource load.
WWW=		https://github.com/knassar702/lorsrf

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/cargo \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
