PORTNAME=	innounp
DISTVERSION=	0.50
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Inno Setup Unpacker.
WWW=		https://sourceforge.net/projects/innounp/files/innounp/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/unrar

RUN_DEPENDS=	??/wine-mono \
		??/wine_gecko \
		emulators/wine


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
