PORTNAME=	backhack
DISTVERSION=	39.561ec86
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool to perform Android app analysis by backing up and extracting apps, allowing you to analyze and modify file system contents for apps.
WWW=		https://github.com/l0gan/backHack

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-pytz@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
