PORTNAME=	uacme
DISTVERSION=	297.6572334
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Defeating Windows User Account Control.
WWW=		https://github.com/hfiref0x/UACME

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
