PORTNAME=	pentmenu
DISTVERSION=	220.0cd7b58
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A bash script for recon and DOS attacks.
WWW=		https://github.com/GinjaChris/pentmenu

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/hping \
		??/openbsd-netcat \
		??/stunnel \
		??/whois \
		security/nmap \
		security/openssl \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
