PORTNAME=	vnc-bypauth
DISTVERSION=	0.0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Multi-threaded bypass authentication scanner for VNC smaller than v4.1.1 servers.
WWW=		http://pentester.fr/resources/tools/techno/VNC/VNC_bypauth/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/lib32-gcc-libs


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
