PORTNAME=	irpas
DISTVERSION=	0.11
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Internetwork Routing Protocol Attack Suite.
WWW=		https://phenoelit-us.org/irpas

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libtirpc \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
