PORTNAME=	ruby-httparty
DISTVERSION=	0.24.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Makes http fun! Also, makes consuming restful web services dead easy.
WWW=		https://rubygems.org/gems/httparty

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/ruby-json \
		??/ruby-mime-types \
		??/ruby-multi_xml \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
