PORTNAME=	thcrut
DISTVERSION=	1.2.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Network discovery and OS Fingerprinting tool.
WWW=		https://github.com/vanhauser-thc/THC-Archive/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/pcre \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
