PORTNAME=	dsd-fme
DISTVERSION=	2024
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Digital Speech Decoder - Florida Man Edition.
WWW=		https://github.com/lwvmobile/dsd-fme

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake

RUN_DEPENDS=	??/blas \
		??/codec2 \
		??/dbus \
		??/fftw \
		??/flac \
		??/itpp \
		??/lame \
		??/lapack \
		??/libasyncns \
		??/libcap \
		??/libgpg-error \
		??/libogg \
		??/libpulse \
		??/libsndfile \
		??/libusb \
		??/libvorbis \
		??/libxau \
		??/libxcb \
		??/libxdmcp \
		??/lz4 \
		??/mbelib \
		??/mpg123 \
		??/ncurses \
		??/opus \
		??/rtl-sdr \
		??/systemd-libs \
		??/xz \
		??/zstd


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
