PORTNAME=	perl-date-parse
DISTVERSION=	2.33
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Parse date strings into time values.
WWW=		http://search.cpan.org/~gbarr/TimeDate-2.30/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
