PORTNAME=	ldapscripts
DISTVERSION=	2.0.8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Simple shell scripts to handle POSIX entries in an LDAP directory.
WWW=		https://sourceforge.net/projects/ldapscripts

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/openldap \
		??/sharutils


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
