PORTNAME=	perl-uniq
DISTVERSION=	0.01
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl extension for managing list of values.
WWW=		http://search.cpan.org/~syamal/Uniq-0.01/Uniq.pm

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
