PORTNAME=	libbfio
DISTVERSION=	325.f258de1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A library to provide basic file input/output abstraction.
WWW=		https://github.com/libyal/libbfio

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/autoconf \
		??/automake \
		??/bison \
		??/flex \
		??/gettext \
		??/libtool \
		??/pkg-config \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
