PORTNAME=	dnsa
DISTVERSION=	0.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A dns security swiss army knife.
WWW=		http://packetfactory.openwall.net/projects/dnsa/index.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libnet \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
