PORTNAME=	blackarch-config-i3
DISTVERSION=	202.01edbd9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	BlackArch Linux configuration files for the i3 window manager.
WWW=		https://github.com/BlackArch/blackarch-config-i3

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/blackarch-config-x11 \
		??/dmenu \
		??/i3-gaps \
		??/i3blocks \
		??/i3lock \
		??/i3status \
		??/rofi \
		??/rxvt-unicode \
		??/terminus-font-ttf


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
