PORTNAME=	umap
DISTVERSION=	25.3ad8121
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The USB host security assessment tool.
WWW=		https://github.com/nccgroup/umap

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-pyserial@${PY_FLAVOR} \
		??/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
