PORTNAME=	pygoocanvas
DISTVERSION=	0.14.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	GooCanvas Python bindings.
WWW=		https://wiki.gnome.org/Projects/PyGoocanvas

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gtk-doc \
		??/pkgconfig \
		devel/git

RUN_DEPENDS=	??/goocanvas1 \
		??/pygtk \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
