PORTNAME=	blackarch-config-cursor
DISTVERSION=	3.08b06e5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	BlackArch cursor theme.
WWW=		https://github.com/BlackArch/blackarch-config-cursor

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/libxcursor


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
