PORTNAME=	proctal
DISTVERSION=	477.f72cefe
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Provides a command line interface and a C library to manipulate the address space of a running program on Linux.
WWW=		https://github.com/daniel-araujo/proctal

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/yuck \
		devel/git \
		lang/php82

RUN_DEPENDS=	??/capstone \
		??/keystone


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
