PORTNAME=	xrdp
DISTVERSION=	0.10.4.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An open source remote desktop protocol (RDP) server.
WWW=		https://github.com/neutrinolabs/xrdp

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmocka \
		??/nasm

RUN_DEPENDS=	??/ffmpeg \
		??/fuse3 \
		??/imlib2 \
		??/libfdk-aac \
		??/libxrandr \
		??/x264


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
