PORTNAME=	rainbowcrack
DISTVERSION=	1.8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Password cracker based on the faster time-memory trade-off. With MySQL and Cisco PIX Algorithm patches.
WWW=		http://project-rainbowcrack.com/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
