PORTNAME=	redsocks
DISTVERSION=	211.19b822e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Transparent redirector of any TCP connection to proxy.
WWW=		https://github.com/darkk/redsocks

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/libevent


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
