PORTNAME=	python-libbde-python
DISTVERSION=	20240502
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Library and tools to access the BitLocker Drive Encryption (BDE) encrypted volumes.
WWW=		https://pypi.org/project/libbde-python/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
