PORTNAME=	ipv6toolkit
DISTVERSION=	861.9ee80b6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	SI6 Networks IPv6 Toolkit.
WWW=		http://www.si6networks.com/tools/ipv6toolkit/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
