PORTNAME=	ruby-docopt
DISTVERSION=	0.6.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Command line option parser, that will make you smile
WWW=		https://rubygems.org/gems/docopt

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
