PORTNAME=	python-atom
DISTVERSION=	0.12.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Memory efficient Python objects.
WWW=		https://github.com/nucleic/atom

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-cppy@${PY_FLAVOR} \
		devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
