PORTNAME=	ssldump
DISTVERSION=	1.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An SSLv3/TLS network protocol analyzer.
WWW=		http://www.rtfm.com/ssldump/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/json-c \
		??/libnet \
		net/libpcap \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
