PORTNAME=	perl-class-errorhandler
DISTVERSION=	0.04
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Base class for error handling.
WWW=		http://search.cpan.org/dist/Class-ErrorHandler

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
