PORTNAME=	rapidscan
DISTVERSION=	221.296a20b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The Multi-Tool Web Vulnerability Scanner.
WWW=		https://github.com/skavngr/rapidscan

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/bind-tools \
		??/davtest \
		??/dirb \
		??/dmitry \
		??/dnsenum \
		??/dnsmap \
		??/dnsrecon \
		??/dnswalk \
		??/fierce \
		??/golismero \
		??/lbd \
		??/nikto \
		??/sslyze \
		??/theharvester \
		??/uniscan \
		??/wafw00f \
		??/wapiti \
		??/whatweb \
		??/whois \
		??/xsser \
		ftp/wget \
		lang/python \
		security/nmap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
