PORTNAME=	perl-time-duration-parse
DISTVERSION=	0.16
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Parse string that represents time duration.
WWW=		http://search.cpan.org/dist/Time-Duration-Parse

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl \
		??/perl-time-duration

RUN_DEPENDS=	??/perl-exporter-lite


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
