PORTNAME=	horusec
DISTVERSION=	v2.9.0.beta.2.r1.g873d4104
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Static code analysis to identify security flaws for many languages.
WWW=		https://github.com/ZupIT/horusec

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
