PORTNAME=	proxenet
DISTVERSION=	712.67fc6b5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	THE REAL hacker friendly proxy for web application pentests.
WWW=		https://github.com/hugsy/proxenet

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git

RUN_DEPENDS=	??/lua \
		??/mbedtls \
		??/python3 \
		lang/python3 \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
