PORTNAME=	vlany
DISTVERSION=	255.9ef014a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Linux LD_PRELOAD rootkit (x86 and x86_64 architectures).
WWW=		https://github.com/mempodippy/vlany

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
