PORTNAME=	pin
DISTVERSION=	3.28.r98749
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A dynamic binary instrumentation tool.
WWW=		https://software.intel.com/en-us/articles/pin-a-binary-instrumentation-tool-downloads

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gcc \
		??/lib32-gcc-libs \
		??/make

RUN_DEPENDS=	??/gcc \
		??/lib32-gcc-libs


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
