PORTNAME=	ikeprobe
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Determine vulnerabilities in the PSK implementation of the VPN server.
WWW=		http://www.ernw.de/download/ikeprobe.zip

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
