PORTNAME=	nomorexor
DISTVERSION=	2.84489f9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool to help guess a files 256 byte XOR key by using frequency analysis.
WWW=		https://github.com/hiddenillusion/NoMoreXOR

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-yara@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
