PORTNAME=	python2-pyspf
DISTVERSION=	2.0.14
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	SPF (Sender Policy Framework) implemented in Python.
WWW=		https://pypi.org/project/pyspf/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
