PORTNAME=	pyqt3
DISTVERSION=	3.18.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A set of Python bindings for the Qt3 toolkit.
WWW=		http://www.riverbankcomputing.com/software/pyqt/intro

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-sip@${PY_FLAVOR} \
		??/qscintilla-qt3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
