PORTNAME=	spike-proxy
DISTVERSION=	148
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Proxy for detecting vulnerabilities in web applications.
WWW=		http://www.immunitysec.com/resources-freesoftware.shtml

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-pyopenssl@${PY_FLAVOR} \
		lang/python3 \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
