PORTNAME=	blackarch-keyring
DISTVERSION=	20251011
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	BlackArch Linux PGP keyring.
WWW=		https://github.com/BlackArch/blackarch-keyring

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
