PORTNAME=	tls-prober
DISTVERSION=	286.72b1029
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool to fingerprint SSL/TLS servers.
WWW=		https://github.com/WestpointLtd/tls_prober

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
