PORTNAME=	jd-gui
DISTVERSION=	1.6.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A standalone graphical utility that displays Java source codes of .class files.
WWW=		https://github.com/java-decompiler/jd-gui

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment \
		??/libxtst


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
