PORTNAME=	ipmipwn
DISTVERSION=	6.74a08a8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	IPMI cipher 0 attack tool.
WWW=		https://github.com/AnarchyAngel/IPMIPWN

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/ipmitool \
		lang/python3 \
		security/nmap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
