PORTNAME=	shortfuzzy
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A web fuzzing script written in perl.
WWW=		http://packetstormsecurity.com/files/104872/Short-Fuzzy-Rat-Scanner.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-http-message \
		??/perl-libwww


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
