PORTNAME=	winpwn
DISTVERSION=	411.cba1769
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Automation for internal Windows Penetrationtest / AD-Security.
WWW=		https://github.com/S3cur3Th1sSh1t/WinPwn

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
