PORTNAME=	disitool
DISTVERSION=	0.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool to work with Windows executables digital signatures.
WWW=		https://blog.didierstevens.com/my-software/#disitool

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-pefile@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
