PORTNAME=	flamerobin
DISTVERSION=	2687.7d85a473
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool to handle Firebird database management.
WWW=		http://www.flamerobin.org/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/boost \
		??/boost-libs \
		??/libfbclient \
		??/wxgtk3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
