PORTNAME=	wsfuzzer
DISTVERSION=	1.9.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Python tool written to automate SOAP pentesting of web services.
WWW=		https://www.owasp.org/index.php/Category:OWASP_WSFuzzer_Project

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment \
		??/py-pyxml@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
