PORTNAME=	thumbcacheviewer
DISTVERSION=	1.0.3.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Extract Windows thumbcache database files.
WWW=		https://github.com/thumbcacheviewer/thumbcacheviewer

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/wine-mono \
		??/wine_gecko \
		emulators/wine


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
