PORTNAME=	perl-digest-md2
DISTVERSION=	2.04
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl interface to the MD2 Algorithm.
WWW=		https://metacpan.org/release/Digest-MD2

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gmp \
		??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
