PORTNAME=	shareenum
DISTVERSION=	48.db728dd
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool to enumerate shares from Windows hosts.
WWW=		https://github.com/CroweCybersecurity/shareenum

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/samba \
		??/tdb


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
