PORTNAME=	batman-alfred
DISTVERSION=	2025.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Almighty Lightweight Fact Remote Exchange Daemon.
WWW=		http://www.open-mesh.org/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/dbus \
		??/gpsd \
		??/libnl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
