PORTNAME=	gau
DISTVERSION=	169.bfc58a0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fetch known URLs from AlienVaults Open Threat Exchange, the Wayback Machine, and Common Crawl.
WWW=		https://github.com/lc/gau/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
