PORTNAME=	tls-attacker
DISTVERSION=	8620.15d809a7b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Java-based framework for analyzing TLS libraries.
WWW=		https://github.com/RUB-NDS/TLS-Attacker

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/maven \
		devel/git

RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
