PORTNAME=	yasuo
DISTVERSION=	121.994dcb1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A ruby script that scans for vulnerable & exploitable 3rd-party web applications on a network.
WWW=		https://github.com/0xsauby/yasuo

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/ruby-pkg-config \
		lang/ruby \
		sysutils/rubygem-bundler \
		textproc/libxslt


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
