PORTNAME=	mp3nema
DISTVERSION=	0.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool aimed at analyzing and capturing data that is hidden between frames in an MP3 file or stream, otherwise noted as out of band data.
WWW=		http://packetstormsecurity.com/files/76432/MP3nema-Forensic-Analysis-Tool.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
