PORTNAME=	fuzztalk
DISTVERSION=	1.0.0.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An XML driven fuzz testing framework that emphasizes easy extensibility and reusability.
WWW=		https://code.google.com/p/fuzztalk

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
