PORTNAME=	pocketsphinx
DISTVERSION=	5prealpha
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Lightweight speech recognition engine, specifically tuned for handheld and mobile devices, though it works equally well on the desktop.
WWW=		http://cmusphinx.sourceforge.net

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/swig \
		lang/python \
		lang/python3

RUN_DEPENDS=	??/gst-plugins-base-libs \
		??/sphinxbase


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
