PORTNAME=	dff-scanner
DISTVERSION=	1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool for finding path of predictable resource locations.
WWW=		https://www.security-net.biz/dff-default-files-and-folders-scanner-p77.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/php82


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
