PORTNAME=	arping-th
DISTVERSION=	2.25
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	ARP Ping from Thomas Habets (aka Debian arping).
WWW=		https://github.com/ThomasHabets/arping

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libcap \
		??/libnet \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
