PORTNAME=	dr0p1t-framework
DISTVERSION=	44.db9bc2d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A framework that creates a dropper that bypass most AVs, some sandboxes and have some tricks.
WWW=		https://github.com/D4Vinci/Dr0p1t-Framework

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/pyinstaller \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
