PORTNAME=	wpsweep
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple ping sweeper, that is, it pings a range of IP addresses and lists the ones that reply.
WWW=		https://vidstromlabs.com/freetools/wpsweep/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
