PORTNAME=	voiper
DISTVERSION=	0.07
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A VoIP security testing toolkit incorporating several VoIP fuzzers and auxiliary tools to assist the auditor.
WWW=		http://voiper.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/wxpython \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
