PORTNAME=	dhcpoptinj
DISTVERSION=	123.58a12c6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	DHCP option injector.
WWW=		https://github.com/misje/dhcpoptinj

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git

RUN_DEPENDS=	??/libnetfilter_queue


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
