PORTNAME=	kismet2earth
DISTVERSION=	2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A set of utilities that convert from Kismet logs to Google Earth .kml format.
WWW=		https://code.google.com/archive/p/kismet2earth

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/sqlite \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
