PORTNAME=	fuzzball2
DISTVERSION=	0.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A fuzzer for TCP and IP protocol options. It sends a bunch of more or less bogus packets to the target.
WWW=		http://nologin.org/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
