PORTNAME=	proxyscan
DISTVERSION=	0.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A security penetration testing tool to scan for hosts and ports through a Web proxy server.
WWW=		http://packetstormsecurity.com/files/69778/proxyScan-0.3.tgz.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-libwww \
		??/perl-lwp-useragent-proxyany


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
