PORTNAME=	yate-bts
DISTVERSION=	6.1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An open source GSM Base Station software.
WWW=		https://yatebts.com/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/yate


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
