PORTNAME=	perl-devel-overloadinfo
DISTVERSION=	0.007
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Introspect overloaded operators.
WWW=		https://metacpan.org/release/Devel-OverloadInfo

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-mro-compat \
		??/perl-package-stash \
		??/perl-sub-identify


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
