PORTNAME=	indxparse
DISTVERSION=	331.038e8ec
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Tool suite for inspecting NTFS artifacts.
WWW=		http://www.williballenthin.com/forensics/mft/indxparse/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-progressbar@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
