PORTNAME=	perl-future
DISTVERSION=	0.47
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl module to deal with operation awaiting completion.
WWW=		https://metacpan.org/release/Future

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl-module-build

RUN_DEPENDS=	??/perl \
		??/perl-test-fatal


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
