PORTNAME=	rasenum
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A small program which lists the information for all of the entries in any phonebook file (.pbk).
WWW=		http://www.cultdeadcow.com/tools/rasenum.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
