PORTNAME=	java24-openjdk
DISTVERSION=	$.fullver.u$.buildver
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Java OpenJDK $_fullver Oracle Build.
WWW=		https://jdk.java.net/$_majorver

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/ca-certificates-utils \
		??/java-environment-common \
		??/java-runtime-common \
		??/nss


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
