PORTNAME=	pixload
DISTVERSION=	87.a8f58a7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Image Payload Creating/Injecting tools.
WWW=		https://github.com/chinarulezzz/pixload

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl \
		??/perl-gd \
		??/perl-image-exiftool \
		??/perl-string-crc32


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
