PORTNAME=	jexboss
DISTVERSION=	86.338b531
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Jboss verify and Exploitation Tool.
WWW=		https://github.com/joaomatosf/jexboss

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-ipaddress@${PY_FLAVOR} \
		??/py-urllib3@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
