PORTNAME=	perl-net-frame
DISTVERSION=	1.21
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The base framework for frame crafting.
WWW=		https://metacpan.org/release/Net-Frame

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl-bit-vector \
		??/perl-class-gomor \
		??/perl-net-ipv6addr \
		??/perl-socket6


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
