PORTNAME=	venom
DISTVERSION=	135.2b84e68
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Multi-hop Proxy for Penetration Testers.
WWW=		https://github.com/Dliv3/Venom

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
