PORTNAME=	delldrac
DISTVERSION=	0.1a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	DellDRAC and Dell Chassis Discovery and Brute Forcer.
WWW=		https://www.trustedsec.com/september-2012/owning-dell-drac-awesome-hack/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
