PORTNAME=	panoptic
DISTVERSION=	207.fbd10fd
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool that automates the process of search and retrieval of content for common log and config files through LFI vulnerability.
WWW=		https://github.com/lightos/Panoptic

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
