PORTNAME=	scalpel
DISTVERSION=	1.1687261
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A frugal, high performance file carver.
WWW=		http://www.digitalforensicssolutions.com/Scalpel/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/tre


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
