PORTNAME=	geoedge
DISTVERSION=	0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This little tools is designed to get geolocalization information of a host, it get the information from two sources (maxmind and geoiptool).
WWW=		

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
