PORTNAME=	lazydroid
DISTVERSION=	25.0f559ec
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool written as a bash script to facilitate some aspects of an Android Assessment
WWW=		https://github.com/nccgroup/LazyDroid

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	ftp/wget


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
