PORTNAME=	silenteye
DISTVERSION=	21.a53a7ff
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A cross-platform application design for an easy use of steganography.
WWW=		https://github.com/achorein/silenteye/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git

RUN_DEPENDS=	??/qca \
		??/qt4


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
