PORTNAME=	evilgrade
DISTVERSION=	2.0.9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Modular framework that takes advantage of poor upgrade implementations by injecting fake updates.
WWW=		https://github.com/infobyte/evilgrade

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-data-dump \
		??/perl-digest-sha1 \
		??/perl-io-socket-ssl \
		??/perl-rpc-xml


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
