PORTNAME=	perl-test-sharedfork
DISTVERSION=	0.35
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Utility module for Test::Builder
WWW=		https://metacpan.org/release/Test-SharedFork

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-test-requires


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
