PORTNAME=	windows-privesc-check
DISTVERSION=	181.9f304fd
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Standalone Executable to Check for Simple Privilege Escalation Vectors on Windows Systems.
WWW=		https://github.com/pentestmonkey/windows-privesc-check

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
