PORTNAME=	python2-iocextract
DISTVERSION=	1.16.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Defanged Indicator of Compromise (IOC) Extractor.
WWW=		https://pypi.org/project/iocextract/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
