PORTNAME=	ps1encode
DISTVERSION=	41.68d7778
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool to generate and encode a PowerShell based Metasploit payloads.
WWW=		https://github.com/CroweCybersecurity/ps1encode

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/metasploit \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
