PORTNAME=	python2-instagramapi
DISTVERSION=	1.0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Unofficial instagram API, give you access to ALL instagram features.
WWW=		https://pypi.org/project/InstagramAPI/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
