PORTNAME=	grabitall
DISTVERSION=	1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Performs traffic redirection by sending spoofed ARP replies.
WWW=		http://ntsecurity.nu/toolbox/grabitall/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
