PORTNAME=	latd
DISTVERSION=	1.31
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A LAT terminal daemon for Linux and BSD.
WWW=		http://sourceforge.net/projects/linux-decnet/files/latd/1.31/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
