PORTNAME=	omi
DISTVERSION=	1.6.2.0.r621.gac91a8f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Open Management Infrastructure.
WWW=		https://github.com/Microsoft/omi

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/bind-tools \
		??/inetutils \
		??/krb5 \
		??/lsb-release \
		??/pam \
		??/pam-krb5 \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
