PORTNAME=	dmg2img
DISTVERSION=	1.6.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A CLI tool to uncompress Apples compressed DMG files to the HFS+ IMG format.
WWW=		http://vu1tur.eu.org/tools/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/bzip2 \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
