PORTNAME=	libowfat
DISTVERSION=	0.32
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	GPL reimplementation of libdjb.
WWW=		http://www.fefe.de/libowfat/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/dietlibc


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
