PORTNAME=	pwcrack
DISTVERSION=	368.b6fba8a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Password hash automatic cracking framework.
WWW=		https://github.com/L-codes/pwcrack-framework

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		sysutils/rubygem-bundler

RUN_DEPENDS=	lang/ruby \
		sysutils/rubygem-bundler


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
