PORTNAME=	ncp
DISTVERSION=	1.2.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A fast file copy tool for LANs.
WWW=		http://www.fefe.de/ncp/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/dietlibc \
		??/libowfat



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
