PORTNAME=	python2-hyperlink
DISTVERSION=	21.0.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A featureful, immutable, and correct URL for Python.
WWW=		https://pypi.org/project/hyperlink/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	??/py-idna@${PY_FLAVOR} \
		??/py-typing@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
