PORTNAME=	morxbook
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A password cracking tool written in perl to perform a dictionary-based attack on a specific Facebook user through HTTPS.
WWW=		http://www.morxploit.com/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-net-ssleay


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
