PORTNAME=	ntp-fingerprint
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An active fingerprinting utility specifically designed to identify the OS the NTP server is running on.
WWW=		http://www.hackingciscoexposed.com/?link=tools

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
