PORTNAME=	dontgo403
DISTVERSION=	v1.1.8.r3.gdf9fdda
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool to bypass 40X response codes..
WWW=		https://github.com/devploit/dontgo403

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
