PORTNAME=	dorkscout
DISTVERSION=	1.0.r13.gdd87daf
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Golang tool to automate google dork scan against the entire internet or specific targets.
WWW=		https://github.com/R4yGM/dorkscout

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
