PORTNAME=	iosforensic
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	iOS forensic tool.
WWW=		https://github.com/Flo354/iOSForensic

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libplist \
		??/openssh \
		??/py-magic@${PY_FLAVOR} \
		??/sqlite3 \
		??/sshpass \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
