PORTNAME=	perl-cpan-meta
DISTVERSION=	2.150010
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The distribution metadata for a CPAN dist.
WWW=		http://search.cpan.org/dist/CPAN-Meta

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-cpan-meta-requirements \
		??/perl-parse-cpan-meta


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
