PORTNAME=	sipshock
DISTVERSION=	7.6ab5591
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A scanner for SIP proxies vulnerable to Shellshock.
WWW=		https://github.com/zaf/sipshock

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
