PORTNAME=	lbd
DISTVERSION=	20130719
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Load Balancing detector,
WWW=		http://ge.mine.nu/code/lbd

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/dnsutils \
		??/openbsd-netcat \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
