PORTNAME=	local-php-security-checker
DISTVERSION=	v2.1.3.r1.g1d1fdac
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A command line tool that checks your PHP application packages with known security vulnerabilities.
WWW=		https://github.com/fabpot/local-php-security-checker

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
