PORTNAME=	perl-net-cidr
DISTVERSION=	0.21
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Manipulate IPv4/IPv6 netblocks in CIDR notation.
WWW=		http://search.cpan.org/dist/Net-CIDR

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
