PORTNAME=	netscout
DISTVERSION=	37.2f409df
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	OSINT tool that finds domains, subdomains, directories, endpoints and files.
WWW=		https://github.com/caio-ishikawa/netscout

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
