PORTNAME=	kolkata
DISTVERSION=	3.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A web application fingerprinting engine written in Perl that combines cryptography with IDS evasion.
WWW=		https://www.blackhatlibrary.net/Kolkata

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-libwhisker2 \
		??/perl-yaml \
		??/perl-yaml-libyaml


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
