PORTNAME=	tbear
DISTVERSION=	1.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Transient Bluetooth Environment Auditor includes an ncurses-based Bluetooth scanner (a bit similar to kismet), a Bluetooth DoS tool, and a Bluetooth hidden device locator.
WWW=		http://freshmeat.net/projects/t-bear

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/bluez \
		??/bluez-libs \
		??/ncurses \
		??/ncurses5-compat-libs


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
