PORTNAME=	python-instagram-private-api
DISTVERSION=	1.6.0.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Python wrapper for the Instagram private API with no 3rd party dependencies.
WWW=		https://github.com/ping/instagram_private_api

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
