PORTNAME=	nfsshell
DISTVERSION=	19980519
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Userland NFS command tool.
WWW=		http://www.paramecium.org/~leendert/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gcc \
		??/make

RUN_DEPENDS=	??/libtirpc \
		??/libtirpc-compat \
		??/readline


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
