PORTNAME=	hashrat
DISTVERSION=	1.15
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Hashing tool supporting MD5, SHA1, SHA256, SHA512, Whirlpool, JH and their HMAC.
WWW=		https://github.com/ColumPaget/Hashrat

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
