PORTNAME=	allthevhosts
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A vhost discovery tool that scrapes various web applications.
WWW=		http://labs.portcullis.co.uk/tools/finding-all-the-vhosts/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-beautifulsoup4@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
