PORTNAME=	perl-net-pcap
DISTVERSION=	0.21
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl/CPAN Module Net::Pcap.
WWW=		https://metacpan.org/release/Net-Pcap

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
