PORTNAME=	dex2jar
DISTVERSION=	2.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool for converting Androids .dex format to Javas .class format.
WWW=		https://github.com/pxb1988/dex2jar

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
