PORTNAME=	ext4magic
DISTVERSION=	0.3.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	File carver used when recovering from disasters or in digital forensics activities.
WWW=		https://sourceforge.net/projects/ext4magic/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/bzip2 \
		??/e2fsprogs \
		??/file \
		??/util-linux


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
