PORTNAME=	whoxyrm
DISTVERSION=	1.0.0.r5.g77318a7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A reverse whois tool based on Whoxy API.
WWW=		https://github.com/MilindPurswani/whoxyrm

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
