PORTNAME=	shed
DISTVERSION=	2.0.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	.NET runtime inspector.
WWW=		https://github.com/enkomio/shed/releases

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/lib32-gnutls \
		??/wine-mono


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
