PORTNAME=	ruby-rubyntlm
DISTVERSION=	0.6.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Ruby/NTLM library.
WWW=		https://github.com/winrb/rubyntlm

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
