PORTNAME=	airgeddon
DISTVERSION=	v11.61.r0.gd7e2423
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Multi-use bash script for Linux systems to audit wireless networks.
WWW=		https://github.com/v1s1t0r1sh3r3/airgeddon

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/coreutils \
		devel/git

RUN_DEPENDS=	??/aircrack-ng \
		??/coreutils \
		??/gawk \
		??/iproute2 \
		??/iw \
		??/pciutils \
		??/procps-ng \
		??/sed \
		??/tmux \
		??/xterm \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
