PORTNAME=	phantomjs
DISTVERSION=	2.1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Headless WebKit with JavaScript API.
WWW=		https://phantomjs.org/download.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/fontconfig


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
