PORTNAME=	gwtenum
DISTVERSION=	7.f27a5aa
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Enumeration of GWT-RCP method calls.
WWW=		http://www.gdssecurity.com/l/t/d.php?k=GwtEnum

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
