PORTNAME=	bluez-hciconfig
DISTVERSION=	5.65
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Deprecated hciconfig tool from bluez.
WWW=		http://www.bluez.org/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/bluez \
		??/bluez-libs \
		??/bluez-tools \
		??/bluez-utils


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
