PORTNAME=	qt5-websockets
DISTVERSION=	5.15.18+kde+r2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Provides WebSocket communication compliant with RFC 6455
WWW=		https://www.qt.io

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/qt5-declarative \
		devel/git

RUN_DEPENDS=	??/qt5-base


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
