PORTNAME=	ligolo-ng
DISTVERSION=	v0.8.2.r7.g1f3c198
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An advanced, yet simple, tunneling tool that uses a TUN interface.
WWW=		https://github.com/nicocha30/ligolo-ng/releases

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
