PORTNAME=	osert
DISTVERSION=	97.8c515be
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Markdown Templates for Offensive Security exam reports.
WWW=		https://github.com/noraj/OSCP-Exam-Report-Template-Markdown

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	archivers/unzip \
		devel/git

RUN_DEPENDS=	??/haskell-pandoc \
		??/p7zip \
		??/texlive-core \
		??/texlive-fontsextra \
		??/texlive-fontsrecommended \
		??/texlive-latexextra \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
