PORTNAME=	missionplanner
DISTVERSION=	1.3.83
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A GroundControl Station for Ardupilot.
WWW=		https://firmware.ardupilot.org/Tools/MissionPlanner/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	archivers/unzip

RUN_DEPENDS=	??/mono


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
