PORTNAME=	jwt-hack
DISTVERSION=	v2.4.0.r107.gbef6db0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool for hacking / security testing to JWT.
WWW=		https://github.com/hahwul/jwt-hack

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/cargo \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
