PORTNAME=	depdep
DISTVERSION=	2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A merciless sentinel which will seek sensitive files containing critical info leaking through your network.
WWW=		https://github.com/galkan/depdep

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/apache-tika \
		??/cifs-utils \
		??/java-environment \
		??/smbclient \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
