PORTNAME=	duplicut
DISTVERSION=	2.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Remove duplicates from massive wordlist, without sorting it (for dictionnary-based password cracking).
WWW=		https://github.com/nil0x42/duplicut

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/make



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
