PORTNAME=	wordlistctl
DISTVERSION=	0.9.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fetch, install and search wordlist archives from websites.
WWW=		https://github.com/BlackArch/wordlistctl

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-termcolor@${PY_FLAVOR} \
		lang/python \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
