PORTNAME=	fraud-bridge
DISTVERSION=	rel.0.32s.r3.g88a5baa
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	ICMP and DNS tunneling via IPv4 and IPv6.
WWW=		https://github.com/stealth/fraud-bridge

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/libgcrypt


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
