PORTNAME=	ipobfuscator
DISTVERSION=	27.f005262
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple tool to convert the IP to a DWORD IP.
WWW=		https://github.com/OsandaMalith/IPObfuscator

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
