PORTNAME=	sqlninja
DISTVERSION=	0.2.999
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool targeted to exploit SQL Injection vulnerabilities on a web application that uses Microsoft SQL Server as its back-end.
WWW=		http://sqlninja.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-dbd-sqlite \
		??/perl-dbi \
		??/perl-io-socket-ssl \
		??/perl-net-dns \
		??/perl-net-pcap \
		??/perl-net-rawip \
		??/perl-netpacket


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
