PORTNAME=	regreport
DISTVERSION=	1.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Windows registry forensic analysis tool.
WWW=		https://www.gaijin.at/dlregreport.php

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/p7zip \
		ftp/curl



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
