PORTNAME=	httprecon
DISTVERSION=	7.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool for web server fingerprinting, also known as http fingerprinting.
WWW=		http://www.computec.ch/projekte/httprecon/?s=download

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
