PORTNAME=	hurl-encoder
DISTVERSION=	20.afca9c5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Hexadecimal & URL (en/de)coder.
WWW=		https://github.com/fnord0/hURL

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl \
		??/perl-cgi \
		??/perl-digest-sha1 \
		??/perl-mime-types \
		??/perl-uri


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
