PORTNAME=	bluelog
DISTVERSION=	1.1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Bluetooth scanner and sniffer written to do a single task, log devices that are in discoverable mode.
WWW=		http://www.digifail.com/software/bluelog.shtml

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	ftp/wget

RUN_DEPENDS=	??/bluez \
		??/bluez-libs


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
