PORTNAME=	ntfs-file-extractor
DISTVERSION=	6.f2b23d72
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Extract files off NTFS.
WWW=		https://github.com/jschicht/NtfsFileExtractor

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/wine-mono \
		??/wine_gecko \
		emulators/wine


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
