PORTNAME=	python-bitstruct
DISTVERSION=	8.21.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This module performs conversions between Python values and C bit field structs represented as Python byte strings.
WWW=		https://pypi.org/project/bitstruct/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
