PORTNAME=	python-pyhunter
DISTVERSION=	1.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An (unofficial) Python wrapper for the Hunter.io API.
WWW=		https://pypi.org/project/pyhunter/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
