PORTNAME=	sysinternals-suite
DISTVERSION=	6.9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Sysinternals tools suite.
WWW=		http://sysinternals.com/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
