PORTNAME=	hashcheck
DISTVERSION=	2.72b0c6e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Search for leaked passwords while maintaining a high level of privacy using the k-anonymity method.
WWW=		https://github.com/Telefonica/HashCheck

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
