PORTNAME=	python-libewf-python
DISTVERSION=	20240506
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A library to access the Expert Witness Compression Format (EWF).
WWW=		https://pypi.org/project/libewf-python/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
