PORTNAME=	ratproxy
DISTVERSION=	1.58
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A passive web application security assessment tool.
WWW=		http://code.google.com/p/ratproxy/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
