PORTNAME=	leroy-jenkins
DISTVERSION=	3.bdc3965
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A python tool that will allow remote execution of commands on a Jenkins server and its nodes.
WWW=		https://github.com/captainhooligan/Leroy-Jenkins

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-pycurl@${PY_FLAVOR} \
		??/pygtk \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
