PORTNAME=	udsim
DISTVERSION=	33.b379464
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A graphical simulator that can emulate different modules in a vehicle and respond to UDS request.
WWW=		https://github.com/zombieCraig/UDSim/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/sdl2 \
		??/sdl2_image \
		??/sdl2_ttf


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
