PORTNAME=	blind-sql-bitshifting
DISTVERSION=	1.c1da934
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A blind SQL injection module that uses bitshfting to calculate characters.
WWW=		https://github.com/libeclipse/blind-sql-bitshifting

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3 \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
