PORTNAME=	starttls-mitm
DISTVERSION=	7.b257756
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A mitm proxy that will transparently proxy and dump both plaintext and TLS traffic.
WWW=		https://github.com/ipopov/starttls-mitm

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
