PORTNAME=	arpspoof-smikims
DISTVERSION=	31.ef5f0b1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Performs an ARP spoofing attack using the Linux kernels raw sockets.
WWW=		https://github.com/smikims/arpspoof

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
