PORTNAME=	zgrab2
DISTVERSION=	v1.0.0.r10.g062ec5e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fast Application Layer Scanner.
WWW=		https://github.com/zmap/zgrab2

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
