PORTNAME=	libjpeg6-turbo
DISTVERSION=	1.5.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	libjpeg derivative with accelerated baseline JPEG compression and decompression.
WWW=		https://libjpeg-turbo.org/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/nasm



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
