PORTNAME=	hyperfox
DISTVERSION=	121.1a8c26f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A security tool for proxying and recording HTTP and HTTPs traffic.
WWW=		https://github.com/xiam/hyperfox

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go

RUN_DEPENDS=	??/sqlite


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
