PORTNAME=	radiography
DISTVERSION=	2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A forensic tool which grabs as much information as possible from a Windows system.
WWW=		http://www.security-projects.com/?RadioGraPhy

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
