PORTNAME=	sn1per
DISTVERSION=	707.34747b3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Automated Pentest Recon Scanner.
WWW=		https://github.com/1N3/Sn1per

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/amap \
		??/android-tools \
		??/arachni \
		??/bind \
		??/brutex \
		??/cisco-torch \
		??/cutycapt \
		??/dnsenum \
		??/dnsrecon \
		??/dos2unix \
		??/enum4linux \
		??/firefox \
		??/golismero \
		??/goohak \
		??/hydra \
		??/jq \
		??/metasploit \
		??/nbtscan \
		??/nikto \
		??/postgresql \
		??/py-colorama@${PY_FLAVOR} \
		??/py-dnspython@${PY_FLAVOR} \
		??/py-paramiko@${PY_FLAVOR} \
		??/py-requests-file@${PY_FLAVOR} \
		??/py-tldextract@${PY_FLAVOR} \
		??/py-urllib3@${PY_FLAVOR} \
		??/rpcbind \
		??/ruby-mechanize \
		??/ruby-net-http-persistent \
		??/ruby-rake \
		??/ruby-ruby-nmap \
		??/ruby-text-table \
		??/smtp-user-enum \
		??/sqlmap \
		??/sslscan \
		??/sslyze \
		??/testssl.sh \
		??/theharvester \
		??/w3af \
		??/wapiti \
		??/whatweb \
		??/whois \
		??/wpscan \
		??/xdg-utils \
		??/xprobe2 \
		??/xsstracer \
		archivers/unzip \
		ftp/curl \
		lang/php82 \
		lang/python \
		lang/ruby \
		security/nmap \
		shells/bash \
		www/node \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
