PORTNAME=	serializationdumper
DISTVERSION=	34.6d161cd
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool to dump Java serialization streams in a more human readable form.
WWW=		https://github.com/NickstaDB/SerializationDumper/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/java-environment \
		??/java-runtime


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
