PORTNAME=	littleblackbox
DISTVERSION=	0.1.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Penetration testing tool, search in a collection of thousands of private SSL keys extracted from various embedded devices.
WWW=		http://code.google.com/p/littleblackbox/wiki/FAQ

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/tar

RUN_DEPENDS=	??/openssl-1.0 \
		??/sqlite \
		ftp/curl \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
