PORTNAME=	maltego
DISTVERSION=	4.11.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An open source intelligence and forensics application, enabling to easily gather information about DNS, domains, IP addresses, websites, persons, etc.
WWW=		https://www.maltego.com/downloads/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/giflib \
		??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
