PORTNAME=	tchunt-ng
DISTVERSION=	208.b8cf7fc
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Reveal encrypted files stored on a filesystem.
WWW=		https://github.com/antagon/TCHunt-ng

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
