PORTNAME=	perl-class-loader
DISTVERSION=	2.03
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Loads modules and creates objects on demand.
WWW=		http://search.cpan.org/~VIPUL/Class-Loader-2.03/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gmp \
		??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
