PORTNAME=	geoipgen
DISTVERSION=	0.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A country to IP addresses generator.
WWW=		https://code.google.com/archive/p/geoipgen/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/ruby-getoptlong \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
