PORTNAME=	domain-analyzer
DISTVERSION=	0.8.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Finds all the security information for a given domain name.
WWW=		http://sourceforge.net/projects/domainanalyzer/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-dnspython@${PY_FLAVOR} \
		??/py-httplib2@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
