PORTNAME=	hashdb
DISTVERSION=	1089.1da1b9f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A block hash toolkit.
WWW=		https://github.com/NPS-DEEP/hashdb/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/libewf \
		??/libtool \
		??/libxml2 \
		??/tre \
		lang/python3 \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
