PORTNAME=	yay
DISTVERSION=	12.5.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Yet another yogurt. Pacman wrapper and AUR helper written in go.
WWW=		https://github.com/Jguer/yay

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/go-pie

RUN_DEPENDS=	??/pacman \
		devel/git


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
