PORTNAME=	perl-net-libdnet6
DISTVERSION=	0.28
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Adds IPv6 support to Net::Libdnet.
WWW=		http://search.cpan.org/~gomor/Net-Libdnet6/lib/Net/Libdnet6.pm

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
