PORTNAME=	dnsgrep
DISTVERSION=	14.3f4fa7c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A utility for quickly searching presorted DNS names.
WWW=		https://github.com/erbbysam/DNSGrep

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/go


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
