PORTNAME=	python-taxii2-client
DISTVERSION=	0.5.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	OASIS TC Open Repository: TAXII 2 Client Library Written in Python.
WWW=		https://github.com/oasis-open/cti-taxii-client

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
