PORTNAME=	armor
DISTVERSION=	5.bae27a6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple Bash script designed to create encrypted macOS payloads capable of evading antivirus scanners.
WWW=		https://github.com/tokyoneon/Armor

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	ftp/wget \
		security/openssl \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
