PORTNAME=	http-traceroute
DISTVERSION=	0.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This is a python script that uses the Max-Forwards header in HTTP and SIP to perform a traceroute-like scanning functionality.
WWW=		http://packetstormsecurity.com/files/107167/Traceroute-Like-HTTP-Scanner.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
