PORTNAME=	myrescue
DISTVERSION=	0.9.8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A hard disk recovery tool that reads undamaged regions first.
WWW=		http://myrescue.sourceforge.net

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
