PORTNAME=	wafp
DISTVERSION=	0.01.26c3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An easy to use Web Application Finger Printing tool written in ruby using sqlite3 databases for storing the fingerprints.
WWW=		http://packetstormsecurity.com/files/84468/Web-Application-Finger-Printer-0.01-26c3.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/ruby-sqlite3 \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
