PORTNAME=	snmpattack
DISTVERSION=	1.8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	SNMP scanner and attacking tool.
WWW=		http://www.c0decafe.de/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-net-ip \
		??/perl-net-rawip \
		??/perl-net-snmp


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
