PORTNAME=	dislocker
DISTVERSION=	v0.7.3.r69.g38dab03
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Read BitLocker encrypted volumes under Linux.
WWW=		https://github.com/Aorimn/dislocker

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		??/make \
		devel/git

RUN_DEPENDS=	??/fuse \
		??/mbedtls \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
