PORTNAME=	perl-algorithm-permute
DISTVERSION=	0.16
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl module for handy and fast permutations with object oriented interface.
WWW=		http://search.cpan.org/dist/Algorithm-Permute/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
