PORTNAME=	de4dot
DISTVERSION=	2090.b7d5728
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	.NET deobfuscator and unpacker.
WWW=		https://github.com/de4dot/de4dot

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/mono \
		??/mono-msbuild \
		devel/git

RUN_DEPENDS=	??/mono


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
