PORTNAME=	o-saft
DISTVERSION=	7169.bf4aa66e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool to show informations about SSL certificate and tests the SSL connection according given list of ciphers and various SSL configurations.
WWW=		https://www.owasp.org/index.php/O-Saft

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl \
		??/perl-io-socket-inet6 \
		??/perl-io-socket-ssl \
		??/perl-net-ssleay


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
