PORTNAME=	pth
DISTVERSION=	2.0.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The GNU Portable Threads.
WWW=		https://www.gnu.org/software/pth/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/awk


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
