PORTNAME=	python-libmsiecf-python
DISTVERSION=	20240425
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Library and tools to access the Microsoft Internet Explorer (MSIE) Cache File (index.dat) files.
WWW=		https://github.com/libyal/libmsiecf

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
