PORTNAME=	xmpppy
DISTVERSION=	0.5.0.rc1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Python library to provide easy scripting with Jabber,
WWW=		https://sourceforge.net/projects/xmpppy/files/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-distribute@${PY_FLAVOR}

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
