PORTNAME=	jdeserialize
DISTVERSION=	31.20635ba
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A library that interprets Java serialized objects. It also comes with a command-line tool that can generate compilable class declarations, extract block data, and print textual representations of instance values.
WWW=		https://github.com/frohoff/jdeserialize/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/ant \
		devel/git

RUN_DEPENDS=	??/java-environment \
		??/java-runtime


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
