PORTNAME=	windows-binaries
DISTVERSION=	20.7d272da
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A colleciton of pentesting Windows binaries.
WWW=		https://github.com/BlackArch/windows-binaries

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
