PORTNAME=	sasm
DISTVERSION=	3.12.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple crossplatform IDE for NASM, MASM, GAS and FASM assembly languages.
WWW=		https://github.com/Dman95/SASM

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/qt4

RUN_DEPENDS=	??/gdb \
		??/libxcb \
		??/mesa \
		??/nasm \
		??/qt5-base


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
