PORTNAME=	fs-nyarl
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A network takeover & forensic analysis tool - useful to advanced PenTest tasks & for fun and profit.
WWW=		http://www.fulgursecurity.com/en/content/fs-nyarl

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/arp-scan \
		??/beef \
		??/chaosreader \
		??/dsniff \
		??/ettercap \
		??/foremost \
		??/hamster \
		??/macchanger \
		??/metasploit \
		??/mitmproxy \
		??/p0f \
		??/sslsplit \
		??/sslstrip \
		??/tcpdump


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
