PORTNAME=	python-fullcontactpy
DISTVERSION=	0.0.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Simple Python interface for FullContact, using Requests.
WWW=		https://pypi.python.org/pypi/fullcontact.py/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
