PORTNAME=	mantra
DISTVERSION=	v3.1.r4.g0634a79
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Hunt down API key leaks in JS files and pages.
WWW=		https://github.com/MrEmpy/mantra

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
