PORTNAME=	dnsdrdos
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Proof of concept code for distributed DNS reflection DoS.
WWW=		http://nullsecurity.net/tools/dos.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
