PORTNAME=	findmyhash
DISTVERSION=	1.1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Crack different types of hashes using free online services.
WWW=		https://code.google.com/archive/p/findmyhash/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-httplib2@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
