PORTNAME=	grepforrfi
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Simple script for parsing web logs for RFIs and Webshells v1.2
WWW=		http://www.irongeek.com/downloads/grepforrfi.txt

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
