PORTNAME=	catana
DISTVERSION=	31.9ea1f0d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Filter your wordlist according to the specified password policy.
WWW=		https://github.com/D3vil0p3r/catana

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
