PORTNAME=	cheat-sh
DISTVERSION=	6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The only cheat sheet you need.
WWW=		https://cheat.sh

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-virtualenv@${PY_FLAVOR} \
		devel/git \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
