PORTNAME=	sipcalc
DISTVERSION=	1.1.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An advanced console based ip subnet calculator.
WWW=		https://www.routemeister.net/projects/sipcalc/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
