PORTNAME=	ruby-net-http-digest_auth
DISTVERSION=	1.4.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An implementation of RFC 2617 - Digest Access Authentication.
WWW=		http://github.com/drbrain/net-http-digest_auth

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	lang/ruby



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
