PORTNAME=	chromedriver
DISTVERSION=	2.41
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Standalone server which implements WebDrivers wire protocol.
WWW=		https://sites.google.com/a/chromium.org/chromedriver/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gconf \
		??/libpng


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
