PORTNAME=	dynamorio
DISTVERSION=	9.0.19046
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A dynamic binary instrumentation framework.
WWW=		https://github.com/DynamoRIO/dynamorio

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
