PORTNAME=	volana
DISTVERSION=	v1.0.0.r26.g6dbf9a4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Shell command obfuscation to avoid detection systems.
WWW=		https://github.com/ariary/volana

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
