PORTNAME=	spike-fuzzer
DISTVERSION=	2.9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	IMMUNITYsecs fuzzer creation kit in C.
WWW=		http://www.immunitysec.com/resources-freesoftware.shtml

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/autoconf \
		??/automake \
		??/gcc \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
