PORTNAME=	perl-rpc-xml
DISTVERSION=	0.82
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A set of classes for core data, message and XML handling.
WWW=		https://metacpan.org/pod/RPC::XML

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-libwww \
		??/perl-xml-libxml


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
