PORTNAME=	grr
DISTVERSION=	55.76f6ee9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	High-throughput fuzzer and emulator of DECREE binaries.
WWW=		https://github.com/trailofbits/grr

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/clang \
		??/cmake \
		??/llvm \
		devel/git

RUN_DEPENDS=	??/gflags \
		??/radamsa \
		??/xed \
		??/xed-intel


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
