PORTNAME=	python-rel
DISTVERSION=	0.4.9.23
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Registered Event Listener. Provides standard (pyevent) interface and functionality without external dependencies.
WWW=		https://pypi.org/project/rel/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-installer@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
