PORTNAME=	bvi
DISTVERSION=	1.4.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A display-oriented editor for binary files operate like vi editor.
WWW=		http://bvi.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/ncurses5-compat-libs


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
