PORTNAME=	rebind
DISTVERSION=	0.3.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	DNS Rebinding Tool.
WWW=		http://code.google.com/p/rebind/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/subversion

RUN_DEPENDS=	??/readline \
		??/sqlite3 \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
