PORTNAME=	sireprat
DISTVERSION=	34.b8ef60b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Remote Command Execution as SYSTEM on Windows IoT Core.
WWW=		https://github.com/SafeBreach-Labs/$_pkgname

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-hexdump@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
