PORTNAME=	multimac
DISTVERSION=	1.0.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Multiple MACs on an adapter.
WWW=		http://sourceforge.net/projects/multimac/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gcc


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
