PORTNAME=	ip-https-tools
DISTVERSION=	7.170691f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tools for the IP over HTTPS (IP-HTTPS) Tunneling Protocol.
WWW=		https://github.com/takeshixx/ip-https-tools

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
