PORTNAME=	tor-autocircuit
DISTVERSION=	0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Was developed to give users a finer control over Tor circuit creation.
WWW=		http://www.thesprawl.org/projects/tor-autocircuit/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-elixir@${PY_FLAVOR} \
		??/py-geoip@${PY_FLAVOR} \
		??/py-pytorctl@${PY_FLAVOR} \
		??/tor


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
