PORTNAME=	pgdbf
DISTVERSION=	113.4e84775
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Convert XBase / FoxPro databases to PostgreSQL
WWW=		https://github.com/kstrauser/pgdbf

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
