PORTNAME=	nili
DISTVERSION=	0.1.1.r4.g285220a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool for Network Scan, Man in the Middle, Protocol Reverse Engineering and Fuzzing.
WWW=		https://github.com/niloofarkheirkhah/nili

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	??/netzob \
		lang/python \
		net/py-scapy@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
