PORTNAME=	python2-sip-pyqt5
DISTVERSION=	4.19.24
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python SIP bindings for C/C++ libraries.
WWW=		https://www.riverbankcomputing.com/software/sip/intro

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	lang/python3



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
