PORTNAME=	blackarch-config-gtk
DISTVERSION=	4.f9f6a21
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	BlackArch config for gtk-2.0.
WWW=		https://github.com/BlackArch/blackarch-config-gtk

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/blackarch-wallpaper \
		??/feh


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
