PORTNAME=	trid
DISTVERSION=	2.24
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An utility designed to identify file types from their binary signatures.
WWW=		http://mark0.net/soft-trid-e.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/lib32-ncurses \
		??/trid-defs


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
