PORTNAME=	outguess
DISTVERSION=	0.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A universal steganographic tool.
WWW=		https://github.com/resurrecting-open-source-projects/outguess

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
