PORTNAME=	wafpass
DISTVERSION=	50.4211785
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Analysing parameters with all payloads bypass methods, aiming at benchmarking security solutions like WAF.
WWW=		https://github.com/wafpassproject/wafpass

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/python3 \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
