PORTNAME=	c7decrypt
DISTVERSION=	0.3.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Cisco password type-7 encryptor and decryptor.
WWW=		https://github.com/claudijd/c7decrypt

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
