PORTNAME=	linux-smart-enumeration
DISTVERSION=	299.eb80976
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Linux enumeration tool for pentesting and CTFs with verbosity levels.
WWW=		https://github.com/diego-treitos/linux-smart-enumeration

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
