PORTNAME=	python-openstep-parser
DISTVERSION=	2.0.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	OpenStep plist reader into python objects.
WWW=		https://pypi.org/project/openstep-parser/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	??/py-coverage@${PY_FLAVOR} \
		??/py-nose@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
