PORTNAME=	ipv666
DISTVERSION=	182.ad45ae8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Golang IPv6 address enumeration.
WWW=		https://github.com/lavalamp-/ipv666

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
