PORTNAME=	perl-math-gmp
DISTVERSION=	2.20
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	High speed arbitrary size integer math.
WWW=		https://metacpan.org/pod/Math::GMP

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gmp \
		??/perl \
		??/perl-alien-base-modulebuild \
		??/perl-alien-gmp \
		??/perl-devel-checklib


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
