PORTNAME=	perl-struct-dumb
DISTVERSION=	0.12
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Make simple lightweight record-like structures.
WWW=		http://search.cpan.org/dist/Struct-Dumb

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl-module-build

RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
