PORTNAME=	fiked
DISTVERSION=	0.0.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fake IDE daemon.
WWW=		https://www.roe.ch/FakeIKEd

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libgcrypt \
		??/libnet


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
