PORTNAME=	pacu
DISTVERSION=	v1.6.1.r2.g50e7ad2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The AWS exploitation framework, designed for testing the security of Amazon Web Services environments.
WWW=		https://github.com/RhinoSecurityLabs/pacu

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		devel/py-pip@${PY_FLAVOR} \
		devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
