PORTNAME=	malice
DISTVERSION=	0.3.28
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	VirusTotal Wanna Be - Now with 100% more Hipster.
WWW=		https://github.com/maliceio/malice

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
