PORTNAME=	uncover
DISTVERSION=	v1.2.0.r2.gb01669e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Discover exposed hosts on the internet using multiple search engines.
WWW=		https://github.com/projectdiscovery/uncover

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
