PORTNAME=	dnsgoblin
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Nasty creature constantly searching for DNS servers. It uses standard dns querys and waits for the replies.
WWW=		http://nullsecurity.net/tools/scanner.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
