PORTNAME=	luksipc
DISTVERSION=	0.01
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool to convert unencrypted block devices to encrypted LUKS devices in-place.
WWW=		http://www.johannes-bauer.com/linux/luksipc

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
