PORTNAME=	stenographer
DISTVERSION=	486.355604b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A packet capture solution which aims to quickly spool all packets to disk, then provide simple, fast access to subsets of those packets.
WWW=		https://github.com/google/stenographer

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
