PORTNAME=	python-unicodecsv
DISTVERSION=	0.14.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Pythons stdlib csv module is nice, but it doesnt support unicode. This module is a drop-in replacement which *does*.
WWW=		https://github.com/jdunck/python-unicodecsv

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
