PORTNAME=	evtkit
DISTVERSION=	8.af06db3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fix acquired .evt - Windows Event Log files (Forensics).
WWW=		https://github.com/yarox24/evtkit

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
