PORTNAME=	netkit-rusers
DISTVERSION=	0.17
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Logged in users; Displays who is logged in to machines on local network.
WWW=		https://packages.debian.org/source/sid/net/netkit-rusers

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libtirpc-compat \
		??/rpcsvc-proto


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
