PORTNAME=	xorbruteforcer
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Script that implements a XOR bruteforcing of a given file, although a specific key can be used too.
WWW=		http://eternal-todo.com/category/bruteforce

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
