PORTNAME=	genisys
DISTVERSION=	53.d53bb0c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Powerful Telegram Members Scraping and Adding Toolkit.
WWW=		https://github.com/ahayder/Genisys

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-colorama@${PY_FLAVOR} \
		??/py-keyboard@${PY_FLAVOR} \
		??/py-pyfiglet@${PY_FLAVOR} \
		??/py-telethon@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
