PORTNAME=	flask-session-cookie-manager2
DISTVERSION=	v1.2.2.r1.g3c271d2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Decode and encode Flask session cookie.
WWW=		https://noraj.github.io/flask-session-cookie-manager/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
