PORTNAME=	browselist
DISTVERSION=	1.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Retrieves the browse list ; the output list contains computer names, and the roles they play in the network.
WWW=		https://vidstromlabs.com/browselist/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
