PORTNAME=	ruby-twitter_cldr
DISTVERSION=	6.14.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Ruby implementation of the ICU (International Components for Unicode) that uses the Common Locale Data Repository to format dates, plurals, and more.
WWW=		https://rubygems.org/gems/twitter_cldr

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/ruby-camertron-eprun \
		??/ruby-cldr-plurals-runtime-rb \
		??/ruby-tzinfo \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
