PORTNAME=	padoracle
DISTVERSION=	v0.1.1.r28.gedff268
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Padding Oracle Attack with Node.js.
WWW=		https://github.com/imyelo/padoracle

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		www/npm

RUN_DEPENDS=	www/node


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
