PORTNAME=	bluesnarfer
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A bluetooth attacking tool.
WWW=		http://www.alighieri.org/project.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/bluez-libs


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
