PORTNAME=	stig-viewer
DISTVERSION=	2.8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	XCCDF formatted SRGs and STIGs files viewer for SCAP validation tools.
WWW=		https://www.stig-viewer.com/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
