PORTNAME=	ctypes-sh
DISTVERSION=	161.d8e1af5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Allows you to call routines in shared libraries from within bash.
WWW=		https://github.com/taviso/ctypes.sh

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/elfutils \
		??/libdwarf \
		??/libelf \
		??/libffi \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
