PORTNAME=	openstego
DISTVERSION=	0.8.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool implemented in Java for generic steganography, with support for password-based encryption of the data.
WWW=		https://github.com/syvaidya/openstego/releases

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
