PORTNAME=	stegolego
DISTVERSION=	8.85354f6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Simple program for using stegonography to hide data within BMP images.
WWW=		https://github.com/razc411/StegoLeggo

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
