PORTNAME=	superscan
DISTVERSION=	4.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Powerful TCP port scanner, pinger, resolver.
WWW=		http://www.foundstone.com/us/resources/proddesc/superscan.htm

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
