PORTNAME=	blackarch-devtools
DISTVERSION=	1.9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tools for BlackArch Linux package maintainers.
WWW=		

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/devtools


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
