PORTNAME=	uniscan
DISTVERSION=	6.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple Remote File Include, Local File Include and Remote Command Execution vulnerability scanner.
WWW=		http://sourceforge.net/projects/uniscan/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-devel-overloadinfo \
		??/perl-lwp-protocol-https \
		??/perl-moose


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
