PORTNAME=	git-dump
DISTVERSION=	7.4c9a2a9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Dump the contents of a remote git repository without directory listing enabled.
WWW=		https://github.com/bahamas10/node-git-dump

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		www/npm

RUN_DEPENDS=	devel/git \
		www/node


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
