PORTNAME=	sb0x
DISTVERSION=	19.04f40fe
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple and Lightweight framework for Penetration testing.
WWW=		https://github.com/levi0x0/sb0x-project

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
