PORTNAME=	scap-workbench
DISTVERSION=	1.2.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	SCAP Scanner And Tailoring Graphical User Interface.
WWW=		https://github.com/OpenSCAP/scap-workbench

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/asciidoc \
		??/asciidoctor \
		??/cmake \
		devel/git

RUN_DEPENDS=	??/libutil-linux \
		??/openscap \
		??/openssh-askpass \
		??/qt5-base \
		??/qt5-xmlpatterns


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
