PORTNAME=	laudanum
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A collection of injectable files, designed to be used in a pentest when SQL injection flaws are found and are in multiple languages for different environments.
WWW=		http://laudanum.inguardians.com/#

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
