PORTNAME=	bsqlinjector
DISTVERSION=	14.98c8ce8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Blind SQL injection exploitation tool written in ruby.
WWW=		https://github.com/enjoiz/BSQLinjector

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
