PORTNAME=	regview
DISTVERSION=	1.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Open raw Windows NT 5 Registry files (Windows 2000 or higher).
WWW=		https://www.gaijin.at/en/dlregview.php

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/p7zip \
		ftp/curl



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
