PORTNAME=	mingsweeper
DISTVERSION=	1.00
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A network reconnaissance tool designed to facilitate large address space,high speed node discovery and identification.
WWW=		http://www.hoobie.net/mingsweeper/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
