PORTNAME=	fluxion
DISTVERSION=	1614.a23d48a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A security auditing and social-engineering research tool.
WWW=		https://github.com/FluxionNetwork/fluxion

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/binutils \
		??/coreutils \
		devel/git

RUN_DEPENDS=	??/aircrack-ng \
		??/awk \
		??/bc \
		??/coreutils \
		??/cowpatty \
		??/dhcp \
		??/dsniff \
		??/hostapd \
		??/iw \
		??/lighttpd \
		??/macchanger \
		??/mdk3 \
		??/mdk4 \
		??/p7zip \
		??/php-cgi \
		??/xorg-xdpyinfo \
		??/xterm \
		archivers/unzip \
		ftp/curl \
		security/nmap \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
