PORTNAME=	pack
DISTVERSION=	0.0.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Password Analysis and Cracking Kit.
WWW=		http://thesprawl.org/projects/pack/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/aspell \
		??/aspell-en \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
