PORTNAME=	perl-lwp-protocol-socks
DISTVERSION=	1.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Adds support for the socks protocol and proxy facility.
WWW=		https://metacpan.org/pod/LWP::Protocol::socks

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl-io-socket-socks \
		??/perl-io-socket-ssl \
		??/perl-libwww \
		??/perl-lwp-protocol-https


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
