PORTNAME=	pngcheck
DISTVERSION=	3.0.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Verifies the integrity of PNG, JNG and MNG files by checking the CRCs and decompressing the image data.
WWW=		http://www.libpng.org/pub/png/apps/pngcheck.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libpng


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
