PORTNAME=	libxtrxdsp
DISTVERSION=	12.271f5e6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	DSP specific function for SDR in general and XTRX in specific.
WWW=		https://github.com/xtrx-sdr/libxtrxdsp

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
