PORTNAME=	powershdll
DISTVERSION=	72.62cfa17
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Run PowerShell with rundll32. Bypass software restrictions.
WWW=		https://github.com/p3nt4/PowerShdll

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	devel/git


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
