PORTNAME=	blackarch-config-vim
DISTVERSION=	3.620775f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	BlackArch config for the VIM editor.
WWW=		https://github.com/BlackArch/blackarch-config-vim

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/ctags \
		??/vim


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
