PORTNAME=	aquatone
DISTVERSION=	v1.9.1.shelld3v.r14.g30fbf6e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Tool for Domain Flyovers.
WWW=		https://github.com/shelld3v/aquatone

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/go-pie \
		devel/git

RUN_DEPENDS=	??/chromium


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
