PORTNAME=	der-ascii
DISTVERSION=	104.a97a6e4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A reversible DER and BER pretty-printer.
WWW=		https://github.com/google/der-ascii

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
