PORTNAME=	khc
DISTVERSION=	0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A small tool designed to recover hashed known_hosts fields back to their plain-text equivalents.
WWW=		http://packetstormsecurity.com/files/87003/Known-Host-Cracker-0.2.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
