PORTNAME=	dumpacl
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Dumps NTs ACLs and audit settings.
WWW=		http://www.systemtools.com/cgi-bin/download.pl?DumpAcl

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
