PORTNAME=	python-couchdb
DISTVERSION=	1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python library for working with CouchDB.
WWW=		https://pypi.org/project/CouchDB/#files

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	devel/py-setuptools@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
