PORTNAME=	snyk
DISTVERSION=	1.1283.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	CLI and build-time tool to find and fix known vulnerabilities in open-source dependencies.
WWW=		https://github.com/snyk/cli

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
