PORTNAME=	thezoo
DISTVERSION=	228.8f13742
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A project created to make the possibility of malware analysis open and available to the public.
WWW=		https://github.com/ytisf/theZoo

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
