PORTNAME=	liblms7002m-xtrx
DISTVERSION=	10.b07761b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Compact LMS7002M library suitable for resource-limited MCUs.
WWW=		https://github.com/xtrx-sdr/liblms7002m

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		??/py-cheetah3@${PY_FLAVOR} \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
