PORTNAME=	sipp
DISTVERSION=	1614.5c2bb62
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A free Open Source test tool / traffic generator for the SIP protocol.
WWW=		http://sipp.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		??/subversion \
		devel/git

RUN_DEPENDS=	net/libpcap \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
