PORTNAME=	autopsy
DISTVERSION=	4.22.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The forensic browser. A GUI for the Sleuth Kit.
WWW=		https://github.com/sleuthkit/autopsy

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-runtime \
		??/py-pytsk3@${PY_FLAVOR} \
		??/sleuthkit \
		??/sleuthkit-java \
		??/testdisk


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
