PORTNAME=	assetnote-wordlists
DISTVERSION=	182.a8fef0f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Assetnote generated wordlists.
WWW=		https://github.com/assetnote/wordlists

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
