PORTNAME=	bmc-tools
DISTVERSION=	36.94037ce
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	RDP Bitmap Cache parser.
WWW=		https://github.com/ANSSI-FR/bmc-tools

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
