PORTNAME=	cubicsdr
DISTVERSION=	0.2.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Cross-Platform Software-Defined Radio Application.
WWW=		https://github.com/cjcliffe/CubicSDR

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake

RUN_DEPENDS=	??/freeglut \
		??/hamlib \
		??/hicolor-icon-theme \
		??/libglvnd \
		??/libpulse \
		??/liquid-dsp \
		??/soapysdr \
		??/wxwidgets-common \
		??/wxwidgets-gtk3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
