PORTNAME=	voiphopper
DISTVERSION=	2.04
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A security validation tool that tests to see if a PC can mimic the behavior of an IP Phone. It rapidly automates a VLAN Hop into the Voice VLAN.
WWW=		http://voiphopper.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gcc \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
