PORTNAME=	tcptraceroute
DISTVERSION=	1.5beta7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A traceroute implementation using TCP packets.
WWW=		http://michael.toren.net/code/tcptraceroute/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libnet \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
