PORTNAME=	smtpmap
DISTVERSION=	0.8.234.BETA
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool to identify the running smtp software on a given host.
WWW=		http://www.projectiwear.org/~plasmahh/software.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
