PORTNAME=	redpoint
DISTVERSION=	123.23ef36b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Digital Bonds ICS Enumeration Tools.
WWW=		https://github.com/digitalbond/Redpoint3

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	security/nmap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
