PORTNAME=	otori
DISTVERSION=	0.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Toolbox intended to allow useful exploitation of XML external entity (XXE) vulnerabilities.
WWW=		http://www.beneaththewaves.net/Software/On_The_Outside_Reaching_In.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-simplejson@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
