PORTNAME=	netreconn
DISTVERSION=	1.78
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A collection of network scan/recon tools that are relatively small compared to their larger cousins.
WWW=		http://packetstormsecurity.com/files/86076/NetReconn-Scanning-Tool-Collection-1.76.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
