PORTNAME=	perl-net-frame-layer-icmp6
DISTVERSION=	1.11
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Internet Control Message Protocol v6 layer object.
WWW=		http://search.cpan.org/~gomor/Net-Frame-Layer-ICMPv6/lib/Net/Frame/Layer/ICMPv6.pm

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
