PORTNAME=	spotbugs
DISTVERSION=	4.9.8.r95.gacc820e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool for static analysis to look for bugs in Java code.
WWW=		https://github.com/spotbugs/spotbugs

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gradle \
		devel/git

RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
