PORTNAME=	bulk-extractor
DISTVERSION=	2386.898db1b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Bulk Email and URL extraction tool.
WWW=		https://github.com/simsong/bulk_extractor

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/afflib \
		??/exiv2 \
		??/java-environment \
		??/libewf \
		??/ncurses5-compat-libs \
		??/tre \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
