PORTNAME=	admid-pack
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	ADM DNS spoofing tools - Uses a variety of active and passive methods to spoof DNS packets.
WWW=		http://packetstormsecurity.com/files/10080/ADMid-pkg.tgz.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
