PORTNAME=	w3af
DISTVERSION=	1.6.49
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Web Application Attack and Audit Framework.
WWW=		https://github.com/andresriancho/w3af/releases

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/graphviz \
		??/gtk2 \
		??/halberd \
		??/libxml2 \
		??/libyaml \
		??/py-beautifulsoup3@${PY_FLAVOR} \
		??/py-chardet@${PY_FLAVOR} \
		??/py-clamd@${PY_FLAVOR} \
		??/py-cluster@${PY_FLAVOR} \
		??/py-darts.util.lru@${PY_FLAVOR} \
		??/py-esmre@${PY_FLAVOR} \
		??/py-future@${PY_FLAVOR} \
		??/py-futures@${PY_FLAVOR} \
		??/py-gitpython@${PY_FLAVOR} \
		??/py-guess-language@${PY_FLAVOR} \
		??/py-jinja@${PY_FLAVOR} \
		??/py-lxml@${PY_FLAVOR} \
		??/py-markdown@${PY_FLAVOR} \
		??/py-msgpack@${PY_FLAVOR} \
		??/py-nltk@${PY_FLAVOR} \
		??/py-ntlm@${PY_FLAVOR} \
		??/py-pdfminer@${PY_FLAVOR} \
		??/py-phply@${PY_FLAVOR} \
		??/py-pip@${PY_FLAVOR} \
		??/py-pyasn1@${PY_FLAVOR} \
		??/py-pybloomfiltermmap@${PY_FLAVOR} \
		??/py-pygithub@${PY_FLAVOR} \
		??/py-pyopenssl@${PY_FLAVOR} \
		??/py-pysqlite@${PY_FLAVOR} \
		??/py-stopit@${PY_FLAVOR} \
		??/py-tblib@${PY_FLAVOR} \
		??/py-vulndb@${PY_FLAVOR} \
		??/py-xdot@${PY_FLAVOR} \
		??/py-yaml@${PY_FLAVOR} \
		??/pygtk \
		??/pygtksourceview2 \
		??/sqlite \
		lang/python3 \
		net/py-scapy@${PY_FLAVOR} \
		textproc/libxslt


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
