PORTNAME=	backports-drivers-frag+ack
DISTVERSION=	1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	$_patch for compat-drivers-patched
WWW=		https://backports.wiki.kernel.org/index.php/Main_Page

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
