PORTNAME=	crackmapexec-pingcastle
DISTVERSION=	9.16340d2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	NetExec & CrackMapExec module that execute PingCastle on a remote machine.
WWW=		https://github.com/TRIKKSS/CrackMapExec-PingCastle

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
