PORTNAME=	sj
DISTVERSION=	2.3.0.r0.g4c46611
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool for auditing endpoints defined in exposed (Swagger/OpenAPI) definition files.
WWW=		https://github.com/BishopFox/sj

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
