PORTNAME=	impacket-ba
DISTVERSION=	0.13.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Collection of classes for working with network protocols.
WWW=		https://github.com/fortra/impacket

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-charset-normalizer@${PY_FLAVOR} \
		??/py-flask@${PY_FLAVOR} \
		??/py-ldap3@${PY_FLAVOR} \
		??/py-ldapdomaindump@${PY_FLAVOR} \
		??/py-pyasn1-modules@${PY_FLAVOR} \
		??/py-pyasn1@${PY_FLAVOR} \
		??/py-pycryptodomex@${PY_FLAVOR} \
		??/py-pyopenssl@${PY_FLAVOR} \
		devel/py-setuptools@${PY_FLAVOR} \
		devel/py-six@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
