PORTNAME=	puredns
DISTVERSION=	v2.1.1.r2.gd823415
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fast domain resolver and subdomain bruteforcing with accurate wildcard filtering.
WWW=		https://github.com/d3mondev/puredns

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go

RUN_DEPENDS=	??/massdns


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
