PORTNAME=	unfurl
DISTVERSION=	33.8f10d05
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Pull out bits of URLs provided on stdin.
WWW=		https://github.com/tomnomnom/unfurl

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
