PORTNAME=	eraser
DISTVERSION=	6.2.0.2992
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Windows tool which allows you to completely remove sensitive data from your hard drive by overwriting it several times with carefully selected patterns.
WWW=		https://eraser.heidi.ie/download/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
