PORTNAME=	bmap
DISTVERSION=	1.0.17
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool that can store data in slackspace on any filesystem. It can detect used slackspace and recover the data.
WWW=		http://www.securityfocus.com/tools/1359

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/linuxdoc-tools



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
