PORTNAME=	obexftp
DISTVERSION=	0.24.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool for transfer files to/from any OBEX enabled device.
WWW=		http://dev.zuckschwerdt.org/openobex/wiki/ObexFtp

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/asciidoc \
		??/cmake \
		??/fuse2 \
		??/swig \
		??/tk \
		??/xmlto \
		lang/python3 \
		lang/ruby

RUN_DEPENDS=	??/expat \
		??/fuse2 \
		??/openobex


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
