PORTNAME=	browser-fuzzer
DISTVERSION=	3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Browser Fuzzer 3
WWW=		http://www.krakowlabs.com/dev.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
