PORTNAME=	hostbox-ssh
DISTVERSION=	0.1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A ssh password/account scanner.
WWW=		http://stridsmanit.wordpress.com/2012/12/02/brute-forcing-passwords-with-hostbox-ssh-0-1-1/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-paramiko@${PY_FLAVOR} \
		??/wxpython \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
