PORTNAME=	udptunnel
DISTVERSION=	19
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tunnels TCP over UDP packets.
WWW=		http://code.google.com/p/udptunnel/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
