PORTNAME=	ruby-ruby-nmap
DISTVERSION=	1.0.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Ruby interface to Nmap, the exploration tool and security / port scanner.
WWW=		https://rubygems.org/gems/ruby-nmap

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/ruby-rdoc

RUN_DEPENDS=	??/ruby-nokogiri \
		??/ruby-rprogram \
		lang/ruby \
		security/nmap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
