PORTNAME=	python2-pybloomfiltermmap
DISTVERSION=	0.3.15
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Bloom filter (bloomfilter) for Python built on mmap.
WWW=		http://github.com/axiak/pybloomfiltermmap/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
