PORTNAME=	elettra
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A plausible deniable cryptography tool that supports a dynamic number of files and requires a password for each file.
WWW=		https://www.winstonsmith.info/julia/elettra/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake

RUN_DEPENDS=	??/libmcrypt \
		??/mhash \
		??/zlib


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
