PORTNAME=	stegseek
DISTVERSION=	v0.6.r10.g5896978
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Lightning fast steghide cracker.
WWW=		https://github.com/RickdeJager/stegseek

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git

RUN_DEPENDS=	??/libjpeg \
		??/libmcrypt \
		??/mhash \
		??/zlib


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
