PORTNAME=	s3enum
DISTVERSION=	v1.0.0.r17.gc23237b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Amazon S3 bucket enumeration.
WWW=		https://github.com/koenrh/s3enum

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
