PORTNAME=	obexstress
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Script for testing remote OBEX service for some potential vulnerabilities.
WWW=		http://bluetooth-pentest.narod.ru/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/lightblue \
		??/py-pybluez@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
