PORTNAME=	tyton
DISTVERSION=	81.f740076
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Kernel-Mode Rootkit Hunter.
WWW=		https://github.com/nbulischeck/tyton

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gcc \
		??/make \
		devel/git

RUN_DEPENDS=	??/dkms \
		??/gtk3 \
		??/libnotify \
		??/libsystemd \
		??/linux-headers


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
