PORTNAME=	blackarch-config-openbox
DISTVERSION=	40.6914684
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	BlackArch menu, theme and config for openbox window manager.
WWW=		https://github.com/BlackArch/blackarch-config-openbox

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/blackarch-wallpaper \
		??/feh \
		??/openbox \
		??/rxvt-unicode \
		??/terminus-font


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
