PORTNAME=	csrftester
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The OWASP CSRFTester Project attempts to give developers the ability to test their applications for CSRF flaws.
WWW=		http://www.owasp.org/index.php/Category:OWASP_CSRFTester_Project

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
