PORTNAME=	tcgetkey
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A set of tools that deal with acquiring physical memory dumps via FireWire and then scan the memory dump to locate TrueCrypt keys and finally decrypt the encrypted TrueCrypt container using the keys.
WWW=		http://packetstormsecurity.com/files/119146/tcgetkey-0.1.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libforensic1394 \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
