PORTNAME=	padding-oracle-attacker
DISTVERSION=	57.59dd18c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	CLI tool to execute padding oracle attacks with support for concurrent network requests.
WWW=		https://github.com/KishanBagaria/padding-oracle-attacker

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		www/npm

RUN_DEPENDS=	www/node


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
