PORTNAME=	acccheck
DISTVERSION=	0.2.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A password dictionary attack tool that targets windows authentication via the SMB protocol.
WWW=		http://labs.portcullis.co.uk/tools/acccheck/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/smbclient


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
