PORTNAME=	python-omitempty
DISTVERSION=	0.1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Enums for Python.
WWW=		https://pypi.org/project/omitempty/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	??/py-babel@${PY_FLAVOR} \
		??/py-coverage@${PY_FLAVOR} \
		??/py-docutils@${PY_FLAVOR} \
		??/py-jinja@${PY_FLAVOR} \
		??/py-markupsafe@${PY_FLAVOR} \
		??/py-pep8@${PY_FLAVOR} \
		??/py-pluggy@${PY_FLAVOR} \
		??/py-pygments@${PY_FLAVOR} \
		??/py-pytz@${PY_FLAVOR} \
		??/py-snowballstemmer@${PY_FLAVOR} \
		??/py-sphinx@${PY_FLAVOR} \
		??/py-tox@${PY_FLAVOR} \
		??/py-virtualenv@${PY_FLAVOR} \
		devel/py-six@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
