PORTNAME=	recsech
DISTVERSION=	123.1fc298a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool for doing Footprinting and Reconnaissance on the target web.
WWW=		https://github.com/radenvodka/Recsech

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/php82


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
