PORTNAME=	python-yara-rednaga
DISTVERSION=	279.32b6a74
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The Python interface for YARA.
WWW=		https://github.com/rednaga/yara-python-1

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/yara \
		devel/git \
		devel/py-setuptools@${PY_FLAVOR} \
		lang/python



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
