PORTNAME=	maketh
DISTVERSION=	0.2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A packet generator that supports forging ARP, IP, TCP, UDP, ICMP and the ethernet header as well.
WWW=		https://packetstormsecurity.com/files/83892/Maketh-Packet-Generator-0.2.0.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
