PORTNAME=	blackman
DISTVERSION=	0.5.14
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Emerge for BlackArch Linux - Download and compile packages as emerge does.
WWW=		https://github.com/BlackArch/blackman

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/subversion \
		devel/git


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
