PORTNAME=	terminus-font-dv1-ij1-ll2-td1-otb
DISTVERSION=	4.48
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Monospace bitmap font (OTB version) with dv1 (cyrillic de & ve), ij1 (cyrillic i patch), ll2 (pass the il1I test) and td1 (centered ascii tilde) patches.
WWW=		http://terminus-font.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/fontforge

RUN_DEPENDS=	??/fontconfig \
		??/xorg-font-utils


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
