PORTNAME=	staekka
DISTVERSION=	9.57787ca
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This plugin extends Metasploit for some missing features and modules allowing interaction with other/custom exploits/ways of getting shell access.
WWW=		https://github.com/j-0-t/staekka

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/clang \
		??/make \
		devel/git \
		sysutils/rubygem-bundler

RUN_DEPENDS=	??/metasploit


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
