PORTNAME=	jeb-arm
DISTVERSION=	5.20.0.202411121942
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Arm decompiler.
WWW=		https://www.pnfsoftware.com/jeb/arm

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment \
		??/java-runtime-common


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
