PORTNAME=	usernamer
DISTVERSION=	20.12983f8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Pentest Tool to generate usernames/logins based on supplied names.
WWW=		https://github.com/jseidl/usernamer

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
