PORTNAME=	peass
DISTVERSION=	20260201.2ddf3a96.r2.gc1bf38a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Privilege Escalation Awesome Scripts SUITE (with colors).
WWW=		https://github.com/carlospolop/PEASS-ng

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-yaml@${PY_FLAVOR} \
		devel/git \
		ftp/wget \
		www/py-requests@${PY_FLAVOR}

RUN_DEPENDS=	shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
