PORTNAME=	neo4j-community
DISTVERSION=	5.26.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A fully transactional graph database implemented in Java.
WWW=		https://neo4j.com/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/java-environment \
		??/maven

RUN_DEPENDS=	??/java-runtime


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
