PORTNAME=	quicksand-lite
DISTVERSION=	33.c3edf92
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Command line tool for scanning streams within office documents plus xor db attack.
WWW=		https://github.com/tylabs/quicksand_lite

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/libzip \
		??/yara \
		??/zlib


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
