PORTNAME=	evil-winrm
DISTVERSION=	v3.9.r0.g84a543c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The ultimate WinRM shell for hacking/pentesting.
WWW=		https://github.com/Hackplayers/evil-winrm

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/ruby-rexml \
		devel/git \
		lang/ruby \
		security/openssl \
		sysutils/rubygem-bundler \
		textproc/libxslt


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
