PORTNAME=	pyinstxtractor
DISTVERSION=	2025.02.r2.g3b38d8d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	PyInstaller Extractor.
WWW=		https://github.com/extremecoders-re/pyinstxtractor

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
