PORTNAME=	blackarch-menus
DISTVERSION=	10.5244eea
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	BlackArch specific XDG-compliant menu.
WWW=		https://github.com/BlackArch/blackarch-menus

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/xdg-utils


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
