PORTNAME=	libevtx
DISTVERSION=	20181227
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Library and tools to access the Windows XML Event Log (EVTX) format.
WWW=		https://github.com/libyal/libevtx

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
