PORTNAME=	cidr2range
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Script for listing the IP addresses contained in a CIDR netblock.
WWW=		http://www.cpan.org/authors/id/R/RA/RAYNERLUC

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-net-cidr


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
