PORTNAME=	zsteg
DISTVERSION=	v0.2.14.r0.gb75b578
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Detect stegano-hidden data in PNG and BMP.
WWW=		https://github.com/zed-0xff/zsteg

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/ruby-iostruct \
		??/ruby-prime \
		??/ruby-zpng \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
