PORTNAME=	make-pdf
DISTVERSION=	0.1.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This tool will embed javascript inside a PDF document.
WWW=		http://blog.didierstevens.com/programs/pdf-tools/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/dos2unix \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
