PORTNAME=	qbdi
DISTVERSION=	v0.12.1.r3.ga5d225b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Dynamic Binary Instrumentation framework based on LLVM.
WWW=		https://github.com/QBDI/QBDI

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		??/gcc \
		devel/git \
		lang/python



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
