PORTNAME=	chkrootkit
DISTVERSION=	0.59
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Checks for rootkits on a system.
WWW=		http://www.chkrootkit.org/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
