PORTNAME=	python-cfscrape
DISTVERSION=	2.1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A small Python module to bypass Cloudflares anti-bot page, using Requests.
WWW=		https://pypi.org/project/cfscrape/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
