PORTNAME=	aespipe
DISTVERSION=	2.4f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Reads data from stdin and outputs encrypted or decrypted results to stdout.
WWW=		http://loop-aes.sourceforge.net/aespipe/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
