PORTNAME=	imagegrep
DISTVERSION=	8.1f14af2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Grep word in pdf or image based on OCR.
WWW=		https://github.com/coderofsalvation/imagegrep-bash

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/imagemagick \
		??/tesseract \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
