PORTNAME=	perl-alien-gmp
DISTVERSION=	1.16
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Alien package for the GNU Multiple Precision library.
WWW=		https://metacpan.org/pod/Alien::GMP

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl-devel-checklib

RUN_DEPENDS=	??/perl \
		??/perl-alien-base-modulebuild


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
