PORTNAME=	python2-freezegun
DISTVERSION=	0.3.15
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Let your Python tests travel through time.
WWW=		https://github.com/spulec/freezegun

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-dateutil@${PY_FLAVOR} \
		devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	??/py-dateutil@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
