PORTNAME=	heaptrace
DISTVERSION=	2.2.8.2.r20.g06f43fc
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Helps visualize heap operations for pwn and debugging.
WWW=		https://github.com/Arinerron/heaptrace

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
