PORTNAME=	lte-cell-scanner
DISTVERSION=	26.e7f71cb
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An OpenCL accelerated TDD/FDD LTE Scanner.
WWW=		https://github.com/JiaoXianjun/LTE-Cell-Scanner

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/bladerf \
		??/boost \
		??/boost-libs \
		??/cmake \
		??/fftw \
		??/hackrf \
		??/itpp

RUN_DEPENDS=	devel/git


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
