PORTNAME=	winhex
DISTVERSION=	20.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Hex Editor and Disk Editor.
WWW=		https://www.x-ways.net/winhex/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
