PORTNAME=	h2buster
DISTVERSION=	79.6c4dd1c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A threaded, recursive, web directory brute-force scanner over HTTP/2.
WWW=		https://github.com/00xc/h2buster

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-hyper@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
