PORTNAME=	perl-term-menu
DISTVERSION=	0.10
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl extension for asking questions and printing menus at the terminal.
WWW=		https://metacpan.org/pod/Term::Menu

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
