PORTNAME=	sucrack
DISTVERSION=	1.2.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A multi-threaded Linux/UNIX tool for brute-force cracking local user accounts via su.
WWW=		http://labs.portcullis.co.uk/application/sucrack

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
