PORTNAME=	vcsmap
DISTVERSION=	v2.0.2.r1.g3889964
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A plugin-based tool to scan public version control systems for sensitive information.
WWW=		https://github.com/melvinsh/vcsmap

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/ruby \
		sysutils/rubygem-bundler \
		textproc/libxslt


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
