PORTNAME=	python-pyqt5-webengine
DISTVERSION=	5.15.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python bindings for QtWebEngine.
WWW=		https://pypi.org/project/PyQtWebEngine/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/pyqt-builder \
		??/sip

RUN_DEPENDS=	??/py-pyqt5@${PY_FLAVOR} \
		??/qt5-webengine


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
