PORTNAME=	kalibrate-rtl
DISTVERSION=	69.340003e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fork of http://thre.at/kalibrate/ for use with rtl-sdr devices.
WWW=		https://github.com/steve-m/kalibrate-rtl

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/fftw \
		??/rtl-sdr


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
