PORTNAME=	unifuzzer
DISTVERSION=	5.3385a3b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A fuzzing tool for closed-source binaries based on Unicorn and LibFuzzer.
WWW=		https://github.com/rk700/uniFuzzer

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/clang \
		devel/git

RUN_DEPENDS=	??/unicorn


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
