PORTNAME=	nbname
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Decodes and displays all NetBIOS name packets it receives on UDP port 137 and more!
WWW=		http://www.cultdeadcow.com/tools/bo.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
