PORTNAME=	cisco-torch
DISTVERSION=	0.4b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Cisco Torch mass scanning, fingerprinting, and exploitation tool.
WWW=		https://github.com/foreni-packages/cisco-torch/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-net-snmp \
		??/perl-net-ssh-perl \
		??/perl-net-ssleay \
		??/perl-net-telnet


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
