PORTNAME=	waybackurls
DISTVERSION=	13.8d27cf3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fetch all the URLs that the Wayback Machine knows about for a domain.
WWW=		https://github.com/tomnomnom/waybackurls

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
