PORTNAME=	blackmate
DISTVERSION=	49.6e5f2d3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	BlackArch specific Xfce4 WM.
WWW=		https://github.com/Anyon3/blackmate

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/blackarch-config-gtk \
		??/blackarch-menus \
		??/sudo \
		??/xdg-utils \
		??/xfce4-session \
		??/xfce4-terminal \
		ftp/wget


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
