PORTNAME=	sdrtrunk
DISTVERSION=	0.6.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A cross-platform java application for decoding, monitoring, recording and streaming trunked mobile and related radio protocols using SDR.
WWW=		https://github.com/DSheirer/sdrtrunk

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/alsa-lib \
		??/at-spi2-core \
		??/gtk3 \
		??/java-environment \
		??/libnet


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
