PORTNAME=	facebrute
DISTVERSION=	7.ece355b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This script tries to guess passwords for a given facebook account using a list of passwords (dictionary).
WWW=		https://github.com/emerinohdz/FaceBrute

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-httplib2@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
