PORTNAME=	ftpmap
DISTVERSION=	52.cbeabbe
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Scans remote FTP servers to identify what software and what versions they are running.
WWW=		http://wcoserver.googlecode.com/files/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
