PORTNAME=	ridrelay
DISTVERSION=	34.f2fa99c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Enumerate usernames on a domain where you have no creds by using SMB Relay with low priv.
WWW=		https://github.com/skorov/ridrelay

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/impacket \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
