PORTNAME=	perl-crypt-rsa
DISTVERSION=	1.99
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	RSA public-key cryptosystem.
WWW=		http://search.cpan.org/dist/Crypt-RSA

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/perl-module-install

RUN_DEPENDS=	??/perl-class-loader \
		??/perl-convert-ascii-armour \
		??/perl-crypt-blowfish \
		??/perl-crypt-cbc \
		??/perl-crypt-primes \
		??/perl-crypt-random \
		??/perl-data-buffer \
		??/perl-digest-md2 \
		??/perl-digest-sha1 \
		??/perl-math-pari \
		??/perl-sort-versions \
		??/perl-tie-encryptedhash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
