PORTNAME=	ostinato
DISTVERSION=	1.2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An open-source, cross-platform packet/traffic generator and analyzer with a friendly GUI.
WWW=		https://github.com/pstavirs/ostinato/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/protobuf \
		??/protobuf-c \
		??/qt4 \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
