PORTNAME=	netmask
DISTVERSION=	2.4.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Helps determine network masks.
WWW=		http://packages.qa.debian.org/n/netmask.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
