PORTNAME=	sgp4
DISTVERSION=	v1.0.r9.gd176906
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Simplified perturbations models.
WWW=		https://github.com/dnwrnr/sgp4

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
