PORTNAME=	iptodomain
DISTVERSION=	18.f1afcd7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This tool extract domains from IP address based in the information saved in virustotal.
WWW=		https://github.com/Hackplayers/iptodomain

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
