PORTNAME=	raven
DISTVERSION=	33.8646a58
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Linkedin information gathering tool that can be used by pentesters to gather information about an organization employees using Linkedin.
WWW=		https://github.com/0x09AL/raven

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
