PORTNAME=	jcrack
DISTVERSION=	0.3.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A utility to create dictionary files that will crack the default passwords of select wireless gateways
WWW=		http://www.thedrahos.net/jcrack/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/crunch \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
