PORTNAME=	metabigor
DISTVERSION=	79.c0a3ecf
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Intelligence Tool but without API key.
WWW=		https://github.com/j3ssie/metabigor

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go

RUN_DEPENDS=	??/masscan \
		??/zmap \
		security/nmap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
