PORTNAME=	wcvs
DISTVERSION=	2.0.0.r2.g75159ea
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Web Cache Vulnerability Scanner is a Go-based CLI tool for testing for web cache poisoning.
WWW=		https://github.com/Hackmanit/Web-Cache-Vulnerability-Scanner

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
