PORTNAME=	schnappi-dhcp
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Can fuck network with no DHCP.
WWW=		http://www.emanuelegentili.eu/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
