PORTNAME=	teamsuserenum
DISTVERSION=	v1.0.r1.g0c8b6c2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	User enumeration with Microsoft Teams API
WWW=		https://github.com/immunIT/TeamsUserEnum

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
