PORTNAME=	perl-net-ssh-perl
DISTVERSION=	2.14
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl client interface to SSH.
WWW=		http://search.cpan.org/dist/Net-SSH-Perl

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl-convert-pem \
		??/perl-crypt-dh \
		??/perl-crypt-dsa \
		??/perl-crypt-idea \
		??/perl-crypt-rsa \
		??/perl-cryptx \
		??/perl-digest-bubblebabble \
		??/perl-digest-hmac \
		??/perl-digest-sha1 \
		??/perl-math-gmp \
		??/perl-scalar-list-utils \
		??/perl-string-crc32


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
