PORTNAME=	windowsspyblocker
DISTVERSION=	4.38.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Block spying and tracking on Windows.
WWW=		https://github.com/crazy-max/WindowsSpyBlocker/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
