PORTNAME=	cangibrina
DISTVERSION=	123.6de0165
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Dashboard Finder.
WWW=		https://github.com/fnk0c/cangibrina

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-beautifulsoup4@${PY_FLAVOR} \
		??/py-html5lib@${PY_FLAVOR} \
		??/py-mechanize@${PY_FLAVOR} \
		??/py-pysocks@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
