PORTNAME=	ruby-zpng
DISTVERSION=	0.4.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Pure ruby PNG file manipulation and validation.
WWW=		https://github.com/zed-0xff/zpng

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/ruby-rainbow \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
