PORTNAME=	novnc
DISTVERSION=	1.4.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	HTML VNC Client Library and Application.
WWW=		https://github.com/novnc/noVNC

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/inetutils \
		??/py-numpy@${PY_FLAVOR} \
		??/websockify \
		??/which \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
