PORTNAME=	smtptx
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A very simple tool used for sending simple email and do some basic email testing from a pentester perspective.
WWW=		http://www.0x90.se/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-dnspython@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
