PORTNAME=	memfetch
DISTVERSION=	0.05b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Dumps any userspace process memory without affecting its execution.
WWW=		http://lcamtuf.coredump.cx/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/make



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
