PORTNAME=	azazel
DISTVERSION=	15.a41fbb5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A userland rootkit based off of the original LD_PRELOAD technique from Jynx rootkit.
WWW=		https://github.com/chokepoint/azazel

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
