PORTNAME=	aimage
DISTVERSION=	3.3.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool to create aff-images.
WWW=		https://pkgs.fedoraproject.org/repo/pkgs/aimage/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/afflib \
		??/readline \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
