PORTNAME=	findmyiphone
DISTVERSION=	19.aef3ac8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Locates all devices associated with an iCloud account
WWW=		https://github.com/manwhoami/findmyiphone

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
