PORTNAME=	wireless-ids
DISTVERSION=	24.b132071
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Ability to detect suspicious activity such as (WEP/WPA/WPS) attack by sniffing the air for wireless packets.
WWW=		https://github.com/SYWorks/wireless-ids

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
