PORTNAME=	dbusmap
DISTVERSION=	16.6bb2831
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Simple utility for enumerating D-Bus endpoints, an nmap for D-Bus.
WWW=		https://github.com/taviso/dbusmap

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/glib2 \
		??/libxml2 \
		??/procps-ng


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
