PORTNAME=	ruby2.6
DISTVERSION=	2.6.9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An object-oriented language for quick and easy programming, version 2.6.
WWW=		https://www.ruby-lang.org/en/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/tk

RUN_DEPENDS=	??/gdbm \
		??/gmp \
		??/libffi \
		??/libxcrypt \
		??/libyaml \
		??/zlib \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
