PORTNAME=	wpintel
DISTVERSION=	6.741c0c9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Chrome extension designed for WordPress Vulnerability Scanning and information gathering.
WWW=		https://github.com/Tuhinshubhra/WPintel

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/chromium


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
