PORTNAME=	python2-pynids
DISTVERSION=	0.6.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Python wrapper for libnids.
WWW=		http://jon.oberheide.org/pynids/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/glib2 \
		??/libnet \
		lang/python3 \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
