PORTNAME=	rats
DISTVERSION=	6.4ba54ce
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A rough auditing tool for security in source code files.
WWW=		https://github.com/andrew-d/rough-auditing-tool-for-security

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/expat


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
