PORTNAME=	zarn
DISTVERSION=	0.0.9.r108.g80301cb
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A lightweight static security analysis tool for modern Perl Apps.
WWW=		https://github.com/htrgouvea/zarn

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl \
		??/perl-file-find-rule \
		??/perl-getopt-long \
		??/perl-json \
		??/perl-ppi \
		??/perl-yaml-tiny


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
