PORTNAME=	httpry
DISTVERSION=	0.1.8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A specialized packet sniffer designed for displaying and logging HTTP traffic.
WWW=		http://dumpsterventures.com/jason/httpry/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gzip

RUN_DEPENDS=	net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
