PORTNAME=	xspear
DISTVERSION=	1.4.1.r9.g57bb7b4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Powerful XSS Scanning and Parameter analysis tool&gem.
WWW=		https://github.com/hahwul/XSpear

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/ruby \
		sysutils/rubygem-bundler \
		textproc/libxslt


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
