PORTNAME=	sipcrack
DISTVERSION=	0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A SIP protocol login cracker.
WWW=		http://www.remote-exploit.org/codes_sipcrack.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
