PORTNAME=	perl-net-frame-dump
DISTVERSION=	1.18
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Base-class for a tcpdump like implementation.
WWW=		https://metacpan.org/pod/Net::Frame::Dump

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
