PORTNAME=	autonse
DISTVERSION=	25.7c87f4c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Massive NSE (Nmap Scripting Engine) AutoSploit and AutoScanner.
WWW=		https://github.com/m4ll0k/AutoNSE

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/iputils \
		security/nmap \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
