PORTNAME=	lorg
DISTVERSION=	98.aa4f1a3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Apache Logfile Security Analyzer.
WWW=		https://github.com/jensvoid/lorg

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/php82


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
