PORTNAME=	kubesploit
DISTVERSION=	105.ab2a57a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Cross-platform post-exploitation HTTP/2 Command & Control server.
WWW=		https://github.com/cyberark/kubesploit

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		ftp/wget



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
