PORTNAME=	moonwalk
DISTVERSION=	v1.0.0.r18.g68d5be1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Cover your tracks during Linux Exploitation by leaving zero traces on system logs and filesystem timestamps.
WWW=		https://github.com/mufeedvh/moonwalk

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/cargo \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
