PORTNAME=	arpoison
DISTVERSION=	0.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The UNIX arp cache update utility.
WWW=		http://www.arpoison.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libnet


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
