PORTNAME=	retire
DISTVERSION=	5.4.2.r4.gb9f6ed1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Scanner detecting the use of JavaScript libraries with known vulnerabilities.
WWW=		http://retirejs.github.io/retire.js/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		www/npm

RUN_DEPENDS=	www/node


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
