PORTNAME=	webslayer
DISTVERSION=	5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool designed for brute forcing Web Applications.
WWW=		https://code.google.com/p/webslayer/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/subversion

RUN_DEPENDS=	??/py-pycurl@${PY_FLAVOR} \
		??/py-pyqt4@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
