PORTNAME=	rfidiot
DISTVERSION=	107.88f2ef9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An open source python library for exploring RFID devices.
WWW=		http://rfidiot.org/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-distribute@${PY_FLAVOR} \
		??/py-pycryptodome@${PY_FLAVOR} \
		devel/git

RUN_DEPENDS=	lang/python3 \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
