PORTNAME=	perl-crypt-idea
DISTVERSION=	1.10
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl interface to IDEA block cipher.
WWW=		http://search.cpan.org/~DPARIS/Crypt-IDEA-1.10/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gmp \
		??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
