PORTNAME=	libbde
DISTVERSION=	340.ebc8e15
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A library to access the BitLocker Drive Encryption (BDE) format.
WWW=		https://github.com/libyal/libbde

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/autoconf \
		??/automake \
		??/bison \
		??/flex \
		??/gettext \
		??/libtool \
		??/pkg-config \
		devel/git

RUN_DEPENDS=	lang/python \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
