PORTNAME=	princeprocessor
DISTVERSION=	140.4160061
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Standalone password candidate generator using the PRINCE algorithm.
WWW=		https://github.com/jsteube/princeprocessor/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gcc \
		devel/git

RUN_DEPENDS=	??/lib32-glibc


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
