PORTNAME=	evilmaid
DISTVERSION=	1.01
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	TrueCrypt loader backdoor to sniff volume password.
WWW=		https://theinvisiblethings.blogspot.com

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
