PORTNAME=	ligolo-mp
DISTVERSION=	v2.1.0.r9.g27ca577
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Multiplayer pivoting solution.
WWW=		https://github.com/ttpreport/ligolo-mp

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/zip \
		devel/git \
		lang/go

RUN_DEPENDS=	??/awk \
		??/gnupg \
		ftp/curl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
