PORTNAME=	avml
DISTVERSION=	v0.15.0.r54.g3de58ee
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A portable volatile memory acquisition tool for Linux.
WWW=		https://github.com/microsoft/avml

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/musl \
		??/rust-musl \
		devel/cargo \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
