PORTNAME=	postenum
DISTVERSION=	126.f91ba1c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Clean, nice and easy tool for basic/advanced privilege escalation techniques.
WWW=		https://github.com/mbahadou/postenum

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
