PORTNAME=	mimipenguin
DISTVERSION=	153.ecb2ffc
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool to dump the login password from the current linux user.
WWW=		https://github.com/huntergregal/mimipenguin

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
