PORTNAME=	perl-net-frame-layer-sinfp3
DISTVERSION=	1.01
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Frame crafting made easy.
WWW=		http://search.cpan.org/CPAN/authors/id/G/GO/GOMOR/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
