PORTNAME=	swftools
DISTVERSION=	0.9.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A collection of SWF manipulation and creation utilities.
WWW=		http://www.swftools.org/download.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/bison \
		??/flex \
		??/patch \
		??/zlib

RUN_DEPENDS=	??/fontconfig \
		??/freeglut \
		??/giflib \
		??/lame \
		??/libjpeg \
		??/t1lib


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
