PORTNAME=	hxd
DISTVERSION=	2.5.0.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Freeware Hex Editor and Disk Editor.
WWW=		https://mh-nexus.de/en/hxd/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/innoextract

RUN_DEPENDS=	??/wine-mono \
		??/wine_gecko \
		emulators/wine


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
