PORTNAME=	morbid
DISTVERSION=	0.8.7.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Twisted-based publish/subscribe messaging server that uses the STOMP protocol.
WWW=		https://pypi.org/project/morbid/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-distribute@${PY_FLAVOR}

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
