PORTNAME=	didier-stevens-suite
DISTVERSION=	436.dc97844
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Didier Stevens Suite.
WWW=		https://github.com/DidierStevens/DidierStevensSuite

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
