PORTNAME=	ciphertest
DISTVERSION=	22.e33eb4a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A better SSL cipher checker using gnutls.
WWW=		https://github.com/OpenSecurityResearch/ciphertest

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
