PORTNAME=	persistencesniper
DISTVERSION=	v1.17.1.r0.g13006aa
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Hunt persistences implanted in Windows machines.
WWW=		https://github.com/last-byte/PersistenceSniper

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
