PORTNAME=	isr-form
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Simple html parsing tool that extracts all form related information and generates reports of the data. Allows for quick analyzing of data.
WWW=		http://www.infobyte.com.ar/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-data-dump


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
