PORTNAME=	idswakeup
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A collection of tools that allows to test network intrusion detection systems.
WWW=		http://www.hsc.fr/ressources/outils/idswakeup/index.html.en

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libnet


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
