PORTNAME=	origami
DISTVERSION=	2.1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Aims at providing a scripting tool to generate and analyze malicious PDF files.
WWW=		https://github.com/gdelugre/origami

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/ruby-colorize \
		??/ruby-rdoc \
		??/rubygems \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
