PORTNAME=	xorsearch
DISTVERSION=	1.11.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Program to search for a given string in an XOR, ROL or ROT encoded binary file.
WWW=		http://blog.didierstevens.com/programs/xorsearch/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
