PORTNAME=	miranda-upnp
DISTVERSION=	1.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Python-based Universal Plug-N-Play client application designed to discover, query and interact with UPNP devices.
WWW=		https://code.google.com/archive/p/miranda-upnp/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
