PORTNAME=	trinity
DISTVERSION=	5200.294c4652
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Linux System call fuzzer.
WWW=		http://codemonkey.org.uk/projects/trinity/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
