PORTNAME=	sphinxbase
DISTVERSION=	5prealpha
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Common library for sphinx speech recognition.
WWW=		http://cmusphinx.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/bison \
		??/swig

RUN_DEPENDS=	??/lapack \
		??/libpulse \
		lang/python \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
