PORTNAME=	ssrf-sheriff
DISTVERSION=	8.02cd31d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple SSRF-testing sheriff written in Go.
WWW=		https://github.com/teknogeek/ssrf-sheriff

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
