PORTNAME=	hakrawler
DISTVERSION=	235.7615255
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Simple, fast web crawler designed for easy, quick discovery of endpoints and assets within a web application.
WWW=		https://github.com/hakluke/hakrawler

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
