PORTNAME=	dragon-backdoor
DISTVERSION=	7.c7416b7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A sniffing, non binding, reverse down/exec, portknocking service Based on cd00r.c.
WWW=		https://github.com/Shellntel/backdoors

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
