PORTNAME=	hashid
DISTVERSION=	397.7e8473a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Software to identify the different types of hashes used to encrypt data.
WWW=		https://github.com/psypanda/hashID

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
