PORTNAME=	lotophagi
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	a relatively compact Perl script designed to scan remote hosts for default (or common) Lotus NSF and BOX databases.
WWW=		http://packetstormsecurity.com/files/55250/lotophagi.rar.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-libwww


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
