PORTNAME=	smtptester
DISTVERSION=	13.634e1ee
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Small python3 tool to check common vulnerabilities in SMTP servers.
WWW=		https://github.com/xFreed0m/SMTPTester

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-colorlog@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
