PORTNAME=	shellcode-compiler
DISTVERSION=	26.8a25463
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Compiles C/C++ style code into a small, position-independent and NULL-free shellcode for Windows & Linux.
WWW=		https://github.com/NytroRST/ShellcodeCompiler

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
