PORTNAME=	openvas
DISTVERSION=	20250606
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Meta package for installing all OpenVAS components.
WWW=		https://www.blackarch.org/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
