PORTNAME=	honggfuzz
DISTVERSION=	4172.f0314885
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A general-purpose fuzzer with simple, command-line interface.
WWW=		https://code.google.com/p/honggfuzz/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/binutils \
		??/libunwind


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
