PORTNAME=	python-colorizer
DISTVERSION=	0.1.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Console colorizer, which acts like grep but paint each match in its own color.
WWW=		http://github.com/svetlyak40wt/colorizer/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
