PORTNAME=	qt5-webchannel
DISTVERSION=	5.15.18+kde+r3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Provides access to QObject or QML objects from HTML clients for seamless integration of Qt applications with HTML/JavaScript clients
WWW=		https://www.qt.io

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/qt5-declarative


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
