PORTNAME=	perl-net-ssl-expiredate
DISTVERSION=	1.21
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Obtain expiration date of certificate.
WWW=		https://metacpan.org/pod/Net::SSL::ExpireDate

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-class-accessor \
		??/perl-datetime \
		??/perl-time-duration-parse \
		??/perl-universal-require


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
