PORTNAME=	commonspeak
DISTVERSION=	46.ba24110
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Leverages publicly available datasets from Google BigQuery to generate wordlists.
WWW=		https://github.com/assetnote/commonspeak2

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/go-pie \
		??/golang-glide \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
