PORTNAME=	dirbuster
DISTVERSION=	1.0.RC1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An application designed to brute force directories and files names on web/application servers
WWW=		http://www.owasp.org/index.php/Category:OWASP_DirBuster_Project

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
