PORTNAME=	dracnmap
DISTVERSION=	69.09d3945
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool to exploit the network and gathering information with nmap help.
WWW=		https://github.com/screetsec/Dracnmap

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/firefox \
		??/nano \
		??/xterm \
		security/nmap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
