PORTNAME=	xed-intel
DISTVERSION=	1141.95ca7183
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	X86 encoder decoder.
WWW=		https://github.com/intelxed/xed

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/python



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
