PORTNAME=	wmbusmeters
DISTVERSION=	1.17.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Read the wired or wireless mbus protocol to acquire utility meter readings.
WWW=		https://github.com/wmbusmeters/wmbusmeters

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libxml2 \
		??/rtl-sdr


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
