PORTNAME=	sleuthkit-java
DISTVERSION=	4.14.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Java dependencies for The Sleuth Kit.
WWW=		https://github.com/sleuthkit/sleuthkit/releases/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/ant \
		??/java-environment

RUN_DEPENDS=	??/java-runtime \
		??/sleuthkit


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
