PORTNAME=	prometheus-firewall
DISTVERSION=	176.a316d66
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Firewall analyzer written in ruby
WWW=		https://github.com/averagesecurityguy/prometheus

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
