PORTNAME=	blackarch-artwork
DISTVERSION=	80.fc42f1e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Artwork for BlackArch Linux.
WWW=		https://github.com/BlackArch/blackarch-artwork

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
