PORTNAME=	rmiscout
DISTVERSION=	1.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Enumerate Java RMI functions and exploit RMI parameter unmarshalling vulnerabilities.
WWW=		https://github.com/BishopFox/rmiscout

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/jre8-openjdk-headless


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
