PORTNAME=	snitch
DISTVERSION=	1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Turn back the asterisks in password fields to plaintext passwords.
WWW=		http://ntsecurity.nu/toolbox/snitch/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
