PORTNAME=	katana-pd
DISTVERSION=	v1.2.2.r103.g30123f5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Crawling and spidering framework.
WWW=		https://github.com/projectdiscovery/katana

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
