PORTNAME=	bss
DISTVERSION=	0.8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Bluetooth stack smasher / fuzzer.
WWW=		http://www.secuobs.com/news/15022006-bss_0_8.shtml

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-pycurl@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
