PORTNAME=	python-gitignore-parser
DISTVERSION=	v0.1.12.r1.g1db5f1b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A spec-compliant gitignore parser for Python 3.5+
WWW=		https://github.com/mherrmann/gitignore_parser

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
