PORTNAME=	sfuzz
DISTVERSION=	200.e1b62bd
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple fuzzer.
WWW=		http://aconole.brad-x.com/programs/sfuzz.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
