PORTNAME=	ftp-fuzz
DISTVERSION=	1337
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The master of all master fuzzing scripts specifically targeted towards FTP server software.
WWW=		http://nullsecurity.net/tools/fuzzer.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
