PORTNAME=	owasp-zsc
DISTVERSION=	316.f763dea
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Shellcode/Obfuscate Code Generator.
WWW=		https://github.com/zscproject/OWASP-ZSC

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
