PORTNAME=	interrogate
DISTVERSION=	5.eb5f071
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A proof-of-concept tool for identification of cryptographic keys in
WWW=		https://github.com/carmaa/interrogate

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
