PORTNAME=	asleap
DISTVERSION=	2.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Actively recover LEAP/PPTP passwords.
WWW=		https://www.willhackforsushi.com/?page_id=41

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
