PORTNAME=	libemu
DISTVERSION=	584.bf443cb
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A small library written in c offering basic x86 emulation and shellcode detection.
WWW=		http://libemu.carnivore.it/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
