PORTNAME=	apkstudio
DISTVERSION=	v6.3.0.r0.gc6e2724
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An IDE for decompiling/editing & then recompiling of android application binaries.
WWW=		http://www.vaibhavpandey.com/apkstudio/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/qt5-tools \
		??/vulkan-headers \
		archivers/unzip \
		devel/git

RUN_DEPENDS=	??/android-apktool \
		??/android-tools \
		??/qt6-base


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
