PORTNAME=	ppee
DISTVERSION=	1.12
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Professional PE file Explorer for reversers, malware researchers and those who want to statically inspect PE files in more details.
WWW=		https://www.mzrst.com/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
