PORTNAME=	pdfresurrect
DISTVERSION=	0.12
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool aimed at analyzing PDF documents.
WWW=		http://packetstormsecurity.com/files/118459/PDFResurrect-PDF-Analyzer-0.12.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gzip



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
