PORTNAME=	blueranger
DISTVERSION=	1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple Bash script which uses Link Quality to locate Bluetooth device radios.
WWW=		https://www.hackfromacave.com/projects/blueranger.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
