PORTNAME=	python2-couchdb
DISTVERSION=	1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python library for working with CouchDB.
WWW=		https://github.com/djc/couchdb-python/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
