PORTNAME=	mkbrutus
DISTVERSION=	27.ddd5f8e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Password bruteforcer for MikroTik devices or boxes running RouterOS.
WWW=		http://mkbrutusproject.github.io/MKBRUTUS/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
