PORTNAME=	invoke-dosfuscation
DISTVERSION=	7.6260f5b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Cmd.exe Command Obfuscation Generator & Detection Test Harness.
WWW=		https://github.com/danielbohannon/Invoke-DOSfuscation

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
