PORTNAME=	python-bintrees
DISTVERSION=	2.2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Package provides Binary-, RedBlack- and AVL-Trees.
WWW=		https://github.com/mozman/bintrees

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cython0 \
		??/py-build@${PY_FLAVOR} \
		??/py-installer@${PY_FLAVOR} \
		??/py-wheel@${PY_FLAVOR} \
		devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
