PORTNAME=	openrisk
DISTVERSION=	v0.0.1.r29.g5bbee19
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Generates a risk score based on the results of a Nuclei scan using OpenAIs GPT-3 model.
WWW=		https://github.com/projectdiscovery/openrisk

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
