PORTNAME=	perl-http-dav
DISTVERSION=	0.49
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A client module for the WebDAV protocol.
WWW=		http://search.cpan.org/dist/HTTP-DAV

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl-libwww \
		??/perl-uri \
		??/perl-xml-dom


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
