PORTNAME=	xray
DISTVERSION=	109.7e8cc67
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool for recon, mapping and OSINT gathering from public networks.
WWW=		https://github.com/evilsocket/xray

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/go-pie \
		??/golang-glide \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
