PORTNAME=	graphw00f
DISTVERSION=	1.2.1.r2.gb4096a8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	GraphQL endpoint detection and engine fingerprinting.
WWW=		https://github.com/dolevf/graphw00f

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
