PORTNAME=	barmie
DISTVERSION=	1.01
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Java RMI enumeration and attack tool.
WWW=		https://github.com/NickstaDB/BaRMIe

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
