PORTNAME=	dotpeek
DISTVERSION=	2021.3.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Free .NET Decompiler and Assembly Browser.
WWW=		https://www.jetbrains.com/decompiler/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
