PORTNAME=	nsoq
DISTVERSION=	1.9.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Network Security Tool for packet manipulation that allows a large number of options.
WWW=		https://github.com/FelipeEcker/nsoq/tags

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
