PORTNAME=	rsmangler
DISTVERSION=	1.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	rsmangler takes a wordlist and mangle it
WWW=		http://www.randomstorm.com/rsmangler-security-tool.php

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
