PORTNAME=	python2-openpyxl
DISTVERSION=	2.6.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Python library to read/write Excel 2007 xlsx/xlsm files.
WWW=		https://pypi.org/project/openpyxl/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	??/py-et-xmlfile@${PY_FLAVOR} \
		??/py-jdcal@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
