PORTNAME=	portmanteau
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An experimental unix driver IOCTL security tool that is useful for fuzzing and discovering device driver attack surface.
WWW=		https://packetstormsecurity.com/files/134230/Portmanteau-Unix-Driver-IOCTL-Security-Tool.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/sqlite \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
