PORTNAME=	obevilion
DISTVERSION=	409.29fbe9d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Another archive cracker created in python, cracking [zip/7z/rar].
WWW=		https://github.com/BL4CKvGHOST/Ob3vil1on

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/p7zip \
		??/py-colorama@${PY_FLAVOR} \
		??/py-pyqt4@${PY_FLAVOR} \
		??/tk \
		??/unrar \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
