PORTNAME=	pass-station
DISTVERSION=	v3.0.0.r1.gb9e4739
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	CLI & library to search for default credentials among thousands of Products / Vendors.
WWW=		https://noraj.github.io/pass-station/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/ruby-docopt \
		??/ruby-paint \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
