PORTNAME=	graphql-path-enum
DISTVERSION=	23.5450280
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool that lists the different ways of reaching a given type in a GraphQL schema.
WWW=		https://gitlab.com/dee-see/graphql-path-enum

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/cargo \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
