PORTNAME=	gr-dect2
DISTVERSION=	39.0d973fe
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Real-time DECT voice channel decoding by Gnuradio.
WWW=		https://github.com/pavelyazev/gr-dect2

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/boost \
		??/boost-libs \
		??/cmake \
		??/doxygen \
		??/pybind11 \
		??/swig \
		devel/git

RUN_DEPENDS=	??/gnuradio \
		??/gnuradio-osmosdr \
		??/hackrf


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
