PORTNAME=	python-pyric
DISTVERSION=	184.bc0dce3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python Radio Interface Controller Linux wireless library for the Python Wireless Developer and Pentester.
WWW=		https://pypi.org/project/pyric/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
