PORTNAME=	tekdefense-automater
DISTVERSION=	88.42548cf
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	IP URL and MD5 OSINT Analysis
WWW=		https://github.com/1aN0rmus/TekDefense-Automater

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
