PORTNAME=	hacktv
DISTVERSION=	543.80d98ea
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Analogue TV transmitter for the HackRF.
WWW=		

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/ffmpeg \
		??/hackrf \
		??/soapysdr


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
