PORTNAME=	networkminer
DISTVERSION=	3.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Network Forensic Analysis Tool for advanced Network Traffic Analysis, sniffer and packet analyzer.
WWW=		http://www.netresec.com/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/mono \
		??/xterm


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
