PORTNAME=	thedorkbox
DISTVERSION=	7.43852d3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Comprehensive collection of Google Dorks & OSINT techniques to find Confidential Data.
WWW=		https://github.com/cybersafeblr/thedorkbox

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/php82


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
