PORTNAME=	subover
DISTVERSION=	71.3d258e2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Powerful Subdomain Takeover Tool.
WWW=		https://github.com/Ice3man543/SubOver

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
