PORTNAME=	powerops
DISTVERSION=	32.13fe55b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	PowerShell Runspace Portable Post Exploitation Tool aimed at making Penetration Testing with PowerShell easier.
WWW=		https://github.com/fdiskyou/PowerOPS

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
