PORTNAME=	findsploit
DISTVERSION=	87.3e61d8d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Find exploits in local and online databases instantly.
WWW=		https://github.com/1N3/findsploit

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/exploitdb \
		??/firefox \
		??/metasploit \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
