PORTNAME=	wssip
DISTVERSION=	75.56d0d2c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Application for capturing, modifying and sending custom WebSocket data from client to server and vice versa.
WWW=		https://github.com/nccgroup/wssip

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/libxtst \
		devel/git \
		lang/python \
		lang/python3 \
		www/npm

RUN_DEPENDS=	??/coffee-script \
		www/node


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
