PORTNAME=	webanalyze
DISTVERSION=	121.707f3a4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Port of Wappalyzer (uncovers technologies used on websites) in go to automate scanning.
WWW=		https://github.com/rverton/webanalyze

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
