PORTNAME=	hyde
DISTVERSION=	16.0931514
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Just another tool in C to do DDoS (with spoofing).
WWW=		https://github.com/CoolerVoid/Hyde

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
