PORTNAME=	python2-python-geoip-geolite2
DISTVERSION=	2015.0303
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Provides access to the geolite2 database.
WWW=		https://pypi.org/project/python-geoip-geolite2/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
