PORTNAME=	sslscan2
DISTVERSION=	763.c56018e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tests SSL/TLS enabled services to discover supported cipher suites.
WWW=		https://github.com/rbsec/sslscan

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
