PORTNAME=	setowner
DISTVERSION=	1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Allows you to set file ownership to any account, as long as you have the Restore files and directories user right.
WWW=		https://vidstromlabs.com/freetools/setowner/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
