PORTNAME=	rootbrute
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Local root account bruteforcer.
WWW=		http://www.packetstormsecurity.org/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-pexpect@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
