PORTNAME=	zxing
DISTVERSION=	3.4.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Multi-format 1D/2D barcode image processing library (C++ version).
WWW=		https://github.com/zxing/zxing/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/scons

RUN_DEPENDS=	??/imagemagick


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
