PORTNAME=	dpkt-svn
DISTVERSION=	82
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fast, simple packet creation / parsing module for python, with definitions for the basic TCP/IP protocols.
WWW=		http://code.google.com/p/dpkt/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/subversion

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
