PORTNAME=	tcpcopy
DISTVERSION=	1285.929511d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A TCP stream replay tool to support real testing of Internet server applications.
WWW=		https://github.com/session-replay-tools/tcpcopy

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
