PORTNAME=	python2-functools32
DISTVERSION=	3.2.3.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Backport of the functools module from Python 3.2.3 for use on 2.7 and PyPy.
WWW=		https://pypi.org/project/functools32/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
