PORTNAME=	graudit
DISTVERSION=	726.7d19c1a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Grep rough source code auditing tool.
WWW=		https://github.com/wireghoul/graudit

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
