PORTNAME=	passdetective
DISTVERSION=	1.0.6.r4.g458f12e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Scans shell command history to detect mistakenly written passwords, API keys, and secrets.
WWW=		https://github.com/aydinnyunus/PassDetective

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
