PORTNAME=	ppscan
DISTVERSION=	0.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Yet another port scanner with HTTP and FTP tunneling support.
WWW=		https://packetstormsecurity.com/files/82897/PPScan-Portscanner-0.3.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
