PORTNAME=	jondo
DISTVERSION=	00.20.001
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Redirects internet traffic trough a mix of proxy servers to hide the origin of the requests.
WWW=		https://anonymous-proxy-servers.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
