PORTNAME=	goop-dump
DISTVERSION=	74.5865759
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool to dump a git repository from a website, focused on as-complete-as-possible dumps and handling weird edge-cases.
WWW=		https://github.com/nyancrimew/goop

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
