PORTNAME=	python-http-tools
DISTVERSION=	6.0.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	httptools helps you to capture, repeat and live intercept HTTP requests. It is built on top of [mitmproxy].
WWW=		https://pypi.org/project/http-tools/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	??/mitmproxy \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
