PORTNAME=	dnsobserver
DISTVERSION=	5.f331482
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A handy DNS service written in Go to aid in the detection of several types of blind vulnerabilities.
WWW=		https://github.com/allyomalley/dnsobserver

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
