PORTNAME=	stowaway
DISTVERSION=	v2.2.r42.gc22010f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Multi-hop proxy tool for security researchers and pentesters.
WWW=		https://github.com/ph4ntonn/Stowaway

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
