PORTNAME=	perl-net-ssh2
DISTVERSION=	0.72
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Support for the SSH 2 protocol via libssh2.
WWW=		https://metacpan.org/release/Net-SSH2

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libssh2 \
		??/perl \
		??/zlib \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
