PORTNAME=	prowler
DISTVERSION=	7609.ecc8eaf366
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool for AWS security assessment, auditing and hardening.
WWW=		https://github.com/alfresco/prowler

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/aws-cli \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
