PORTNAME=	chw00t
DISTVERSION=	39.1fd1016
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Unices chroot breaking tool.
WWW=		https://github.com/earthquake/chw00t

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
