PORTNAME=	lunar
DISTVERSION=	1089.f31c4c4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A UNIX security auditing tool based on several security frameworks.
WWW=		https://github.com/lateralblast/lunar

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/bc \
		??/netkit-bsd-finger \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
