PORTNAME=	pydictor
DISTVERSION=	100.4a77f0a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A useful hacker dictionary builder for a brute-force attack.
WWW=		https://github.com/LandGrey/pydictor

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
