PORTNAME=	johnny
DISTVERSION=	20120424
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	GUI for John the Ripper.
WWW=		http://openwall.info/wiki/john/johnny

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/john \
		??/qt4


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
