PORTNAME=	dmde
DISTVERSION=	4.2.2.816
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Disk Editor and Data Recovery Software.
WWW=		https://dmde.com/download.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gtk2


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
