PORTNAME=	rp
DISTVERSION=	170.0b39cac
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A full-cpp written tool that aims to find ROP sequences in PE/Elf/Mach-O x86/x64 binaries.
WWW=		https://github.com/0vercl0k/rp

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
