PORTNAME=	syringe
DISTVERSION=	12.79a703e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A General Purpose DLL & Code Injection Utility.
WWW=		https://github.com/securestate/syringe

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
