PORTNAME=	fuzzdb
DISTVERSION=	475.5656ab2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Attack and Discovery Pattern Dictionary for Application Fault Injection Testing.
WWW=		https://github.com/fuzzdb-project/fuzzdb

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
