PORTNAME=	parse-evtx
DISTVERSION=	3.a4b02b9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool to parse the Windows XML Event Log (EVTX) format.
WWW=		https://github.com/KasperskyLab/ForensicsTools

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
