PORTNAME=	python2-poppler-qt4
DISTVERSION=	0.24.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Python 2 binding to poppler-qt.
WWW=		https://github.com/wbsoft/python-poppler-qt4

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/poppler-qt4 \
		??/py-pyqt4@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
