PORTNAME=	libpjf
DISTVERSION=	204.a6fb2f5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A C library of data structures with tools (based on libasn).
WWW=		https://github.com/pforemski/libpjf

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/pcre


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
