PORTNAME=	trufflehog
DISTVERSION=	v3.93.1.r1.ge9734c1ff
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Searches through git repositories for high entropy strings, digging deep into commit history.
WWW=		https://github.com/dxa4481/truffleHog

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
