PORTNAME=	skipfish
DISTVERSION=	2.10b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A fully automated, active web application security reconnaissance tool.
WWW=		http://code.google.com/p/skipfish/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libidn \
		??/libidn11 \
		??/openssl-1.0


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
