PORTNAME=	recstudio
DISTVERSION=	4.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Cross platform interactive decompiler.
WWW=		http://www.backerstreet.com/rec/recdload.htm

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gtk2


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
