PORTNAME=	morxcoinpwn
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Mass Bitcoin private keys brute forcing/Take over tool released.
WWW=		http://www.morxploit.com/tools/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/bitcoin-daemon \
		??/morxkeyfmt \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
