PORTNAME=	bad-pdf
DISTVERSION=	v1.1.r31.g4b42f66
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Steal NTLM Hashes with Bad-PDF.
WWW=		https://github.com/deepzec/Bad-Pdf

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/responder \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
