PORTNAME=	libjodycode
DISTVERSION=	3.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Shared code used by several utilities written by Jody Bruchon.
WWW=		https://github.com/jbruchon/libjodycode

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
