PORTNAME=	yawast
DISTVERSION=	0.12.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The YAWAST Antecedent Web Application Security Toolkit.
WWW=		https://pypi.org/project/yawast-ng/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-build@${PY_FLAVOR} \
		devel/py-pip@${PY_FLAVOR}

RUN_DEPENDS=	??/py-appdirs@${PY_FLAVOR} \
		??/py-asn1crypto@${PY_FLAVOR} \
		??/py-attrs@${PY_FLAVOR} \
		??/py-beautifulsoup4@${PY_FLAVOR} \
		??/py-cached-property@${PY_FLAVOR} \
		??/py-cerberus@${PY_FLAVOR} \
		??/py-certifi@${PY_FLAVOR} \
		??/py-cffi@${PY_FLAVOR} \
		??/py-chardet@${PY_FLAVOR} \
		??/py-colorama@${PY_FLAVOR} \
		??/py-cryptography@${PY_FLAVOR} \
		??/py-dateutil@${PY_FLAVOR} \
		??/py-distlib@${PY_FLAVOR} \
		??/py-dnspython@${PY_FLAVOR} \
		??/py-first@${PY_FLAVOR} \
		??/py-idna@${PY_FLAVOR} \
		??/py-importlib-metadata@${PY_FLAVOR} \
		??/py-jsonschema@${PY_FLAVOR} \
		??/py-more-itertools@${PY_FLAVOR} \
		??/py-nassl@${PY_FLAVOR} \
		??/py-ordered-set@${PY_FLAVOR} \
		??/py-orderedmultidict@${PY_FLAVOR} \
		??/py-packaging@${PY_FLAVOR} \
		??/py-pep517@${PY_FLAVOR} \
		??/py-pip-shims@${PY_FLAVOR} \
		??/py-plette@${PY_FLAVOR} \
		??/py-psutil@${PY_FLAVOR} \
		??/py-publicsuffixlist@${PY_FLAVOR} \
		??/py-pycparser@${PY_FLAVOR} \
		??/py-pyparsing@${PY_FLAVOR} \
		??/py-requests-mock@${PY_FLAVOR} \
		??/py-requirementslib@${PY_FLAVOR} \
		??/py-selenium@${PY_FLAVOR} \
		??/py-soupsieve@${PY_FLAVOR} \
		??/py-tls-parser@${PY_FLAVOR} \
		??/py-toml@${PY_FLAVOR} \
		??/py-tomlkit@${PY_FLAVOR} \
		??/py-urllib3@${PY_FLAVOR} \
		??/py-validator-collection@${PY_FLAVOR} \
		??/py-vistir@${PY_FLAVOR} \
		??/py-webdriver-manager@${PY_FLAVOR} \
		??/py-wheel@${PY_FLAVOR} \
		??/py-zipp@${PY_FLAVOR} \
		??/sslyze \
		devel/py-six@${PY_FLAVOR} \
		lang/python \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
