PORTNAME=	perl-net-write-fast
DISTVERSION=	0.18
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Create and inject packets fast.
WWW=		https://metacpan.org/pod/Net::Write::Fast

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl-time-interval


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
