PORTNAME=	xprobe2
DISTVERSION=	0.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An active OS fingerprinting tool.
WWW=		http://sourceforge.net/apps/mediawiki/xprobe/index.php?title=Main_Page

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gcc \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
