PORTNAME=	donut
DISTVERSION=	529.47758d7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Generates x86, x64 or AMD64+x86 P.I. shellcode loading .NET Assemblies from memory.
WWW=		https://github.com/TheWover/donut

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gcc \
		??/make \
		devel/git \
		devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
