PORTNAME=	hashfind
DISTVERSION=	8.e9a9a14
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool to search files for matching password hash types and other interesting data.
WWW=		https://github.com/rurapenthe/hashfind

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
