PORTNAME=	sqid
DISTVERSION=	0.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A SQL injection digger.
WWW=		http://sqid.rubyforge.org/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
