PORTNAME=	perl-exporter-lite
DISTVERSION=	0.08
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Lightweight exporting of variables.
WWW=		https://metacpan.org/pod/Exporter::Lite

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
