PORTNAME=	gdir.pl
DISTVERSION=	9.d2cc05d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl wrapper on gcrypt for directory encryption/decryption.
WWW=		https://gitlab.com/GasparVardanyan/gdir.pl

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/gcrypt \
		??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
