PORTNAME=	drinkme
DISTVERSION=	19.acf1a14
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A shellcode testing harness.
WWW=		https://github.com/emptymonkey/drinkme

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
