PORTNAME=	cpp2il
DISTVERSION=	2022.1.0.pre.release.20.r22.g774a8b9c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool to reverse unitys IL2PP toolchain
WWW=		https://github.com/SamboyCoding/Cpp2IL

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/dotnet-host \
		??/dotnet-sdk \
		devel/git

RUN_DEPENDS=	??/dotnet-runtime-6.0


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
