PORTNAME=	storm-ring
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This simple tool is useful to test a PABX with allow guest parameter set to yes (in this scenario an anonymous caller could place a call).
WWW=		http://packetstormsecurity.com/files/115852/Storm-Ringing-PABX-Test-Tool.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
