PORTNAME=	python2-olefile
DISTVERSION=	0.46
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python package to parse, read and write Microsoft OLE2 files (Structured Storage or Compound Document, Microsoft Office).
WWW=		https://pypi.org/project/olefile/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
