PORTNAME=	jeb-intel
DISTVERSION=	3.0.3.201809240610
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Intel decompiler.
WWW=		https://www.pnfsoftware.com/jeb/intel

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment \
		??/java-runtime-common


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
