PORTNAME=	girsh
DISTVERSION=	v0.41.r0.gfc5b44e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Automatically spawn a reverse shell fully interactive for Linux or Windows victim.
WWW=		https://github.com/nodauf/Girsh

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
