PORTNAME=	neo-regeorg
DISTVERSION=	v5.3.0.r0.gb2dcba9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Improved version of reGeorg, HTTP tunneling pivot tool
WWW=		https://github.com/L-codes/Neo-reGeorg

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
