PORTNAME=	jbrute
DISTVERSION=	0.99
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Open Source Security tool to audit hashed passwords.
WWW=		http://sourceforge.net/projects/jbrute/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
