PORTNAME=	thc-smartbrute
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This tool finds undocumented and secret commands implemented in a smartcard.
WWW=		https://www.thc.org/thc-smartbrute/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/pcsclite


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
