PORTNAME=	python2-ordereddict
DISTVERSION=	1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A drop-in substitute for Python 2.7s collections.OrderedDict that works in Python 2.4-2.6.
WWW=		https://pypi.org/project/ordereddict/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
