PORTNAME=	paru
DISTVERSION=	2.0.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Feature packed AUR helper.
WWW=		https://github.com/morganamilo/paru

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/cargo \
		lang/rust

RUN_DEPENDS=	??/pacman \
		devel/git


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
