PORTNAME=	gatecrasher
DISTVERSION=	2.3ad5225
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Network auditing and analysis tool developed in Python.
WWW=		https://github.com/michaeltelford/gatecrasher

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
