PORTNAME=	redfang
DISTVERSION=	2.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Finds non-discoverable Bluetooth devices by brute-forcing the last six bytes of the devices Bluetooth addresses and calling read_remote_name().
WWW=		http://packetstormsecurity.com/files/31864/redfang.2.5.tar.gz.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gcc

RUN_DEPENDS=	??/bluez-libs


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
