PORTNAME=	vscan
DISTVERSION=	10.da4e47e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	HTTPS / Vulnerability scanner.
WWW=		https://github.com/pasjtene/Vscan

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/apache-ant \
		devel/git

RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
