PORTNAME=	winexe
DISTVERSION=	1.00
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Remotely execute commands on Windows NT/2000/XP/2003 systems.
WWW=		http://sourceforge.net/projects/winexe/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	lang/python3

RUN_DEPENDS=	??/gnutls \
		??/libsasl \
		??/popt \
		??/talloc \
		??/tdb


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
