PORTNAME=	ghauri
DISTVERSION=	1.4.3.r0.g18e3677
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An advanced cross-platform tool that automates the process of detecting and exploiting SQL injection security flaws.
WWW=		https://github.com/r0oth3x49/ghauri

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		devel/py-pip@${PY_FLAVOR} \
		devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
