PORTNAME=	etherflood
DISTVERSION=	1.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Floods a switched network with Ethernet frames with random hardware addresses.
WWW=		http://ntsecurity.nu/toolbox/etherflood/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
