PORTNAME=	fakemail
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Fake mail server that captures e-mails as files for acceptance testing.
WWW=		http://sourceforge.net/projects/fakemail/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
