PORTNAME=	fl0p
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A passive L7 flow fingerprinter that examines TCP/UDP/ICMP packet sequences, can peek into cryptographic tunnels, can tell human beings and robots apart, and performs a couple of other infosec-related tricks.
WWW=		http://lcamtuf.coredump.cx/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gzip

RUN_DEPENDS=	net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
