PORTNAME=	ghostpack
DISTVERSION=	123.20a5f0a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Compiled Binaries for Ghostpack (.NET v4.8.1).
WWW=		https://github.com/r3motecontrol/Ghostpack-CompiledBinaries

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
