PORTNAME=	gksu
DISTVERSION=	2.0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A graphical frontend for su.
WWW=		https://people.debian.org/~kov/gksu/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gtk-doc \
		??/intltool

RUN_DEPENDS=	??/libgksu \
		??/xorg-xauth


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
