PORTNAME=	morxbrute
DISTVERSION=	1.01
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A customizable HTTP dictionary-based password cracking tool written in Perl.
WWW=		http://www.morxploit.com/morxbrute/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
