PORTNAME=	metasploit-autopwn
DISTVERSION=	12.09320cc
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	db_autopwn plugin of metasploit.
WWW=		https://github.com/hahwul/metasploit-autopwn

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/metasploit


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
