PORTNAME=	densityscout
DISTVERSION=	45
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Calculates density for files of any file-system-path to finally output an accordingly descending ordered list.
WWW=		https://www.cert.at/en/downloads/software/software-densityscout

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
