PORTNAME=	darkd0rk3r
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python script that performs dork searching and searches for local file inclusion and SQL injection errors.
WWW=		http://packetstormsecurity.com/files/117403/Dark-D0rk3r-1.0.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
