PORTNAME=	lfisuite
DISTVERSION=	85.470e01f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Totally Automatic LFI Exploiter (+ Reverse Shell) and Scanner.
WWW=		https://github.com/D35m0nd142/LFISuite

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
