PORTNAME=	network-app-stress-tester
DISTVERSION=	19.df75391
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Network Application Stress Testing Yammer.
WWW=		https://github.com/PherricOxide/Network-App-Stress-Tester

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
