PORTNAME=	cisco-snmp-enumeration
DISTVERSION=	10.ad06f57
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Automated Cisco SNMP Enumeration, Brute Force, Configuration Download and Password Cracking.
WWW=		https://github.com/nccgroup/cisco-snmp-enumeration

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/john \
		??/metasploit \
		??/net-snmp \
		??/screen \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
