PORTNAME=	libparistraceroute
DISTVERSION=	383.9588da5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A library written in C dedicated to active network measurements with examples, such as paris-ping and paris-traceroute.
WWW=		https://github.com/libparistraceroute/libparistraceroute

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/autoconf \
		??/automake \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
