PORTNAME=	bridge-utils
DISTVERSION=	1.7.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Utilities for configuring the Linux ethernet bridge.
WWW=		https://wiki.linuxfoundation.org/networking/bridge

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
