PORTNAME=	t1lib
DISTVERSION=	5.1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Library for generating character- and string-glyphs from Adobe Type 1 fonts.
WWW=		https://www.ibiblio.org/pub/Linux/libs/graphics/!INDEX.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libx11 \
		??/libxaw \
		??/libxt


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
