PORTNAME=	python-pytorctl
DISTVERSION=	2013.10.16.4.gc8fcb25
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Python Tor controller with extensions to support path building and various constraints on node and path selection, as well as statistics gathering.
WWW=		http://fscked.org/projects/torctl

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
