PORTNAME=	netz
DISTVERSION=	v0.1.0.r8.g3754e56
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Discover internet-wide misconfigurations while drinking coffee.
WWW=		https://github.com/spectralops/netz

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
