PORTNAME=	gitrob
DISTVERSION=	7.7be4c53
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Reconnaissance tool for GitHub organizations.
WWW=		http://michenriksen.com/blog/gitrob-putting-the-open-source-in-osint/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/go-pie \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
