PORTNAME=	pwndrop
DISTVERSION=	18.385ba70
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Self-deployable file hosting service for red teamers, allowing to easily upload and share payloads over HTTP and WebDAV.
WWW=		https://github.com/kgretzky/pwndrop

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
