PORTNAME=	httprobe
DISTVERSION=	24.0745f64
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Take a list of domains and probe for working HTTP and HTTPS servers
WWW=		https://github.com/tomnomnom/httprobe

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
