PORTNAME=	tlsx
DISTVERSION=	v1.2.2.r2.gd13b67f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	TLS grabber focused on TLS based data collection.
WWW=		https://github.com/projectdiscovery/tlsx

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
