PORTNAME=	csdr
DISTVERSION=	0.18.2.r68.g1f15b8c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple DSP library and command-line tool for Software Defined Radio.
WWW=		https://github.com/jketterl/csdr

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git

RUN_DEPENDS=	??/fftw \
		??/libsamplerate


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
