PORTNAME=	cmseek
DISTVERSION=	382.20f9780
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	CMS (Content Management Systems) Detection and Exploitation suite.
WWW=		https://github.com/Tuhinshubhra/CMSeeK

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
