PORTNAME=	python-pyexcel-text
DISTVERSION=	0.2.7.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A plugin to pyexcel and provides the capability to present and write data in text formats.
WWW=		https://pypi.org/project/pyexcel-text/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	??/py-pyexcel@${PY_FLAVOR} \
		??/py-tabulate@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
