PORTNAME=	atlas
DISTVERSION=	7.77bd6c8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Open source tool that can suggest sqlmap tampers to bypass WAF/IDS/IPS.
WWW=		https://github.com/m4ll0k/Atlas

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-humanfriendly@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
