PORTNAME=	rtl-wmbus
DISTVERSION=	d2be82c.r25.g34684e6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Software defined receiver for wireless M-Bus with RTL-SDR.
WWW=		https://github.com/xaelsouth/rtl-wmbus

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gcc \
		devel/git

RUN_DEPENDS=	??/rtl-sdr


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
