PORTNAME=	python2-hpfeeds
DISTVERSION=	414.34bf4d4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Honeynet Project generic authenticated datafeed protocol.
WWW=		https://github.com/rep/hpfeeds

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
