PORTNAME=	crackmapexec
DISTVERSION=	v6.0.1.r198.gda472cb
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A swiss army knife for pentesting Windows/Active Directory environments.
WWW=		https://github.com/byt3bl33d3r/CrackMapExec

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/netexec


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
