PORTNAME=	directorytraversalscan
DISTVERSION=	1.0.1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Detect directory traversal vulnerabilities in HTTP servers and web applications.
WWW=		http://sourceforge.net/projects/httpdirscan/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
