PORTNAME=	ffm
DISTVERSION=	129.6337eaf
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A hacking harness that you can use during the post-exploitation phase of a red-teaming engagement.
WWW=		https://github.com/JusticeRage/FFM

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-tqdm@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
