PORTNAME=	powercloud
DISTVERSION=	21.0928303
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Deliver powershell payloads via DNS TXT via CloudFlare using PowerShell.
WWW=		https://github.com/mantvydasb/Invoke-PowerCloud

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
