PORTNAME=	dump1090
DISTVERSION=	386.bff92c4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple Mode S decoder for RTLSDR devices.
WWW=		https://github.com/MalcolmRobb/dump1090

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/rtl-sdr


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
