PORTNAME=	proxify
DISTVERSION=	904.cb35116
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Swiss Army knife Proxy tool for HTTP/HTTPS traffic capture, manipulation, and replay on the go.
WWW=		https://github.com/projectdiscovery/proxify

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
