PORTNAME=	mptcp
DISTVERSION=	1.9.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool for manipulation of raw packets that allows a large number of options.
WWW=		http://packetstormsecurity.com/files/119132/Mptcp-Packet-Manipulator-1.9.0.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
