PORTNAME=	fred
DISTVERSION=	0.2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Cross-platform M$ registry hive editor.
WWW=		https://www.pinguin.lu/fred

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/hivex \
		??/qt4 \
		??/qtwebkit

RUN_DEPENDS=	??/hivex \
		??/qt4 \
		??/qtwebkit


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
