PORTNAME=	imagejs
DISTVERSION=	56.a442f94
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Small tool to package javascript into a valid image file.
WWW=		https://github.com/jklmnn/imagejs

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
