PORTNAME=	halcyon
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A repository crawler that runs checksums for static files found within a given git repository.
WWW=		https://www.blackhatlibrary.net/Halcyon

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	devel/git \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
