PORTNAME=	blackarch-config-zsh
DISTVERSION=	12.1ee1abb
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	BlackArch config for the zsh shell.
WWW=		https://github.com/BlackArch/blackarch-config-zsh

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/zsh


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
