PORTNAME=	gtalk-decode
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Google Talk decoder tool that demonstrates recovering passwords from accounts.
WWW=		http://packetstormsecurity.com/files/119154/Google-Talk-Decoder.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	archivers/unzip



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
