PORTNAME=	python-chepy
DISTVERSION=	7.5.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Chepy is python lib/cli equivalent of the awesome CyberChef tool.
WWW=		https://pypi.org/project/chepy/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	??/exrex \
		??/py-base58@${PY_FLAVOR} \
		??/py-colorama@${PY_FLAVOR} \
		??/py-crccheck@${PY_FLAVOR} \
		??/py-decorator@${PY_FLAVOR} \
		??/py-docstring-parser@${PY_FLAVOR} \
		??/py-editor@${PY_FLAVOR} \
		??/py-emoji@${PY_FLAVOR} \
		??/py-fire@${PY_FLAVOR} \
		??/py-hashid@${PY_FLAVOR} \
		??/py-hexdump@${PY_FLAVOR} \
		??/py-jsonpath-rw@${PY_FLAVOR} \
		??/py-jsonpickle@${PY_FLAVOR} \
		??/py-lazy-import@${PY_FLAVOR} \
		??/py-parsel@${PY_FLAVOR} \
		??/py-phpserialize@${PY_FLAVOR} \
		??/py-pillow@${PY_FLAVOR} \
		??/py-prompt_toolkit@${PY_FLAVOR} \
		??/py-pyaml@${PY_FLAVOR} \
		??/py-pycipher@${PY_FLAVOR} \
		??/py-pycryptodome@${PY_FLAVOR} \
		??/py-pydash@${PY_FLAVOR} \
		??/py-pyjwt@${PY_FLAVOR} \
		??/py-pyopenssl@${PY_FLAVOR} \
		??/py-pyperclip@${PY_FLAVOR} \
		??/py-regex@${PY_FLAVOR} \
		??/py-termcolor@${PY_FLAVOR} \
		??/py-typing_extensions@${PY_FLAVOR} \
		??/py-ujson@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
