PORTNAME=	crlfuzz
DISTVERSION=	62.7a442bb
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A fast tool to scan CRLF vulnerability written in Go.
WWW=		https://github.com/dwisiswant0/crlfuzz

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
