PORTNAME=	mdk3
DISTVERSION=	v6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	WLAN penetration tool.
WWW=		https://aspj.aircrack-ng.org/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/aircrack-ng


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
