PORTNAME=	libc-database
DISTVERSION=	45.69815cd
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Database of libc offsets to simplify exploitation.
WWW=		https://github.com/niklasb/libc-database

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		ftp/wget



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
