PORTNAME=	oniongrok
DISTVERSION=	v1.1.11.r0.gcbae9e7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Onion addresses for anything.
WWW=		https://github.com/cmars/oniongrok

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
