PORTNAME=	firmware-mod-kit
DISTVERSION=	184.b31fcb0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Modify firmware images without recompiling.
WWW=		https://github.com/rampageX/firmware-mod-kit

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gcc \
		??/make \
		devel/git

RUN_DEPENDS=	??/py-magic@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
