PORTNAME=	uptux
DISTVERSION=	33.85ccfd0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Linux privilege escalation checks (systemd, dbus, socket fun, etc).
WWW=		https://github.com/initstring/uptux

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
