PORTNAME=	mftref2name
DISTVERSION=	6.7df9eebb
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Resolve file index number to name or vice versa on NTFS.
WWW=		https://github.com/jschicht/MftRef2Name

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/wine-mono \
		??/wine_gecko \
		emulators/wine


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
