PORTNAME=	bleah
DISTVERSION=	54.56672e8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A BLE scanner for smart devices hacking.
WWW=		https://github.com/evilsocket/bleah

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-argparse@${PY_FLAVOR} \
		??/py-bluepy@${PY_FLAVOR} \
		??/py-terminaltables@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
