PORTNAME=	libidn11
DISTVERSION=	1.33
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Implementation of the Stringprep, Punycode and IDNA specifications.
WWW=		https://www.gnu.org/software/libidn/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/gperf \
		??/gtk-doc \
		devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
