PORTNAME=	hoppy
DISTVERSION=	1.8.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A python script which tests http methods for configuration issues leaking information or just to see if they are enabled.
WWW=		https://labs.portcullis.co.uk/downloads/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-pyopenssl@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
