PORTNAME=	python2-mimeparse
DISTVERSION=	1.6.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A module provides basic functions for parsing mime-type names and matching them against a list of media-ranges.
WWW=		https://pypi.org/project/python-mimeparse/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
