PORTNAME=	rtl8812au-aircrack-dkms
DISTVERSION=	1312.c3fb89a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Aircrack-ng kernel module for Realtek (USB adapters only) network cards with 8812au chipset.
WWW=		https://github.com/aircrack-ng/rtl8812au

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/dkms


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
