PORTNAME=	pytacle
DISTVERSION=	alpha2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Automates the task of sniffing GSM frames
WWW=		http://packetstormsecurity.com/files/124299/pytacle-alpha2.tar.gz

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libffi \
		??/pygtk


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
