PORTNAME=	ssdp-scanner
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	SSDP amplification scanner written in Python. Makes use of Scapy.
WWW=		http://packetstormsecurity.com/files/127994/SSDP-Amplification-Scanner.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3 \
		net/py-scapy@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
