PORTNAME=	wxwidgets-common-3.0
DISTVERSION=	3.0.5.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	
WWW=		https://wxwidgets.org

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/glu \
		??/gst-plugins-base \
		??/gtk2 \
		??/libnotify \
		??/webkit2gtk



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
