PORTNAME=	python2-python-owasp-zap-v2
DISTVERSION=	0.0.9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	OWASP ZAP API client.
WWW=		https://www.owasp.org/index.php/OWASP_Zed_Attack_Proxy_Project

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
