PORTNAME=	uniflash
DISTVERSION=	9.2.0.5300
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Universal Flash Programmer for Texas Instruments devices.
WWW=		https://processors.wiki.ti.com/index.php/Category:CCS_UniFlash

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/libxcrypt-compat

RUN_DEPENDS=	??/gconf \
		??/libcanberra \
		??/libudev0-shim \
		??/libusb-compat


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
