PORTNAME=	pyrit
DISTVERSION=	0.5.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The famous WPA precomputed cracker.
WWW=		https://github.com/JPaulMora/Pyrit

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/zlib \
		lang/python3 \
		net/libpcap \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
