PORTNAME=	recoverdm
DISTVERSION=	0.20
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Recover damaged CD DVD and disks with bad sectors.
WWW=		http://www.vanheusden.com/recoverdm/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
