PORTNAME=	ip-tracer
DISTVERSION=	92.6b9c454
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Track and retrieve any ip address information.
WWW=		https://github.com/Rajkumrdusad/IP-Tracer

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/php82 \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
