PORTNAME=	python2-pyptlib
DISTVERSION=	0.0.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A python implementation of the Pluggable Transports for Circumvention specification for Tor.
WWW=		https://pypi.org/project/pyptlib/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
