PORTNAME=	rww-attack
DISTVERSION=	0.9.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Performs a dictionary attack against a live Microsoft Windows Small Business Server.
WWW=		http://packetstormsecurity.com/files/79021/Remote-Web-Workplace-Attack-Tool.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	archivers/unzip

RUN_DEPENDS=	??/py-pycurl@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
