PORTNAME=	libstdc++5
DISTVERSION=	3.3.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	GNU Standard C++ library version 3.
WWW=		https://gcc.gnu.org/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/binutils \
		??/gcc



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
