PORTNAME=	pirana
DISTVERSION=	0.3.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Exploitation framework that tests the security of a email content filter.
WWW=		http://www.guay-leroux.com/projects.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-mime-lite


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
