PORTNAME=	stegdetect
DISTVERSION=	20.28a4f07
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An automated tool for detecting steganographic content in images.
WWW=		https://github.com/redNixon/stegdetect

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/automake \
		devel/git

RUN_DEPENDS=	??/gdk-pixbuf2


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
