PORTNAME=	lfi-scanner
DISTVERSION=	4.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	This is a simple perl script that enumerates local file inclusion attempts when given a specific target.
WWW=		http://packetstormsecurity.com/files/102848/LFI-Scanner-4.0.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-http-message \
		??/perl-libwww


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
