PORTNAME=	mysql2sqlite
DISTVERSION=	14.e5b2c31
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Converts a mysqldump file into a Sqlite 3 compatible file.
WWW=		https://gist.github.com/esperlu/943776

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/mariadb-clients \
		??/sqlite


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
