PORTNAME=	jynx2
DISTVERSION=	1.2bcbebf
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An expansion of the original Jynx LD_PRELOAD rootkit.
WWW=		https://github.com/chokepoint/Jynx2

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
