PORTNAME=	procyon
DISTVERSION=	0.6
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A suite of Java metaprogramming tools focused on code generation and analysis.
WWW=		https://github.com/mstrobel/procyon

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
