PORTNAME=	smbbf
DISTVERSION=	0.9.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	SMB password bruteforcer.
WWW=		http://packetstormsecurity.com/files/25381/smbbf-0.9.1.tar.gz.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
