PORTNAME=	cms-explorer
DISTVERSION=	15.23b58cd
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Designed to reveal the specific modules, plugins, components and themes that various cms driven websites are running.
WWW=		https://github.com/FlorianHeigl/cms-explorer

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl \
		??/perl-libwhisker2


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
