PORTNAME=	talon
DISTVERSION=	v3.1.r1.g8acc175
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A password guessing tool that targets the Kerberos and LDAP services within the Windows Active Directory environment.
WWW=		https://github.com/optiv/Talon

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
