PORTNAME=	sqlpowerinjector
DISTVERSION=	1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Application created in .Net 1.1 that helps the penetration tester to find and exploit SQL injections on a web page.
WWW=		http://www.sqlpowerinjector.com/download.htm

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/unrar



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
