PORTNAME=	exiflooter
DISTVERSION=	40.b8cc568
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Find geolocation on all image urls and directories also integrates with OpenStreetMap.
WWW=		https://github.com/aydinnyunus/exifLooter

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go

RUN_DEPENDS=	??/perl-image-exiftool


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
