PORTNAME=	botb
DISTVERSION=	69.6d33aae
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A container analysis and exploitation tool for pentesters and engineers.
WWW=		https://github.com/brompwnie/botb

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
