PORTNAME=	perl-data-validate-ip
DISTVERSION=	0.31
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	IPv4 and IPv6 validation methods
WWW=		https://metacpan.org/release/Data-Validate-IP

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-netaddr-ip


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
