PORTNAME=	seeker
DISTVERSION=	379.abbbf80
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Accurately Locate People using Social Engineering.
WWW=		https://github.com/thewhiteh4t/seeker

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/openssh \
		lang/php82 \
		lang/python \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
