PORTNAME=	backoori
DISTVERSION=	55.988e507
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool aided persistence via Windows URI schemes abuse.
WWW=		https://github.com/giuliocomi/backoori

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
