PORTNAME=	scratchabit
DISTVERSION=	565.d93d759
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Easily retargetable and hackable interactive disassembler with IDAPython-compatible plugin API.
WWW=		https://github.com/pfalcon/ScratchABit

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
