PORTNAME=	vipermonkey
DISTVERSION=	1160.511ecd5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A VBA parser and emulation engine to analyze malicious macros.
WWW=		https://github.com/decalage2/ViperMonkey

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-pip@${PY_FLAVOR} \
		??/py-virtualenv@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
