PORTNAME=	hoper
DISTVERSION=	v0.1.1.r0.g8d5dbd9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Trace URLs jumps across the rel links to obtain the last URL.
WWW=		https://github.com/gabamnml/hoper

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/ruby \
		sysutils/rubygem-bundler \
		textproc/libxslt


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
