PORTNAME=	dripcap
DISTVERSION=	0.6.15
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Caffeinated Packet Analyzer.
WWW=		https://github.com/dripcap/dripcap

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
