PORTNAME=	python-validictory
DISTVERSION=	1.1.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	General purpose Python data validator that allows validation of arbitrary Python data structures.
WWW=		https://pypi.org/project/validictory/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
