PORTNAME=	python-libvhdi-python
DISTVERSION=	20251119
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Library and tools to access the Virtual Hard Disk (VHD) image format.
WWW=		https://pypi.org/project/libvhdi-python/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
