PORTNAME=	qwtplot3d
DISTVERSION=	0.2.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Qt/OpenGL-based C++ programming library containing 3d-widgets.
WWW=		http://qwtplot3d.sourceforge.net/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/glu \
		??/mesa

RUN_DEPENDS=	??/qt4


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
