PORTNAME=	libghthash
DISTVERSION=	v0.6.2.r1.g1ce70bb
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Extensible, generic and flexible hash table.
WWW=		https://github.com/SimonKagstrom/libghthash

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
