PORTNAME=	ssllabs-scan
DISTVERSION=	255.50e3144
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Command-line client for the SSL Labs APIs
WWW=		https://github.com/ssllabs/ssllabs-scan

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
