PORTNAME=	python-syslog-rfc5424-formatter
DISTVERSION=	1.2.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Logging formatter which produces well-formatted RFC5424 Syslog Protocol messages.
WWW=		https://pypi.org/project/syslog-rfc5424-formatter/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
