PORTNAME=	brosec
DISTVERSION=	278.c51164f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An interactive reference tool to help security professionals utilize useful payloads and commands.
WWW=		https://github.com/gabemarshall/Brosec

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		www/npm

RUN_DEPENDS=	??/xsel \
		www/node


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
