PORTNAME=	pypy3-flit-core
DISTVERSION=	3.12.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A PEP 517 build backend for packages using Flit.
WWW=		https://github.com/pypa/flit

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/pypy3 \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
