PORTNAME=	enyelkm
DISTVERSION=	1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Rootkit for Linux x86 kernels v2.6.
WWW=		http://www.enye-sec.org/programas.html

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
