PORTNAME=	sniffjoke
DISTVERSION=	772.434bfb1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Injects packets in the transmission flow that are able to seriously disturb passive analysis like sniffing, interception and low level information theft.
WWW=		http://www.delirandom.net/sniffjoke/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git

RUN_DEPENDS=	??/iptables \
		??/tcpdump


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
