PORTNAME=	gibberish-detector
DISTVERSION=	v0.1.1.r2.gecac969
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Train a model and detect gibberish strings with it.
WWW=		https://github.com/domanchi/gibberish-detector

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
