PORTNAME=	depant
DISTVERSION=	0.3a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Check network for services with default passwords.
WWW=		http://midnightresearch.com/projects/depant/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/hydra \
		??/py-ipcalc@${PY_FLAVOR} \
		devel/py-setuptools@${PY_FLAVOR} \
		security/nmap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
