PORTNAME=	chrome-decode
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Chrome web browser decoder tool that demonstrates recovering passwords.
WWW=		http://packetstormsecurity.com/files/119153/Chrome-Web-Browser-Decoder.html

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	archivers/unzip



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
