PORTNAME=	sps
DISTVERSION=	4.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Linux packet crafting tool. Supports IPv4, IPv6 including extension headers, and tunneling IPv6 over IPv4.
WWW=		https://sites.google.com/site/simplepacketsender/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gtk2 \
		??/gtk3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
