PORTNAME=	idb
DISTVERSION=	2.10.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool to simplify some common tasks for iOS pentesting and research.
WWW=		https://rubygems.org/gems/idb

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		lang/ruby

RUN_DEPENDS=	??/qt4 \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
