PORTNAME=	perl-time-interval
DISTVERSION=	1.234
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Converts time intervals of days, hours, minutes, and seconds.
WWW=		https://metacpan.org/pod/distribution/Time-Interval/Interval.pod

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
