PORTNAME=	padbuster
DISTVERSION=	11.50e4a3e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Automated script for performing Padding Oracle attacks.
WWW=		http://www.gdssecurity.com/l/t.php

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl \
		??/perl-bytes-random-secure \
		??/perl-crypt-ssleay


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
