PORTNAME=	fscan
DISTVERSION=	v2.0.1.r1.g6b13b2e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Security Auditing Tool.
WWW=		https://github.com/shadow1ng/fscan

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
