PORTNAME=	chronoleak
DISTVERSION=	0.0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	ICMP Timestamp Remote Time Leaker.
WWW=		https://github.com/noraj/ChronoLeak

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/hping \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
