PORTNAME=	sqlbrute
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Brute forces data out of databases using blind SQL injection.
WWW=		http://www.justinclarke.com/archives/2006/03/sqlbrute.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
