PORTNAME=	slackpirate
DISTVERSION=	0.20.r6.g99e470f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Slack Enumeration and Extraction Tool - extract sensitive information from a Slack Workspace.
WWW=		https://github.com/emtunc/SlackPirate

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-colorama@${PY_FLAVOR} \
		??/py-termcolor@${PY_FLAVOR} \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
