PORTNAME=	yuck
DISTVERSION=	1072.b28436e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A bog-standard command line option parser for C that works with only household ingredients.
WWW=		https://github.com/hroptatyr/yuck

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/capstone \
		??/keystone


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
