PORTNAME=	perl-http-request-common
DISTVERSION=	6.32
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Construct common HTTP::Request objects
WWW=		http://search.cpan.org/~gaas/HTTP-Message-6.06/lib/HTTP/Request/Common.pm

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
