PORTNAME=	pdfwalker
DISTVERSION=	7.64c17f0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Frontend to explore the internals of a PDF document with Origami
WWW=		https://github.com/gdelugre/pdfwalker

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/origami \
		??/ruby-gtk2 \
		??/ruby-ruby-gtkhex \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
