PORTNAME=	kerbcrack
DISTVERSION=	1.3d3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Kerberos sniffer and cracker for Windows.
WWW=		https://vidstromlabs.com/freetools/kerbcrack/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
