PORTNAME=	owrx_connector
DISTVERSION=	0.6.2.r26.g03d5b97
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Connectors used by OpenWebRX to interface with SDR hardware.
WWW=		https://github.com/jketterl/owrx_connector

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/cmake \
		devel/git

RUN_DEPENDS=	??/csdr \
		??/libsamplerate


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
