PORTNAME=	themole
DISTVERSION=	0.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Automatic SQL injection exploitation tool.
WWW=		http://sourceforge.net/projects/themole/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-lxml@${PY_FLAVOR} \
		??/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
