PORTNAME=	dependency-check
DISTVERSION=	10.0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool that attempts to detect publicly disclosed vulnerabilities contained within a projects dependencies.
WWW=		https://github.com/jeremylong/DependencyCheck/releases/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
