PORTNAME=	heartleech
DISTVERSION=	1.0.0i.r4.g3ab1d60
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Scans for systems vulnerable to the heartbleed bug, and then download them.
WWW=		https://github.com/robertdavidgraham/heartleech

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/patchelf \
		??/perl \
		devel/git

RUN_DEPENDS=	??/zlib


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
