PORTNAME=	mono-tools
DISTVERSION=	4.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Collection of testing and development tools for use with mono.
WWW=		https://www.mono-project.com/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/zip \
		devel/git

RUN_DEPENDS=	??/gtk-sharp-2


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
