PORTNAME=	python2-pbkdf2_ctypes
DISTVERSION=	0.99.5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A pbkdf2 implementation for python using ctypes.
WWW=		https://pypi.org/project/pbkdf2-ctypes/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
