PORTNAME=	python-ahocorasick
DISTVERSION=	v2.3.0.r0.g6749ed9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python module implementing Aho-Corasick algorithm.
WWW=		https://github.com/WojciechMula/pyahocorasick

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
