PORTNAME=	mosca
DISTVERSION=	130.a7e725d
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Static analysis tool to find bugs like a grep unix command.
WWW=		https://github.com/CoolerVoid/Mosca

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/pcre


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
