PORTNAME=	sdn-toolkit
DISTVERSION=	1.21
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Discover, Identify, and Manipulate SDN-Based Networks
WWW=		http://downloads.sourceforge.net/project/sdn-toolkit

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/dos2unix

RUN_DEPENDS=	??/py-dpkt@${PY_FLAVOR} \
		??/py-simplejson@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
