PORTNAME=	python2-platformdirs
DISTVERSION=	2.0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A small Python module for determining appropriate platform-specific dirs, e.g. a user data dir.
WWW=		https://pypi.org/project/platformdirs/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
