PORTNAME=	jwscan
DISTVERSION=	7.874b3a5
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Scanner for Jar to EXE wrapper like Launch4j, Exe4j, JSmooth, Jar2Exe.
WWW=		https://github.com/katjahahn/JWScan

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/sbt \
		devel/git

RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
