PORTNAME=	uw-loveimap
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Multi threaded imap bounce scanner.
WWW=		http://uberwall.org/bin/download/45/UWloveimap.tgz

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
