PORTNAME=	harpoon
DISTVERSION=	386.52c1071
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	CLI tool for open source and threat intelligence.
WWW=		https://github.com/Te-k/harpoon

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/libxml2 \
		devel/git \
		textproc/libxslt

RUN_DEPENDS=	??/py-virtualenv@${PY_FLAVOR} \
		lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
