PORTNAME=	jinjector
DISTVERSION=	25.c1578da
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Joomla modules backdoor injector.
WWW=		https://github.com/giovanni-iannaccone/Jinjector

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
