PORTNAME=	usnjrnlcarver
DISTVERSION=	3.fbfc31f2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Carving Usn pages (UsnJrnl records).
WWW=		https://github.com/jschicht/UsnJrnlCarver

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/wine-mono \
		??/wine_gecko \
		emulators/wine


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
