PORTNAME=	sigthief
DISTVERSION=	25.ffb501b
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Stealing Signatures and Making One Invalid Signature at a Time.
WWW=		https://github.com/secretsquirrel/SigThief

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
