PORTNAME=	statsprocessor
DISTVERSION=	0.11
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A high-performance word-generator based on per-position Markov-attack.
WWW=		http://hashcat.net/wiki/doku.php?id=statsprocessor

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/p7zip



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
