PORTNAME=	sqlite2
DISTVERSION=	2.8.17
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A C library that implements an SQL database engine.
WWW=		http://www.sqlite.org/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/readline


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
