PORTNAME=	sqlping
DISTVERSION=	4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	SQL Server scanning tool that also checks for weak passwords using wordlists.
WWW=		http://www.sqlsecurity.com/downloads

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
