PORTNAME=	eyepwn
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Exploit for Eye-Fi Helper directory traversal vulnerability
WWW=		http://www.pentest.co.uk

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/net-tools \
		lang/python3 \
		net/py-scapy@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
