PORTNAME=	python2-libkeepass
DISTVERSION=	0.3.1.post1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A library to access KeePass 1.x/KeePassX (v3) and KeePass 2.x (v4) files.
WWW=		https://pypi.org/project/libkeepass/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
