PORTNAME=	dalfox
DISTVERSION=	2086.e569033
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Parameter Analysis and XSS Scanning tool.
WWW=		https://github.com/hahwul/dalfox

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
