PORTNAME=	netkit-rwho
DISTVERSION=	0.17
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Remote who client and server (with Debian patches).
WWW=		http://packages.qa.debian.org/n/netkit-rwho.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/sh


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
