PORTNAME=	nmap-parse-output
DISTVERSION=	26.a8e31b3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Converts/manipulates/extracts data from a nmap scan output.
WWW=		https://github.com/hahwul/nmap-parse-output

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	shells/bash \
		textproc/libxslt


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
