PORTNAME=	loic
DISTVERSION=	2.9.9.99
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An open source network stress tool for Windows.
WWW=		https://github.com/NewEraCracker/LOIC

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/monodevelop

RUN_DEPENDS=	??/mono


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
