PORTNAME=	rej
DISTVERSION=	0.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An API and a graphical tool for inspection and manipulation of classfiles for the Java platform.
WWW=		https://sourceforge.net/projects/rejava/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
