PORTNAME=	python2-sip-pyqt4
DISTVERSION=	4.19.25
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	
WWW=		http://www.riverbankcomputing.com/software/sip/intro

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-distutils-extra@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
