PORTNAME=	cryptonark
DISTVERSION=	0.5.7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	SSL security checker.
WWW=		http://blog.techstacks.com/cryptonark.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl-io-socket-ssl \
		??/perl-modern-perl \
		??/perl-mozilla-ca \
		??/perl-tie-hash-indexed


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
