PORTNAME=	blackarch-config-fluxbox
DISTVERSION=	41.a172928
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	BlackArch menu, theme and config for fluxbox window manager.
WWW=		https://github.com/BlackArch/blackarch-config-fluxbox

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/blackarch-wallpaper \
		??/feh \
		??/fluxbox \
		??/rxvt-unicode \
		??/terminus-font


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
