PORTNAME=	topera
DISTVERSION=	19.3e230fd
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An IPv6 security analysis toolkit, with the particularity that their attacks cant be detected by Snort.
WWW=		https://github.com/toperaproject/topera

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3 \
		net/py-scapy@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
