PORTNAME=	wifi-honey
DISTVERSION=	1.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A management tool for wifi honeypots.
WWW=		http://www.digininja.org/projects/wifi_honey.php

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/aircrack-ng \
		??/screen


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
