PORTNAME=	python2-netfilterqueue
DISTVERSION=	0.8.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Python bindings for libnetfilter_queue.
WWW=		https://github.com/fqrouter/python-netfilterqueue

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	??/libnetfilter_queue \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
