PORTNAME=	eindeutig
DISTVERSION=	20050628.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Examine the contents of Outlook Express DBX email repository files.
WWW=		https://www.jonesdykstra.com/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
