PORTNAME=	perl-tie-encryptedhash
DISTVERSION=	1.24
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Hashes (and objects based on hashes) with encrypting fields.
WWW=		https://metacpan.org/pod/Tie::EncryptedHash

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gmp \
		??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
