PORTNAME=	nosqli
DISTVERSION=	37.6fce3eb
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	NoSQL scanner and injector.
WWW=		https://github.com/Charlie-belmer/nosqli

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
