PORTNAME=	ssh-mitm
DISTVERSION=	v2.2.r22.g70998ba
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	SSH man-in-the-middle tool.
WWW=		https://github.com/jtesta/ssh-mitm

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	ftp/wget \
		lang/python \
		security/openssl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
