PORTNAME=	wnmap
DISTVERSION=	0.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A shell script written with the purpose to automate and chain scans via nmap.
WWW=		http://nullsecurity.net/tools/automation.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/vim \
		security/nmap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
