PORTNAME=	ruby-$_gemname
DISTVERSION=	4.3.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Ruby/Pango is a Ruby binding of pango-1.x.
WWW=		https://rubygems.org/gems/pango

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/gobject-introspection \
		??/pango \
		??/ruby-cairo \
		??/ruby-cairo-gobject \
		??/ruby-gobject-introspection \
		lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
