PORTNAME=	malcom
DISTVERSION=	708.02e55b9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Analyze a systems network communication using graphical representations of network traffic.
WWW=		https://github.com/tomchop/malcom

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-pip@${PY_FLAVOR} \
		devel/git

RUN_DEPENDS=	??/py-typing@${PY_FLAVOR} \
		??/py-virtualenv@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
