PORTNAME=	armitage
DISTVERSION=	150813
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A graphical cyber attack management tool for Metasploit.
WWW=		http://www.fastandeasyhacking.com/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/ant \
		??/subversion \
		??/zip \
		archivers/unzip

RUN_DEPENDS=	??/java-environment \
		??/metasploit \
		??/postgresql \
		??/ruby-msgpack \
		security/nmap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
