PORTNAME=	motsa-dns-spoofing
DISTVERSION=	2.6ac6980
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	ManOnTheSideAttack-DNS Spoofing.
WWW=		https://github.com/waytoalpit/ManOnTheSideAttack-DNS-Spoofing

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3 \
		net/py-scapy@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
