PORTNAME=	shellnoob
DISTVERSION=	37.6586133
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A toolkit that eases the writing and debugging of shellcode.
WWW=		https://github.com/reyammer/shellnoob

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
