PORTNAME=	scannerl
DISTVERSION=	76.8133065
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	The modular distributed fingerprinting engine.
WWW=		https://github.com/kudelskisecurity/scannerl

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/rebar \
		devel/git

RUN_DEPENDS=	??/erlang \
		??/erlang-eldap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
