PORTNAME=	conn
DISTVERSION=	1.0.39
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Small C library usefull to easy build ipv4/ipv6 network daemons/clients.
WWW=		http://kernel.embedromix.ro/us/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
