PORTNAME=	lfi-image-helper
DISTVERSION=	0.8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A simple script to infect images with PHP Backdoors for local file inclusion attacks.
WWW=		http://packetstormsecurity.com/files/129871/LFI-Image-Helper-0.8.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl \
		??/perl-color-output \
		??/perl-image-exiftool


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
