PORTNAME=	python-isc_dhcp_leases
DISTVERSION=	0.10.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Small python module for reading /var/lib/dhcp/dhcpd.leases from isc-dhcp-server.
WWW=		https://pypi.org/project/isc_dhcp_leases/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
