PORTNAME=	rtpbreak
DISTVERSION=	1.3a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Detects, reconstructs and analyzes any RTP session.
WWW=		https://packetstorm.news/files/id/66494/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libnet \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
