PORTNAME=	perl-io-socket-timeout
DISTVERSION=	0.32
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	IO::Socket with read/write timeout.
WWW=		https://metacpan.org/pod/IO::Socket::Timeout

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
