PORTNAME=	klee-uclibc
DISTVERSION=	1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	KLEEs version of uClibc.
WWW=		https://github.com/klee/klee-uclibc

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/clang \
		??/llvm \
		ftp/wget \
		lang/python



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
