PORTNAME=	perl-net-write
DISTVERSION=	1.10
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A portable interface to open and send raw data to network.
WWW=		https://metacpan.org/release/Net-Write

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl-class-gomor \
		??/perl-net-pcap \
		??/perl-socket6


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
