PORTNAME=	python2-pcapfile
DISTVERSION=	0.12.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Pure Python package for reading and parsing libpcap savefiles.
WWW=		https://pypi.python.org/pypi/pypcapfile/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
