PORTNAME=	tnscmd
DISTVERSION=	1.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A lame tool to prod the oracle tnslsnr process (1521/tcp).
WWW=		http://www.jammed.com/~jwa/hacks/security/tnscmd/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
