PORTNAME=	ruby-http_configuration
DISTVERSION=	1.0.4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Gem that provides the ability to set defaults for proxies and timeouts for Net::HTTP.
WWW=		http://github.com/bdurand/http_configuration

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	lang/ruby



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
