PORTNAME=	turner
DISTVERSION=	32.fad9423
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tunnels HTTP over a permissive/open TURN server; supports HTTP and SOCKS5 proxy.
WWW=		https://github.com/staaldraad/turner

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
