PORTNAME=	python-dicttoxml
DISTVERSION=	1.7.16
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Converts a Python dictionary or other native data type into a valid XML string.
WWW=		https://pypi.python.org/pypi/dicttoxml/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
