PORTNAME=	onetwopunch
DISTVERSION=	v1.0.0.r2.gd4ab4e8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Use unicornscan to quickly scan all open ports, and then pass the open ports to nmap for detailed scans.
WWW=		https://github.com/superkojiman/onetwopunch

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/unicornscan \
		security/nmap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
