PORTNAME=	certgraph
DISTVERSION=	194.9826815
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Crawl the graph of certificate Alternate Names.
WWW=		https://github.com/lanrat/certgraph

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
