PORTNAME=	yaf
DISTVERSION=	2.15.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Yet Another Flowmeter.
WWW=		https://tools.netsa.cert.org/yaf/download.html

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libfixbuf \
		??/libltdl \
		net/libpcap


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
