PORTNAME=	cisco7crack
DISTVERSION=	2.f1c21dd
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Crypt and decrypt the cisco enable 7 passwords.
WWW=		https://github.com/madrisan/cisco7crack

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
