PORTNAME=	gowitness
DISTVERSION=	3.1.1.r1.g67cc249
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A golang, web screenshot utility using Chrome Headless.
WWW=		https://github.com/sensepost/gowitness

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go

RUN_DEPENDS=	??/chromium


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
