PORTNAME=	poison
DISTVERSION=	1.5.41
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A fast, asynchronous syn and udp scanner.
WWW=		http://nologin.org/main.pl?action=codeList&

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
