PORTNAME=	pth-toolkit
DISTVERSION=	7.3641cdc
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Modified version of the passing-the-hash tool collection made to work straight out of the box.
WWW=		https://github.com/byt3bl33d3r/pth-toolkit

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
