PORTNAME=	python2-pygoogle-simple
DISTVERSION=	0.2.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Search in google by AJAX Google API.
WWW=		https://pypi.python.org/pypi/pygoogle-simple/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/py-setuptools@${PY_FLAVOR}



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
