PORTNAME=	damm
DISTVERSION=	32.60e7ec7
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Differential Analysis of Malware in Memory.
WWW=		https://github.com/504ensicsLabs/DAMM

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
