PORTNAME=	doona
DISTVERSION=	145.7a4796c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A fork of the Bruteforce Exploit Detector Tool (BED).
WWW=		https://github.com/wireghoul/doona

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
