PORTNAME=	tidos-framework
DISTVERSION=	v2.0.beta2.r22.g4098187
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Offensive Web Application Penetration Testing Framework.
WWW=		https://github.com/0xInfection/TIDoS-Framework

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/exiv2 \
		??/konsole \
		??/libxml2 \
		??/mariadb \
		??/ncurses \
		??/photon \
		??/py-bs4@${PY_FLAVOR} \
		??/py-builtwith@${PY_FLAVOR} \
		??/py-colorama@${PY_FLAVOR} \
		??/py-dnslib@${PY_FLAVOR} \
		??/py-emailprotectionslib@${PY_FLAVOR} \
		??/py-google@${PY_FLAVOR} \
		??/py-idna@${PY_FLAVOR} \
		??/py-lxml@${PY_FLAVOR} \
		??/py-mechanize@${PY_FLAVOR} \
		??/py-mysql-connector@${PY_FLAVOR} \
		??/py-mysqlclient@${PY_FLAVOR} \
		??/py-pexpect@${PY_FLAVOR} \
		??/py-pillow@${PY_FLAVOR} \
		??/py-ptyprocess@${PY_FLAVOR} \
		??/py-pyqt5@${PY_FLAVOR} \
		??/py-shodan@${PY_FLAVOR} \
		??/py-texttable@${PY_FLAVOR} \
		??/py-tld@${PY_FLAVOR} \
		??/py-tldextract@${PY_FLAVOR} \
		??/sslyze \
		??/tcpdump \
		??/tor \
		devel/py-pip@${PY_FLAVOR} \
		devel/py-six@${PY_FLAVOR} \
		lang/python \
		net/py-scapy@${PY_FLAVOR} \
		security/nmap \
		www/py-requests@${PY_FLAVOR}


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
