PORTNAME=	samplicator
DISTVERSION=	175.ceeb1d2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Send copies of (UDP) datagrams to multiple receivers, with optional sampling and spoofing.
WWW=		https://github.com/sleinen/samplicator

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
