PORTNAME=	vinetto
DISTVERSION=	0.07beta
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A forensics tool to examine Thumbs.db files.
WWW=		https://vinetto.sourceforge.net

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-pillow@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
