PORTNAME=	gittools
DISTVERSION=	70.7cac63a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A repository with 3 tools for pwning websites with .git repositories available.
WWW=		https://github.com/internetwache/GitTools

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	devel/git \
		ftp/curl \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
