PORTNAME=	kekeo
DISTVERSION=	2.2.0.20211214
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A little toolbox to play with Microsoft Kerberos in C.
WWW=		https://github.com/gentilkiwi/kekeo

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
