PORTNAME=	sub3suite
DISTVERSION=	v0.0.4.r8.gb5bfa2a
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A free, open source, cross platform Intelligence Gathering tool.
WWW=		https://github.com/3nock/sub3suite

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/make \
		??/qtcreator \
		devel/git

RUN_DEPENDS=	??/qt5-base


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
