PORTNAME=	blackhash
DISTVERSION=	0.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Creates a filter from system hashes.
WWW=		http://16s.us/blackhash/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/crypto++


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
