PORTNAME=	kraken
DISTVERSION=	32.368a837
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A project to encrypt A5/1 GSM signaling using a Time/Memory Tradeoff Attack.
WWW=		http://opensource.srlabs.de/projects/a51-decrypt

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
