PORTNAME=	cafebabe
DISTVERSION=	0.1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Java bytecode editor & decompiler.
WWW=		https://github.com/GraxCode/Cafebabe/releases/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/java-environment


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
