PORTNAME=	bloodhound-cli
DISTVERSION=	v0.2.0.r0.g19e79d9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Command-line interface for BloodHound v5.
WWW=		https://github.com/SpecterOps/bloodhound-cli

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
