PORTNAME=	hakrevdns
DISTVERSION=	47.3001d16
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Small, fast tool for performing reverse DNS lookups en masse.
WWW=		https://github.com/hakluke/hakrevdns

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
