PORTNAME=	gpredict
DISTVERSION=	1669.2a57f14
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A real-time satellite tracking and orbit prediction application.
WWW=		http://gpredict.oz9aec.net/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/intltool \
		devel/git

RUN_DEPENDS=	??/glib2 \
		??/goocanvas \
		??/grig \
		??/gtk3 \
		??/hamlib \
		ftp/curl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
