PORTNAME=	xspy
DISTVERSION=	1.0c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A utility for monitoring keypresses on remote X servers.
WWW=		http://www.freshports.org/security/xspy/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/imake

RUN_DEPENDS=	??/libx11


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
