PORTNAME=	linux-inject
DISTVERSION=	100.268d4e4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Tool for injecting a shared object into a Linux process.
WWW=		https://github.com/gaffe23/linux-inject

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/clang \
		??/make \
		devel/git

RUN_DEPENDS=	??/lib32-gcc-libs


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
