PORTNAME=	airoscript
DISTVERSION=	45.0a122ee
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A script to simplify the use of aircrack-ng tools.
WWW=		http://midnightresearch.com/projects/wicrawl/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/aircrack-ng \
		??/dhclient \
		??/mdk3 \
		??/perl-yaml-syck


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
