PORTNAME=	python2-qrcode
DISTVERSION=	6.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python library to generate QR codes.
WWW=		https://pypi.org/project/qrcode/#files

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/py-pillow@${PY_FLAVOR} \
		devel/py-setuptools@${PY_FLAVOR} \
		devel/py-six@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
