PORTNAME=	lfifreak
DISTVERSION=	21.0c6adef
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A unique automated LFi Exploiter with Bind/Reverse Shells.
WWW=		https://github.com/OsandaMalith/LFiFreak/

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/py-beautifulsoup4@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
