PORTNAME=	bob-the-butcher
DISTVERSION=	0.8.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A distributed password cracker package.
WWW=		https://btb.banquise.net/

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/libevent


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
