PORTNAME=	recomposer
DISTVERSION=	2.90f85ed
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Randomly changes Win32/64 PE Files for safer uploading to malware and sandbox sites.
WWW=		https://github.com/secretsquirrel/recomposer

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
