PORTNAME=	php-rfi-payload-decoder
DISTVERSION=	30.bd42caa
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Decode and analyze RFI payloads developed in PHP.
WWW=		https://github.com/bwall/PHP-RFI-Payload-Decoder

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/apache \
		lang/php82


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
