PORTNAME=	bruteforce-luks
DISTVERSION=	54.788d637
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Try to find the password of a LUKS encrypted volume.
WWW=		https://github.com/glv2/bruteforce-luks

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/cryptsetup


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
