PORTNAME=	htrosbif
DISTVERSION=	134.9dc3f86
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Active HTTP server fingerprinting and recon tool.
WWW=		https://github.com/lkarsten/htrosbif

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl \
		??/perl-json-xs \
		??/perl-list-moreutils \
		??/perl-test-deep


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
