PORTNAME=	eternal-scanner
DISTVERSION=	101.3979b0f
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	An internet scanner for exploit CVE-2017-0144 (Eternal Blue).
WWW=		https://github.com/peterpt/eternal_scanner

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/masscan \
		??/metasploit \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
