PORTNAME=	pixd
DISTVERSION=	9.f49add4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Colourful visualization tool for binary files.
WWW=		https://github.com/FireyFly/pixd

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
