PORTNAME=	python2-automat
DISTVERSION=	20.2.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Self-service finite-state machines for the programmer on the go.
WWW=		https://pypi.org/project/Automat/#files

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/py-attrs@${PY_FLAVOR} \
		??/py-m2r@${PY_FLAVOR} \
		??/py-setuptools-scm@${PY_FLAVOR}

RUN_DEPENDS=	??/py-attrs@${PY_FLAVOR} \
		lang/python3


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
