PORTNAME=	perl-digest-perl-md5
DISTVERSION=	1.9
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Perl implementation of Ron Rivests MD5 Algorithm.
WWW=		http://search.cpan.org/dist/Digest-Perl-MD5

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/perl


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
