PORTNAME=	streamfinder
DISTVERSION=	1.2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Searches for Alternate Data Streams (ADS).
WWW=		https://www.gaijin.at/en/dlstreamfind.php

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/unrar \
		ftp/curl



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
