PORTNAME=	xxeserv
DISTVERSION=	14.2c7f444
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A mini webserver with FTP support for XXE payloads.
WWW=		https://github.com/staaldraad/xxeserv

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
