PORTNAME=	blackarch-config-awesome
DISTVERSION=	49.ea88207
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	BlackArch menu, theme and config for awesome window manager.
WWW=		https://github.com/BlackArch/blackarch-config-awesome

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/awesome \
		??/blackarch-wallpaper \
		??/feh \
		??/rxvt-unicode \
		??/terminus-font-ttf


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
