PORTNAME=	s3scanner
DISTVERSION=	v3.1.1.r10.g9e26bc4
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A tool to find open S3 buckets in AWS or other cloud providers.
WWW=		https://github.com/sa7mon/S3Scanner

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
