PORTNAME=	sourcemapper
DISTVERSION=	37.467916e
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Extract JavaScript source trees from Sourcemap files.
WWW=		https://github.com/denandz/sourcemapper

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		lang/go



USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
