PORTNAME=	regripper
DISTVERSION=	109.bdf7ac2
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Open source forensic software used as a Windows Registry data extraction command line or GUI tool.
WWW=		https://github.com/keydet89/RegRipper3.0

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/perl \
		??/perl-parse-registry


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
