PORTNAME=	ruby-multi_xml
DISTVERSION=	0.8.1
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Provides swappable XML backends utilizing LibXML, Nokogiri, Ox, or REXML.
WWW=		https://rubygems.org/gems/multi_xml

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	??/ruby-rdoc

RUN_DEPENDS=	lang/ruby \
		sysutils/rubygem-bundler


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
