PORTNAME=	terminus-font-ttf
DISTVERSION=	4.49.3
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Monospaced bitmap font designed for long work with computers (TTF version, mainly for Java applications).
WWW=		https://files.ax86.net/terminus-ttf

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	??/fontconfig \
		??/xorg-mkfontdir


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
