PORTNAME=	resourcehacker
DISTVERSION=	5.1.8
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Resource compiler and decompiler for Windows® applications.
WWW=		http://www.angusj.com/resourcehacker/

LICENSE=	GPLv3 # Defaulting to GPLv3




USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
