PORTNAME=	mara-framework
DISTVERSION=	176.ac4ac88
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	A Mobile Application Reverse engineering and Analysis Framework.
WWW=		https://github.com/xtiankisutsa/MARA_Framework

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/figlet \
		??/gtk2 \
		??/java-environment \
		??/py-pydot@${PY_FLAVOR} \
		??/python3 \
		??/tree \
		devel/git \
		lang/python3 \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
