PORTNAME=	python-feedformater
DISTVERSION=	32.7391193
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Python (2 & 3) library for generating news feeds in RSS and Atom formats.
WWW=		https://github.com/marianoguerra/feedformatter

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git \
		devel/py-setuptools@${PY_FLAVOR}

RUN_DEPENDS=	lang/python


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
