PORTNAME=	ruby-unicode-display-width
DISTVERSION=	2.0.0
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Determines the monospace display width of a string using EastAsianWidth.txt, Unicode general category, and other data.
WWW=		https://rubygems.org/gems/unicode-display_width

LICENSE=	GPLv3 # Defaulting to GPLv3


RUN_DEPENDS=	lang/ruby


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
