PORTNAME=	tweetshell
DISTVERSION=	21.47a415c
CATEGORIES=	freebsd security

MAINTAINER=	mauro.risonho@gmail.com
COMMENT=	Multi-thread Twitter BruteForcer in Shell Script.
WWW=		https://github.com/thelinuxchoice/tweetshell

LICENSE=	GPLv3 # Defaulting to GPLv3

BUILD_DEPENDS=	devel/git

RUN_DEPENDS=	??/tor \
		ftp/curl \
		shells/bash


USE_GITHUB=	yes
GH_ACCOUNT=	# Needs manual check

.include <bsd.port.mk>
